"""تخصصات أوسع: قانون، تربية، اجتماع، فلسفة، جغرافيا، لسانيات، مختبر، مركبات."""

from __future__ import annotations

WIDE_ENTRIES: list[tuple[str, str]] = [
    ("civil law", "القانون المدني"),
    ("criminal law", "القانون الجنائي"),
    ("constitutional law", "القانون الدستوري"),
    ("administrative law", "القانون الإداري"),
    ("commercial law", "القانون التجاري"),
    ("labor law", "قانون العمل"),
    ("public international law", "القانون الدولي العام"),
    ("private international law", "القانون الدولي الخاص"),
    ("contract law", "قانون العقود"),
    ("tort law", "قانون المسؤولية التقصيرية"),
    ("property law", "قانون الملكية"),
    ("family law", "قانون الأحوال الشخصية"),
    ("legal personality", "شخصية قانونية"),
    ("legal capacity", "أهلية قانونية"),
    ("natural person", "شخص طبيعي"),
    ("juridical person", "شخص معنوي"),
    ("legal obligation", "التزام قانوني"),
    ("contractual offer", "إيجاب تعاقدي"),
    ("contractual acceptance", "قبول تعاقدي"),
    ("breach of contract", "إخلال بالعقد"),
    ("compensatory damages", "تعويض جابر"),
    ("specific performance", "تنفيذ عيني"),
    ("statute of limitations", "التقادم"),
    ("court jurisdiction", "اختصاص المحكمة"),
    ("legal venue", "مكان انعقاد المحكمة"),
    ("civil plaintiff", "المدعي"),
    ("civil defendant", "المدعى عليه"),
    ("appellant party", "المستأنف"),
    ("appellee party", "المستأنف عليه"),
    ("court judgment", "حكم المحكمة"),
    ("jury verdict", "حكم هيئة المحلفين"),
    ("judicial appeal", "استئناف قضائي"),
    ("court of cassation", "محكمة التمييز"),
    ("court injunction", "أمر قضائي"),
    ("burden of proof", "عبء الإثبات"),
    ("presumption of innocence", "قرينة البراءة"),
    ("due process", "ضمانات الإجراءات القانونية"),
    ("rule of law", "سيادة القانون"),
    ("separation of powers", "فصل السلطات"),
    ("judicial review", "رقابة قضائية"),
    ("primary legislation", "تشريع أصلي"),
    ("secondary legislation", "تشريع فرعي"),
    ("executive decree", "مرسوم"),
    ("written constitution", "دستور مكتوب"),
    ("constitutional amendment", "تعديل دستوري"),
    ("state sovereignty", "سيادة الدولة"),
    ("legal citizenship", "مواطنة قانونية"),
    ("human rights", "حقوق الإنسان"),
    ("fundamental rights", "حقوق أساسية"),
    ("criminal liability", "مسؤولية جنائية"),
    ("civil liability", "مسؤولية مدنية"),
    ("criminal intent", "قصد جنائي"),
    ("civil negligence", "إهمال مدني"),
    ("strict liability", "مسؤولية مطلقة"),
    ("actus reus", "الركن المادي"),
    ("mens rea", "الركن المعنوي"),
    ("felony offense", "جناية"),
    ("misdemeanor offense", "جنحة"),
    ("petty offense", "مخالفة"),
    ("intentional homicide", "قتل عمد"),
    ("negligent homicide", "قتل خطأ"),
    ("theft offense", "جريمة السرقة"),
    ("criminal fraud", "احتيال جنائي"),
    ("embezzlement offense", "اختلاس"),
    ("bribery offense", "رشوة"),
    ("forgery offense", "تزوير"),
    ("defamation claim", "دعوى قذف"),
    ("self defense", "دفاع شرعي"),
    ("judicial precedent", "سابقة قضائية"),
    ("binding precedent", "سابقة ملزمة"),
    ("common law system", "نظام القانون العام"),
    ("civil law system", "نظام القانون المدني"),
    ("legal mortgage", "رهن قانوني"),
    ("legal lien", "امتياز قانوني"),
    ("easement right", "حق الارتفاق"),
    ("lease contract", "عقد إيجار"),
    ("intellectual property", "ملكية فكرية"),
    ("copyright protection", "حماية حق المؤلف"),
    ("patent protection", "حماية براءة الاختراع"),
    ("trademark protection", "حماية العلامة التجارية"),
    ("trade secret", "سر تجاري"),
    ("fair use doctrine", "مبدأ الاستخدام العادل"),
    ("commercial arbitration", "تحكيم تجاري"),
    ("legal mediation", "وساطة قانونية"),
    ("civil litigation", "تقاض مدني"),
    ("statement of claim", "لائحة الدعوى"),
    ("witness testimony", "شهادة الشاهد"),
    ("expert witness", "شاهد خبير"),
    ("hearsay evidence", "شهادة سماعية"),
    ("cross examination", "استجواب مقابل"),
    ("direct examination", "استجواب مباشر"),
    ("sworn affidavit", "إفادة مشفوعة بيمين"),
    ("search warrant", "أمر تفتيش"),
    ("arrest warrant", "أمر قبض"),
    ("bail hearing", "جلسة الكفالة"),
    ("probation order", "أمر وضع تحت المراقبة"),
    ("parole release", "إفراج شرطي"),
    ("custodial sentence", "عقوبة سالبة للحرية"),
    ("monetary fine", "غرامة مالية"),
    ("capital punishment", "عقوبة الإعدام"),
    ("extradition request", "طلب تسليم"),
    ("political asylum", "لجوء سياسي"),
    ("refugee status", "صفة اللاجئ"),
    ("international treaty", "معاهدة دولية"),
    ("treaty ratification", "تصديق المعاهدة"),
    ("treaty reservation", "تحفظ على المعاهدة"),
    ("customary international law", "العرف الدولي"),
    ("diplomatic immunity", "حصانة دبلوماسية"),
    ("right of self determination", "حق تقرير المصير"),
    ("international humanitarian law", "القانون الدولي الإنساني"),
    ("war crime", "جريمة حرب"),
    ("crime against humanity", "جريمة ضد الإنسانية"),
    ("crime of genocide", "جريمة الإبادة الجماعية"),
    ("international court of justice", "محكمة العدل الدولية"),
    ("international criminal court", "المحكمة الجنائية الدولية"),
    ("pedagogical approach", "مقاربة تربوية"),
    ("curriculum design", "تصميم المنهج"),
    ("course syllabus", "مفردات المقرر"),
    ("learning outcome", "ناتج التعلم"),
    ("formative assessment", "تقويم تكويني"),
    ("summative assessment", "تقويم ختامي"),
    ("assessment rubric", "سلم تقدير"),
    ("bloom taxonomy", "تصنيف بلوم"),
    ("higher order thinking", "تفكير عالي الرتبة"),
    ("differentiated instruction", "تعليم متمايز"),
    ("inclusive education", "تعليم جامع"),
    ("special education", "تربية خاصة"),
    ("individualized education plan", "خطة تعليم فردية"),
    ("classroom management", "إدارة الصف"),
    ("lesson plan", "خطة الدرس"),
    ("instructional design", "تصميم تعليمي"),
    ("educational scaffolding", "سقالات تعليمية"),
    ("constructivist learning", "تعلم بنائي"),
    ("behaviorist learning", "تعلم سلوكي"),
    ("cognitivist learning", "تعلم معرفي"),
    ("student centered learning", "تعلم متمحور حول الطالب"),
    ("teacher centered learning", "تعلم متمحور حول المعلم"),
    ("cooperative learning", "تعلم تعاوني"),
    ("collaborative learning", "تعلم تشاركي"),
    ("problem based learning", "تعلم قائم على المشكلات"),
    ("project based learning", "تعلم قائم على المشاريع"),
    ("flipped classroom", "صف مقلوب"),
    ("blended learning", "تعلم مدمج"),
    ("distance learning", "تعلم عن بعد"),
    ("electronic learning", "تعلم إلكتروني"),
    ("learning management system", "نظام إدارة التعلم"),
    ("academic achievement", "تحصيل دراسي"),
    ("grade point average", "المعدل التراكمي"),
    ("credit hour", "ساعة معتمدة"),
    ("course prerequisite", "متطلب سابق"),
    ("academic probation", "إنذار أكاديمي"),
    ("academic integrity", "نزاهة أكاديمية"),
    ("plagiarism detection", "كشف الانتحال"),
    ("citation style", "أسلوب الاستشهاد"),
    ("apa citation style", "توثيق جمعية علم النفس الأمريكية"),
    ("harvard referencing", "توثيق هارفارد"),
    ("annotated bibliography", "قائمة مراجع مشروحة"),
    ("research gap", "فجوة بحثية"),
    ("thesis statement", "جملة الأطروحة"),
    ("doctoral dissertation", "أطروحة دكتوراه"),
    ("master thesis", "رسالة ماجستير"),
    ("paper abstract", "مستخلص البحث"),
    ("keywords list", "قائمة الكلمات المفتاحية"),
    ("peer review", "تحكيم الأقران"),
    ("journal impact factor", "معامل تأثير المجلة"),
    ("open access publishing", "نشر مفتوح الوصول"),
    ("primary source", "مصدر أولي"),
    ("secondary source", "مصدر ثانوي"),
    ("ethical approval", "موافقة أخلاقية"),
    ("institutional review board", "لجنة أخلاقيات البحث"),
    ("informed consent procedure", "إجراء الموافقة المستنيرة"),
    ("social structure", "بنية اجتماعية"),
    ("social institution", "مؤسسة اجتماعية"),
    ("socialization process", "عملية التنشئة الاجتماعية"),
    ("social stratification", "تدرج اجتماعي"),
    ("social mobility", "حراك اجتماعي"),
    ("social class", "طبقة اجتماعية"),
    ("socioeconomic status", "وضع اجتماعي اقتصادي"),
    ("cultural subculture", "ثقافة فرعية"),
    ("social norm", "معيار اجتماعي"),
    ("social sanction", "جزاء اجتماعي"),
    ("social deviance", "انحراف اجتماعي"),
    ("social anomie", "لامعيارية"),
    ("social control", "ضبط اجتماعي"),
    ("social stigma", "وصمة اجتماعية"),
    ("social stereotype", "صورة نمطية"),
    ("social prejudice", "تحيز اجتماعي"),
    ("social discrimination", "تمييز اجتماعي"),
    ("gender role", "دور جندري"),
    ("social inequality", "لامساواة اجتماعية"),
    ("relative poverty", "فقر نسبي"),
    ("absolute poverty", "فقر مطلق"),
    ("urbanization process", "عملية التحضر"),
    ("human migration", "هجرة بشرية"),
    ("cultural globalization", "عولمة ثقافية"),
    ("social change", "تغير اجتماعي"),
    ("collective behavior", "سلوك جمعي"),
    ("social movement", "حركة اجتماعية"),
    ("structural functionalism", "وظيفية بنائية"),
    ("conflict theory", "نظرية الصراع"),
    ("symbolic interactionism", "تفاعلية رمزية"),
    ("social capital", "رأس مال اجتماعي"),
    ("cultural capital", "رأس مال ثقافي"),
    ("theory of knowledge", "نظرية المعرفة"),
    ("metaphysical inquiry", "بحث ميتافيزيقي"),
    ("ontological question", "سؤال أنطولوجي"),
    ("moral philosophy", "فلسفة أخلاقية"),
    ("aesthetic theory", "نظرية الجمال"),
    ("deductive reasoning", "استدلال استنباطي"),
    ("inductive reasoning", "استدلال استقرائي"),
    ("abductive reasoning", "استدلال إبعادي"),
    ("logical syllogism", "قياس منطقي"),
    ("logical fallacy", "مغالطة منطقية"),
    ("argument premise", "مقدمة الحجة"),
    ("argument validity", "صحة الحجة"),
    ("argument soundness", "سلامة الحجة"),
    ("philosophical empiricism", "تجريبية فلسفية"),
    ("philosophical rationalism", "عقلانية فلسفية"),
    ("philosophical skepticism", "شكوكية فلسفية"),
    ("utilitarian ethics", "أخلاق نفعية"),
    ("deontological ethics", "أخلاق الواجب"),
    ("virtue ethics", "أخلاق الفضيلة"),
    ("categorical imperative", "أمر قطعي"),
    ("social contract theory", "نظرية العقد الاجتماعي"),
    ("free will", "إرادة حرة"),
    ("philosophical determinism", "حتمية فلسفية"),
    ("mind body dualism", "ثنائية العقل والجسم"),
    ("philosophical materialism", "مادية فلسفية"),
    ("philosophical idealism", "مثالية فلسفية"),
    ("phenomenological method", "منهج فينومينولوجي"),
    ("existential philosophy", "فلسفة وجودية"),
    ("logical positivism", "وضعية منطقية"),
    ("philosophical pragmatism", "براغماتية فلسفية"),
    ("geographic equator", "خط الاستواء"),
    ("prime meridian", "خط غرينتش"),
    ("tropic of cancer", "مدار السرطان"),
    ("tropic of capricorn", "مدار الجدي"),
    ("arctic circle", "الدائرة القطبية الشمالية"),
    ("antarctic circle", "الدائرة القطبية الجنوبية"),
    ("time zone", "منطقة زمنية"),
    ("map projection", "مسقط خرائطي"),
    ("topographic map", "خريطة طبوغرافية"),
    ("thematic map", "خريطة موضوعية"),
    ("remote sensing", "استشعار عن بعد"),
    ("satellite imagery", "صور فضائية"),
    ("land use", "استعمال الأرض"),
    ("population density", "كثافة سكانية"),
    ("crude birth rate", "معدل المواليد الخام"),
    ("crude death rate", "معدل الوفيات الخام"),
    ("total fertility rate", "معدل الخصوبة الكلي"),
    ("demographic transition", "تحول ديموغرافي"),
    ("migration push factor", "عامل طرد للهجرة"),
    ("migration pull factor", "عامل جذب للهجرة"),
    ("rural urban migration", "هجرة ريفية حضرية"),
    ("primate city", "مدينة مهيمنة"),
    ("central place theory", "نظرية المكان المركزي"),
    ("climate classification", "تصنيف المناخ"),
    ("tropical climate", "مناخ مداري"),
    ("desert climate", "مناخ صحراوي"),
    ("mediterranean climate", "مناخ متوسطي"),
    ("temperate climate", "مناخ معتدل"),
    ("polar climate", "مناخ قطبي"),
    ("monsoon climate", "مناخ موسمي"),
    ("orographic rainfall", "مطر تضاريسي"),
    ("convectional rainfall", "مطر حملي"),
    ("frontal rainfall", "مطر جبهي"),
    ("coriolis effect", "تأثير كوريوليس"),
    ("trade winds", "رياح تجارية"),
    ("prevailing westerlies", "رياح غربية سائدة"),
    ("jet stream", "تيار نفاث"),
    ("el nino phenomenon", "ظاهرة النينيو"),
    ("la nina phenomenon", "ظاهرة النينيا"),
    ("surface albedo", "وضاءة السطح"),
    ("physical weathering", "تجوية فيزيائية"),
    ("chemical weathering", "تجوية كيميائية"),
    ("surface erosion", "تعرية سطحية"),
    ("sediment deposition", "ترسيب الرواسب"),
    ("river delta", "دلتا نهرية"),
    ("river meander", "التواء نهري"),
    ("oxbow lake", "بحيرة هلالية"),
    ("flood plain", "سهل فيضي"),
    ("drainage basin", "حوض تصريف"),
    ("river tributary", "رافد نهري"),
    ("river confluence", "التقاء نهرين"),
    ("river estuary", "مصب خليجي"),
    ("continental shelf", "رصيف قاري"),
    ("abyssal plain", "سهل سحيق"),
    ("tsunami wave", "موجة تسونامي"),
    ("volcanic eruption", "ثوران بركاني"),
    ("magma chamber", "حجرة الصهارة"),
    ("lava flow", "دفق الحمم"),
    ("earthquake epicenter", "مركز الزلزال السطحي"),
    ("tectonic plate", "صفيحة تكتونية"),
    ("speech phoneme", "فونيم"),
    ("grammatical morpheme", "مورفيم صرفي"),
    ("sentence syntax", "تركيب الجملة"),
    ("lexical semantics", "دلالة معجمية"),
    ("linguistic pragmatics", "تداولية لسانية"),
    ("phonological system", "نظام صوتي وظيفي"),
    ("morphological analysis", "تحليل صرفي"),
    ("mental lexicon", "معجم ذهني"),
    ("prescriptive grammar", "قواعد معيارية"),
    ("descriptive grammar", "قواعد وصفية"),
    ("grammatical subject", "فاعل نحوي"),
    ("grammatical object", "مفعول نحوي"),
    ("dependent clause", "جملة تابعة"),
    ("independent clause", "جملة مستقلة"),
    ("noun phrase", "مركب اسمي"),
    ("verb phrase", "مركب فعلي"),
    ("active voice", "مبني للمعلوم"),
    ("passive voice", "مبني للمجهول"),
    ("grammatical tense", "زمن نحوي"),
    ("grammatical aspect", "جهة نحوية"),
    ("regional dialect", "لهجة إقليمية"),
    ("language register", "مستوى لغوي"),
    ("societal bilingualism", "ثنائية لغوية مجتمعية"),
    ("code switching", "تناوب لغوي"),
    ("first language acquisition", "اكتساب اللغة الأولى"),
    ("second language acquisition", "اكتساب اللغة الثانية"),
    ("communicative competence", "كفاية تواصلية"),
    ("discourse analysis", "تحليل الخطاب"),
    ("corpus linguistics", "لسانيات المدونة"),
    ("sociolinguistic study", "دراسة لسانية اجتماعية"),
    ("psycholinguistic study", "دراسة لسانية نفسية"),
    ("historical linguistics", "لسانيات تاريخية"),
    ("comparative linguistics", "لسانيات مقارنة"),
    ("translation studies", "دراسات الترجمة"),
    ("source language", "لغة المصدر"),
    ("target language", "لغة الهدف"),
    ("literal translation", "ترجمة حرفية"),
    ("free translation", "ترجمة حرة"),
    ("translation equivalence", "تكافؤ ترجمي"),
    ("laboratory beaker", "كأس مختبري"),
    ("erlenmeyer flask", "دورق إرلنماير"),
    ("volumetric flask", "دورق حجمي"),
    ("laboratory burette", "سحاحة مختبرية"),
    ("volumetric pipette", "ماصة حجمية"),
    ("graduated cylinder", "أسطوانة مدرجة"),
    ("test tube", "أنبوب اختبار"),
    ("watch glass", "زجاجة ساعة"),
    ("laboratory crucible", "بوتقة مختبرية"),
    ("bunsen burner", "موقد بنسن"),
    ("laboratory desiccator", "مجفف مختبري"),
    ("separating funnel", "قمع فصل"),
    ("buchner funnel", "قمع بوخنر"),
    ("mortar and pestle", "هاون ومدقة"),
    ("analytical balance", "ميزان تحليلي"),
    ("uv visible spectrophotometer", "مطياف فوق بنفسجي ومرئي"),
    ("laboratory centrifuge", "نابذة مختبرية"),
    ("steam autoclave", "موصدة بخارية"),
    ("laboratory incubator", "حاضنة مختبرية"),
    ("laminar flow hood", "غطاء تدفق صفائحي"),
    ("fume hood", "غطاء أبخرة"),
    ("petri dish", "طبق بتري"),
    ("inoculating loop", "إبرة زرع"),
    ("compound light microscope", "مجهر ضوئي مركب"),
    ("scanning electron microscope", "مجهر إلكتروني ماسح"),
    ("transmission electron microscope", "مجهر إلكتروني نافذ"),
    ("sodium chloride", "كلوريد الصوديوم"),
    ("hydrochloric acid solution", "محلول حمض الهيدروكلوريك"),
    ("sulfuric acid solution", "محلول حمض الكبريتيك"),
    ("nitric acid solution", "محلول حمض النتريك"),
    ("acetic acid solution", "محلول حمض الخليك"),
    ("sodium hydroxide solution", "محلول هيدروكسيد الصوديوم"),
    ("potassium hydroxide", "هيدروكسيد البوتاسيوم"),
    ("calcium carbonate", "كربونات الكالسيوم"),
    ("calcium hydroxide", "هيدروكسيد الكالسيوم"),
    ("calcium oxide", "أكسيد الكالسيوم"),
    ("carbon dioxide gas", "غاز ثاني أكسيد الكربون"),
    ("carbon monoxide gas", "غاز أول أكسيد الكربون"),
    ("ammonia gas", "غاز الأمونيا"),
    ("methane gas", "غاز الميثان"),
    ("ethane gas", "غاز الإيثان"),
    ("propane gas", "غاز البروبان"),
    ("butane gas", "غاز البيوتان"),
    ("ethanol solvent", "مذيب الإيثانول"),
    ("methanol solvent", "مذيب الميثانول"),
    ("glucose sugar", "سكر الغلوكوز"),
    ("fructose sugar", "سكر الفركتوز"),
    ("sucrose sugar", "سكر السكروز"),
    ("starch polysaccharide", "عديد سكر النشا"),
    ("cellulose polysaccharide", "عديد سكر السليلوز"),
    ("cholesterol molecule", "جزيء الكوليسترول"),
    ("triglyceride molecule", "جزيء ثلاثي الغليسريد"),
    ("phospholipid molecule", "جزيء الشحم الفوسفوري"),
    ("sodium bicarbonate", "بيكربونات الصوديوم"),
    ("magnesium sulfate", "كبريتات المغنيسيوم"),
    ("copper sulfate", "كبريتات النحاس"),
    ("silver nitrate", "نترات الفضة"),
    ("barium chloride", "كلوريد الباريوم"),
    ("potassium permanganate", "برمنغنات البوتاسيوم"),
    ("hydrogen peroxide", "فوق أكسيد الهيدروجين"),
    ("sulfur dioxide", "ثاني أكسيد الكبريت"),
    ("nitrogen dioxide", "ثاني أكسيد النتروجين"),
    ("nitric oxide", "أكسيد النتريك"),
    ("ozone molecule", "جزيء الأوزون"),
    ("water molecule", "جزيء الماء"),
    ("hydrogen element", "عنصر الهيدروجين"),
    ("helium element", "عنصر الهيليوم"),
    ("lithium element", "عنصر الليثيوم"),
    ("beryllium element", "عنصر البريليوم"),
    ("boron element", "عنصر البورون"),
    ("carbon element", "عنصر الكربون"),
    ("nitrogen element", "عنصر النتروجين"),
    ("oxygen element", "عنصر الأكسجين"),
    ("fluorine element", "عنصر الفلور"),
    ("neon element", "عنصر النيون"),
    ("sodium element", "عنصر الصوديوم"),
    ("magnesium element", "عنصر المغنيسيوم"),
    ("aluminum element", "عنصر الألمنيوم"),
    ("silicon element", "عنصر السيليكون"),
    ("phosphorus element", "عنصر الفوسفور"),
    ("sulfur element", "عنصر الكبريت"),
    ("chlorine element", "عنصر الكلور"),
    ("argon element", "عنصر الأرغون"),
    ("potassium element", "عنصر البوتاسيوم"),
    ("calcium element", "عنصر الكالسيوم"),
    ("iron element", "عنصر الحديد"),
    ("copper element", "عنصر النحاس"),
    ("zinc element", "عنصر الخارصين"),
    ("silver element", "عنصر الفضة"),
    ("gold element", "عنصر الذهب"),
    ("mercury element", "عنصر الزئبق"),
    ("lead element", "عنصر الرصاص"),
    ("tin element", "عنصر القصدير"),
    ("iodine element", "عنصر اليود"),
    ("uranium element", "عنصر اليورانيوم"),
    ("plutonium element", "عنصر البلوتونيوم"),
    ("literature review chapter", "فصل مراجعة الأدبيات"),
    ("research methodology chapter", "فصل منهجية البحث"),
    ("data analysis chapter", "فصل تحليل البيانات"),
    ("discussion chapter", "فصل المناقشة"),
    ("conclusion chapter", "فصل الخاتمة"),
    ("recommendation section", "قسم التوصيات"),
    ("study limitation", "محدودية الدراسة"),
    ("future research", "بحث مستقبلي"),
    ("conceptual definition", "تعريف مفاهيمي"),
    ("operational definition", "تعريف إجرائي"),
    ("independent variable definition", "تعريف المتغير المستقل"),
    ("dependent variable definition", "تعريف المتغير التابع"),
    ("control variable", "متغير ضابط"),
    ("extraneous variable", "متغير دخيل"),
    ("research hypothesis", "فرضية البحث"),
    ("null hypothesis statement", "نص الفرضية الصفرية"),
    ("alternative hypothesis statement", "نص الفرضية البديلة"),
    ("directional hypothesis", "فرضية موجهة"),
    ("nondirectional hypothesis", "فرضية غير موجهة"),
    ("pilot study", "دراسة استطلاعية"),
    ("main study", "الدراسة الرئيسة"),
    ("data collection instrument", "أداة جمع البيانات"),
    ("questionnaire design", "تصميم الاستبيان"),
    ("interview protocol", "دليل المقابلة"),
    ("focus group discussion", "حلقة نقاش مركزة"),
    ("observation checklist", "قائمة ملاحظة"),
    ("coding scheme", "مخطط الترميز"),
    ("intercoder reliability", "ثبات بين المرمزين"),
    ("descriptive statistics", "إحصاء وصفي"),
    ("inferential statistics", "إحصاء استدلالي"),
    ("frequency table", "جدول تكراري"),
    ("cross tabulation", "جدول تقاطعي"),
    ("bar chart", "مخطط أعمدة"),
    ("pie chart", "مخطط دائري"),
    ("line graph", "مخطط خطي"),
    ("error bar", "شريط الخطأ"),
    ("standard deviation value", "قيمة الانحراف المعياري"),
    ("mean difference", "فرق المتوسطات"),
    ("effect size measure", "مقياس حجم الأثر"),
    ("confidence interval estimate", "تقدير فترة الثقة"),
    ("statistical significance", "دلالة إحصائية"),
    ("practical significance", "دلالة عملية"),
    ("data normality", "اعتدالية البيانات"),
    ("outlier detection", "كشف القيم الشاذة"),
    ("missing data", "بيانات مفقودة"),
    ("data cleaning", "تنظيف البيانات"),
    ("reference list", "قائمة المراجع"),
    ("in text citation", "استشهاد داخل النص"),
    ("direct quotation", "اقتباس مباشر"),
    ("paraphrased source", "مصدر معاد صوغه"),
    ("academic writing style", "أسلوب الكتابة الأكاديمية"),
    ("topic sentence", "جملة الموضوع"),
    ("supporting sentence", "جملة داعمة"),
    ("cohesive device", "أداة تماسك"),
    ("transition word", "كلمة انتقال"),
    ("formal register", "مستوى رسمي"),
    ("objective tone", "نبرة موضوعية"),
    ("political system", "نظام سياسي"),
    ("presidential system", "نظام رئاسي"),
    ("parliamentary system", "نظام برلماني"),
    ("separation of powers doctrine", "مبدأ فصل السلطات"),
    ("checks and balances", "كوابح وتوازنات"),
    ("electoral system", "نظام انتخابي"),
    ("proportional representation", "تمثيل نسبي"),
    ("majority rule", "حكم الأغلبية"),
    ("political party", "حزب سياسي"),
    ("public opinion", "رأي عام"),
    ("political legitimacy", "شرعية سياسية"),
    ("civil society", "مجتمع مدني"),
    ("public policy", "سياسة عامة"),
    ("policy implementation", "تنفيذ السياسة"),
    ("policy evaluation", "تقويم السياسة"),
    ("foreign policy", "سياسة خارجية"),
    ("national security", "أمن قومي"),
    ("balance of power", "توازن القوى"),
    ("soft power", "قوة ناعمة"),
    ("hard power", "قوة صلبة"),
    ("international organization", "منظمة دولية"),
    ("united nations", "الأمم المتحدة"),
    ("security council", "مجلس الأمن"),
    ("general assembly", "الجمعية العامة"),
    ("non governmental organization", "منظمة غير حكومية"),
    ("gross national income", "الدخل القومي الإجمالي"),
    ("per capita income", "دخل الفرد"),
    ("gini coefficient", "معامل جيني"),
    ("human development index", "دليل التنمية البشرية"),
    ("purchasing power parity", "تعادل القوة الشرائية"),
    ("foreign direct investment", "استثمار أجنبي مباشر"),
    ("balance of trade", "ميزان تجاري"),
    ("tariff rate", "معدل التعرفة"),
    ("import quota", "حصة استيراد"),
    ("exchange rate regime", "نظام سعر الصرف"),
    ("fixed exchange rate", "سعر صرف ثابت"),
    ("floating exchange rate", "سعر صرف عائم"),
    ("inflation targeting", "استهداف التضخم"),
    ("central bank", "بنك مركزي"),
    ("monetary base", "قاعدة نقدية"),
    ("reserve requirement", "متطلب الاحتياطي"),
    ("open market operation", "عملية سوق مفتوحة"),
    ("discount rate", "سعر الخصم"),
    ("liquidity trap", "فخ السيولة"),
    ("crowding out effect", "أثر المزاحمة"),
    ("multiplier effect", "أثر المضاعف"),
    ("marginal propensity to consume", "الميل الحدي للاستهلاك"),
    ("marginal propensity to save", "الميل الحدي للادخار"),
    ("is lm model", "نموذج آي إس-إل إم"),
    ("aggregate demand curve", "منحنى الطلب الكلي"),
    ("aggregate supply curve", "منحنى العرض الكلي"),
    ("business cycle", "دورة الأعمال"),
    ("economic recession", "ركود اقتصادي"),
    ("economic depression", "كساد اقتصادي"),
    ("economic expansion", "توسع اقتصادي"),
    ("structural adjustment", "تكييف هيكلي"),
    ("comparative advantage theory", "نظرية الميزة النسبية"),
    ("opportunity cost concept", "مفهوم تكلفة الفرصة"),
    ("sunk cost", "تكلفة غارقة"),
    ("marginal analysis", "تحليل حدي"),
    ("break even analysis", "تحليل نقطة التعادل"),
    ("cost benefit analysis", "تحليل التكلفة والمنفعة"),
    ("net present value method", "طريقة صافي القيمة الحالية"),
    ("internal rate of return method", "طريقة معدل العائد الداخلي"),
    ("payback period method", "طريقة فترة الاسترداد"),
    ("working capital management", "إدارة رأس المال العامل"),
    ("capital budgeting", "موازنة رأسمالية"),
    ("capital structure", "هيكل رأس المال"),
    ("weighted average cost of capital", "متوسط تكلفة رأس المال المرجح"),
    ("financial leverage", "رفع مالي"),
    ("operating leverage", "رفع تشغيلي"),
    ("dividend policy", "سياسة توزيع الأرباح"),
    ("retained earnings", "أرباح محتجزة"),
    ("cash flow from operations", "تدفق نقدي من العمليات"),
    ("cash flow from investing", "تدفق نقدي من الاستثمار"),
    ("cash flow from financing", "تدفق نقدي من التمويل"),
    ("balance sheet equation", "معادلة الميزانية"),
    ("income statement item", "بند قائمة الدخل"),
    ("statement of changes in equity", "قائمة التغير في حقوق الملكية"),
    ("notes to financial statements", "إيضاحات القوائم المالية"),
    ("audit opinion", "رأي المدقق"),
    ("unqualified opinion", "رأي غير متحفظ"),
    ("qualified opinion", "رأي متحفظ"),
    ("adverse opinion", "رأي معاكس"),
    ("disclaimer of opinion", "امتناع عن إبداء الرأي"),
    ("internal audit", "تدقيق داخلي"),
    ("external audit", "تدقيق خارجي"),
    ("material misstatement", "تحريف جوهري"),
    ("going concern assumption", "فرض الاستمرارية"),
    ("accrual accounting", "محاسبة الاستحقاق"),
    ("cash accounting", "محاسبة نقدية"),
    ("double entry bookkeeping", "مسك دفاتر القيد المزدوج"),
    ("chart of accounts structure", "هيكل دليل الحسابات"),
    ("subsidiary ledger", "دفتر أستاذ مساعد"),
    ("control account", "حساب مراقبة"),
    ("bank reconciliation statement", "كشف التسوية البنكية"),
    ("petty cash fund", "سلفة النثرية"),
    ("inventory valuation", "تقييم المخزون"),
    ("lower of cost or market", "التكلفة أو السوق أيهما أقل"),
    ("depreciation method", "طريقة الإهلاك"),
    ("straight line method", "طريقة القسط الثابت"),
    ("declining balance method", "طريقة القسط المتناقص"),
    ("impairment loss", "خسارة انخفاض القيمة"),
    ("provision for doubtful debts", "مخصص الديون المشكوك فيها"),
    ("contingent liability", "التزام محتمل"),
    ("deferred tax", "ضريبة مؤجلة"),
    ("earnings management", "إدارة الأرباح"),
    ("corporate governance", "حوكمة الشركات"),
    ("board of directors", "مجلس الإدارة"),
    ("shareholder equity", "حقوق المساهمين"),
    ("stakeholder theory", "نظرية أصحاب المصلحة"),
    ("agency theory", "نظرية الوكالة"),
    ("swot matrix", "مصفوفة سوات"),
    ("pestel analysis", "تحليل بستل"),
    ("porter five forces", "قوى بورتر الخمس"),
    ("value chain analysis", "تحليل سلسلة القيمة"),
    ("competitive advantage", "ميزة تنافسية"),
    ("market segmentation", "تجزئة السوق"),
    ("target market", "سوق مستهدف"),
    ("market positioning", "تموضع سوقي"),
    ("marketing mix", "المزيج التسويقي"),
    ("product life cycle", "دورة حياة المنتج"),
    ("brand equity", "قيمة العلامة"),
    ("customer relationship management", "إدارة علاقة العملاء"),
    ("supply chain integration", "تكامل سلسلة الإمداد"),
    ("just in time system", "نظام الوقت المحدد"),
    ("total quality management system", "نظام إدارة الجودة الشاملة"),
    ("kaizen philosophy", "فلسفة كايزن"),
    ("six sigma process", "عملية ستة سيغما"),
    ("key performance indicator", "مؤشر أداء رئيس"),
    ("balanced scorecard", "بطاقة الأداء المتوازن"),
    ("organizational structure", "هيكل تنظيمي"),
    ("span of control", "نطاق الإشراف"),
    ("chain of command", "سلسلة القيادة"),
    ("delegation of authority", "تفويض السلطة"),
    ("centralization of authority", "مركزية السلطة"),
    ("decentralization of authority", "لامركزية السلطة"),
    ("motivation theory", "نظرية الدافعية"),
    ("maslow hierarchy of needs", "هرم ماسلو للحاجات"),
    ("herzberg two factor theory", "نظرية هيرزبرغ ذات العاملين"),
    ("expectancy theory", "نظرية التوقع"),
    ("leadership style", "نمط القيادة"),
    ("transformational leadership", "قيادة تحويلية"),
    ("transactional leadership", "قيادة تبادلية"),
    ("situational leadership", "قيادة موقفية"),
    ("human resource planning", "تخطيط الموارد البشرية"),
    ("job analysis", "تحليل الوظيفة"),
    ("job description", "وصف الوظيفة"),
    ("job specification", "مواصفات شاغل الوظيفة"),
    ("recruitment process", "عملية الاستقطاب"),
    ("selection process", "عملية الاختيار"),
    ("performance appraisal", "تقويم الأداء"),
    ("training needs analysis", "تحليل احتياجات التدريب"),
    ("compensation system", "نظام التعويضات"),
    ("employee turnover", "دوران العاملين"),
    ("organizational culture", "ثقافة تنظيمية"),
    ("change management", "إدارة التغيير"),
    ("conflict management", "إدارة الصراع"),
    ("negotiation process", "عملية التفاوض"),
    ("decision making process", "عملية صنع القرار"),
    ("bounded rationality", "عقلانية محدودة"),
    ("groupthink phenomenon", "ظاهرة التفكير الجمعي"),
]
