"""مصطلحات الحاسوب والشبكات والاقتصاد والمحاسبة والإدارة وعلم النفس والعمارة."""

from __future__ import annotations

CS_ENTRIES: list[tuple[str, str]] = [
    ("abstract data type", "نوع بيانات مجرد"),
    ("singly linked list", "قائمة مترابطة أحادية"),
    ("doubly linked list", "قائمة مترابطة مزدوجة"),
    ("circular linked list", "قائمة مترابطة دائرية"),
    ("stack data structure", "بنية بيانات المكدس"),
    ("queue data structure", "بنية بيانات الطابور"),
    ("priority queue", "طابور أولوية"),
    ("deque data structure", "طابور مزدوج النهاية"),
    ("binary heap", "كومة ثنائية"),
    ("min heap", "كومة صغرى"),
    ("max heap", "كومة كبرى"),
    ("binary search tree property", "خاصية شجرة البحث الثنائية"),
    ("avl tree", "شجرة إيه في إل"),
    ("red black tree", "شجرة حمراء سوداء"),
    ("b tree", "شجرة بي"),
    ("b plus tree", "شجرة بي زائد"),
    ("trie data structure", "بنية بيانات التراي"),
    ("hash collision", "تصادم التجزئة"),
    ("separate chaining", "السلسلة المنفصلة"),
    ("open addressing", "العنونة المفتوحة"),
    ("linear probing", "سبر خطي"),
    ("quadratic probing", "سبر تربيعي"),
    ("double hashing", "تجزئة مزدوجة"),
    ("load factor of hash table", "معامل تحميل جدول التجزئة"),
    ("adjacency list", "قائمة تجاور"),
    ("adjacency matrix representation", "تمثيل بمصفوفة التجاور"),
    ("depth first traversal", "اجتياز بالعمق"),
    ("breadth first traversal", "اجتياز بالعرض"),
    ("topological sort", "فرز طوبولوجي"),
    ("strongly connected component", "مكون شديد الترابط"),
    ("shortest path algorithm", "خوارزمية أقصر مسار"),
    ("greedy choice property", "خاصية الاختيار الجشع"),
    ("optimal substructure", "بنية جزئية مثلى"),
    ("divide and conquer strategy", "استراتيجية فرق تسد"),
    ("master theorem", "المبرهنة الرئيسية"),
    ("recurrence solution", "حل علاقة التراجع"),
    ("amortized analysis", "تحليل مطفأ"),
    ("big omega notation", "ترميز أوميغا الكبير"),
    ("big theta notation", "ترميز ثيتا الكبير"),
    ("worst case complexity", "تعقيد أسوأ حالة"),
    ("average case complexity", "تعقيد الحالة المتوسطة"),
    ("best case complexity", "تعقيد أفضل حالة"),
    ("space complexity analysis", "تحليل تعقيد الحيز"),
    ("in place algorithm", "خوارزمية في المكان"),
    ("stable sorting", "فرز مستقر"),
    ("comparison sort", "فرز بالمقارنة"),
    ("merge sort", "فرز بالدمج"),
    ("quick sort", "فرز سريع"),
    ("heap sort", "فرز كومة"),
    ("insertion sort", "فرز بالإدراج"),
    ("selection sort", "فرز بالاختيار"),
    ("bubble sort", "فرز فقاعي"),
    ("counting sort", "فرز بالعد"),
    ("radix sort", "فرز أساسه"),
    ("bucket sort", "فرز بالدلاء"),
    ("binary search algorithm", "خوارزمية البحث الثنائي"),
    ("linear search algorithm", "خوارزمية البحث الخطي"),
    ("interpolation search", "بحث بالاستيفاء"),
    ("knapsack problem", "مسألة الحقيبة"),
    ("traveling salesman problem", "مسألة البائع المتجول"),
    ("np complete problem", "مسألة تامة من صنف إن بي"),
    ("np hard problem", "مسألة صعبة من صنف إن بي"),
    ("polynomial time", "زمن كثير الحدود"),
    ("exponential time", "زمن أسي"),
    ("process control block", "كتلة تحكم العملية"),
    ("context switching overhead", "كلفة تبديل السياق"),
    ("cpu scheduling", "جدولة المعالج"),
    ("first come first served", "الأول وصولا الأول خدمة"),
    ("shortest job first", "الأقصر أولا"),
    ("round robin scheduling", "جدولة الدور الدوري"),
    ("priority scheduling", "جدولة بالأولوية"),
    ("multilevel queue scheduling", "جدولة طوابير متعددة المستويات"),
    ("preemptive scheduling", "جدولة استباقية"),
    ("nonpreemptive scheduling", "جدولة غير استباقية"),
    ("turnaround time", "زمن الإنجاز"),
    ("waiting time of process", "زمن انتظار العملية"),
    ("response time of process", "زمن استجابة العملية"),
    ("cpu utilization", "استخدام المعالج"),
    ("throughput of system", "إنتاجية النظام"),
    ("deadlock prevention", "منع التوقف التام"),
    ("deadlock avoidance", "تجنب التوقف التام"),
    ("deadlock detection", "كشف التوقف التام"),
    ("banker algorithm", "خوارزمية المصرفي"),
    ("resource allocation graph", "بيان تخصيص الموارد"),
    ("mutual exclusion condition", "شرط الاستبعاد المتبادل"),
    ("hold and wait", "الاحتجاز والانتظار"),
    ("no preemption condition", "شرط عدم الاستباق"),
    ("circular wait", "الانتظار الدائري"),
    ("paging memory", "ذاكرة بالصفحات"),
    ("segmentation memory", "ذاكرة بالقطع"),
    ("page table", "جدول الصفحات"),
    ("translation lookaside buffer", "مخزن الترجمة الجانبي"),
    ("page replacement", "استبدال الصفحات"),
    ("fifo page replacement", "استبدال الصفحات بالأول دخولا"),
    ("least recently used", "الأقل استخداما مؤخرا"),
    ("optimal page replacement", "استبدال الصفحات الأمثل"),
    ("thrashing condition", "حالة الانهيار الأدائي"),
    ("working set model", "نموذج مجموعة العمل"),
    ("internal fragmentation", "تجزؤ داخلي"),
    ("external fragmentation", "تجزؤ خارجي"),
    ("compaction of memory", "رص الذاكرة"),
    ("demand paging", "تصفيح عند الطلب"),
    ("copy on write", "نسخ عند الكتابة"),
    ("file allocation table", "جدول تخصيص الملفات"),
    ("indexed allocation", "تخصيص مفهرس"),
    ("contiguous allocation", "تخصيص متجاور"),
    ("linked allocation", "تخصيص مترابط"),
    ("directory structure", "بنية الدليل"),
    ("absolute path", "مسار مطلق"),
    ("relative path", "مسار نسبي"),
    ("access control list", "قائمة تحكم بالوصول"),
    ("discretionary access control", "تحكم وصول تقديري"),
    ("mandatory access control", "تحكم وصول إلزامي"),
    ("user mode", "وضع المستخدم"),
    ("kernel mode", "وضع النواة"),
    ("system call", "نداء نظام"),
    ("interrupt handler", "معالج المقاطعة"),
    ("device driver", "برنامج تعريف الجهاز"),
    ("spooling technique", "تقنية التخزين المؤقت للطابعة"),
    ("compiler phases", "مراحل المترجم"),
    ("lexical analysis", "تحليل معجمي"),
    ("syntax analysis", "تحليل نحوي"),
    ("semantic analysis", "تحليل دلالي"),
    ("intermediate code", "شفرة وسيطة"),
    ("code optimization", "تحسين الشفرة"),
    ("code generation", "توليد الشفرة"),
    ("symbol table", "جدول الرموز"),
    ("parse tree", "شجرة إعراب"),
    ("abstract syntax tree", "شجرة نحو مجردة"),
    ("regular expression", "تعبير منتظم"),
    ("finite automaton", "آلية منتهية"),
    ("deterministic finite automaton", "آلية منتهية حتمية"),
    ("nondeterministic finite automaton", "آلية منتهية غير حتمية"),
    ("pushdown automaton", "آلية بمكدس"),
    ("turing machine", "آلة تورنغ"),
    ("context free grammar", "قواعد خالية من السياق"),
    ("chomsky normal form", "شكل تشومسكي الطبيعي"),
    ("first and follow sets", "مجموعتا الأول والتالي"),
    ("ll parser", "محلل إل إل"),
    ("lr parser", "محلل إل آر"),
    ("shift reduce parsing", "إعراب بالإزاحة والاختزال"),
    ("object oriented design", "تصميم كائني التوجه"),
    ("class diagram", "مخطط الأصناف"),
    ("sequence diagram", "مخطط التسلسل"),
    ("use case diagram", "مخطط حالات الاستخدام"),
    ("activity diagram", "مخطط النشاط"),
    ("state diagram", "مخطط الحالة"),
    ("inheritance hierarchy", "تسلسل الوراثة"),
    ("method overriding", "إعادة تعريف الدالة"),
    ("method overloading", "زيادة تحميل الدالة"),
    ("dynamic binding", "ربط ديناميكي"),
    ("static binding", "ربط ساكن"),
    ("interface segregation", "فصل الواجهات"),
    ("dependency inversion", "قلب التبعية"),
    ("single responsibility", "مسؤولية واحدة"),
    ("open closed principle", "مبدأ الفتح والإغلاق"),
    ("liskov substitution", "استبدال ليسكوف"),
    ("design pattern", "نمط تصميم"),
    ("singleton pattern", "نمط المفرد"),
    ("factory pattern", "نمط المصنع"),
    ("observer pattern", "نمط المراقب"),
    ("strategy pattern", "نمط الاستراتيجية"),
    ("adapter pattern", "نمط المهايئ"),
    ("decorator pattern", "نمط المزين"),
    ("unit testing", "اختبار وحدة"),
    ("integration testing", "اختبار تكامل"),
    ("system testing", "اختبار النظام"),
    ("regression testing", "اختبار الانحدار"),
    ("black box testing", "اختبار الصندوق الأسود"),
    ("white box testing", "اختبار الصندوق الأبيض"),
    ("test case specification", "مواصفة حالة الاختبار"),
    ("software requirements", "متطلبات البرمجيات"),
    ("functional requirement", "متطلب وظيفي"),
    ("nonfunctional requirement", "متطلب غير وظيفي"),
    ("software development life cycle", "دورة حياة تطوير البرمجيات"),
    ("waterfall model", "نموذج الشلال"),
    ("agile methodology", "منهجية أجايل"),
    ("scrum framework", "إطار سكرم"),
    ("sprint planning", "تخطيط السبرنت"),
    ("version control system", "نظام إدارة الإصدارات"),
    ("branch and merge", "تفرع ودمج"),
    ("continuous integration", "تكامل مستمر"),
    ("continuous delivery", "تسليم مستمر"),
    ("relational model", "نموذج علائقي"),
    ("entity relationship diagram", "مخطط الكيانات والعلاقات"),
    ("cardinality of relationship", "أساسية العلاقة"),
    ("participation constraint", "قيد المشاركة"),
    ("weak entity", "كيان ضعيف"),
    ("strong entity", "كيان قوي"),
    ("candidate key", "مفتاح مرشح"),
    ("super key", "مفتاح فائق"),
    ("composite key", "مفتاح مركب"),
    ("first normal form", "الصيغة الطبيعية الأولى"),
    ("second normal form", "الصيغة الطبيعية الثانية"),
    ("third normal form", "الصيغة الطبيعية الثالثة"),
    ("boyce codd normal form", "صيغة بويس-كود الطبيعية"),
    ("functional dependency", "تبعية دالية"),
    ("transitive dependency", "تبعية متعدية"),
    ("lossless decomposition", "تفكيك دون فقد"),
    ("dependency preservation", "حفظ التبعيات"),
    ("sql select statement", "عبارة الاختيار في لغة الاستعلام"),
    ("sql join operation", "عملية الربط في لغة الاستعلام"),
    ("group by clause", "عبارة التجميع"),
    ("having clause", "عبارة التصفية بعد التجميع"),
    ("nested query", "استعلام متداخل"),
    ("correlated subquery", "استعلام فرعي مرتبط"),
    ("transaction isolation level", "مستوى عزل المعاملة"),
    ("dirty read", "قراءة وسخة"),
    ("nonrepeatable read", "قراءة غير قابلة للتكرار"),
    ("phantom read", "قراءة شبحية"),
    ("two phase locking", "قفل ثنائي الطور"),
    ("write ahead logging", "تسجيل قبل الكتابة"),
    ("checkpoint recovery", "استعادة بنقطة فحص"),
    ("b tree index", "فهرس شجرة بي"),
    ("hash index", "فهرس تجزئة"),
    ("query optimization", "تحسين الاستعلام"),
    ("osi reference model", "النموذج المرجعي للاتصال المفتوح"),
    ("physical layer", "الطبقة الفيزيائية"),
    ("data link layer", "طبقة ربط البيانات"),
    ("network layer", "طبقة الشبكة"),
    ("transport layer", "طبقة النقل"),
    ("session layer", "طبقة الجلسة"),
    ("presentation layer", "طبقة العرض"),
    ("application layer", "طبقة التطبيق"),
    ("tcp three way handshake", "المصافحة الثلاثية لبروتوكول التحكم بالنقل"),
    ("tcp congestion control", "تحكم ازدحام بروتوكول النقل"),
    ("slow start algorithm", "خوارزمية البداية البطيئة"),
    ("sliding window protocol", "بروتوكول النافذة المنزلقة"),
    ("stop and wait protocol", "بروتوكول التوقف والانتظار"),
    ("go back n protocol", "بروتوكول الرجوع بعدد"),
    ("selective repeat protocol", "بروتوكول التكرار الانتقائي"),
    ("cyclic redundancy check", "فحص التكرار الدوري"),
    ("hamming code", "ترميز هامنغ"),
    ("parity bit", "بت التكافؤ"),
    ("manchester encoding", "ترميز مانشستر"),
    ("amplitude shift keying", "تعديل بإزاحة السعة"),
    ("frequency shift keying", "تعديل بإزاحة التردد"),
    ("phase shift keying", "تعديل بإزاحة الطور"),
    ("quadrature amplitude modulation", "تعديل سعوي تربيعي"),
    ("nyquist sampling theorem", "مبرهنة نيكويست لأخذ العينات"),
    ("shannon capacity", "سعة شانون"),
    ("channel capacity", "سعة القناة"),
    ("bandwidth delay product", "جداء عرض النطاق والتأخير"),
    ("packet switching", "تبديل الحزم"),
    ("circuit switching", "تبديل الدارات"),
    ("routing algorithm", "خوارزمية التوجيه"),
    ("distance vector routing", "توجيه بمتجه المسافة"),
    ("link state routing", "توجيه بحالة الوصلة"),
    ("ip subnetting", "تجزئة عناوين بروتوكول الإنترنت"),
    ("classless inter domain routing", "توجيه بين النطاقات دون أصناف"),
    ("network address translation", "ترجمة عنوان الشبكة"),
    ("address resolution protocol", "بروتوكول تحليل العنوان"),
    ("dynamic host configuration", "تهيئة المضيف الديناميكية"),
    ("domain name resolution", "تحليل اسم النطاق"),
    ("hypertext transfer", "نقل النص التشعبي"),
    ("secure socket layer", "طبقة المقابس الآمنة"),
    ("transport layer security", "أمن طبقة النقل"),
    ("public key infrastructure", "بنية المفتاح العام"),
    ("digital certificate", "شهادة رقمية"),
    ("symmetric encryption", "تشفير متناظر"),
    ("asymmetric encryption", "تشفير غير متناظر"),
    ("advanced encryption standard", "معيار التشفير المتقدم"),
    ("rivest shamir adleman", "خوارزمية ريفيست شامير أدلمان"),
    ("diffie hellman exchange", "تبادل ديفي-هلمان"),
    ("cryptographic hash", "تجزئة تعموية"),
    ("message authentication code", "رمز مصادقة الرسالة"),
    ("digital signature algorithm", "خوارزمية التوقيع الرقمي"),
    ("man in the middle attack", "هجوم الرجل في الوسط"),
    ("denial of service attack", "هجوم حرمان الخدمة"),
    ("distributed denial of service", "حرمان خدمة موزع"),
    ("sql injection", "حقن لغة الاستعلام"),
    ("cross site scripting", "تنفيذ عبر المواقع"),
    ("buffer overflow", "طفحان المخزن"),
    ("firewall rule", "قاعدة جدار ناري"),
    ("intrusion detection system", "نظام كشف التسلل"),
    ("intrusion prevention system", "نظام منع التسلل"),
    ("virtual private network", "شبكة خاصة افتراضية"),
    ("wireless security protocol", "بروتوكول أمن لاسلكي"),
    ("convolutional layer", "طبقة تلافيفية"),
    ("pooling layer", "طبقة تجميع"),
    ("fully connected layer", "طبقة متصلة كليا"),
    ("softmax function", "دالة سوفتماكس"),
    ("relu activation", "تنشيط الوحدة الخطية المصححة"),
    ("sigmoid activation", "تنشيط سيغمويد"),
    ("tanh activation", "تنشيط الظل الزائدي"),
    ("backpropagation algorithm", "خوارزمية الانتشار العكسي"),
    ("stochastic gradient descent", "نزول التدرج العشوائي"),
    ("mini batch gradient descent", "نزول التدرج بالدفعات الصغيرة"),
    ("learning rate schedule", "جدولة معدل التعلم"),
    ("weight initialization", "تهيئة الأوزان"),
    ("batch normalization layer", "طبقة تطبيع الدفعة"),
    ("dropout regularization", "تنظيم بالإسقاط"),
    ("l2 regularization", "تنظيم إل-2"),
    ("early stopping", "إيقاف مبكر"),
    ("confusion matrix metrics", "مقاييس مصفوفة الالتباس"),
    ("precision metric", "مقياس الإحكام"),
    ("recall metric", "مقياس الاستدعاء"),
    ("f1 score metric", "مقياس إف-1"),
    ("roc curve", "منحنى خاصية تشغيل المستقبل"),
    ("area under curve", "المساحة تحت المنحنى"),
    ("k fold cross validation", "تحقق متقاطع بطيات"),
    ("bias variance tradeoff", "موازنة الانحياز والتباين"),
    ("underfitting model", "نموذج قاصر الملاءمة"),
    ("overfitting model", "نموذج مفرط الملاءمة"),
    ("feature scaling", "تحجيم السمات"),
    ("one hot encoding", "ترميز أحادي ساخن"),
    ("dimensionality reduction", "خفض الأبعاد"),
    ("k nearest neighbors", "الجيران الأقرب"),
    ("naive bayes classifier", "مصنف بايز الساذج"),
    ("decision tree classifier", "مصنف شجرة القرار"),
    ("random forest classifier", "مصنف الغابة العشوائية"),
    ("support vector classifier", "مصنف المتجهات الداعمة"),
    ("linear regression model", "نموذج الانحدار الخطي"),
    ("logistic regression classifier", "مصنف الانحدار اللوجستي"),
    ("clustering algorithm", "خوارزمية التجميع"),
    ("elbow method", "طريقة الكوع"),
    ("silhouette score", "درجة الصورة الظلية"),
    ("word embedding", "تضمين الكلمات"),
    ("attention mechanism", "آلية الانتباه"),
    ("transformer model", "نموذج المحول"),
    ("recurrent layer", "طبقة تكرارية"),
    ("vanishing gradient", "تلاشي التدرج"),
    ("exploding gradient", "انفجار التدرج"),
    ("transfer learning", "تعلم منقول"),
    ("fine tuning model", "ضبط دقيق للنموذج"),
    ("law of demand", "قانون الطلب"),
    ("law of supply", "قانون العرض"),
    ("market equilibrium", "توازن السوق"),
    ("price elasticity of demand", "مرونة الطلب السعرية"),
    ("income elasticity of demand", "مرونة الطلب الدخلية"),
    ("cross elasticity of demand", "مرونة الطلب التقاطعية"),
    ("consumer surplus", "فائض المستهلك"),
    ("producer surplus", "فائض المنتج"),
    ("deadweight loss", "خسارة الموزن الميت"),
    ("marginal utility", "منفعة حدية"),
    ("diminishing marginal utility", "تناقص المنفعة الحدية"),
    ("indifference curve", "منحنى السواء"),
    ("budget constraint", "قيد الميزانية"),
    ("marginal rate of substitution", "معدل الإحلال الحدي"),
    ("production function", "دالة الإنتاج"),
    ("marginal product", "ناتج حدي"),
    ("average product", "ناتج متوسط"),
    ("law of diminishing returns", "قانون تناقص الغلة"),
    ("economies of scale", "وفورات الحجم"),
    ("diseconomies of scale", "تبذيرات الحجم"),
    ("short run cost", "تكلفة الأجل القصير"),
    ("long run cost", "تكلفة الأجل الطويل"),
    ("average total cost", "متوسط التكلفة الكلية"),
    ("average variable cost", "متوسط التكلفة المتغيرة"),
    ("average fixed cost", "متوسط التكلفة الثابتة"),
    ("marginal cost curve", "منحنى التكلفة الحدية"),
    ("perfect competition", "منافسة تامة"),
    ("monopoly market", "سوق احتكار"),
    ("monopolistic competition", "منافسة احتكارية"),
    ("oligopoly market", "سوق احتكار القلة"),
    ("price discrimination", "تمييز سعري"),
    ("game theory equilibrium", "توازن نظرية الألعاب"),
    ("nash equilibrium", "توازن ناش"),
    ("gross domestic product components", "مكونات الناتج المحلي الإجمالي"),
    ("nominal gdp", "ناتج محلي اسمي"),
    ("real gdp", "ناتج محلي حقيقي"),
    ("gdp deflator", "مكماش الناتج"),
    ("consumer price index", "رقم قياسي لأسعار المستهلك"),
    ("inflation rate", "معدل التضخم"),
    ("unemployment rate", "معدل البطالة"),
    ("frictional unemployment", "بطالة احتكاكية"),
    ("structural unemployment", "بطالة هيكلية"),
    ("cyclical unemployment", "بطالة دورية"),
    ("phillips curve", "منحنى فيليبس"),
    ("aggregate demand", "طلب كلي"),
    ("aggregate supply", "عرض كلي"),
    ("fiscal policy", "سياسة مالية"),
    ("monetary policy", "سياسة نقدية"),
    ("money supply", "عرض النقد"),
    ("money demand", "طلب النقد"),
    ("interest rate", "سعر الفائدة"),
    ("exchange rate", "سعر الصرف"),
    ("balance of payments", "ميزان المدفوعات"),
    ("current account", "حساب جار"),
    ("capital account", "حساب رأس المال"),
    ("trade balance", "ميزان تجاري"),
    ("comparative advantage", "ميزة نسبية"),
    ("absolute advantage", "ميزة مطلقة"),
    ("tariff barrier", "حاجز جمركي"),
    ("quota restriction", "قيد الحصة"),
    ("journal entry", "قيد يومية"),
    ("debit entry", "قيد مدين"),
    ("credit entry", "قيد دائن"),
    ("chart of accounts", "دليل الحسابات"),
    ("general journal", "يومية عامة"),
    ("general ledger account", "حساب دفتر الأستاذ"),
    ("trial balance preparation", "إعداد ميزان المراجعة"),
    ("adjusting entry", "قيد تسوية"),
    ("closing entry", "قيد إقفال"),
    ("accrual basis", "أساس الاستحقاق"),
    ("cash basis", "أساس نقدي"),
    ("revenue recognition", "الاعتراف بالإيراد"),
    ("matching principle", "مبدأ المقابلة"),
    ("going concern", "الاستمرارية"),
    ("historical cost", "التكلفة التاريخية"),
    ("fair value", "القيمة العادلة"),
    ("accounts receivable turnover", "دوران الذمم المدينة"),
    ("inventory turnover", "دوران المخزون"),
    ("current ratio", "نسبة التداول"),
    ("quick ratio", "نسبة السيولة السريعة"),
    ("debt to equity ratio", "نسبة الدين إلى حقوق الملكية"),
    ("return on assets", "العائد على الأصول"),
    ("return on equity", "العائد على حقوق الملكية"),
    ("gross profit margin", "هامش مجمل الربح"),
    ("net profit margin", "هامش صافي الربح"),
    ("earnings per share", "ربحية السهم"),
    ("straight line depreciation", "إهلاك القسط الثابت"),
    ("declining balance depreciation", "إهلاك القسط المتناقص"),
    ("units of production depreciation", "إهلاك وحدات الإنتاج"),
    ("accumulated depreciation", "مجمع الإهلاك"),
    ("prepaid expense", "مصروف مدفوع مقدما"),
    ("accrued expense", "مصروف مستحق"),
    ("unearned revenue", "إيراد غير مكتسب"),
    ("accrued revenue", "إيراد مستحق"),
    ("cost of goods sold", "تكلفة البضاعة المباعة"),
    ("fifo inventory method", "طريقة الوارد أولا صادر أولا"),
    ("lifo inventory method", "طريقة الوارد أخيرا صادر أولا"),
    ("weighted average cost", "متوسط التكلفة المرجح"),
    ("bank reconciliation", "تسوية بنكية"),
    ("petty cash", "صندوق نثري"),
    ("internal control", "رقابة داخلية"),
    ("audit trail", "مسار تدقيق"),
    ("materiality concept", "مفهوم الأهمية النسبية"),
    ("conservatism principle", "مبدأ الحيطة"),
    ("project charter", "ميثاق المشروع"),
    ("work breakdown structure diagram", "مخطط هيكل تجزئة العمل"),
    ("critical path", "المسار الحرج"),
    ("float time", "زمن الفائض"),
    ("total float", "الفائض الكلي"),
    ("free float", "الفائض الحر"),
    ("gantt chart", "مخطط غانت"),
    ("pert chart", "مخطط تقييم ومراجعة البرامج"),
    ("earned value", "القيمة المكتسبة"),
    ("planned value", "القيمة المخططة"),
    ("actual cost of work", "التكلفة الفعلية للعمل"),
    ("cost variance", "انحراف التكلفة"),
    ("schedule variance", "انحراف الجدول"),
    ("cost performance index", "مؤشر أداء التكلفة"),
    ("schedule performance index", "مؤشر أداء الجدول"),
    ("risk register", "سجل المخاطر"),
    ("qualitative risk analysis", "تحليل مخاطر نوعي"),
    ("quantitative risk analysis", "تحليل مخاطر كمي"),
    ("risk response plan", "خطة الاستجابة للمخاطر"),
    ("stakeholder analysis", "تحليل أصحاب المصلحة"),
    ("scope baseline", "خط أساس النطاق"),
    ("change control", "ضبط التغيير"),
    ("quality management plan", "خطة إدارة الجودة"),
    ("statistical process control", "ضبط إحصائي للعملية"),
    ("control chart", "مخطط ضبط"),
    ("pareto chart", "مخطط باريتو"),
    ("cause and effect diagram", "مخطط السبب والأثر"),
    ("six sigma methodology", "منهجية ستة سيغما"),
    ("lean manufacturing", "تصنيع رشيق"),
    ("kaizen improvement", "تحسين كايزن"),
    ("just in time inventory", "مخزون في الوقت المحدد"),
    ("economic order quantity", "كمية الطلب الاقتصادية"),
    ("reorder point", "نقطة إعادة الطلب"),
    ("safety stock", "مخزون أمان"),
    ("lead time", "زمن التوريد"),
    ("supply chain management", "إدارة سلسلة الإمداد"),
    ("bullwhip effect", "تأثير السوط"),
    ("classical conditioning theory", "نظرية الإشراط الكلاسيكي"),
    ("operant conditioning theory", "نظرية الإشراط الإجرائي"),
    ("positive reinforcement", "تعزيز إيجابي"),
    ("negative reinforcement", "تعزيز سلبي"),
    ("positive punishment", "عقاب إيجابي"),
    ("negative punishment", "عقاب سلبي"),
    ("extinction of behavior", "انطفاء السلوك"),
    ("observational learning", "تعلم بالملاحظة"),
    ("working memory model", "نموذج الذاكرة العاملة"),
    ("sensory memory", "ذاكرة حسية"),
    ("long term potentiation", "تقوية طويلة الأمد"),
    ("cognitive dissonance", "تنافر معرفي"),
    ("confirmation bias", "انحياز التأكيد"),
    ("availability heuristic", "حدس التوفر"),
    ("representativeness heuristic", "حدس التمثيل"),
    ("maslow hierarchy", "هرم ماسلو"),
    ("intrinsic motivation", "دافع داخلي"),
    ("extrinsic motivation", "دافع خارجي"),
    ("self efficacy", "كفاءة ذاتية"),
    ("locus of control", "مصدر الضبط"),
    ("attachment theory", "نظرية التعلق"),
    ("piaget stages", "مراحل بياجيه"),
    ("sensorimotor stage", "المرحلة الحسحركية"),
    ("preoperational stage", "مرحلة ما قبل العمليات"),
    ("concrete operational stage", "مرحلة العمليات الحسية"),
    ("formal operational stage", "مرحلة العمليات الشكلية"),
    ("zone of proximal development", "منطقة النمو القريب"),
    ("null hypothesis significance testing", "اختبار دلالة الفرضية الصفرية"),
    ("effect size", "حجم الأثر"),
    ("statistical power analysis", "تحليل القوة الإحصائية"),
    ("confidence interval interpretation", "تفسير فترة الثقة"),
    ("random assignment", "تعيين عشوائي"),
    ("random selection", "اختيار عشوائي"),
    ("confounding variable", "متغير مربك"),
    ("mediating variable", "متغير وسيط"),
    ("moderating variable", "متغير معدل"),
    ("internal validity", "صدق داخلي"),
    ("external validity", "صدق خارجي"),
    ("construct validity", "صدق البناء"),
    ("reliability of measurement", "ثبات القياس"),
    ("test retest reliability", "ثبات إعادة الاختبار"),
    ("inter rater reliability", "ثبات بين المقدرين"),
    ("cronbach alpha", "ألفا كرونباخ"),
    ("likert scale", "مقياس ليكرت"),
    ("qualitative coding", "ترميز نوعي"),
    ("thematic analysis", "تحليل موضوعي"),
    ("grounded theory", "نظرية متجذرة"),
    ("ethnographic study", "دراسة إثنوغرافية"),
    ("case study design", "تصميم دراسة الحالة"),
    ("longitudinal design", "تصميم طولي"),
    ("cross sectional design", "تصميم مقطعي"),
    ("meta analysis study", "دراسة تحليل تلوي"),
    ("systematic review", "مراجعة منهجية"),
    ("literature review section", "قسم مراجعة الأدبيات"),
    ("research question", "سؤال بحثي"),
    ("conceptual framework", "إطار مفاهيمي"),
    ("theoretical framework", "إطار نظري"),
    ("sampling frame", "إطار المعاينة"),
    ("simple random sample", "عينة عشوائية بسيطة"),
    ("stratified random sample", "عينة عشوائية طبقية"),
    ("cluster sample", "عينة عنقودية"),
    ("convenience sample", "عينة ميسرة"),
    ("snowball sample", "عينة كرة الثلج"),
    ("sample size determination", "تحديد حجم العينة"),
    ("margin of error", "هامش الخطأ"),
    ("response rate", "معدل الاستجابة"),
    ("informed consent procedure", "إجراء الموافقة المستنيرة"),
    ("research ethics", "أخلاقيات البحث"),
    ("floor plan drawing", "رسم المسقط الأفقي"),
    ("elevation drawing", "رسم الواجهة"),
    ("section drawing", "رسم المقطع"),
    ("site analysis", "تحليل الموقع"),
    ("building orientation", "توجيه المبنى"),
    ("natural ventilation", "تهوية طبيعية"),
    ("daylight factor", "معامل الإضاءة الطبيعية"),
    ("thermal comfort", "راحة حرارية"),
    ("acoustic comfort", "راحة صوتية"),
    ("reverberation time", "زمن الترداد"),
    ("sound transmission class", "صنف انتقال الصوت"),
    ("u value of wall", "قيمة العبور الحراري للجدار"),
    ("r value of insulation", "قيمة المقاومة الحرارية للعزل"),
    ("thermal bridge", "جسر حراري"),
    ("vapor barrier", "حاجز بخار"),
    ("waterproofing membrane", "غشاء عزل مائي"),
    ("expansion joint in building", "فاصل تمدد في المبنى"),
    ("load bearing masonry", "بناء حامل"),
    ("curtain wall system", "نظام جدار ستائري"),
    ("space frame", "إطار فراغي"),
    ("shell structure", "منشأ قشري"),
    ("folded plate", "بلاطة مطوية"),
    ("span to depth ratio", "نسبة البحر إلى العمق"),
    ("floor area ratio limit", "حد نسبة مساحة الطوابق"),
    ("building setback", "ارتداد المبنى"),
    ("occupancy load", "حمل الإشغال"),
    ("means of egress", "وسائل الخروج"),
    ("fire compartmentation", "تقسيم حريق"),
    ("universal design", "تصميم شامل"),
    ("accessible route", "مسار ميسر"),
    ("modular coordination", "تنسيق نمطي"),
    ("grid planning", "تخطيط شبكي"),
    ("circulation diagram", "مخطط الحركة"),
    ("bubble diagram", "مخطط فقاعي"),
    ("conceptual design", "تصميم مفاهيمي"),
    ("schematic design", "تصميم تخطيطي"),
    ("design development", "تطوير التصميم"),
    ("construction documents", "وثائق التنفيذ"),
    ("bill of quantities", "جدول الكميات"),
    ("cost estimate", "تقدير التكلفة"),
    ("life cycle cost", "تكلفة دورة الحياة"),
    ("building information model", "نموذج معلومات البناء"),
    ("clash detection", "كشف التعارض"),
    ("parametric design", "تصميم بارامتري"),
]
