"""مصطلحات الهندسة: مدني، تربة، مياه، كهرباء، ميكانيك، كيمياء، نفط، مواد."""

from __future__ import annotations

ENG_ENTRIES: list[tuple[str, str]] = [
    ("superstructure element", "عنصر البنية الفوقية"),
    ("substructure element", "عنصر البنية التحتية"),
    ("bridge abutment", "كتف الجسر"),
    ("bridge pier", "ركيزة الجسر"),
    ("bridge girder", "جائز الجسر"),
    ("beam flange", "شفة الجائز"),
    ("beam web", "جانة الجائز"),
    ("fillet weld", "لحام زاوي"),
    ("butt weld", "لحام تناكبي"),
    ("high strength bolt", "برغي عالي المقاومة"),
    ("gusset plate", "صفيحة وصل"),
    ("base plate", "صفيحة قاعدة"),
    ("anchor bolt", "برغي تثبيت"),
    ("expansion joint", "فاصل تمدد"),
    ("construction joint", "فاصل صب"),
    ("contraction joint", "فاصل تقلص"),
    ("waterstop strip", "شريط مانع للتسرب"),
    ("concrete admixture", "مضاف خرساني"),
    ("water reducing admixture", "مضاف مخفض للماء"),
    ("air entraining admixture", "مضاف حابس للهواء"),
    ("water cement ratio", "نسبة الماء إلى الأسمنت"),
    ("concrete workability", "قابلية تشغيل الخرسانة"),
    ("concrete segregation", "انفصال مكونات الخرسانة"),
    ("concrete bleeding", "نضح الخرسانة"),
    ("concrete shrinkage", "انكماش الخرسانة"),
    ("concrete creep", "زحف الخرسانة"),
    ("reinforcement cover", "غطاء التسليح"),
    ("effective depth", "العمق الفعال"),
    ("neutral axis", "المحور المحايد"),
    ("lever arm", "ذراع العزم"),
    ("balanced section", "مقطع متوازن"),
    ("under reinforced section", "مقطع ناقص التسليح"),
    ("over reinforced section", "مقطع زائد التسليح"),
    ("modular ratio", "النسبة المعيارية"),
    ("transformed section", "مقطع محوّل"),
    ("critical section", "مقطع حرج"),
    ("main reinforcement", "تسليح رئيسي"),
    ("distribution reinforcement", "تسليح توزيع"),
    ("compression reinforcement", "تسليح الضغط"),
    ("tension reinforcement", "تسليح الشد"),
    ("torsion reinforcement", "تسليح اللي"),
    ("temperature reinforcement", "تسليح الحرارة"),
    ("stirrup spacing", "تباعد الكانات"),
    ("standard hook", "عكفة قياسية"),
    ("development length of bar", "طول تثبيت القضيب"),
    ("lap length", "طول التراكب"),
    ("one way slab design", "تصميم بلاطة باتجاه واحد"),
    ("two way slab design", "تصميم بلاطة باتجاهين"),
    ("flat slab design", "تصميم بلاطة مسطحة"),
    ("punching shear check", "تحقق القص الثاقب"),
    ("short column design", "تصميم عمود قصير"),
    ("slender column design", "تصميم عمود نحيف"),
    ("biaxial bending", "انحناء ثنائي المحور"),
    ("uniaxial bending", "انحناء أحادي المحور"),
    ("axial load", "حمل محوري"),
    ("eccentric load", "حمل لامركزي"),
    ("uniformly distributed load", "حمل موزع بانتظام"),
    ("concentrated load", "حمل مركز"),
    ("triangular load", "حمل مثلثي"),
    ("moving load", "حمل متحرك"),
    ("impact load", "حمل صدم"),
    ("earthquake load", "حمل زلزالي"),
    ("snow load", "حمل الثلج"),
    ("factored load", "حمل مصعّد"),
    ("service load", "حمل الخدمة"),
    ("characteristic strength", "مقاومة مميزة"),
    ("design strength", "مقاومة تصميمية"),
    ("partial safety factor", "معامل أمان جزئي"),
    ("load factor", "معامل الحمل"),
    ("shape factor", "معامل الشكل"),
    ("plastic analysis", "تحليل لدن"),
    ("collapse mechanism", "آلية الانهيار"),
    ("static indeterminacy", "عدم التعيين السكوني"),
    ("kinematic indeterminacy", "عدم التعيين الحركي"),
    ("degree of redundancy", "درجة الزيادة"),
    ("stiffness method", "طريقة الجسوءة"),
    ("flexibility method", "طريقة المرونة"),
    ("displacement method", "طريقة الإزاحات"),
    ("force method", "طريقة القوى"),
    ("moment area method", "طريقة العزم والمساحة"),
    ("conjugate beam method", "طريقة الجائز المرافق"),
    ("three moment theorem", "مبرهنة العزوم الثلاثة"),
    ("castigliano theorem", "مبرهنة كاستيليانو"),
    ("virtual work principle", "مبدأ الشغل الافتراضي"),
    ("maxwell reciprocal theorem", "مبرهنة ماكسويل التبادلية"),
    ("shear force diagram", "مخطط قوة القص"),
    ("bending moment diagram", "مخطط عزم الانحناء"),
    ("point of contraflexure", "نقطة انقلاب العزم"),
    ("fixed end moment", "عزم الطرف المثبت"),
    ("carry over factor", "معامل النقل"),
    ("distribution factor", "معامل التوزيع"),
    ("simply supported span", "بحر بسيط الاستناد"),
    ("continuous beam span", "بحر جائز مستمر"),
    ("propped cantilever beam", "جائز كابولي مسنود"),
    ("fixed end beam", "جائز مثبت الطرفين"),
    ("overhanging beam", "جائز ذو طرف ناتئ"),
    ("pinned support", "مسند مفصلي"),
    ("roller support", "مسند متدحرج"),
    ("fixed support", "مسند مثبت"),
    ("simple support", "مسند بسيط"),
    ("elastic support", "مسند مرن"),
    ("support settlement", "هبوط المسند"),
    ("temperature stress", "إجهاد حراري"),
    ("residual stress", "إجهاد متبق"),
    ("allowable stress", "إجهاد مسموح"),
    ("proof stress", "إجهاد الضمان"),
    ("maximum shear stress", "إجهاد القص الأعظم"),
    ("combined stress state", "حالة إجهاد مركب"),
    ("brittle failure", "انهيار هش"),
    ("ductile failure", "انهيار لدن"),
    ("fatigue failure", "انهيار بالكلال"),
    ("local buckling", "انبعاج موضعي"),
    ("lateral torsional buckling", "انبعاج جانبي التوائي"),
    ("euler buckling load", "حمل انبعاج أويلر"),
    ("slenderness ratio", "نسبة النحافة"),
    ("effective length", "طول فعال"),
    ("end restraint condition", "شرط تقييد الطرف"),
    ("immediate deflection", "سهم آني"),
    ("long term deflection", "سهم طويل الأمد"),
    ("deflection limit", "حد السهم"),
    ("crack width", "عرض الشق"),
    ("exposure class", "صنف التعرض"),
    ("fire resistance rating", "تصنيف مقاومة الحريق"),
    ("formwork system", "نظام القالب"),
    ("scaffolding system", "نظام السقالة"),
    ("temporary shoring", "تدعيم مؤقت"),
    ("underpinning work", "تدعيم تحت الأساس"),
    ("dewatering system", "نظام نزح المياه"),
    ("sheet pile wall", "جدار ألواح وتدية"),
    ("cofferdam structure", "سد صندوقي مؤقت"),
    ("pile cap", "قلنسوة الأوتاد"),
    ("pile group", "مجموعة أوتاد"),
    ("end bearing pile", "وتد ارتكاز"),
    ("friction pile", "وتد احتكاك"),
    ("bored pile", "وتد محفور"),
    ("driven pile", "وتد مدقوق"),
    ("negative skin friction", "احتكاك سطحي سالب"),
    ("pile integrity test", "اختبار سلامة الوتد"),
    ("soil nailing", "تسمير التربة"),
    ("ground anchor", "مرساة أرضية"),
    ("gravity retaining wall", "جدار ساند ثقلي"),
    ("cantilever retaining wall", "جدار ساند كابولي"),
    ("counterfort retaining wall", "جدار ساند بكتف"),
    ("gabion wall", "جدار أقفاص حجرية"),
    ("geotextile fabric", "نسيج أرضي"),
    ("geomembrane liner", "غشاء أرضي"),
    ("geogrid reinforcement", "تسليح بشبكة أرضية"),
    ("lime stabilization", "تثبيت بالكلس"),
    ("cement stabilization", "تثبيت بالأسمنت"),
    ("optimum moisture content", "محتوى الرطوبة الأمثل"),
    ("maximum dry density", "الكثافة الجافة العظمى"),
    ("relative compaction", "الرص النسبي"),
    ("relative density of soil", "الكثافة النسبية للتربة"),
    ("void ratio", "نسبة الفراغات"),
    ("degree of saturation", "درجة التشبع"),
    ("specific gravity of solids", "الوزن النوعي للحبيبات"),
    ("bulk unit weight", "وزن وحدة الحجم الكلي"),
    ("dry unit weight", "وزن وحدة الحجم الجاف"),
    ("saturated unit weight", "وزن وحدة الحجم المشبع"),
    ("submerged unit weight", "وزن وحدة الحجم المغمور"),
    ("coefficient of permeability", "معامل النفاذية"),
    ("hydraulic conductivity", "موصلية هيدروليكية"),
    ("seepage flow", "جريان التسرب"),
    ("flow net", "شبكة الجريان"),
    ("soil liquefaction", "تمييع التربة"),
    ("piping failure", "انهيار بالأنابيب"),
    ("coefficient of consolidation", "معامل الانضمام"),
    ("compression index", "دليل الانضغاط"),
    ("swelling index", "دليل الانتفاخ"),
    ("preconsolidation pressure", "ضغط الانضمام المسبق"),
    ("overconsolidation ratio", "نسبة فرط الانضمام"),
    ("normally consolidated clay", "غضار منضم طبيعيا"),
    ("overconsolidated clay", "غضار مفرط الانضمام"),
    ("primary consolidation", "انضمام أولي"),
    ("secondary compression", "انضغاط ثانوي"),
    ("time factor", "عامل الزمن"),
    ("drainage path length", "طول مسار التصريف"),
    ("prefabricated vertical drain", "مصرف شاقولي مسبق الصنع"),
    ("surcharge preloading", "تحميل مسبق بردم"),
    ("undrained shear strength", "مقاومة القص غير المصرفة"),
    ("drained shear strength", "مقاومة القص المصرفة"),
    ("mohr coulomb criterion", "معيار مور-كولوم"),
    ("unconfined compression test", "اختبار الضغط غير المحصور"),
    ("vane shear test", "اختبار القص بالمروحة"),
    ("cone penetration test", "اختبار الاختراق بالمخروط"),
    ("borehole log", "سجل البئر الاستكشافي"),
    ("undisturbed sample", "عينة غير مشوشة"),
    ("disturbed sample", "عينة مشوشة"),
    ("groundwater table", "منسوب المياه الجوفية"),
    ("drawdown of water table", "هبوط منسوب الماء"),
    ("theis equation", "معادلة ثايس"),
    ("aquifer transmissivity", "ناقلية الخزان الجوفي"),
    ("aquifer storativity", "معامل تخزين الخزان"),
    ("specific yield of aquifer", "العطاء النوعي للخزان"),
    ("cone of depression", "مخروط الانخفاض"),
    ("radius of influence", "نصف قطر التأثير"),
    ("specific capacity of well", "السعة النوعية للبئر"),
    ("open channel flow", "جريان القنوات المفتوحة"),
    ("critical flow", "جريان حرج"),
    ("subcritical flow", "جريان دون الحرج"),
    ("supercritical flow", "جريان فوق الحرج"),
    ("hydraulic jump", "قفزة هيدروليكية"),
    ("specific energy", "طاقة نوعية"),
    ("specific force", "قوة نوعية"),
    ("gradually varied flow", "جريان متغير تدريجيا"),
    ("rapidly varied flow", "جريان متغير بسرعة"),
    ("manning roughness", "خشونة ماننغ"),
    ("chezy coefficient", "معامل شيزي"),
    ("weir discharge", "تصريف الهدار"),
    ("sharp crested weir", "هدار حاد القمة"),
    ("broad crested weir", "هدار عريض القمة"),
    ("orifice discharge", "تصريف الفوهة"),
    ("sluice gate", "بوابة قناة"),
    ("stilling basin", "حوض تهدئة"),
    ("spillway structure", "مفيض"),
    ("gravity dam", "سد ثقلي"),
    ("arch dam", "سد قوسي"),
    ("embankment dam", "سد ترابي"),
    ("seepage through dam", "تسرب عبر السد"),
    ("phreatic line", "خط التشبع"),
    ("filter drain", "مصرف مرشح"),
    ("riprap protection", "حماية بالرمي الحجاري"),
    ("design flood", "فيضان تصميمي"),
    ("probable maximum flood", "الفيضان الأعظم المحتمل"),
    ("unit hydrograph", "مخطط مائي واحدي"),
    ("rational method", "الطريقة المنطقية"),
    ("time of concentration", "زمن التركيز"),
    ("runoff coefficient", "معامل الجريان السطحي"),
    ("rainfall intensity", "شدة المطر"),
    ("infiltration capacity", "سعة الرشح"),
    ("evapotranspiration loss", "فقد التبخر والنتح"),
    ("reservoir routing", "تتبع الخزان"),
    ("channel routing", "تتبع القناة"),
    ("water treatment plant", "محطة معالجة المياه"),
    ("wastewater treatment plant", "محطة معالجة مياه الصرف"),
    ("coagulation process", "عملية التخثير"),
    ("flocculation process", "عملية التنديف"),
    ("sedimentation tank", "حوض ترسيب"),
    ("rapid sand filter", "مرشح رملي سريع"),
    ("slow sand filter", "مرشح رملي بطيء"),
    ("chlorine disinfection", "تعقيم بالكلور"),
    ("break point chlorination", "كلورة نقطة الانكسار"),
    ("hardness of water", "عسرة الماء"),
    ("alkalinity of water", "قلوية الماء"),
    ("turbidity of water", "عكارة الماء"),
    ("dissolved oxygen", "أكسجين مذاب"),
    ("biochemical oxygen demand test", "اختبار طلب الأكسجين الحيوي"),
    ("chemical oxygen demand test", "اختبار طلب الأكسجين الكيميائي"),
    ("activated sludge process", "عملية الحمأة المنشطة"),
    ("trickling filter", "مرشح نضح"),
    ("aeration tank", "حوض تهوية"),
    ("secondary clarifier", "مرسب ثانوي"),
    ("sludge digestion", "هضم الحمأة"),
    ("sludge dewatering", "نزع ماء الحمأة"),
    ("sewer network", "شبكة مجاري"),
    ("storm sewer", "مجرور مطري"),
    ("sanitary sewer", "مجرور صحي"),
    ("manhole structure", "منهل"),
    ("population equivalent", "مكافئ سكاني"),
    ("design period", "مدة التصميم"),
    ("peak factor", "معامل الذروة"),
    ("fire demand", "احتياج الحريق"),
    ("water distribution network", "شبكة توزيع المياه"),
    ("service reservoir", "خزان خدمة"),
    ("rising main", "خط دفع"),
    ("gravity main", "خط جاذبية"),
    ("flexible pavement design", "تصميم الرصف المرن"),
    ("rigid pavement design", "تصميم الرصف الصلب"),
    ("california bearing ratio", "نسبة تحمل كاليفورنيا"),
    ("equivalent single axle load", "حمل المحور المفرد المكافئ"),
    ("pavement layer", "طبقة الرصف"),
    ("subbase layer", "طبقة ما تحت الأساس"),
    ("binder course", "طبقة رابطة"),
    ("surface course", "طبقة سطحية"),
    ("prime coat", "طبقة تشريب"),
    ("tack coat", "طبقة لاصقة"),
    ("marshall mix design", "تصميم خلطة مارشال"),
    ("bitumen grade", "درجة البيتومين"),
    ("aggregate gradation", "تدرج الركام"),
    ("los angeles abrasion", "اهتراء لوس أنجلس"),
    ("flakiness index", "دليل التفلطح"),
    ("elongation index", "دليل الاستطالة"),
    ("impact value of aggregate", "قيمة صدم الركام"),
    ("crushing value of aggregate", "قيمة سحق الركام"),
    ("sight distance", "مسافة الرؤية"),
    ("stopping sight distance design", "تصميم مسافة الرؤية للتوقف"),
    ("overtaking sight distance", "مسافة رؤية التجاوز"),
    ("super elevation", "ميل عرضي"),
    ("transition curve", "منحنى انتقالي"),
    ("clothoid spiral", "منحنى قماشي"),
    ("summit curve", "منحنى قمة"),
    ("valley curve", "منحنى وادي"),
    ("design speed", "سرعة تصميمية"),
    ("traffic capacity", "سعة المرور"),
    ("passenger car unit", "وحدة سيارة مكافئة"),
    ("annual average daily traffic", "معدل المرور اليومي السنوي"),
    ("level of service concept", "مفهوم مستوى الخدمة"),
    ("signal cycle time", "زمن دورة الإشارة"),
    ("saturation flow", "جريان الإشباع"),
    ("green time", "زمن الأخضر"),
    ("intergreen time", "زمن بين الأخضر"),
    ("queue length", "طول الطابور"),
    ("origin destination survey", "مسح المنشأ والمقصد"),
    ("modal split", "توزيع الوسائط"),
    ("trip generation", "توليد الرحلات"),
    ("trip distribution", "توزيع الرحلات"),
    ("traffic assignment", "تعيين المرور"),
    ("theodolite traverse", "مضلع بالثيودوليت"),
    ("closed traverse", "مضلع مغلق"),
    ("open traverse", "مضلع مفتوح"),
    ("latitude departure", "مركبة العرض والانحراف"),
    ("bowditch rule", "قاعدة بووديتش"),
    ("transit rule", "قاعدة العبور"),
    ("contour interval", "فترة الكنتور"),
    ("horizontal equivalent", "المكافئ الأفقي"),
    ("reduced level", "منسوب مختزل"),
    ("back sight reading", "قراءة خلفية"),
    ("fore sight reading", "قراءة أمامية"),
    ("intermediate sight", "قراءة وسطية"),
    ("height of instrument", "ارتفاع الجهاز"),
    ("rise and fall method", "طريقة الصعود والهبوط"),
    ("height of collimation method", "طريقة ارتفاع خط النظر"),
    ("local attraction", "جذب موضعي"),
    ("magnetic bearing", "انحراف مغناطيسي"),
    ("true bearing", "انحراف حقيقي"),
    ("whole circle bearing", "انحراف الدائرة الكاملة"),
    ("reduced bearing", "انحراف ربعي"),
    ("closing error", "خطأ الإغلاق"),
    ("plane table survey", "مسح باللوحة المستوية"),
    ("tachometric survey", "مسح تاكيومتري"),
    ("global positioning survey", "مسح بنظام تحديد المواقع"),
    ("digital elevation model", "نموذج ارتفاعات رقمي"),
    ("geographic coordinate system", "نظام إحداثيات جغرافي"),
    ("projected coordinate system", "نظام إحداثيات مسقط"),
    ("universal transverse mercator", "مسقط مركاتور المستعرض العالمي"),
    ("synchronous speed", "سرعة تزامنية"),
    ("rotor speed", "سرعة الدوار"),
    ("slip of induction motor", "انزلاق المحرك الحثي"),
    ("torque speed curve", "منحنى العزم والسرعة"),
    ("starting torque", "عزم الإقلاع"),
    ("breakdown torque", "عزم الانهيار"),
    ("full load torque", "عزم الحمل الكامل"),
    ("locked rotor current", "تيار الدوار المقفل"),
    ("no load current", "تيار اللاحمل"),
    ("power factor correction", "تصحيح معامل القدرة"),
    ("capacitor bank", "مجموعة مكثفات"),
    ("synchronous condenser", "مكثف تزامني"),
    ("voltage drop", "هبوط الجهد"),
    ("short circuit capacity", "سعة القصر"),
    ("fault current", "تيار العطل"),
    ("symmetrical fault", "عطل متماثل"),
    ("unsymmetrical fault", "عطل غير متماثل"),
    ("single line to ground fault", "عطل خط إلى الأرض"),
    ("line to line fault", "عطل خط إلى خط"),
    ("double line to ground fault", "عطل خطين إلى الأرض"),
    ("three phase fault", "عطل ثلاثي الطور"),
    ("bus admittance matrix", "مصفوفة مسايرة القضبان"),
    ("bus impedance matrix", "مصفوفة ممانعة القضبان"),
    ("newton raphson load flow", "سريان أحمال نيوتن-رافسون"),
    ("gauss seidel load flow", "سريان أحمال غاوس-سايدل"),
    ("fast decoupled load flow", "سريان أحمال مفصول سريع"),
    ("economic dispatch", "توزيع اقتصادي"),
    ("unit commitment", "التزام الوحدات"),
    ("automatic generation control", "تحكم آلي بالتوليد"),
    ("load frequency control", "تحكم حمل-تردد"),
    ("swing equation", "معادلة التأرجح"),
    ("equal area criterion", "معيار المساحات المتساوية"),
    ("critical clearing time", "زمن الفصل الحرج"),
    ("power system stability", "استقرار منظومة القدرة"),
    ("steady state stability", "استقرار الحالة المستقرة"),
    ("dynamic stability", "استقرار ديناميكي"),
    ("voltage stability", "استقرار الجهد"),
    ("reactive power compensation", "تعويض القدرة المفاعلة"),
    ("shunt capacitor", "مكثف تفرعي"),
    ("series capacitor", "مكثف تسلسلي"),
    ("static var compensator", "معوض قدرة مفاعلة ساكن"),
    ("flexible ac transmission", "نقل تيار متناوب مرن"),
    ("high voltage direct current", "تيار مستمر عالي الجهد"),
    ("overhead transmission line", "خط نقل هوائي"),
    ("underground cable", "كابل أرضي"),
    ("corona loss", "فقد الهالة"),
    ("skin effect loss", "فقد التأثير السطحي"),
    ("proximity effect loss", "فقد تأثير التجاور"),
    ("sag of conductor", "ارتخاء الموصل"),
    ("string efficiency", "كفاءة سلسلة العوازل"),
    ("lightning surge", "صدمة صاعقة"),
    ("switching surge", "صدمة فتح وإغلاق"),
    ("insulation coordination", "تنسيق العزل"),
    ("protective relaying", "حماية بالمرحلات"),
    ("overcurrent relay", "مرحّل زيادة التيار"),
    ("distance relay", "مرحّل مسافة"),
    ("differential relay", "مرحّل تفاضلي"),
    ("buchholz relay", "مرحّل بوخهولز"),
    ("circuit breaker rating", "مقنن قاطع الدائرة"),
    ("arc quenching", "إخماد القوس"),
    ("current chopping", "قطع التيار المبكر"),
    ("restriking voltage", "جهد إعادة القدح"),
    ("recovery voltage", "جهد الاستعادة"),
    ("instrument transformer", "محول قياس"),
    ("burden of transformer", "حمل محول القياس"),
    ("transformer efficiency", "مردود المحول"),
    ("voltage regulation of transformer", "تنظيم جهد المحول"),
    ("equivalent circuit of transformer", "دارة مكافئة للمحول"),
    ("open circuit test", "اختبار الدارة المفتوحة"),
    ("short circuit test", "اختبار دارة القصر"),
    ("all day efficiency", "مردود اليوم الكامل"),
    ("auto transformer", "محول ذاتي"),
    ("three phase transformer", "محول ثلاثي الطور"),
    ("star delta starter", "مقلع نجمة-مثلث"),
    ("direct online starter", "مقلع مباشر"),
    ("soft starter", "مقلع ناعم"),
    ("variable speed drive", "سوق متغير السرعة"),
    ("pulse width modulated inverter", "عاكس بتعديل عرض النبضة"),
    ("thyristor rectifier", "مقوم ثايرستوري"),
    ("chopper converter", "مقطع جهد مستمر"),
    ("buck converter", "محول خافض"),
    ("boost converter", "محول رافع"),
    ("buck boost converter", "محول خافض رافع"),
    ("flyback converter", "محول ارتدادي"),
    ("forward converter", "محول أمامي"),
    ("total harmonic distortion limit", "حد التشوه التوافقي الكلي"),
    ("power quality disturbance", "اضطراب جودة القدرة"),
    ("voltage sag", "انخفاض جهد لحظي"),
    ("voltage swell", "ارتفاع جهد لحظي"),
    ("harmonic filter", "مرشح توافقيات"),
    ("first law energy balance", "موازنة طاقة القانون الأول"),
    ("second law statement", "نص القانون الثاني"),
    ("carnot efficiency", "مردود كارنو"),
    ("entropy generation", "توليد الإنتروبيا"),
    ("availability of energy", "الإتاحية"),
    ("irreversibility loss", "فقد اللاانعكاسية"),
    ("isentropic efficiency", "مردود متساوي الإنتروبيا"),
    ("polytropic process", "عملية متعددة الخواص"),
    ("ideal gas process", "عملية غاز مثالي"),
    ("otto cycle efficiency", "مردود دورة أوتو"),
    ("diesel cycle efficiency", "مردود دورة ديزل"),
    ("dual cycle", "دورة مزدوجة"),
    ("brayton cycle", "دورة برايتون"),
    ("rankine cycle efficiency", "مردود دورة رانكن"),
    ("regenerative rankine cycle", "دورة رانكن باسترجاع"),
    ("reheat rankine cycle", "دورة رانكن بإعادة التسخين"),
    ("vapor compression refrigeration", "تبريد بانضغاط البخار"),
    ("vapor absorption refrigeration", "تبريد بامتصاص البخار"),
    ("ton of refrigeration", "طن تبريد"),
    ("refrigerating effect", "الأثر التبريدي"),
    ("coefficient of performance value", "قيمة معامل الأداء"),
    ("psychrometric process", "عملية على مخطط الهواء الرطب"),
    ("sensible heating", "تسخين محسوس"),
    ("sensible cooling", "تبريد محسوس"),
    ("humidification process", "عملية ترطيب"),
    ("dehumidification process", "عملية إزالة رطوبة"),
    ("cooling tower", "برج تبريد"),
    ("approach of cooling tower", "اقتراب برج التبريد"),
    ("range of cooling tower", "مدى برج التبريد"),
    ("fouling factor", "معامل التوسخ"),
    ("effectiveness ntu method", "طريقة الفعالية وعدد وحدات الانتقال"),
    ("log mean temperature difference", "متوسط فرق الحرارة اللوغاريتمي"),
    ("critical radius of insulation", "نصف القطر الحرج للعزل"),
    ("fin efficiency", "مردود الزعنفة"),
    ("fin effectiveness", "فعالية الزعنفة"),
    ("black body radiation", "إشعاع الجسم الأسود"),
    ("view factor", "معامل الرؤية"),
    ("stefan boltzmann law", "قانون ستيفان-بولتزمان"),
    ("wien displacement law", "قانون فين للإزاحة"),
    ("laminar boundary layer", "طبقة حدية صفائحية"),
    ("turbulent boundary layer", "طبقة حدية مضطربة"),
    ("boundary layer separation", "انفصال الطبقة الحدية"),
    ("drag coefficient", "معامل السحب"),
    ("lift coefficient", "معامل الرفع"),
    ("mach number value", "قيمة عدد ماخ"),
    ("reynolds number value", "قيمة عدد رينولدز"),
    ("froude number", "عدد فرود"),
    ("weber number", "عدد ويبر"),
    ("euler number", "عدد أويلر"),
    ("nusselt number value", "قيمة عدد نسلت"),
    ("prandtl number value", "قيمة عدد برانتل"),
    ("grashof number", "عدد غراشوف"),
    ("stanton number", "عدد ستانتون"),
    ("darcy friction factor", "معامل احتكاك دارسي"),
    ("moody chart", "مخطط مودي"),
    ("minor losses", "فواقد موضعية"),
    ("major losses", "فواقد احتكاكية"),
    ("pump characteristic curve", "منحنى خصائص المضخة"),
    ("system curve", "منحنى المنظومة"),
    ("best efficiency point", "نقطة المردود الأفضل"),
    ("net positive suction head available", "صافي ضغط السحب المتاح"),
    ("net positive suction head required", "صافي ضغط السحب المطلوب"),
    ("cavitation inception", "بدء التكهف"),
    ("specific speed of pump", "السرعة النوعية للمضخة"),
    ("affinity laws", "قوانين التشابه"),
    ("spur gear tooth", "سن الترس العدل"),
    ("gear module", "معيار الترس"),
    ("circular pitch", "خطوة دائرية"),
    ("diametral pitch", "خطوة قطرية"),
    ("pressure angle", "زاوية الضغط"),
    ("contact ratio", "نسبة التماس"),
    ("backlash of gears", "خلوص التروس"),
    ("epicyclic gear train", "قطار تروس كوكبي"),
    ("velocity ratio", "نسبة السرعة"),
    ("mechanical advantage", "فائدة آلية"),
    ("cam profile", "مقطع الحدبة"),
    ("follower motion", "حركة التابع"),
    ("simple harmonic motion of follower", "حركة توافقية بسيطة للتابع"),
    ("flywheel design", "تصميم الحذافة"),
    ("coefficient of fluctuation of speed", "معامل تذبذب السرعة"),
    ("turning moment diagram", "مخطط عزم التدوير"),
    ("balancing of rotating masses", "موازنة الكتل الدوارة"),
    ("balancing of reciprocating masses", "موازنة الكتل الترددية"),
    ("critical speed of shaft", "السرعة الحرجة للعمود"),
    ("whirling of shaft", "دوران العمود الاضطرابي"),
    ("torsion of circular shaft", "لي العمود الدائري"),
    ("angle of twist", "زاوية اللي"),
    ("polar section modulus", "معامل المقطع القطبي"),
    ("journal bearing design", "تصميم المحمل المنزلق"),
    ("sommerfeld number", "عدد سومرفيلد"),
    ("hydrodynamic lubrication", "تزييت هيدروديناميكي"),
    ("boundary lubrication", "تزييت حدي"),
    ("rolling contact bearing", "محمل تماس دحروجي"),
    ("bearing life", "عمر المحمل"),
    ("static load rating", "مقنن الحمل الساكن"),
    ("dynamic load rating", "مقنن الحمل الديناميكي"),
    ("sn diagram", "مخطط الإجهاد وعدد الدورات"),
    ("endurance limit stress", "إجهاد حد الكلال"),
    ("fatigue stress concentration factor", "معامل تركيز إجهاد الكلال"),
    ("goodman criterion", "معيار غودمان"),
    ("soderberg criterion", "معيار سودربرغ"),
    ("gerber criterion", "معيار غيربر"),
    ("miner rule", "قاعدة ماينر"),
    ("fracture toughness value", "قيمة متانة الكسر"),
    ("stress intensity factor", "معامل شدة الإجهاد"),
    ("paris law", "قانون باريس"),
    ("ductile to brittle transition", "انتقال من السلوك اللدن إلى الهش"),
    ("charpy impact test", "اختبار صدم تشاربي"),
    ("izod impact test", "اختبار صدم آيزود"),
    ("brinell hardness", "صلادة برينل"),
    ("rockwell hardness", "صلادة روكويل"),
    ("vickers hardness", "صلادة فيكرز"),
    ("tensile test", "اختبار الشد"),
    ("compression test", "اختبار الضغط"),
    ("young modulus value", "قيمة معامل يونغ"),
    ("poisson ratio value", "قيمة نسبة بواسون"),
    ("shear modulus value", "قيمة معامل القص"),
    ("bulk modulus value", "قيمة معامل الحجم"),
    ("yield point", "نقطة الخضوع"),
    ("ultimate tensile stress", "إجهاد الشد الأقصى"),
    ("percent elongation", "نسبة الاستطالة"),
    ("percent reduction in area", "نسبة نقص المساحة"),
    ("true stress", "إجهاد حقيقي"),
    ("true strain", "انفعال حقيقي"),
    ("engineering stress", "إجهاد هندسي"),
    ("engineering strain", "انفعال هندسي"),
    ("strain hardening", "تقسية بالانفعال"),
    ("necking phenomenon", "ظاهرة التعنق"),
    ("mild steel", "فولاذ طري"),
    ("high carbon steel", "فولاذ عالي الكربون"),
    ("alloy steel", "فولاذ سبائكي"),
    ("tool steel", "فولاذ العدد"),
    ("cast iron grade", "درجة حديد الزهر"),
    ("gray cast iron", "حديد زهر رمادي"),
    ("ductile cast iron", "حديد زهر مطيل"),
    ("aluminum alloy", "سبيكة ألمنيوم"),
    ("copper alloy", "سبيكة نحاس"),
    ("brass alloy", "سبيكة النحاس الأصفر"),
    ("bronze alloy", "سبيكة البرونز"),
    ("titanium alloy", "سبيكة تيتانيوم"),
    ("nickel alloy", "سبيكة نيكل"),
    ("polymer matrix composite", "مركب ذو قالب بوليمري"),
    ("metal matrix composite", "مركب ذو قالب معدني"),
    ("ceramic matrix composite", "مركب ذو قالب سيراميكي"),
    ("carbon fiber", "ليف كربوني"),
    ("glass fiber", "ليف زجاجي"),
    ("epoxy resin", "راتنج إيبوكسي"),
    ("thermoplastic polymer", "بوليمر لدن حراريا"),
    ("thermosetting polymer", "بوليمر متصلب حراريا"),
    ("glass transition temperature", "درجة الانتقال الزجاجي"),
    ("melting temperature", "درجة الانصهار"),
    ("phase transformation", "تحول طوري"),
    ("eutectic point", "نقطة يوتكتيكية"),
    ("eutectoid point", "نقطة يوتكتويدية"),
    ("peritectic reaction", "تفاعل بريتكتيكي"),
    ("solid solution strengthening", "تقوية بالمحلول الجامد"),
    ("precipitation hardening", "تقسية بالترسيب"),
    ("grain size refinement", "تنعيم حجم الحبيبات"),
    ("hall petch relation", "علاقة هول-بيتش"),
    ("dislocation motion", "حركة الانخلاعات"),
    ("edge dislocation", "انخلاع حافي"),
    ("screw dislocation", "انخلاع لولبي"),
    ("slip system", "نظام انزلاق"),
    ("critical resolved shear stress", "إجهاد القص الحرج المحلول"),
    ("work hardening", "تقسية بالتشكيل"),
    ("recovery process", "عملية الاستعادة"),
    ("recrystallization process", "عملية إعادة التبلور"),
    ("grain growth", "نمو الحبيبات"),
    ("full annealing", "تلدين كامل"),
    ("normalizing heat treatment", "معالجة المعايرة الحرارية"),
    ("quenching and tempering", "سقاية وإرجاع"),
    ("martensite structure", "بنية مارتنزيت"),
    ("austenite structure", "بنية أوستنيت"),
    ("pearlite structure", "بنية برليت"),
    ("bainite structure", "بنية باينيت"),
    ("ferrite structure", "بنية فريت"),
    ("cementite structure", "بنية سمنتيت"),
    ("time temperature transformation", "تحول الزمن ودرجة الحرارة"),
    ("continuous cooling transformation", "تحول التبريد المستمر"),
    ("jominy end quench test", "اختبار جوميني للسقاية الطرفية"),
    ("hardenability of steel", "قابلية تقسية الفولاذ"),
    ("case hardening", "تقسية سطحية"),
    ("carburizing treatment", "معالجة الكربنة"),
    ("nitriding treatment", "معالجة النتردة"),
    ("corrosion rate", "معدل التآكل"),
    ("uniform corrosion", "تآكل منتظم"),
    ("pitting corrosion", "تآكل نقري"),
    ("crevice corrosion", "تآكل شقي"),
    ("intergranular corrosion", "تآكل بين الحبيبات"),
    ("galvanic series", "سلسلة غلفانية"),
    ("cathodic protection", "حماية مهبطية"),
    ("sacrificial anode", "مصعد تضحية"),
    ("impressed current protection", "حماية بتيار مسلط"),
    ("pourbaix diagram", "مخطط بوربيه"),
    ("passive film", "غشاء خمول"),
    ("mass balance equation", "معادلة موازنة الكتلة"),
    ("energy balance equation", "معادلة موازنة الطاقة"),
    ("degree of freedom analysis", "تحليل درجات الحرية"),
    ("recycle ratio", "نسبة إعادة التدوير"),
    ("purge ratio", "نسبة التنفيس"),
    ("bypass ratio", "نسبة التجاوز"),
    ("single pass conversion", "تحول المسار الواحد"),
    ("overall conversion", "التحول الكلي"),
    ("reaction extent", "امتداد التفاعل"),
    ("limiting reactant", "متفاعل محدد"),
    ("excess reactant", "متفاعل فائض"),
    ("percent excess", "نسبة الفائض"),
    ("theoretical yield", "المردود النظري"),
    ("actual yield", "المردود الفعلي"),
    ("percent yield", "نسبة المردود"),
    ("space time", "زمن الحيز"),
    ("space velocity", "سرعة الحيز"),
    ("batch reactor design", "تصميم مفاعل دفعي"),
    ("cstr design equation", "معادلة تصميم مفاعل الخزان المستمر"),
    ("plug flow design equation", "معادلة تصميم مفاعل الجريان الكتلي"),
    ("residence time distribution", "توزيع زمن البقاء"),
    ("rate law", "قانون المعدل"),
    ("elementary reaction", "تفاعل أولي"),
    ("nonelementary reaction", "تفاعل غير أولي"),
    ("reaction order", "رتبة التفاعل"),
    ("half life of reaction", "عمر نصفي للتفاعل"),
    ("arrhenius plot", "مخطط أرينيوس"),
    ("activation energy value", "قيمة طاقة التنشيط"),
    ("catalyst deactivation", "تعطل الحفاز"),
    ("effectiveness factor", "معامل الفعالية"),
    ("thiele modulus", "معامل ثيل"),
    ("binary distillation", "تقطير ثنائي"),
    ("mccabe thiele method", "طريقة ماكيب-ثيل"),
    ("minimum reflux", "أدنى راجع"),
    ("minimum number of stages", "أدنى عدد مراحل"),
    ("feed stage", "مرحلة التغذية"),
    ("q line", "خط الحالة الحرارية"),
    ("relative volatility value", "قيمة التطايرية النسبية"),
    ("vapor liquid equilibrium", "اتزان بخار-سائل"),
    ("bubble point calculation", "حساب نقطة الفقاعة"),
    ("dew point calculation", "حساب نقطة الندى"),
    ("flash distillation", "تقطير ومضي"),
    ("absorption column", "عمود امتصاص"),
    ("stripping column", "عمود نزع"),
    ("height of transfer unit", "ارتفاع وحدة الانتقال"),
    ("number of transfer units", "عدد وحدات الانتقال"),
    ("overall mass transfer coefficient", "معامل انتقال الكتلة الكلي"),
    ("two film theory", "نظرية الغشائين"),
    ("drying rate", "معدل التجفيف"),
    ("constant rate period", "فترة المعدل الثابت"),
    ("falling rate period", "فترة المعدل المتناقص"),
    ("critical moisture content", "محتوى الرطوبة الحرج"),
    ("humidity chart", "مخطط الرطوبة"),
    ("wet bulb temperature value", "قيمة درجة الحرارة الرطبة"),
    ("adiabatic saturation temperature", "درجة حرارة الإشباع الكظوم"),
    ("reservoir simulation", "محاكاة المكمن"),
    ("material balance of reservoir", "موازنة مادة المكمن"),
    ("drive mechanism", "آلية الدفع"),
    ("solution gas drive", "دفع الغاز الذائب"),
    ("gas cap drive", "دفع القبة الغازية"),
    ("water drive", "دفع مائي"),
    ("gravity drainage", "تصريف بالجاذبية"),
    ("recovery factor", "معامل الاستخلاص"),
    ("original oil in place", "النفط الأصلي في المكان"),
    ("original gas in place", "الغاز الأصلي في المكان"),
    ("movable oil", "نفط قابل للحركة"),
    ("residual oil saturation", "تشبع النفط المتبقي"),
    ("connate water saturation", "تشبع الماء المتأصل"),
    ("critical gas saturation", "تشبع الغاز الحرج"),
    ("relative permeability curve", "منحنى النفاذية النسبية"),
    ("capillary pressure curve", "منحنى الضغط الشعري"),
    ("wettability alteration", "تغيير قابلية التبلل"),
    ("interfacial tension reduction", "خفض التوتر البيني"),
    ("mobility ratio", "نسبة الحركية"),
    ("sweep efficiency", "كفاءة الكسح"),
    ("displacement efficiency", "كفاءة الإزاحة"),
    ("areal sweep efficiency", "كفاءة الكسح المساحي"),
    ("vertical sweep efficiency", "كفاءة الكسح الشاقولي"),
    ("polymer flooding", "حقن البوليمر"),
    ("surfactant flooding", "حقن المواد الخافضة للتوتر"),
    ("alkaline flooding", "حقن قلوي"),
    ("miscible flooding", "حقن امتزاجي"),
    ("immiscible flooding", "حقن غير امتزاجي"),
    ("steam injection", "حقن البخار"),
    ("cyclic steam stimulation", "تنشيط بخاري دوري"),
    ("in situ combustion", "احتراق في المكان"),
    ("hydraulic fracture conductivity", "موصلية الشق الهيدروليكي"),
    ("fracture half length", "نصف طول الشق"),
    ("proppant pack", "حشوة المادة الداعمة"),
    ("drilling hydraulics", "هيدروليكا الحفر"),
    ("annular velocity", "سرعة حلقية"),
    ("equivalent circulating density", "الكثافة الدورانية المكافئة"),
    ("mud weight", "وزن الطين"),
    ("yield point of mud", "نقطة خضوع الطين"),
    ("plastic viscosity of mud", "لزوجة الطين اللدنة"),
    ("gel strength", "قوة الهلام"),
    ("filter cake", "كعكة الترشيح"),
    ("fluid loss", "فقد السائل"),
    ("kick tolerance", "سماحية الاندفاع"),
    ("shut in pressure", "ضغط الإغلاق"),
    ("kill mud weight", "وزن طين القتل"),
    ("wait and weight method", "طريقة الانتظار والوزن"),
    ("driller method", "طريقة الحفار"),
    ("casing design", "تصميم التغليف"),
    ("burst pressure", "ضغط الانفجار"),
    ("collapse pressure", "ضغط الانطباق"),
    ("tension load of casing", "حمل شد التغليف"),
    ("cement slurry", "روبة السمنت"),
    ("cement bond log", "سجل تماسك السمنت"),
    ("perforation interval", "مجال التثقيب"),
    ("well productivity", "إنتاجية البئر"),
    ("inflow performance relationship", "علاقة أداء الجريان الداخل"),
    ("vertical lift performance", "أداء الرفع الشاقولي"),
    ("nodal analysis of well", "تحليل عقدي للبئر"),
    ("artificial lift", "رفع اصطناعي"),
    ("sucker rod pump", "مضخة ذات قضيب ماص"),
    ("electrical submersible pump", "مضخة غاطسة كهربائية"),
    ("gas lift", "رفع بالغاز"),
    ("separator vessel", "وعاء فاصل"),
    ("two phase separator", "فاصل ثنائي الطور"),
    ("three phase separator", "فاصل ثلاثي الطور"),
    ("stock tank oil", "نفط خزان التخزين"),
    ("formation volume factor", "معامل حجم التكوين"),
    ("solution gas oil ratio", "نسبة الغاز الذائب إلى النفط"),
    ("oil viscosity", "لزوجة النفط"),
    ("gas deviation factor", "معامل انحراف الغاز"),
    ("pseudocritical pressure", "ضغط حرج كاذب"),
    ("pseudocritical temperature", "درجة حرارة حرجة كاذبة"),
    ("standing correlation", "علاقة ستاندنغ"),
    ("beggs and brill correlation", "علاقة بيغز وبريل"),
    ("hagedorn and brown correlation", "علاقة هاغدورن وبراون"),
    ("pressure traverse", "مقطع الضغط"),
    ("wellhead choke", "خانق رأس البئر"),
    ("critical flow of choke", "جريان حرج في الخانق"),
    ("subcritical flow of choke", "جريان دون الحرج في الخانق"),
]
