"""مصطلحات ميكانيك التربة والهندسة الجيوتقنية."""

from __future__ import annotations

SOIL_ENTRIES: list[tuple[str, str]] = [
    # ── علاقات الأطوار والتصنيف ──
    ("three phase soil system", "نظام التربة ثلاثي الأطوار"),
    ("phase diagram of soil", "مخطط أطوار التربة"),
    ("water content of soil sample", "محتوى رطوبة عينة التربة"),
    ("gravimetric moisture of soil", "الرطوبة الوزنية للتربة"),
    ("degree of saturation of soil", "درجة تشبع التربة"),
    ("air content of soil voids", "محتوى الهواء في فراغات التربة"),
    ("porosity of soil mass", "مسامية كتلة التربة"),
    ("void ratio of soil mass", "نسبة فراغات كتلة التربة"),
    ("specific volume of soil", "الحجم النوعي للتربة"),
    ("moist unit weight of soil", "وزن وحدة الحجم الرطب للتربة"),
    ("buoyant unit weight of soil", "وزن وحدة الحجم الطافي للتربة"),
    ("zero air voids curve", "منحنى انعدام الفراغات الهوائية"),
    ("shrinkage ratio of soil", "نسبة انكماش التربة"),
    ("linear shrinkage of soil", "الانكماش الخطي للتربة"),
    ("volumetric shrinkage of soil", "الانكماش الحجمي للتربة"),
    ("pycnometer specific gravity", "الوزن النوعي بالبيكومتر"),
    ("oven dry water content", "محتوى الرطوبة بالتجفيف بالفرن"),
    ("casagrande plasticity chart", "مخطط لدونة كازاغراندي"),
    ("a line on plasticity chart", "خط A على مخطط اللدونة"),
    ("u line on plasticity chart", "خط U على مخطط اللدونة"),
    ("group index of soil", "دليل مجموعة التربة"),
    ("aashto group index", "دليل مجموعة آشتو"),
    ("low plasticity clay", "غضار قليل اللدونة"),
    ("high plasticity clay", "غضار عالي اللدونة"),
    ("lean clay classification", "تصنيف الغضار النحيل"),
    ("fat clay classification", "تصنيف الغضار السمين"),
    ("silty sand classification", "تصنيف الرمل الغريني"),
    ("clayey sand classification", "تصنيف الرمل الغضاري"),
    ("poorly graded sand", "رمل سيئ التدرج"),
    ("well graded gravel", "حصى جيد التدرج"),
    ("fines content of soil", "محتوى النواعم في التربة"),
    ("gravel content of soil", "محتوى الحصى في التربة"),
    ("sand content of soil", "محتوى الرمل في التربة"),
    ("silt content of soil", "محتوى الغرين في التربة"),
    ("clay content of soil", "محتوى الغضار في التربة"),
    ("effective grain size", "حجم الحبيبة الفعال"),
    ("d10 particle size", "حجم الحبيبة D10"),
    ("d30 particle size", "حجم الحبيبة D30"),
    ("d60 particle size", "حجم الحبيبة D60"),
    ("grain size curve of soil", "منحنى التدرج الحبيبي للتربة"),
    ("stokes law of sedimentation", "قانون ستوكس للترسيب"),
    ("hydrometer test of fines", "اختبار الهيدروميتر للنواعم"),
    ("colloidal clay fraction", "الجزء الغضاري الغروي"),
    ("specific surface of clay", "السطح النوعي للغضار"),
    ("cation exchange capacity of clay", "سعة التبادل الكاتيوني للغضار"),
    ("diffuse double layer", "الطبقة الكهربائية المزدوجة"),
    ("kaolinite clay mineral", "معدن الكاولينيت"),
    ("illite clay mineral", "معدن الإليت"),
    ("montmorillonite clay mineral", "معدن المونتموريلونيت"),
    ("smectite clay mineral", "معدن السميكتايت"),
    ("chlorite clay mineral", "معدن الكلوريت"),
    ("flocculated clay structure", "بنية غضارية متلبكة"),
    ("dispersed clay structure", "بنية غضارية مشتتة"),
    ("honeycomb soil structure", "بنية تربة خلوية"),
    ("single grained structure", "بنية أحادية الحبيبات"),
    ("thixotropy of clay", "التكسوتروبية للغضار"),
    ("remolded clay strength", "مقاومة الغضار المعاد التشكيل"),
    ("undisturbed clay strength", "مقاومة الغضار غير المشوش"),
    ("very soft clay consistency", "قوام غضار شديد الليونة"),
    ("soft clay consistency", "قوام غضار لين"),
    ("stiff clay consistency", "قوام غضار صلب"),
    ("hard clay consistency", "قوام غضار قاس"),
    # ── الرص والكثافة الحقلية ──
    ("compaction effort of soil", "جهد رص التربة"),
    ("field compaction control", "ضبط الرص الحقلي"),
    ("sand cone density test", "اختبار الكثافة بمخروط الرمل"),
    ("rubber balloon density test", "اختبار الكثافة بالبالون المطاطي"),
    ("nuclear density gauge", "مقياس الكثافة النووي"),
    ("core cutter method", "طريقة القاطع اللبابي"),
    ("field dry density of fill", "الكثافة الجافة الحقلية للردم"),
    ("lift thickness of compacted fill", "سمك الطبقة للردم المرصوص"),
    ("moisture conditioning of fill", "تهيئة رطوبة الردم"),
    ("wet of optimum compaction", "الرص أرطب من الأمثل"),
    ("dry of optimum compaction", "الرص أجف من الأمثل"),
    ("line of optimums", "خط القيم المثلى"),
    ("family of compaction curves", "عائلة منحنيات الرص"),
    ("sheepsfoot roller compaction", "الرص بالمحدلة ذات الأقدام"),
    ("vibratory roller compaction", "الرص بالمحدلة الهزازة"),
    ("smooth drum roller", "محدلة ذات أسطوانة ملساء"),
    ("pneumatic roller compaction", "الرص بالمحدلة الهوائية"),
    ("proof rolling of subgrade", "الرص الاختباري لطبقة التأسيس"),
    ("engineered fill specification", "مواصفة الردم الهندسي"),
    ("uncontrolled fill deposit", "ردم غير مضبوط"),
    ("relative density of sand", "الكثافة النسبية للرمل"),
    ("minimum void ratio of sand", "نسبة الفراغات الدنيا للرمل"),
    ("maximum void ratio of sand", "نسبة الفراغات القصوى للرمل"),
    ("angle of repose of sand", "زاوية استقرار الرمل"),
    ("overcompaction of clay fill", "فرط رص ردم الغضار"),
    # ── النفاذية والتسرب ──
    ("constant head permeability test", "اختبار النفاذية بالضاغط الثابت"),
    ("falling head permeability test", "اختبار النفاذية بالضاغط المتناقص"),
    ("horizontal permeability of soil", "النفاذية الأفقية للتربة"),
    ("vertical permeability of soil", "النفاذية الشاقولية للتربة"),
    ("permeability of stratified soil", "نفاذية التربة المتطبقة"),
    ("equivalent permeability of layers", "النفاذية المكافئة للطبقات"),
    ("hazen permeability formula", "صيغة هازن للنفاذية"),
    ("kozeny carman equation", "معادلة كوزيني-كارمان"),
    ("discharge velocity of seepage", "سرعة التصريف للتسرب"),
    ("seepage velocity through voids", "سرعة التسرب خلال الفراغات"),
    ("temperature effect on permeability", "أثر الحرارة على النفاذية"),
    ("confined seepage under structure", "تسرب محصور تحت المنشأ"),
    ("unconfined seepage through embankment", "تسرب غير محصور عبر الردم"),
    ("seepage quantity from flow net", "كمية التسرب من شبكة الجريان"),
    ("number of flow channels", "عدد قنوات الجريان"),
    ("number of equipotential drops", "عدد سقوطات الجهد"),
    ("factor of safety against piping", "معامل الأمان ضد الأنابيب"),
    ("factor of safety against heave", "معامل الأمان ضد الرفع"),
    ("weighted creep distance", "مسافة الزحف الموزونة"),
    ("bligh creep theory", "نظرية الزحف لبلاي"),
    ("lane weighted creep theory", "نظرية الزحف الموزون للين"),
    ("filter compatibility with soil", "توافق المرشح مع التربة"),
    ("retention criterion of filter", "معيار احتباس المرشح"),
    ("permeability criterion of filter", "معيار نفاذية المرشح"),
    ("clogging of soil filter", "انسداد مرشح التربة"),
    ("chimney drain in embankment", "مصرف مدخنة في الردم"),
    ("blanket drain under embankment", "مصرف بساط تحت الردم"),
    ("toe filter of earth dam", "مرشح قدم السد الترابي"),
    ("internal erosion of earth dam", "التعرية الداخلية للسد الترابي"),
    ("backward erosion piping", "أنابيب بالتعرية الراجعة"),
    ("contact erosion of soil", "تعرية التماس للتربة"),
    ("suffusion of fine soil", "انجراف النواعم داخل الهيكل"),
    # ── الإجهاد الفعال وغير المشبع ──
    ("total vertical stress in soil", "الإجهاد الشاقولي الكلي في التربة"),
    ("effective vertical stress in soil", "الإجهاد الشاقولي الفعال في التربة"),
    ("neutral stress of pore water", "الإجهاد الحيادي لماء المسام"),
    ("geostatic stress in soil", "الإجهاد الجيوستاتيكي في التربة"),
    ("overburden pressure of soil", "ضغط العبء للتربة"),
    ("buoyant stress below water table", "الإجهاد الطافي تحت منسوب الماء"),
    ("pore air pressure in soil", "ضغط هواء المسام في التربة"),
    ("matric suction of unsaturated soil", "المصن الشعري للتربة غير المشبعة"),
    ("osmotic suction of soil", "المصن الأسموزي للتربة"),
    ("total suction of soil", "المصن الكلي للتربة"),
    ("soil water characteristic curve", "منحنى خاصية ماء التربة"),
    ("bishop effective stress equation", "معادلة الإجهاد الفعال لبيشوب"),
    ("unsaturated shear strength", "مقاومة قص التربة غير المشبعة"),
    ("height of capillary rise", "ارتفاع الصعود الشعري"),
    ("capillary pressure in soil pores", "الضغط الشعري في مسام التربة"),
    ("partially saturated soil mass", "كتلة تربة مشبعة جزئيا"),
    ("fully saturated soil mass", "كتلة تربة مشبعة كليا"),
    ("stress history of clay deposit", "تاريخ إجهاد ترسب الغضار"),
    ("maximum past pressure of clay", "الضغط الأقصى السابق للغضار"),
    ("casagrande preconsolidation construction", "إنشاء كازاغراندي لضغط الانضمام المسبق"),
    ("underconsolidated clay deposit", "ترسب غضار ناقص الانضمام"),
    ("normally consolidated soil profile", "مقطع تربة منضمة طبيعيا"),
    ("overconsolidated soil profile", "مقطع تربة مفرطة الانضمام"),
    ("at rest pressure coefficient", "معامل الضغط الساكن"),
    ("jaky formula for earth pressure", "صيغة جاكي لضغط التربة"),
    # ── مقاومة القص ──
    ("mohr coulomb failure envelope", "غلاف انهيار مور-كولوم"),
    ("shear strength parameters of soil", "معاملات مقاومة قص التربة"),
    ("effective cohesion of soil", "تماسك التربة الفعال"),
    ("undrained cohesion of clay", "تماسك الغضار غير المصرف"),
    ("effective angle of friction", "زاوية الاحتكاك الفعالة"),
    ("total stress friction angle", "زاوية الاحتكاك بالإجهاد الكلي"),
    ("peak friction angle of sand", "زاوية الاحتكاك القصوى للرمل"),
    ("residual friction angle of clay", "زاوية الاحتكاك المتبقية للغضار"),
    ("critical state friction angle", "زاوية احتكاك الحالة الحرجة"),
    ("constant volume friction angle", "زاوية احتكاك الحجم الثابت"),
    ("dilatancy of dense sand", "تمدد الرمل الكثيف"),
    ("contractive behavior of loose sand", "سلوك انكماشي للرمل المخلخل"),
    ("critical void ratio of sand", "نسبة الفراغات الحرجة للرمل"),
    ("stress path in triaxial test", "مسار الإجهاد في الاختبار ثلاثي المحاور"),
    ("effective stress path of soil", "مسار الإجهاد الفعال للتربة"),
    ("total stress path of soil", "مسار الإجهاد الكلي للتربة"),
    ("undrained stress path", "مسار الإجهاد غير المصرف"),
    ("skempton pore pressure parameters", "معاملات ضغط المسام لسكيمبتون"),
    ("pore pressure parameter a", "معامل ضغط المسام A"),
    ("pore pressure parameter b", "معامل ضغط المسام B"),
    ("deviator stress in triaxial test", "إجهاد الانحراف في الاختبار ثلاثي المحاور"),
    ("confining cell pressure", "ضغط الخلية المحيط"),
    ("triaxial cu test with pore pressure", "اختبار منضم غير مصرف مع ضغط المسام"),
    ("triaxial drained compression", "انضغاط ثلاثي المحاور مصرف"),
    ("triaxial undrained compression", "انضغاط ثلاثي المحاور غير مصرف"),
    ("unconfined compressive strength of soil", "مقاومة الانضغاط غير المحصور للتربة"),
    ("ring shear test of soil", "اختبار القص الحلقي للتربة"),
    ("simple shear test of soil", "اختبار القص البسيط للتربة"),
    ("torsional shear test", "اختبار القص الالتوائي"),
    ("plane strain test of soil", "اختبار الانفعال المستوي للتربة"),
    ("true triaxial apparatus", "جهاز ثلاثي المحاور الحقيقي"),
    ("hollow cylinder torsional test", "اختبار الأسطوانة المجوفة الالتوائي"),
    ("strain softening of clay", "تليين الغضار مع الانفعال"),
    ("peak strength of dense sand", "المقاومة القصوى للرمل الكثيف"),
    ("steady state strength of sand", "مقاومة الحالة المستقرة للرمل"),
    ("residual strength of clay", "المقاومة المتبقية للغضار"),
    ("secant modulus of soil", "معامل التربة القاطع"),
    ("tangent modulus of soil", "معامل التربة المماسي"),
    ("undrained modulus of clay", "معامل الغضار غير المصرف"),
    ("drained modulus of soil", "معامل التربة المصرف"),
    ("shear modulus of soil", "معامل قص التربة"),
    ("bulk modulus of soil", "معامل التربة الحجمي"),
    ("poisson ratio of soil", "نسبة بواسون للتربة"),
    ("elastic parameters of soil", "المعاملات المرنة للتربة"),
    ("critical state soil mechanics", "ميكانيك التربة للحالة الحرجة"),
    ("cam clay constitutive model", "نموذج كام كلاي البنائي"),
    ("modified cam clay model", "نموذج كام كلاي المعدل"),
    ("normal consolidation line", "خط الانضمام الطبيعي"),
    ("critical state line of soil", "خط الحالة الحرجة للتربة"),
    ("swelling line of clay", "خط انتفاخ الغضار"),
    ("state boundary surface", "سطح حد الحالة"),
    ("yield surface of soil", "سطح الخضوع للتربة"),
    ("hardening rule of soil", "قاعدة التصلب للتربة"),
    ("progressive failure of slope", "الانهيار المتدرج للمنحدر"),
    # ── الانضمام والهبوط ──
    ("terzaghi consolidation theory", "نظرية الانضمام لتيرزاغي"),
    ("one dimensional consolidation", "انضمام أحادي البعد"),
    ("radial consolidation of clay", "الانضمام الشعاعي للغضار"),
    ("biot consolidation theory", "نظرية الانضمام لبيو"),
    ("degree of consolidation of clay", "درجة انضمام الغضار"),
    ("average degree of consolidation", "درجة الانضمام المتوسطة"),
    ("time factor of consolidation", "عامل زمن الانضمام"),
    ("vertical coefficient of consolidation", "معامل الانضمام الشاقولي"),
    ("horizontal coefficient of consolidation", "معامل الانضمام الأفقي"),
    ("double drainage of clay layer", "تصريف مزدوج لطبقة الغضار"),
    ("single drainage of clay layer", "تصريف مفرد لطبقة الغضار"),
    ("drainage path of clay", "مسار تصريف الغضار"),
    ("e log pressure curve", "منحنى نسبة الفراغات مع لوغاريتم الضغط"),
    ("virgin compression curve", "منحنى الانضغاط البكر"),
    ("unload reload curve of clay", "منحنى إزالة التحميل وإعادته للغضار"),
    ("coefficient of compressibility of clay", "معامل انضغاطية الغضار"),
    ("compression ratio of clay", "نسبة انضغاط الغضار"),
    ("recompression ratio of clay", "نسبة إعادة انضغاط الغضار"),
    ("coefficient of secondary compression", "معامل الانضغاط الثانوي"),
    ("secondary settlement of clay", "هبوط الغضار الثانوي"),
    ("creep settlement of soil", "هبوط زحف التربة"),
    ("casagrande logarithm of time method", "طريقة كازاغراندي للوغاريتم الزمن"),
    ("taylor square root of time method", "طريقة تايلور لجذر الزمن"),
    ("load increment ratio of oedometer", "نسبة زيادة الحمل في الأويدومتر"),
    ("ninety percent consolidation", "انضمام بنسبة تسعين بالمئة"),
    ("primary consolidation completion", "اكتمال الانضمام الأولي"),
    ("dissipation of excess pore pressure", "تبدد ضغط المسام الزائد"),
    ("consolidation settlement of embankment", "هبوط انضمام الردم"),
    ("immediate elastic settlement", "الهبوط المرن الآني"),
    ("elastic settlement of footing on sand", "الهبوط المرن للقاعدة على الرمل"),
    ("schmertmann settlement method", "طريقة شميرتمان للهبوط"),
    ("strain influence factor", "معامل تأثير الانفعال"),
    ("janbu modulus number", "رقم معامل يانبو"),
    ("boussinesq point load stress", "إجهاد حمل بوسينسك النقطي"),
    ("stress under strip load", "الإجهاد تحت الحمل الشريطي"),
    ("stress under circular footing", "الإجهاد تحت القاعدة الدائرية"),
    ("stress under rectangular footing", "الإجهاد تحت القاعدة المستطيلة"),
    ("two to one stress spread", "انتشار الإجهاد بنسبة اثنين إلى واحد"),
    ("influence factor of stress", "معامل تأثير الإجهاد"),
    ("angular distortion limit", "حد التشوه الزاوي"),
    ("allowable differential settlement", "الهبوط التفاضلي المسموح"),
    ("rigid footing contact pressure", "ضغط تماس القاعدة الصلدة"),
    ("flexible footing contact pressure", "ضغط تماس القاعدة المرنة"),
    ("settlement of embankment on soft clay", "هبوط الردم على غضار لين"),
    ("size effect on sand settlement", "أثر الحجم على هبوط الرمل"),
    # ── قدرة التحمل ──
    ("general shear failure of soil", "انهيار القص العام للتربة"),
    ("local shear failure of soil", "انهيار القص الموضعي للتربة"),
    ("punching shear failure of soil", "انهيار القص الثاقب للتربة"),
    ("terzaghi bearing capacity equation", "معادلة قدرة التحمل لتيرزاغي"),
    ("skempton bearing capacity of clay", "قدرة تحمل سكيمبتون للغضار"),
    ("prandtl failure mechanism", "آلية انهيار براندتل"),
    ("radial shear zone under footing", "منطقة القص الشعاعي تحت القاعدة"),
    ("net safe bearing pressure", "ضغط التحمل الآمن الصافي"),
    ("gross bearing pressure of footing", "ضغط التحمل الإجمالي للقاعدة"),
    ("water table correction of bearing", "تصحيح منسوب الماء لقدرة التحمل"),
    ("eccentric load on footing soil", "حمل لامركزي على تربة القاعدة"),
    ("inclined load bearing capacity", "قدرة التحمل للحمل المائل"),
    ("layered soil bearing capacity", "قدرة تحمل التربة المتطبقة"),
    ("footing on sand overlying clay", "قاعدة على رمل فوق غضار"),
    ("footing on clay overlying sand", "قاعدة على غضار فوق رمل"),
    ("spt correlation for bearing capacity", "ربط الاختراق القياسي بقدرة التحمل"),
    ("cpt correlation for bearing capacity", "ربط المخروط بقدرة التحمل"),
    ("plate load test interpretation", "تفسير اختبار تحميل الصفيحة"),
    ("allowable settlement criterion", "معيار الهبوط المسموح"),
    ("foundation on expansive clay", "أساس على غضار انتفاخي"),
    ("foundation on collapsible soil", "أساس على تربة قابلة للانهيار"),
    ("buoyancy of embedded foundation", "طفو الأساس المطمور"),
    # ── ضغط التربة والحفريات ──
    ("rankine active earth pressure", "ضغط التربة الفعال لرانكين"),
    ("rankine passive earth pressure", "ضغط التربة المقاوم لرانكين"),
    ("coulomb trial wedge", "وتد التجربة لكولوم"),
    ("culmann graphical construction", "الإنشاء البياني لكولمان"),
    ("wall friction angle of soil", "زاوية احتكاك الجدار مع التربة"),
    ("sloping backfill earth pressure", "ضغط التربة لردم مائل"),
    ("line surcharge behind wall", "حمل خطي إضافي خلف الجدار"),
    ("strip surcharge behind wall", "حمل شريطي إضافي خلف الجدار"),
    ("compaction induced lateral pressure", "ضغط جانبي ناتج عن الرص"),
    ("apparent earth pressure diagram", "مخطط ضغط التربة الظاهري"),
    ("peck apparent pressure envelope", "غلاف الضغط الظاهري لبيك"),
    ("strut load in braced cut", "حمل الدعامة في الحفر المدعم"),
    ("braced excavation in clay", "حفر مدعم في الغضار"),
    ("basal heave of excavation", "رفع قاع الحفر"),
    ("factor of safety against basal heave", "معامل الأمان ضد رفع القاع"),
    ("hydraulic heave in excavation", "الرفع الهيدروليكي في الحفر"),
    ("wellpoint dewatering system", "نظام نزح بالنقاط البئرية"),
    ("deep well dewatering", "نزح بآبار عميقة"),
    ("sump pumping of excavation", "ضخ الحوض في الحفر"),
    ("free earth support method", "طريقة الاستناد الحر للتربة"),
    ("fixed earth support method", "طريقة الاستناد المثبت للتربة"),
    ("anchored sheet pile penetration", "اختراق الألواح الوتدية المثبتة"),
    ("tieback anchor bond length", "طول تماسك المرساة الخلفية"),
    ("soil nail pullout resistance", "مقاومة سحب مسمار التربة"),
    ("facing of soil nail wall", "كسوة جدار مسامير التربة"),
    ("geogrid pullout resistance", "مقاومة سحب الشبكة الأرضية"),
    ("interface friction of reinforcement", "احتكاك سطح التسليح"),
    ("long term design strength of geogrid", "مقاومة التصميم طويلة الأمد للشبكة"),
    ("creep reduction of geosynthetic", "تخفيض الزحف للتركيب الأرضي"),
    ("reinforced soil retaining wall", "جدار ساند من تربة مسلحة"),
    ("tie length in reinforced soil", "طول الرباط في التربة المسلحة"),
    # ── استقرار المنحدرات ──
    ("limit equilibrium slope analysis", "تحليل المنحدر بتوازن الحد"),
    ("circular slip surface", "سطح انزلاق دائري"),
    ("noncircular slip surface", "سطح انزلاق غير دائري"),
    ("translational slope slide", "انزلاق انتقالي للمنحدر"),
    ("rotational slope failure", "انهيار دوراني للمنحدر"),
    ("wedge failure of soil slope", "انهيار وتدي لمنحدر التربة"),
    ("toe circle slip", "انزلاق دائرة المقدم"),
    ("base failure of embankment", "انهيار قاعدة الردم"),
    ("slope failure through foundation soil", "انهيار المنحدر عبر تربة الأساس"),
    ("end of construction stability", "استقرار نهاية الإنشاء"),
    ("long term drained stability", "الاستقرار المصرف طويل الأمد"),
    ("short term undrained stability", "الاستقرار غير المصرف قصير الأمد"),
    ("steady seepage slope stability", "استقرار المنحدر مع تسرب مستقر"),
    ("rapid drawdown slope case", "حالة هبوط المنسوب السريع للمنحدر"),
    ("undrained analysis of clay slope", "تحليل غير مصرف لمنحدر الغضار"),
    ("drained analysis of soil slope", "تحليل مصرف لمنحدر التربة"),
    ("pseudostatic seismic slope analysis", "تحليل منحدر زلزالي شبه ساكن"),
    ("horizontal seismic coefficient", "المعامل الزلزالي الأفقي"),
    ("newmark sliding block analysis", "تحليل بلوك الانزلاق لنيومارك"),
    ("yield acceleration of slope", "تسارع الخضوع للمنحدر"),
    ("permanent seismic displacement", "الإزاحة الزلزالية الدائمة"),
    ("pore pressure ratio in slope", "نسبة ضغط المسام في المنحدر"),
    ("tension crack depth in clay", "عمق شق الشد في الغضار"),
    ("strength reduction factor of slope", "معامل تخفيض المقاومة للمنحدر"),
    ("morgenstern price slope method", "طريقة مورغنسترن-برايس للمنحدر"),
    ("sarma method of slope slices", "طريقة سارما لشرائح المنحدر"),
    ("counterweight berm for stability", "كتف ثقل موازن للاستقرار"),
    ("horizontal drain in slope", "مصرف أفقي في المنحدر"),
    ("landslide stabilization measures", "إجراءات تثبيت الانزلاق"),
    # ── الديناميك والتمييع ──
    ("cyclic liquefaction of saturated sand", "التمييع الدوري للرمل المشبع"),
    ("flow liquefaction of loose sand", "تمييع الجريان للرمل المخلخل"),
    ("cyclic mobility of sand", "الحركة الدورية للرمل"),
    ("cyclic stress ratio of earthquake", "نسبة الإجهاد الدوري للزلزال"),
    ("cyclic resistance ratio of soil", "نسبة المقاومة الدورية للتربة"),
    ("factor of safety against liquefaction", "معامل الأمان ضد التمييع"),
    ("seed idriss liquefaction method", "طريقة سيد-إدريس للتمييع"),
    ("magnitude scaling factor", "معامل تعديل الشدة"),
    ("overburden correction of liquefaction", "تصحيح العبء للتمييع"),
    ("fines correction of liquefaction", "تصحيح النواعم للتمييع"),
    ("spt based liquefaction evaluation", "تقييم التمييع بالاختراق القياسي"),
    ("cpt based liquefaction evaluation", "تقييم التمييع بالمخروط"),
    ("shear wave liquefaction correlation", "ربط التمييع بسرعة موجة القص"),
    ("post liquefaction settlement", "الهبوط بعد التمييع"),
    ("lateral spreading of liquefied ground", "الانتشار الجانبي للأرض المتميع"),
    ("sand boil from liquefaction", "فوران الرمل بسبب التمييع"),
    ("excess pore pressure ratio", "نسبة ضغط المسام الزائد"),
    ("cyclic triaxial liquefaction test", "اختبار التمييع الدوري ثلاثي المحاور"),
    ("cyclic simple shear test", "اختبار القص البسيط الدوري"),
    ("resonant column test of soil", "اختبار العمود الرنان للتربة"),
    ("bender element shear wave test", "اختبار موجة القص بعنصر الانحناء"),
    ("shear wave velocity of soil", "سرعة موجة القص في التربة"),
    ("small strain shear modulus", "معامل القص عند الانفعال الصغير"),
    ("shear modulus reduction curve", "منحنى انخفاض معامل القص"),
    ("damping ratio of soil", "نسبة التخميد للتربة"),
    ("site response analysis of soil", "تحليل استجابة الموقع للتربة"),
    ("soil amplification of ground motion", "تضخيم التربة للحركة الأرضية"),
    ("predominant period of soil deposit", "الدور السائد لترسب التربة"),
    ("impedance contrast of soil layers", "تباين الممانعة بين طبقات التربة"),
    ("equivalent linear site analysis", "تحليل الموقع الخطي المكافئ"),
    ("dynamic stiffness of soil", "الصلابة الديناميكية للتربة"),
    ("radiation damping of foundation soil", "تخميد الإشعاع لتربة الأساس"),
    ("coefficient of elastic uniform compression", "معامل الانضغاط المرن المنتظم"),
    ("block vibration test of soil", "اختبار اهتزاز الكتلة للتربة"),
    ("permissible amplitude of machine foundation", "السعة المسموحة لأساس الماكنة"),
    ("operating frequency ratio", "نسبة تردد التشغيل"),
    # ── الترب ذات المشاكل ──
    ("swell pressure of expansive clay", "ضغط انتفاخ الغضار الانتفاخي"),
    ("free swell index of clay", "دليل الانتفاخ الحر للغضار"),
    ("potential volume change of clay", "تغير الحجم المحتمل للغضار"),
    ("active zone of expansive soil", "النطاق الفعال للتربة الانتفاخية"),
    ("depth of moisture change", "عمق تغير الرطوبة"),
    ("moisture barrier under slab", "حاجز رطوبة تحت البلاطة"),
    ("collapse potential of soil", "قابلية انهيار التربة"),
    ("double oedometer collapse test", "اختبار الانهيار بأويدومتر مزدوج"),
    ("collapse upon wetting", "الانهيار عند الابتلال"),
    ("loess collapse mechanism", "آلية انهيار تربة اللوس"),
    ("dispersive clay pinhole test", "اختبار الثقب للغضار المشتت"),
    ("crumb test of dispersive soil", "اختبار الفتات للتربة المشتتة"),
    ("double hydrometer dispersion test", "اختبار التشتت بالهيدروميتر المزدوج"),
    ("organic content of soil", "المحتوى العضوي للتربة"),
    ("loss on ignition of soil", "الفاقد بالحرق للتربة"),
    ("fibrous peat compressibility", "انضغاطية الخث الليفي"),
    ("amorphous peat deposit", "ترسب خث غير متبلور"),
    ("quick clay landslide", "انزلاق الغضار السريع"),
    ("leached marine clay", "غضار بحري مغسول"),
    ("gypsiferous soil behavior", "سلوك التربة الجبسية"),
    ("calcareous cemented soil", "تربة متلاحمة كلسية"),
    ("residual weathering profile", "مقطع تجوية متبق"),
    ("saprolite soil horizon", "أفق تربة السابروليت"),
    ("colluvial soil deposit", "ترسب تربة انهيارية سفحية"),
    ("glacial till deposit", "ترسب حريث جليدي"),
    ("varved clay deposit", "ترسب غضار مطبّق موسمي"),
    ("lacustrine clay deposit", "ترسب غضار بحيري"),
    ("marine clay deposit", "ترسب غضار بحري"),
    ("aeolian sand deposit", "ترسب رمل ريحي"),
    ("frost susceptible soil", "تربة قابلة للصقيع"),
    ("frost heave pressure", "ضغط انتفاخ الصقيع"),
    ("ice lens formation in soil", "تكوّن عدسات الجليد في التربة"),
    ("thaw weakening of subgrade", "ضعف التأسيس عند الذوبان"),
    ("frost penetration depth", "عمق اختراق الصقيع"),
    ("active layer of permafrost", "الطبقة النشطة في التربة دائمة التجمد"),
    ("soluble sulfate in soil", "الكبريتات الذائبة في التربة"),
    ("contaminated soil for foundation", "تربة ملوثة للأساس"),
    # ── الاستكشاف الحقلي ──
    ("geotechnical site investigation", "الاستكشاف الجيوتقني للموقع"),
    ("soil boring log", "سجل حفر التربة"),
    ("wash boring of soil", "الحفر بالغسل للتربة"),
    ("auger boring of soil", "الحفر بالبريمة للتربة"),
    ("rotary drilling of overburden", "الحفر الدوراني للغطاء"),
    ("corrected spt blow count", "عدد ضربات الاختراق المصحح"),
    ("hammer energy ratio of spt", "نسبة طاقة المطرقة للاختراق القياسي"),
    ("overburden correction of spt", "تصحيح العبء للاختراق القياسي"),
    ("cone tip resistance", "مقاومة رأس المخروط"),
    ("sleeve friction of cone", "احتكاك الغلاف للمخروط"),
    ("friction ratio of cpt", "نسبة الاحتكاك لاختبار المخروط"),
    ("pore pressure piezocone", "مخروط ضغط المسام"),
    ("seismic cone penetration test", "اختبار الاختراق بالمخروط الزلزالي"),
    ("dilatometer material index", "دليل المادة لمقياس التمدد"),
    ("dilatometer constrained modulus", "المعامل المقيد لمقياس التمدد"),
    ("horizontal stress index", "دليل الإجهاد الأفقي"),
    ("pressuremeter limit pressure", "ضغط الحد لمقياس الضغط"),
    ("menard pressuremeter test", "اختبار مقياس الضغط لمينار"),
    ("self boring pressuremeter", "مقياس ضغط ذاتي الحفر"),
    ("field vane shear strength", "مقاومة القص بالمروحة الحقلية"),
    ("vane correction factor", "معامل تصحيح المروحة"),
    ("pocket penetrometer reading", "قراءة مخراق الجيب"),
    ("area ratio of sampler", "نسبة مساحة آخذ العينة"),
    ("sample disturbance of clay", "تشويش عينة الغضار"),
    ("piston sampler of soft clay", "آخذ بمكبس للغضار اللين"),
    ("block sample of clay", "عينة كتلية من الغضار"),
    ("recovery ratio of soil sample", "نسبة استرداد عينة التربة"),
    ("standpipe piezometer reading", "قراءة البيزومتر الأنبوبي"),
    ("vibrating wire piezometer", "بيزومتر السلك المهتز"),
    ("pneumatic piezometer", "بيزومتر هوائي"),
    ("pore pressure measurement in situ", "قياس ضغط المسام في الموقع"),
    ("electrical resistivity of soil", "المقاومية الكهربائية للتربة"),
    ("seismic refraction of site", "الانكسار الزلزالي للموقع"),
    ("ground penetrating radar of subsoil", "رادار اختراق الأرض للتربة"),
    ("subsurface soil profile", "مقطع التربة تحت السطح"),
    ("groundwater level during drilling", "منسوب المياه أثناء الحفر"),
    # ── تحسين التربة ──
    ("preloading of soft clay", "التحميل المسبق للغضار اللين"),
    ("vacuum preloading of clay", "التحميل المسبق بالتفريغ للغضار"),
    ("vertical drain spacing design", "تصميم تباعد المصارف الشاقولية"),
    ("smear zone around vertical drain", "نطاق التلطيخ حول المصرف الشاقولي"),
    ("sand drain consolidation", "انضمام بمصارف رملية"),
    ("stone column bearing capacity", "قدرة تحمل العمود الحجري"),
    ("vibro replacement stone column", "عمود حجري بالاستبدال الاهتزازي"),
    ("vibro flotation of loose sand", "التعويم الاهتزازي للرمل المخلخل"),
    ("dynamic compaction grid spacing", "تباعد شبكة الرص الديناميكي"),
    ("rapid impact compaction", "الرص بالصدمة السريعة"),
    ("compaction grouting of soil", "حقن الرص للتربة"),
    ("compensation grouting", "الحقن التعويضي"),
    ("jet grout soil column", "عمود تربة بالحقن النفاث"),
    ("lime column in soft clay", "عمود كلس في الغضار اللين"),
    ("cement deep mixing column", "عمود الخلط العميق بالأسمنت"),
    ("electroosmotic dewatering of clay", "نزح الغضار بالتناضح الكهربائي"),
    ("ground freezing for excavation", "تجميد الأرض للحفر"),
    ("geocell confinement of soil", "حجز التربة بالخلية الأرضية"),
    ("geonet drainage layer", "طبقة تصريف بالشبكة الأرضية"),
    ("geocomposite drain", "مصرف مركب أرضي"),
    ("lightweight expanded fill", "ردم خفيف ممدد"),
    ("expanded polystyrene embankment", "ردم البوليسترين الممدد"),
    ("chemical grouting of sand", "الحقن الكيميائي للرمل"),
    ("microbially induced calcite precipitation", "ترسيب الكالسايت المحفَّز ميكروبيا"),
    ("fiber reinforced soil", "تربة مسلحة بالألياف"),
    ("lime fly ash stabilization", "تثبيت بكلس ورماد متطاير"),
    ("mechanical stabilization of subgrade", "التثبيت الميكانيكي لطبقة التأسيس"),
    ("soil replacement under footing", "استبدال التربة تحت القاعدة"),
    ("undercut and replace soft soil", "إزالة التربة اللينة واستبدالها"),
    ("resilient modulus of subgrade", "معامل المرونة الراجع لطبقة التأسيس"),
    ("soaked california bearing ratio", "نسبة تحمل كاليفورنيا المشبعة"),
    ("unsoaked california bearing ratio", "نسبة تحمل كاليفورنيا غير المشبعة"),
    ("subgrade reaction for pavement", "رد فعل التأسيس للتبليط"),
    # ── الأوتاد من جهة التربة ──
    ("unit skin friction of pile", "احتكاك سطحي واحدي للوتد"),
    ("unit end bearing of pile", "ارتكاز طرفي واحدي للوتد"),
    ("alpha method for clay piles", "طريقة ألفا لأوتاد الغضار"),
    ("beta method for pile shafts", "طريقة بيتا لجذع الوتد"),
    ("lambda method for piles", "طريقة لامدا للأوتاد"),
    ("tomlinson alpha factor", "معامل ألفا لتوملينسون"),
    ("downdrag load on pile", "حمل السحب السفلي على الوتد"),
    ("neutral plane depth of pile", "عمق المستوي المحايد للوتد"),
    ("pile group in compressible clay", "مجموعة أوتاد في غضار قابل للانضغاط"),
    ("equivalent raft of pile group", "حصيرة مكافئة لمجموعة الأوتاد"),
    ("lateral soil resistance of pile", "مقاومة التربة الجانبية للوتد"),
    ("p y curve for lateral pile", "منحنى القوة-الإزاحة للوتد الجانبي"),
    ("broms method for lateral piles", "طريقة برومس للأوتاد الجانبية"),
    ("free head pile condition", "شرط الرأس الحر للوتد"),
    ("fixed head pile condition", "شرط الرأس المثبت للوتد"),
    ("pile setup after driving", "تزايد قدرة الوتد بعد الدق"),
    ("relaxation of pile capacity", "ارتخاء قدرة الوتد"),
    ("plugging of open ended pile", "انسداد الوتد المفتوح الطرف"),
    ("tremie concreting of bored pile", "صب الوتد المحفور بالقمع"),
    ("crosshole sonic logging of pile", "السبر الصوتي المتقاطع للوتد"),
    ("low strain pile integrity", "سلامة الوتد بالانفعال المنخفض"),
    ("high strain dynamic pile test", "اختبار الوتد الديناميكي عالي الانفعال"),
    ("case method pile capacity", "قدرة الوتد بطريقة كيس"),
    ("davisson offset failure criterion", "معيار انهيار الإزاحة لدافيسون"),
    ("maintained load pile test", "اختبار الوتد بالحمل المثبت"),
    ("constant rate of penetration test", "اختبار معدل الاختراق الثابت"),
    # ── السدود الترابية والمراقبة ──
    ("zoned earth embankment dam", "سد ردم ترابي مقطّع"),
    ("clay core of earth dam", "لب غضاري للسد الترابي"),
    ("pervious shell of dam", "قشرة نفاذة للسد"),
    ("transition filter zone", "نطاق مرشح انتقالي"),
    ("upstream slope of earth dam", "ميل مقدم السد الترابي"),
    ("downstream slope of earth dam", "ميل مؤخر السد الترابي"),
    ("slurry trench cutoff wall", "جدار قطع بخندق الطين"),
    ("soil bentonite cutoff", "قطع بتربة وبنتونيت"),
    ("cement bentonite wall", "جدار أسمنت وبنتونيت"),
    ("staged construction of embankment", "إنشاء الردم على مراحل"),
    ("basal reinforcement of embankment", "تسليح قاعدة الردم"),
    ("stability berm of soft ground", "كتف استقرار على أرض لينة"),
    ("pore pressure monitoring point", "نقطة مراقبة ضغط المسام"),
    ("settlement plate under embankment", "صفيحة هبوط تحت الردم"),
    ("inclinometer in soil slope", "مقياس الميل في منحدر التربة"),
    ("extensometer in soil mass", "مقياس التمدد في كتلة التربة"),
    ("instrumentation of earth structure", "أجهزة رصد المنشأ الترابي"),
    ("riprap on embankment slope", "رمي حجاري على ميل الردم"),
    # ── نموذج التربة والأساس ──
    ("elastic half space of soil", "نصف فضاء مرن للتربة"),
    ("winkler spring model of soil", "نموذج نوابض وينكلر للتربة"),
    ("beam on elastic soil foundation", "جائز على أساس تربة مرن"),
    ("pasternak two parameter foundation", "أساس باستيرناك ذي معاملين"),
    ("modulus of subgrade for beam", "معامل رد الفعل للجائز"),
    ("geotechnical engineering of soils", "الهندسة الجيوتقنية للترب"),
    ("subsurface investigation report", "تقرير الاستكشاف تحت السطحي"),
    ("allowable soil pressure", "ضغط التربة المسموح"),
    ("net allowable soil pressure", "ضغط التربة الصافي المسموح"),
    ("ultimate soil resistance", "مقاومة التربة القصوى"),
    ("strain compatibility of soil", "توافق انفعال التربة"),
    ("plane strain condition in soil", "شرط الانفعال المستوي في التربة"),
    ("axisymmetric soil loading", "تحميل التربة متناظر المحور"),
    ("drained loading of sand", "تحميل مصرف للرمل"),
    ("undrained loading of clay", "تحميل غير مصرف للغضار"),
    ("partially drained soil response", "استجابة التربة المصرفة جزئيا"),
    ("coefficient of volume change", "معامل تغير الحجم"),
    ("specific gravity bottle test", "اختبار قنينة الوزن النوعي"),
    ("liquid limit casagrande cup", "حد السيولة بكأس كازاغراندي"),
    ("fall cone liquid limit", "حد السيولة بالمخروط الساقط"),
    ("plastic limit thread test", "اختبار خيط حد اللدونة"),
    ("shrinkage limit dish test", "اختبار طبق حد الانكماش"),
    # ── رموز التصنيف ──
    ("coarse grained soil classification", "تصنيف التربة خشنة الحبيبات"),
    ("fine grained soil classification", "تصنيف التربة ناعمة الحبيبات"),
    ("dual symbol soil classification", "تصنيف التربة برمز مزدوج"),
    ("borderline soil classification", "تصنيف التربة الحدّي"),
    ("clean gravel classification", "تصنيف الحصى النظيف"),
    ("silty gravel classification", "تصنيف الحصى الغريني"),
    ("clayey gravel classification", "تصنيف الحصى الغضاري"),
    ("clean sand classification", "تصنيف الرمل النظيف"),
    ("low plasticity silt", "غرين قليل اللدونة"),
    ("high plasticity silt", "غرين عالي اللدونة"),
    ("organic silt of low plasticity", "غرين عضوي قليل اللدونة"),
    ("organic clay of high plasticity", "غضار عضوي عالي اللدونة"),
    ("peat soil classification", "تصنيف التربة الخثية"),
    ("aashto granular subgrade", "تأسيس حبيبي حسب آشتو"),
    ("aashto silt clay material", "مادة غرين-غضار حسب آشتو"),
    ("british soil classification system", "نظام التصنيف البريطاني للتربة"),
    ("very loose sand density", "رمل شديد التخلخل"),
    ("loose sand density state", "حالة رمل مخلخل"),
    ("medium dense sand state", "حالة رمل متوسط الكثافة"),
    ("dense sand density state", "حالة رمل كثيف"),
    ("very dense sand state", "حالة رمل شديد الكثافة"),
    ("skempton activity of clay", "فعالية الغضار لسكيمبتون"),
    ("quick clay sensitivity range", "مدى حساسية الغضار السريع"),
    ("inactive clay mineral", "معدن غضار غير فعّال"),
    ("normal activity clay", "غضار ذو فعالية طبيعية"),
    ("active clay mineral behavior", "سلوك معدن غضار فعّال"),
    # ── الترب الجبسية والملحية ──
    ("gypseous soil deposit", "ترسب تربة جبسية"),
    ("gypsum content of soil", "محتوى الجبس في التربة"),
    ("highly gypseous soil", "تربة شديدة الجبسية"),
    ("moderately gypseous soil", "تربة متوسطة الجبسية"),
    ("slightly gypseous soil", "تربة قليلة الجبسية"),
    ("hydrated gypsum in soil", "جبس مائي في التربة"),
    ("anhydrite mineral in soil", "معدن الأنهيدريت في التربة"),
    ("dissolution of gypsum crystals", "ذوبان بلورات الجبس"),
    ("leaching of gypseous soil", "غسل التربة الجبسية"),
    ("collapse of gypseous soil", "انهيار التربة الجبسية"),
    ("soaking test of gypseous soil", "اختبار غمر التربة الجبسية"),
    ("single oedometer soaking test", "اختبار الغمر بأويدومتر مفرد"),
    ("double oedometer gypseous test", "اختبار جبسي بأويدومتر مزدوج"),
    ("leaching settlement of soil", "هبوط الغسل للتربة"),
    ("wetting induced settlement", "هبوط ناتج عن الابتلال"),
    ("collapsibility index of soil", "دليل قابلية الانهيار للتربة"),
    ("initial collapse pressure", "ضغط الانهيار الابتدائي"),
    ("cavity formation after leaching", "تكوّن تجاويف بعد الغسل"),
    ("strength loss after soaking", "فقدان المقاومة بعد الغمر"),
    ("permeability increase after leaching", "زيادة النفاذية بعد الغسل"),
    ("gypsum crust at surface", "قشرة جبسية سطحية"),
    ("secondary gypsum precipitation", "ترسب الجبس الثانوي"),
    ("chemical gypsum content test", "اختبار المحتوى الجبسي الكيميائي"),
    ("prewetting of collapsible soil", "الترطيب المسبق للتربة القابلة للانهيار"),
    ("soil replacement of gypsum layer", "استبدال طبقة التربة الجبسية"),
    ("impermeable membrane under gypsum soil", "غشاء كتيم تحت التربة الجبسية"),
    ("drainage control on gypseous ground", "ضبط التصريف في الأرض الجبسية"),
    ("cement treatment of gypseous soil", "معالجة التربة الجبسية بالأسمنت"),
    ("pile through gypseous layer", "وتد عبر الطبقة الجبسية"),
    ("sabkha soil deposit", "ترسب تربة السبخة"),
    ("saline sabkha crust", "قشرة سبخة ملحية"),
    ("salt heave of soil", "انتفاخ ملحي للتربة"),
    ("total soluble salts of soil", "الأملاح الذائبة الكلية في التربة"),
    ("sulfate content of soil", "محتوى الكبريتات في التربة"),
    ("chloride content of soil", "محتوى الكلوريد في التربة"),
    ("carbonate content of soil", "محتوى الكربونات في التربة"),
    ("soil aggressiveness to concrete", "عدوانية التربة على الخرسانة"),
    ("corrosion of foundation in saline soil", "تآكل الأساس في التربة الملحية"),
    ("electrical conductivity of soil extract", "الناقلية الكهربائية لمستخلص التربة"),
    ("exchangeable sodium of soil", "الصوديوم القابل للتبادل في التربة"),
    ("dispersion percentage of clay", "نسبة تشتت الغضار"),
    ("ph of soil suspension", "أس معلق التربة الهيدروجيني"),
    # ── معاملات الحالة الحرجة والقص ──
    ("compression index lambda of clay", "دليل الانضغاط لامدا للغضار"),
    ("swelling index kappa of clay", "دليل الانتفاخ كابا للغضار"),
    ("critical state stress ratio", "نسبة إجهاد الحالة الحرجة"),
    ("specific volume at critical state", "الحجم النوعي عند الحالة الحرجة"),
    ("isotropic compression of clay", "الانضغاط المتماثل للغضار"),
    ("bolton dilatancy correlation", "علاقة بولتون للتمدد"),
    ("rowe stress dilatancy relation", "علاقة رو بين الإجهاد والتمدد"),
    ("back pressure saturation of specimen", "إشباع العينة بالضغط الخلفي"),
    ("pore pressure parameter b check", "تحقق معامل ضغط المسام B"),
    ("membrane correction of triaxial", "تصحيح الغشاء في الاختبار ثلاثي المحاور"),
    ("area correction of triaxial specimen", "تصحيح مساحة عينة ثلاثي المحاور"),
    ("maximum deviator stress", "إجهاد الانحراف الأعظم"),
    ("axial strain at failure", "الانفعال المحوري عند الانهيار"),
    ("volumetric strain of drained test", "الانفعال الحجمي للاختبار المصرف"),
    ("pore pressure at failure", "ضغط المسام عند الانهيار"),
    ("reversal shear for residual strength", "قص عكسي للمقاومة المتبقية"),
    ("fall cone undrained strength", "مقاومة غير مصرفة بالمخروط الساقط"),
    ("laboratory vane strength", "مقاومة المروحة المخبرية"),
    ("failure envelope in terms of effective stress", "غلاف الانهيار بدلالة الإجهاد الفعال"),
    ("failure envelope in total stress", "غلاف الانهيار بالإجهاد الكلي"),
    ("cohesion intercept of failure envelope", "تقاطع التماسك لغلاف الانهيار"),
    ("friction angle from triaxial tests", "زاوية الاحتكاك من اختبارات ثلاثي المحاور"),
    ("undrained shear strength profile", "مقطع مقاومة القص غير المصرفة"),
    ("strength increase with depth", "زيادة المقاومة مع العمق"),
    ("normalized undrained strength", "المقاومة غير المصرفة المعيّرة"),
    ("strength ratio of clay", "نسبة مقاومة الغضار"),
    ("strain rate of shear test", "معدل انفعال اختبار القص"),
    ("peak to residual strength drop", "هبوط المقاومة من القصوى إلى المتبقية"),
    # ── الانضمام تفصيلا ──
    ("isochrone of pore pressure", "خط تساوي ضغط المسام"),
    ("parabolic isochrone assumption", "فرض خط قطع مكافئ لضغط المسام"),
    ("barron radial consolidation", "الانضمام الشعاعي لبارون"),
    ("hansbo vertical drain theory", "نظرية هانسبو للمصرف الشاقولي"),
    ("mandel cryer effect", "أثر ماندل-كراير"),
    ("coefficient of consolidation from square root time", "معامل الانضمام من جذر الزمن"),
    ("coefficient of consolidation from log time", "معامل الانضمام من لوغاريتم الزمن"),
    ("volume compressibility from oedometer", "الانضغاطية الحجمية من الأويدومتر"),
    ("compression index from void ratio plot", "دليل الانضغاط من منحنى نسبة الفراغات"),
    ("swelling index from unloading", "دليل الانتفاخ من إزالة التحميل"),
    ("recompression of overconsolidated clay", "إعادة انضغاط الغضار مفرط الانضمام"),
    ("settlement of normally consolidated layer", "هبوط الطبقة المنضمة طبيعيا"),
    ("time settlement curve of clay", "منحنى الهبوط مع الزمن للغضار"),
    ("degree of consolidation at mid layer", "درجة الانضمام في منتصف الطبقة"),
    ("average consolidation of double drainage", "الانضمام المتوسط للتصريف المزدوج"),
    ("thickness of compressible layer", "سمك الطبقة القابلة للانضغاط"),
    ("stress increment in clay layer", "زيادة الإجهاد في طبقة الغضار"),
    ("initial void ratio of clay", "نسبة الفراغات الابتدائية للغضار"),
    ("final void ratio after consolidation", "نسبة الفراغات النهائية بعد الانضمام"),
    ("primary consolidation settlement formula", "صيغة هبوط الانضمام الأولي"),
    ("secondary compression settlement formula", "صيغة هبوط الانضغاط الثانوي"),
    ("time for fifty percent consolidation", "زمن الانضمام بنسبة خمسين بالمئة"),
    ("time for ninety percent consolidation", "زمن الانضمام بنسبة تسعين بالمئة"),
    ("drainage boundary pervious", "حد تصريف نفاذ"),
    ("drainage boundary impervious", "حد تصريف كتيم"),
    # ── قدرة التحمل والهبوط تفصيلا ──
    ("bearing capacity factor for cohesion", "معامل قدرة التحمل للتماسك"),
    ("bearing capacity factor for surcharge", "معامل قدرة التحمل للحمل الإضافي"),
    ("bearing capacity factor for weight", "معامل قدرة التحمل لوزن التربة"),
    ("shape correction of bearing capacity", "تصحيح الشكل لقدرة التحمل"),
    ("depth correction of bearing capacity", "تصحيح العمق لقدرة التحمل"),
    ("load inclination correction", "تصحيح ميل الحمل"),
    ("base tilt correction of footing", "تصحيح ميل قاعدة الأساس"),
    ("ground slope correction of bearing", "تصحيح ميل الأرض لقدرة التحمل"),
    ("local shear reduced strength", "مقاومة مخفضة للقص الموضعي"),
    ("effective width of eccentric footing", "العرض الفعال للقاعدة اللامركزية"),
    ("meyerhof effective foundation area", "مساحة الأساس الفعالة لمايرهوف"),
    ("no tension beneath footing", "انعدام الشد تحت القاعدة"),
    ("triangular contact pressure", "ضغط تماس مثلثي"),
    ("trapezoidal contact pressure", "ضغط تماس شبه منحرف"),
    ("factor of safety on ultimate pressure", "معامل الأمان على الضغط الأقصى"),
    ("settlement limited allowable pressure", "الضغط المسموح المحدود بالهبوط"),
    ("burland burbidge settlement method", "طريقة برلاند-بوربيدج للهبوط"),
    ("meyerhof spt settlement method", "طريقة مايرهوف لهبوط الاختراق القياسي"),
    ("fox depth correction of settlement", "تصحيح فوكس لعمق الهبوط"),
    ("steinbrenner settlement influence", "تأثير شتاينبرينر للهبوط"),
    ("immediate settlement of saturated clay", "الهبوط الآني للغضار المشبع"),
    ("settlement from compressibility coefficient", "الهبوط من معامل الانضغاطية"),
    ("settlement from compression index", "الهبوط من دليل الانضغاط"),
    ("plate load size correction", "تصحيح حجم اختبار الصفيحة"),
    ("allowable pressure from plate test", "الضغط المسموح من اختبار الصفيحة"),
    ("kentledge reaction of plate test", "رد فعل أثقال اختبار الصفيحة"),
    ("screw plate load test", "اختبار تحميل الصفيحة اللولبية"),
    ("foundation inspection at formation", "معاينة الأساس عند منسوب التأسيس"),
    ("formation level of soil", "منسوب التأسيس للتربة"),
    ("blinding concrete on formation", "خرسانة نظافة على منسوب التأسيس"),
    ("allowable pressure at formation level", "الضغط المسموح عند منسوب التأسيس"),
    # ── ضغط التربة والجدران ──
    ("wall displacement for active state", "إزاحة الجدار لحالة الضغط الفعال"),
    ("wall displacement for passive state", "إزاحة الجدار لحالة الضغط المقاوم"),
    ("equivalent fluid pressure of backfill", "ضغط المائع المكافئ للردم"),
    ("adhesion of clay to wall", "التصاق الغضار بالجدار"),
    ("wall adhesion reduction factor", "معامل تخفيض التصاق الجدار"),
    ("inclined back face of wall", "وجه خلفي مائل للجدار"),
    ("log spiral passive surface", "سطح مقاوم لولبي لوغاريتمي"),
    ("overturning moment about wall toe", "عزم الانقلاب حول مقدمة الجدار"),
    ("resisting moment of wall weight", "عزم المقاومة من وزن الجدار"),
    ("sliding resistance of wall base", "مقاومة انزلاق قاعدة الجدار"),
    ("passive resistance in front of wall", "المقاومة السلبية أمام الجدار"),
    ("shear key below wall base", "مفتاح قص تحت قاعدة الجدار"),
    ("weep hole drainage of wall", "تصريف فتحات البكاء في الجدار"),
    ("hydrostatic thrust on wall", "دفع هيدروستاتيكي على الجدار"),
    ("submerged backfill earth pressure", "ضغط تربة الردم المغمور"),
    ("partly submerged backfill", "ردم مغمور جزئيا"),
    ("factor of safety against bearing of wall", "معامل الأمان ضد تحمل الجدار"),
    ("resultant location within middle third", "موقع المحصلة ضمن الثلث الأوسط"),
    ("middle third rule of wall base", "قاعدة الثلث الأوسط لقاعدة الجدار"),
    ("drainage layer behind wall", "طبقة تصريف خلف الجدار"),
    ("retained soil height", "ارتفاع التربة المحجوزة"),
    ("embedment depth of wall", "عمق انغراس الجدار"),
    ("prop stiffness of excavation", "صلابة دعامة الحفر"),
    ("wall deflection of braced cut", "انحراف جدار الحفر المدعم"),
    ("ground settlement behind excavation", "هبوط الأرض خلف الحفر"),
    ("building damage due to excavation", "ضرر المبنى بسبب الحفر"),
    ("basal stability of clay excavation", "استقرار قاع الحفر في الغضار"),
    ("uplift of basement slab", "رفع بلاطة القبو"),
    ("factor of safety against buoyancy", "معامل الأمان ضد الطفو"),
    ("permanent basement drainage", "تصريف القبو الدائم"),
    ("circular shaft earth pressure", "ضغط التربة على البئر الدائري"),
    ("bottom plug of cofferdam", "سدادة قاع السد الصندوقي"),
    ("piping into open excavation", "الأنابيب إلى الحفر المفتوح"),
    # ── الأوتاد تفصيلا ──
    ("shaft resistance in sand", "مقاومة الجذع في الرمل"),
    ("shaft resistance in clay", "مقاومة الجذع في الغضار"),
    ("base resistance of bored pile", "مقاومة قاعدة الوتد المحفور"),
    ("bored pile base reduction factor", "معامل تخفيض قاعدة الوتد المحفور"),
    ("nordlund driven pile method", "طريقة نوردلوند للوتد المدقوق"),
    ("api offshore pile method", "طريقة المعهد الأمريكي لأوتاد البحر"),
    ("fleming pile settlement method", "طريقة فليمنغ لهبوط الوتد"),
    ("elastic shortening of pile shaft", "التقصير المرن لجذع الوتد"),
    ("converse labarre group efficiency", "كفاءة المجموعة لطريقة كونفيرس-لابار"),
    ("feld rule for pile groups", "قاعدة فيلد لمجموعات الأوتاد"),
    ("center to center pile spacing", "التباعد من مركز إلى مركز للأوتاد"),
    ("minimum spacing of piles", "التباعد الأدنى للأوتاد"),
    ("settlement ratio of pile group", "نسبة هبوط مجموعة الأوتاد"),
    ("pile interaction factor", "معامل تداخل الأوتاد"),
    ("pile driving blow count", "عدد ضربات دق الوتد"),
    ("final set of pile driving", "الهبوط النهائي لدق الوتد"),
    ("pile driving refusal", "رفض استمرار دق الوتد"),
    ("driving stress in concrete pile", "إجهاد الدق في الوتد الخرساني"),
    ("pile helmet cushion", "وسادة خوذة الوتد"),
    ("preboring before pile driving", "الحفر المسبق قبل دق الوتد"),
    ("jetting during pile installation", "الاندفاع المائي أثناء تركيب الوتد"),
    ("pressure grouted pile shaft", "جذع وتد محقون بالضغط"),
    ("grouted bond of micropile", "تماسك حقن الوتد الدقيق"),
    ("uplift capacity of tension pile", "قدرة الرفع لوتد الشد"),
    ("tension load test of pile", "اختبار حمل الشد للوتد"),
    ("lateral deflection of pile head", "الانحراف الجانبي لرأس الوتد"),
    ("bending moment in lateral pile", "عزم الانحناء في الوتد الجانبي"),
    ("p multiplier of pile group", "مضاعف منحنى القوة لمجموعة الأوتاد"),
    ("shadowing of trailing piles", "تظليل الأوتاد الخلفية"),
    ("cyclic degradation of shaft friction", "تدهور الاحتكاك الدوري للجذع"),
    ("bitumen slip layer against downdrag", "طبقة بيتومين ضد السحب السفلي"),
    ("scour reduction of pile capacity", "انخفاض قدرة الوتد بسبب النحر"),
    ("wave equation drivability study", "دراسة قابلية الدق بمعادلة الموجة"),
    ("hammer energy transferred to pile", "طاقة المطرقة المنتقلة إلى الوتد"),
    ("residual load locked in pile", "الحمل المتبقي المحبوس في الوتد"),
    ("chin extrapolation of pile test", "استقراء تشن لاختبار الوتد"),
    ("failure load of static pile test", "حمل انهيار اختبار الوتد الساكن"),
    # ── التثبيت الأرضي والتركيبات ──
    ("separation function of geotextile", "وظيفة الفصل للنسيج الأرضي"),
    ("filtration function of geotextile", "وظيفة الترشيح للنسيج الأرضي"),
    ("reinforcement function of geogrid", "وظيفة التسليح للشبكة الأرضية"),
    ("apparent opening size of geotextile", "حجم الفتحة الظاهري للنسيج الأرضي"),
    ("permittivity of geotextile", "إنفاذية النسيج الأرضي"),
    ("transmissivity of drainage geonet", "ناقلية التصريف للشبكة الأرضية"),
    ("pullout test of soil reinforcement", "اختبار سحب تسليح التربة"),
    ("installation damage reduction factor", "معامل تخفيض ضرر التركيب"),
    ("durability reduction of reinforcement", "تخفيض الديمومة للتسليح"),
    ("allowable strength of geogrid", "المقاومة المسموحة للشبكة الأرضية"),
    ("internal stability of reinforced wall", "الاستقرار الداخلي للجدار المسلح"),
    ("external stability of reinforced wall", "الاستقرار الخارجي للجدار المسلح"),
    ("compound stability of mse wall", "الاستقرار المركب لجدار التربة المسلحة"),
    ("vertical spacing of reinforcement", "التباعد الشاقولي للتسليح"),
    ("embedment length of geogrid", "طول انغراس الشبكة الأرضية"),
    ("facing connection of mse wall", "وصلة واجهة جدار التربة المسلحة"),
    ("seismic design of reinforced soil", "التصميم الزلزالي للتربة المسلحة"),
    ("soil nail bond stress", "إجهاد تماسك مسمار التربة"),
    ("soil nail inclination", "ميل مسمار التربة"),
    ("shotcrete facing of nailed wall", "واجهة خرسانة مقذوفة للجدار المسمّر"),
    ("proof test of ground anchor", "اختبار إثبات المرساة الأرضية"),
    ("lock off load of anchor", "حمل قفل المرساة"),
    ("free length of ground anchor", "الطول الحر للمرساة الأرضية"),
    ("creep test of ground anchor", "اختبار زحف المرساة الأرضية"),
    ("temporary ground anchor", "مرساة أرضية مؤقتة"),
    ("permanent ground anchor", "مرساة أرضية دائمة"),
    ("corrosion protection of anchor", "حماية المرساة من التآكل"),
    # ── الأنفاق والأعمال الترابية ──
    ("face stability of soil tunnel", "استقرار جبهة نفق التربة"),
    ("volume loss due to tunneling", "فقد الحجم بسبب الأنفاق"),
    ("peck gaussian settlement trough", "حوض هبوط بيك الغاوسي"),
    ("inflection point of settlement trough", "نقطة انعطاف حوض الهبوط"),
    ("horizontal strain from tunneling", "الانفعال الأفقي بسبب الأنفاق"),
    ("borrow area of embankment fill", "منطقة استعارة ردم السد"),
    ("cut and fill earthwork balance", "موازنة قطع وردم الأعمال الترابية"),
    ("unsuitable soil for fill", "تربة غير صالحة للردم"),
    ("suitable fill acceptance", "قبول الردم الصالح"),
    ("moisture window for compaction", "نافذة الرطوبة للرص"),
    ("field density test frequency", "تكرار اختبار الكثافة الحقلية"),
    ("recompaction of failed layer", "إعادة رص الطبقة الراسبة"),
    ("soft spot excavation and replacement", "إزالة البقعة اللينة واستبدالها"),
    ("benching fill on sidelong ground", "درج الردم على أرض مائلة"),
    ("topsoil strip before filling", "إزالة التربة السطحية قبل الردم"),
    ("working platform on soft clay", "منصة عمل على غضار لين"),
    ("geogrid reinforced working platform", "منصة عمل مسلحة بشبكة أرضية"),
    ("rutting criterion of platform", "معيار التخدد للمنصة"),
    ("capping layer over weak subgrade", "طبقة تغطية فوق تأسيس ضعيف"),
    ("design cbr of pavement subgrade", "نسبة التحمل التصميمية لتأسيس التبليط"),
    ("equilibrium moisture of subgrade", "رطوبة التوازن لطبقة التأسيس"),
    ("lime treated pavement subgrade", "تأسيس تبليط معالج بالكلس"),
    ("cement treated subgrade layer", "طبقة تأسيس معالجة بالأسمنت"),
    ("geotextile separator under subbase", "نسيج فاصل تحت طبقة الأساس المساعدة"),
    ("frost protection depth of pavement", "عمق حماية التبليط من الصقيع"),
    # ── الاستكشاف وأجهزة القياس ──
    ("trial pit soil description", "وصف التربة في الحفرة الاختبارية"),
    ("borehole location plan", "مخطط مواقع الآبار"),
    ("termination depth of borehole", "عمق إنهاء البئر"),
    ("groundwater strike in borehole", "ظهور المياه في البئر"),
    ("standing groundwater level", "منسوب المياه المستقر"),
    ("wax sealed undisturbed sample", "عينة غير مشوشة مختومة بالشمع"),
    ("sample quality class one", "عينة من صنف الجودة الأول"),
    ("remolded sample quality class", "صنف جودة العينة المعاد تشكيلها"),
    ("pore pressure dissipation test", "اختبار تبدد ضغط المسام"),
    ("time for fifty percent dissipation", "زمن تبدد خمسين بالمئة"),
    ("horizontal consolidation from dissipation", "الانضمام الأفقي من التبدد"),
    ("pressuremeter creep pressure", "ضغط زحف مقياس الضغط"),
    ("unload reload pressuremeter modulus", "معامل إزالة التحميل لمقياس الضغط"),
    ("dilatometer lift off pressure", "ضغط الانفصال لمقياس التمدد"),
    ("masw surface wave survey", "مسح الأمواج السطحية المتعدد القنوات"),
    ("electrical resistivity tomography", "تصوير المقاومية الكهربائية"),
    ("downhole shear wave survey", "مسح موجة القص داخل البئر"),
    ("geotechnical factual report", "التقرير الجيوتقني الوقائعي"),
    ("geotechnical interpretative report", "التقرير الجيوتقني التفسيري"),
    ("design soil profile", "مقطع التربة التصميمي"),
    ("characteristic soil parameter", "معامل التربة المميّز"),
    ("cautious estimate of soil strength", "تقدير حذر لمقاومة التربة"),
    ("partial factor on friction angle", "المعامل الجزئي على زاوية الاحتكاك"),
    ("partial factor on cohesion", "المعامل الجزئي على التماسك"),
    ("partial factor on undrained strength", "المعامل الجزئي على المقاومة غير المصرفة"),
    ("geotechnical ultimate limit state", "حالة الحد الأقصى الجيوتقنية"),
    ("geotechnical serviceability limit", "حد الخدمة الجيوتقني"),
    ("observational method of construction", "طريقة المراقبة أثناء الإنشاء"),
    # ── النمذجة والانزلاقات ──
    ("mohr coulomb soil model", "نموذج مور-كولوم للتربة"),
    ("hardening soil constitutive model", "نموذج التربة المتصلبة البنائي"),
    ("soft soil creep constitutive model", "نموذج زحف التربة اللينة"),
    ("small strain hardening soil model", "نموذج التربة المتصلبة للانفعال الصغير"),
    ("strength reduction slope analysis", "تحليل المنحدر بتخفيض المقاومة"),
    ("interface element soil to structure", "عنصر تماس بين التربة والمنشأ"),
    ("initial geostatic stress procedure", "إجراء الإجهاد الجيوستاتيكي الابتدائي"),
    ("numerical staged construction", "الإنشاء المرحلي العددي"),
    ("embedded pile structural element", "عنصر إنشائي لوتد مطمور"),
    ("rotational landslide mechanism", "آلية انزلاق دوراني"),
    ("translational landslide mechanism", "آلية انزلاق انتقالي"),
    ("lateral spread ground failure", "انهيار الانتشار الجانبي للأرض"),
    ("debris flow of soil", "جريان الحطام للتربة"),
    ("soil creep on natural slope", "زحف التربة على المنحدر الطبيعي"),
    ("crown crack of landslide", "شق تاج الانزلاق"),
    ("toe bulge of sliding mass", "انتفاخ مقدم الكتلة المنزلقة"),
    ("main scarp of landslide", "الجرف الرئيسي للانزلاق"),
    ("reactivation of ancient landslide", "إعادة تنشيط انزلاق قديم"),
    ("rainfall triggered slope failure", "انهيار منحدر محفَّز بالمطر"),
    ("earthquake triggered landslide", "انزلاق محفَّز بالزلزال"),
    ("toe erosion triggering slide", "حت المقدم المسبب للانزلاق"),
    ("crest loading of slope", "تحميل قمة المنحدر"),
    ("residual factor of safety", "معامل الأمان المتبقي"),
    ("filter paper method for suction", "طريقة ورق الترشيح للمص"),
    ("pressure plate suction test", "اختبار المص بصفيحة الضغط"),
    ("chilled mirror soil suction", "مص التربة بالمرآة المبردة"),
    ("terzaghi filter retention criterion", "معيار احتباس المرشح لتيرزاغي"),
    ("terzaghi filter permeability criterion", "معيار نفاذية المرشح لتيرزاغي"),
    ("d15 of filter to d85 of soil", "D15 للمرشح إلى D85 للتربة"),
    ("relative compaction percentage of fill", "نسبة الرص المئوية للردم"),
    ("standard proctor compaction energy", "طاقة رص بروكتور القياسي"),
    ("modified proctor compaction energy", "طاقة رص بروكتور المعدل"),
    ("flexible wall permeability test", "اختبار النفاذية بجدار مرن"),
    ("constant volume swell pressure test", "اختبار ضغط الانتفاخ بحجم ثابت"),
    ("collapse strain upon inundation", "انفعال الانهيار عند الغمر"),
    ("cbr penetration resistance", "مقاومة اختراق نسبة التحمل"),
    ("four day soaked cbr", "نسبة التحمل بعد غمر أربعة أيام"),
    ("organic content by ignition", "المحتوى العضوي بالحرق"),
    ("linear shrinkage bar mold", "قالب قضيب الانكماش الخطي"),
    ("particle density of soil solids", "كثافة حبيبات التربة الصلبة"),
    ("dry density of compacted specimen", "الكثافة الجافة للعينة المرصوصة"),
    ("number of compaction layers", "عدد طبقات الرص"),
    ("blows per compaction layer", "الضربات لكل طبقة رص"),
]
