"""مصطلحات إضافية لتخصصات جامعية أوسع.

تُدمَج مع القاموس الأساسي. الكلمة غير الموجودة هنا لا تُترجم منفردة.
"""

from __future__ import annotations

# مختصرات واضحة تُستبدل حتى داخل الجملة.
EXTRA_FORCE_SHORT = {
    "adc", "api", "bim", "bios", "cnn", "css", "dac", "dft", "dhcp", "dns",
    "fft", "ftp", "gis", "gps", "gui", "hplc", "html", "http", "hvac", "igbt",
    "json", "knn", "lan", "lstm", "mosfet", "nlp", "nmr", "oop", "osi", "pca",
    "plc", "pwm", "rnn", "scada", "sql", "ssh", "svm", "tcp", "udp", "vlan",
    "wan", "xml",
}

EXTRA_ENTRIES: list[tuple[str, str]] = [
    # ── نفط وغاز ──
    ("reservoir engineering", "هندسة المكامن"),
    ("petroleum engineering", "هندسة النفط"),
    ("crude oil", "نفط خام"),
    ("natural gas", "غاز طبيعي"),
    ("associated gas", "غاز مصاحب"),
    ("drilling fluid", "سائل الحفر"),
    ("drilling mud", "طين الحفر"),
    ("blowout preventer", "مانع الانفجار"),
    ("well casing", "غلاف البئر"),
    ("well completion", "إكمال البئر"),
    ("well logging", "جس الآبار"),
    ("mud logging", "تسجيل طين الحفر"),
    ("directional drilling", "حفر موجه"),
    ("horizontal well", "بئر أفقية"),
    ("vertical well", "بئر عمودية"),
    ("drilling bit", "لقمة الحفر"),
    ("drill string", "خيط الحفر"),
    ("weight on bit", "الوزن على اللقمة"),
    ("rate of penetration", "معدل الاختراق"),
    ("lost circulation", "فقدان سائل الحفر"),
    ("stuck pipe", "أنبوب عالق"),
    ("well kick", "اندفاع البئر"),
    ("well blowout", "انفجار البئر"),
    ("bottom hole pressure", "ضغط قاع البئر"),
    ("wellhead pressure", "ضغط رأس البئر"),
    ("reservoir pressure", "ضغط المكمن"),
    ("formation pressure", "ضغط التكوين"),
    ("pore pressure", "ضغط المسام"),
    ("capillary pressure", "ضغط شعري"),
    ("bubble point", "نقطة الفقاعة"),
    ("dew point", "نقطة الندى"),
    ("pour point", "نقطة الانسكاب"),
    ("flash point", "نقطة الوميض"),
    ("cloud point", "نقطة التغبش"),
    ("api gravity", "كثافة معهد البترول"),
    ("gas oil ratio", "نسبة الغاز إلى النفط"),
    ("water cut", "نسبة الماء"),
    ("relative permeability", "نفاذية نسبية"),
    ("absolute permeability", "نفاذية مطلقة"),
    ("effective porosity", "مسامية فعالة"),
    ("primary porosity", "مسامية أولية"),
    ("wettability", "قابلية التبلل"),
    ("interfacial tension", "توتر بيني"),
    ("enhanced oil recovery", "الاستخلاص المعزز للنفط"),
    ("primary recovery", "استخلاص أولي"),
    ("secondary recovery", "استخلاص ثانوي"),
    ("water flooding", "حقن الماء"),
    ("gas injection", "حقن الغاز"),
    ("hydraulic fracturing", "تكسير هيدروليكي"),
    ("proppant", "مادة داعمة"),
    ("well stimulation", "تنشيط البئر"),
    ("acidizing", "تحميض"),
    ("workover", "إصلاح البئر"),
    ("skin factor", "معامل التلف"),
    ("productivity index", "دليل الإنتاجية"),
    ("injectivity index", "دليل الحقن"),
    ("material balance equation", "معادلة الموازنة المادية"),
    ("decline curve", "منحنى الانحدار"),
    ("pressure transient analysis", "تحليل العابر الضغطي"),
    ("well test", "اختبار البئر"),
    ("pvt analysis", "تحليل الضغط والحجم والحرارة"),
    ("phase envelope", "غلاف الأطوار"),
    ("reservoir rock", "صخر مكمني"),
    ("source rock", "صخر مصدري"),
    ("cap rock", "صخر الغطاء"),
    ("geological fault", "صدع جيولوجي"),
    ("seismic survey", "مسح زلزالي"),
    ("seismic reflection", "انعكاس زلزالي"),
    ("oil migration", "هجرة النفط"),
    ("anticline", "طية محدبة"),
    ("syncline", "طية مقعرة"),
    ("octane number", "رقم الأوكتان"),
    ("cetane number", "رقم السيتان"),
    ("distillation column", "عمود التقطير"),
    ("fractional distillation", "تقطير تجزيئي"),
    ("catalytic cracking", "تكسير حفزي"),
    ("catalytic reforming", "إعادة تشكيل حفزية"),
    ("hydrotreating", "معالجة بالهيدروجين"),
    ("desulfurization", "إزالة الكبريت"),
    ("gas sweetening", "تحلية الغاز"),
    ("refinery", "مصفاة"),
    ("upstream operations", "عمليات المنبع"),
    ("downstream operations", "عمليات المصب"),
    ("oil pipeline", "خط أنابيب"),
    ("instruction pipeline", "خط تعليمات"),
    ("flow assurance", "ضمان الجريان"),
    ("multiphase flow", "جريان متعدد الأطوار"),
    ("annular pressure", "ضغط حلقي"),
    ("christmas tree", "مجموعة صمامات رأس البئر"),
    ("porosity", "مسامية"),
    ("saturation", "تشبع"),
    ("permeable zone", "نطاق نافذ"),
    # ── إنشاءات وتربة وطرق ومساحة ──
    ("moment distribution method", "طريقة توزيع العزوم"),
    ("slope deflection method", "طريقة الميل والدوران"),
    ("influence line", "خط التأثير"),
    ("degree of freedom", "درجة حرية"),
    ("stiffness matrix", "مصفوفة الجسوءة"),
    ("flexibility matrix", "مصفوفة المرونة"),
    ("plastic hinge", "مفصل لدن"),
    ("load combination", "تركيبة أحمال"),
    ("serviceability limit state", "حالة حد الخدمة"),
    ("ultimate limit state", "حالة الحد الأقصى"),
    ("limit state design", "تصميم حالات الحدود"),
    ("working stress design", "تصميم إجهاد التشغيل"),
    ("shear wall", "جدار قص"),
    ("moment resisting frame", "إطار مقاوم للعزوم"),
    ("braced frame", "إطار مسنود"),
    ("pile foundation", "أساس وتدي"),
    ("raft foundation", "أساس حصيري"),
    ("isolated footing", "قاعدة منفصلة"),
    ("combined footing", "قاعدة مشتركة"),
    ("soil compaction", "رص التربة"),
    ("proctor test", "اختبار بروكتور"),
    ("atterberg limits", "حدود أتربرغ"),
    ("liquid limit", "حد السيولة"),
    ("plastic limit", "حد اللدونة"),
    ("plasticity index", "دليل اللدونة"),
    ("effective stress", "إجهاد فعال"),
    ("pore water pressure", "ضغط ماء المسام"),
    ("angle of internal friction", "زاوية الاحتكاك الداخلي"),
    ("cohesion", "تماسك"),
    ("triaxial test", "اختبار ثلاثي المحاور"),
    ("direct shear test", "اختبار القص المباشر"),
    ("standard penetration test", "اختبار الاختراق القياسي"),
    ("plate load test", "اختبار تحميل الصفيحة"),
    ("active earth pressure", "ضغط التربة الفعال"),
    ("passive earth pressure", "ضغط التربة المقاوم"),
    ("earth pressure", "ضغط التربة"),
    ("slope stability", "استقرار المنحدر"),
    ("traffic volume", "حجم المرور"),
    ("level of service", "مستوى الخدمة"),
    ("stopping sight distance", "مسافة الرؤية للتوقف"),
    ("superelevation", "رفع جانبي"),
    ("horizontal curve", "منحنى أفقي"),
    ("vertical curve", "منحنى رأسي"),
    ("flexible pavement", "رصف مرن"),
    ("rigid pavement", "رصف صلب"),
    ("asphalt", "إسفلت"),
    ("subgrade", "طبقة التأسيس"),
    ("base course", "طبقة الأساس"),
    ("wearing course", "طبقة سطحية"),
    ("contour line", "خط كنتور"),
    ("survey benchmark", "علامة منسوب"),
    ("total station", "محطة رصد متكاملة"),
    ("theodolite", "ثيودوليت"),
    ("cartesian coordinates", "إحداثيات ديكارتية"),
    ("map scale", "مقياس الرسم"),
    ("azimuth", "سمت"),
    ("latitude", "خط العرض"),
    ("longitude", "خط الطول"),
    ("traverse survey", "مسح بالمضاريع"),
    ("differential leveling", "تسوية تفاضلية"),
    ("reinforced concrete design", "تصميم الخرسانة المسلحة"),
    ("development length", "طول التماسك"),
    ("lap splice", "تراكب التسليح"),
    ("reinforcement stirrup", "كانة"),
    ("one way slab", "بلاطة باتجاه واحد"),
    ("two way slab", "بلاطة باتجاهين"),
    ("flat slab", "بلاطة مسطحة"),
    ("punching shear", "قص ثاقب"),
    ("short column", "عمود قصير"),
    ("slender column", "عمود نحيف"),
    ("singly reinforced", "تسليح مفرد"),
    ("doubly reinforced", "تسليح مزدوج"),
    # ── قدرة كهربائية وآلات وإلكترونيات ──
    ("power system", "نظام قدرة"),
    ("transmission line", "خط نقل"),
    ("distribution system", "نظام توزيع"),
    ("electrical substation", "محطة تحويل كهربائية"),
    ("circuit breaker", "قاطع دائرة"),
    ("protective relay", "مرحّل حماية"),
    ("synchronous machine", "آلة تزامنية"),
    ("induction motor", "محرك حثي"),
    ("synchronous generator", "مولد تزامني"),
    ("squirrel cage", "قفص سنجابي"),
    ("wound rotor", "دوار ملفوف"),
    ("rotor slip", "انزلاق الدوار"),
    ("field winding", "ملف المجال"),
    ("armature winding", "ملف المنتج"),
    ("per unit system", "نظام الوحدة النسبية"),
    ("load flow", "سريان الأحمال"),
    ("fault analysis", "تحليل الأعطال"),
    ("symmetrical components", "المركبات المتماثلة"),
    ("positive sequence", "تتابع موجب"),
    ("negative sequence", "تتابع سالب"),
    ("zero sequence", "تتابع صفري"),
    ("transient stability", "استقرار عابر"),
    ("voltage regulation", "تنظيم الجهد"),
    ("power transformer", "محول قدرة"),
    ("current transformer", "محول تيار"),
    ("potential transformer", "محول جهد"),
    ("lightning arrester", "مانعة صواعق"),
    ("electrical grounding", "تأريض كهربائي"),
    ("skin effect", "تأثير سطحي"),
    ("power electronics", "إلكترونيات القدرة"),
    ("full wave rectifier", "مقوم موجة كاملة"),
    ("half wave rectifier", "مقوم نصف موجة"),
    ("voltage source inverter", "عاكس مصدر جهد"),
    ("pulse width modulation", "تعديل عرض النبضة"),
    ("total harmonic distortion", "تشوه توافقي كلي"),
    ("reactive power", "قدرة مفاعلة"),
    ("active power", "قدرة فعالة"),
    ("apparent power", "قدرة ظاهرية"),
    ("star connection", "توصيل نجمي"),
    ("delta connection", "توصيل مثلثي"),
    ("line voltage", "جهد الخط"),
    ("phase voltage", "جهد الطور"),
    ("line current", "تيار الخط"),
    ("phase current", "تيار الطور"),
    ("insulated gate bipolar transistor", "ترانزستور ثنائي القطب ذو بوابة معزولة"),
    ("metal oxide semiconductor field effect transistor", "ترانزستور تأثير المجال"),
    ("analog to digital converter", "محول تماثلي رقمي"),
    ("digital to analog converter", "محول رقمي تماثلي"),
    ("programmable logic controller", "متحكم منطقي قابل للبرمجة"),
    ("supervisory control and data acquisition", "نظام التحكم الإشرافي وجمع البيانات"),
    ("variable frequency drive", "سوق متغير التردد"),
    ("gain margin", "هامش الكسب"),
    ("phase margin", "هامش الطور"),
    ("steady state error", "خطأ الحالة المستقرة"),
    ("rise time", "زمن الصعود"),
    ("settling time", "زمن الاستقرار"),
    ("percent overshoot", "نسبة التجاوز"),
    ("damping ratio", "نسبة التخميد"),
    ("natural frequency", "تردد طبيعي"),
    ("state space", "فضاء الحالة"),
    ("controllability", "قابلية التحكم"),
    ("observability", "قابلية الرصد"),
    ("routh hurwitz criterion", "معيار روث-هيرويتز"),
    ("root locus method", "طريقة المحل الهندسي للجذور"),
    ("bode diagram", "مخطط بود"),
    ("nyquist criterion", "معيار نيكويست"),
    ("lead compensator", "معوض متقدم"),
    ("lag compensator", "معوض متأخر"),
    ("proportional controller", "متحكم تناسبي"),
    ("integral controller", "متحكم تكاملي"),
    ("derivative controller", "متحكم تفاضلي"),
    # ── ميكانيك وتصنيع وتكييف ──
    ("internal energy", "طاقة داخلية"),
    ("latent heat", "حرارة كامنة"),
    ("sensible heat", "حرارة محسوسة"),
    ("vapor compression cycle", "دورة انضغاط البخار"),
    ("coefficient of performance", "معامل الأداء"),
    ("relative humidity", "رطوبة نسبية"),
    ("dry bulb temperature", "درجة الحرارة الجافة"),
    ("wet bulb temperature", "درجة الحرارة الرطبة"),
    ("refrigerant", "وسيط التبريد"),
    ("expansion valve", "صمام التمدد"),
    ("evaporator", "مبخر"),
    ("logarithmic mean temperature difference", "متوسط فرق درجة الحرارة اللوغاريتمي"),
    ("navier stokes equations", "معادلات نافير-ستوكس"),
    ("momentum equation", "معادلة الزخم"),
    ("venturi meter", "مقياس فنتوري"),
    ("orifice meter", "مقياس الفوهة"),
    ("pitot tube", "أنبوب بيتو"),
    ("kinematic viscosity", "لزوجة كينماتيكية"),
    ("dynamic viscosity", "لزوجة ديناميكية"),
    ("newtonian fluid", "مائع نيوتوني"),
    ("non newtonian fluid", "مائع غير نيوتوني"),
    ("friction factor", "معامل الاحتكاك"),
    ("head loss", "فقد الضغط"),
    ("centrifugal pump", "مضخة طرد مركزي"),
    ("positive displacement pump", "مضخة إزاحة موجبة"),
    ("net positive suction head", "صافي ضغط السحب الموجب"),
    ("cavitation", "تكهف"),
    ("specific speed", "السرعة النوعية"),
    ("spur gear", "ترس عدل"),
    ("helical gear", "ترس مائل"),
    ("bevel gear", "ترس مخروطي"),
    ("worm gear", "ترس دودي"),
    ("gear ratio", "نسبة التروس"),
    ("journal bearing", "محمل منزلق"),
    ("ball bearing", "محمل كريات"),
    ("roller bearing", "محمل دحاريج"),
    ("stress concentration", "تركيز الإجهاد"),
    ("endurance limit", "حد الكلال"),
    ("computer numerical control", "تحكم رقمي حاسوبي"),
    ("additive manufacturing", "تصنيع بالإضافة"),
    ("injection molding", "قولبة بالحقن"),
    ("surface roughness", "خشونة السطح"),
    ("centrifugal force", "قوة طاردة مركزية"),
    ("centripetal force", "قوة جابذة"),
    ("radius of gyration", "نصف قطر التدويم"),
    ("centroid", "مركز المساحة"),
    ("section modulus", "معامل المقطع"),
    ("second moment of area", "عزم المساحة الثاني"),
    ("polar moment of inertia", "عزم القصور القطبي"),
    ("shear center", "مركز القص"),
    ("principal axis", "محور رئيسي"),
    ("mohr circle", "دائرة مور"),
    ("von mises stress", "إجهاد فون ميزس"),
    ("tresca criterion", "معيار تريسكا"),
    ("hooke law", "قانون هوك"),
    ("cast iron", "حديد زهر"),
    ("stainless steel", "فولاذ مقاوم للصدأ"),
    ("composite material", "مادة مركبة"),
    ("phase diagram", "مخطط الأطوار"),
    ("grain boundary", "حد الحبيبة"),
    ("solid solution", "محلول جامد"),
    ("cold working", "تشكيل على البارد"),
    ("hot working", "تشكيل على الساخن"),
    ("fracture toughness", "متانة الكسر"),
    ("creep", "زحف"),
    ("annealing", "تلدين"),
    ("quenching", "تقسية بالتبريد السريع"),
    ("tempering", "إرجاع"),
    ("microstructure", "بنية مجهرية"),
    ("galvanic corrosion", "تآكل غلفاني"),
    ("stress corrosion cracking", "تشقق التآكل الإجهادي"),
    # ── هندسة كيميائية ومواد ──
    ("unit operation", "عملية وحدة"),
    ("unit process", "عملية تحويل"),
    ("shell and tube heat exchanger", "مبادل حراري أنابيب وغلاف"),
    ("packed column", "عمود محشو"),
    ("tray column", "عمود صواني"),
    ("reflux ratio", "نسبة الراجع"),
    ("relative volatility", "تطايرية نسبية"),
    ("mass transfer coefficient", "معامل انتقال الكتلة"),
    ("heat transfer coefficient", "معامل انتقال الحرارة"),
    ("overall heat transfer coefficient", "معامل انتقال الحرارة الكلي"),
    ("reynolds number", "عدد رينولدز"),
    ("nusselt correlation", "علاقة نسلت"),
    ("fick law", "قانون فيك"),
    ("fourier law", "قانون فورييه"),
    ("newton law of cooling", "قانون نيوتن للتبريد"),
    ("arrhenius equation", "معادلة أرينيوس"),
    ("rate constant", "ثابت معدل التفاعل"),
    ("order of reaction", "رتبة التفاعل"),
    ("batch reactor", "مفاعل دفعي"),
    ("continuous stirred tank reactor", "مفاعل خزان مستمر التقليب"),
    ("plug flow reactor", "مفاعل جريان كتلي"),
    ("reaction conversion", "تحول التفاعل"),
    ("reaction yield", "مردود التفاعل"),
    ("reaction selectivity", "انتقائية التفاعل"),
    ("recycle stream", "تيار إعادة تدوير"),
    ("purge stream", "تيار تنفيس"),
    ("bypass stream", "تيار تجاوز"),
    ("degrees of freedom analysis", "تحليل درجات الحرية"),
    ("psychrometric chart", "مخطط الهواء الرطب"),
    ("humidity ratio", "نسبة الرطوبة"),
    ("dew point temperature", "درجة حرارة نقطة الندى"),
    # ── حاسوب وشبكات وأمن وذكاء ──
    ("object oriented programming", "برمجة كائنية التوجه"),
    ("functional programming", "برمجة دالية"),
    ("data abstraction", "تجريد البيانات"),
    ("inheritance", "وراثة"),
    ("polymorphism", "تعدد الأشكال"),
    ("encapsulation", "تغليف"),
    ("linked list", "قائمة مترابطة"),
    ("binary tree", "شجرة ثنائية"),
    ("binary search tree", "شجرة بحث ثنائية"),
    ("hash table", "جدول تجزئة"),
    ("breadth first search", "بحث بالعرض"),
    ("depth first search", "بحث بالعمق"),
    ("dynamic programming", "برمجة ديناميكية"),
    ("greedy algorithm", "خوارزمية جشعة"),
    ("divide and conquer", "فرق تسد"),
    ("big o notation", "ترميز أو الكبير"),
    ("time complexity analysis", "تحليل التعقيد الزمني"),
    ("call stack", "مكدس الاستدعاء"),
    ("virtual memory", "ذاكرة افتراضية"),
    ("cache memory", "ذاكرة مخبأة"),
    ("page fault", "خطأ صفحة"),
    ("deadlock", "توقف تام"),
    ("mutual exclusion", "استبعاد متبادل"),
    ("context switch", "تبديل السياق"),
    ("process scheduling", "جدولة العمليات"),
    ("file system", "نظام ملفات"),
    ("syntax error", "خطأ نحوي"),
    ("runtime error", "خطأ وقت التشغيل"),
    ("version control", "إدارة الإصدارات"),
    ("source code", "شفرة مصدرية"),
    ("application programming interface", "واجهة برمجية"),
    ("relational database", "قاعدة بيانات علائقية"),
    ("primary key", "مفتاح أساسي"),
    ("foreign key", "مفتاح أجنبي"),
    ("database normalization", "تطبيع قواعد البيانات"),
    ("structured query language", "لغة الاستعلامات البنيوية"),
    ("inner join", "ربط داخلي"),
    ("left join", "ربط أيسر"),
    ("database transaction", "معاملة قاعدة بيانات"),
    ("atomicity", "ذرية"),
    ("durability", "ديمومة"),
    ("cloud computing", "حوسبة سحابية"),
    ("virtual machine", "آلة افتراضية"),
    ("firewall", "جدار ناري"),
    ("malware", "برمجية خبيثة"),
    ("phishing", "تصيد"),
    ("authentication", "مصادقة"),
    ("authorization", "تفويض"),
    ("public key", "مفتاح عام"),
    ("private key", "مفتاح خاص"),
    ("digital signature", "توقيع رقمي"),
    ("hash function", "دالة تجزئة"),
    ("checksum", "مجموع اختباري"),
    ("packet loss", "فقدان الحزم"),
    ("throughput", "إنتاجية"),
    ("ip address", "عنوان بروتوكول الإنترنت"),
    ("subnet mask", "قناع الشبكة الفرعية"),
    ("default gateway", "البوابة الافتراضية"),
    ("domain name system", "نظام أسماء النطاقات"),
    ("local area network", "شبكة محلية"),
    ("wide area network", "شبكة واسعة"),
    ("wireless network", "شبكة لاسلكية"),
    ("osi model", "نموذج الاتصال المفتوح"),
    ("hypertext transfer protocol", "بروتوكول نقل النص التشعبي"),
    ("transmission control protocol", "بروتوكول التحكم بالنقل"),
    ("user datagram protocol", "بروتوكول مخطط بيانات المستخدم"),
    ("signal to noise ratio", "نسبة الإشارة إلى الضوضاء"),
    ("bit error rate", "معدل خطأ البتات"),
    ("sampling theorem", "مبرهنة أخذ العينات"),
    ("fast fourier transform", "تحويل فورييه السريع"),
    ("discrete fourier transform", "تحويل فورييه المتقطع"),
    ("convolutional neural network", "شبكة عصبية تلافيفية"),
    ("recurrent neural network", "شبكة عصبية تكرارية"),
    ("long short term memory", "ذاكرة طويلة قصيرة المدى"),
    ("support vector machine", "آلة المتجهات الداعمة"),
    ("decision tree", "شجرة قرار"),
    ("random forest", "غابة عشوائية"),
    ("k means clustering", "تجميع بالمتوسطات"),
    ("principal component analysis", "تحليل المكونات الرئيسية"),
    ("natural language processing", "معالجة اللغات الطبيعية"),
    ("computer vision", "رؤية حاسوبية"),
    ("reinforcement learning", "تعلم تعزيزي"),
    ("supervised learning", "تعلم موجّه"),
    ("unsupervised learning", "تعلم غير موجّه"),
    ("training set", "مجموعة التدريب"),
    ("test set", "مجموعة الاختبار"),
    ("validation set", "مجموعة التحقق"),
    ("feature extraction", "استخراج السمات"),
    ("confusion matrix", "مصفوفة الالتباس"),
    ("cross validation", "تحقق متقاطع"),
    ("learning rate", "معدل التعلم"),
    ("activation function", "دالة التنشيط"),
    ("loss function", "دالة الخسارة"),
    ("hidden layer", "طبقة مخفية"),
    ("overfitting", "فرط الملاءمة"),
    ("hyperparameter", "وسيط فائق"),
    ("gradient descent algorithm", "خوارزمية نزول التدرج"),
    # ── رياضيات عددية وإحصاء متقدم ──
    ("mean value theorem", "مبرهنة القيمة المتوسطة"),
    ("intermediate value theorem", "مبرهنة القيمة الوسطى"),
    ("fundamental theorem of calculus", "المبرهنة الأساسية للحسبان"),
    ("green theorem", "مبرهنة غرين"),
    ("stokes theorem", "مبرهنة ستوكس"),
    ("divergence theorem", "مبرهنة التباعد"),
    ("singular value decomposition", "تحليل القيم الشاذة"),
    ("lu decomposition", "تحليل إل يو"),
    ("qr decomposition", "تحليل كيو آر"),
    ("cholesky decomposition", "تحليل تشوليسكي"),
    ("condition number", "عدد الشرط"),
    ("positive definite matrix", "مصفوفة موجبة التعريف"),
    ("symmetric matrix", "مصفوفة متناظرة"),
    ("diagonal matrix", "مصفوفة قطرية"),
    ("sparse matrix", "مصفوفة متفرقة"),
    ("simpson rule", "قاعدة سيمبسون"),
    ("trapezoidal rule", "قاعدة شبه المنحرف"),
    ("runge kutta method", "طريقة رونغ-كوتا"),
    ("finite volume method", "طريقة الحجوم المحدودة"),
    ("monte carlo method", "طريقة مونت كارلو"),
    ("least squares method", "طريقة المربعات الصغرى"),
    ("curve fitting", "ملاءمة منحنى"),
    ("truncation error", "خطأ البتر"),
    ("round off error", "خطأ التدوير"),
    ("central limit theorem", "مبرهنة النهاية المركزية"),
    ("bayes theorem", "مبرهنة بايز"),
    ("conditional probability", "احتمال شرطي"),
    ("mutually exclusive events", "أحداث متنافية"),
    ("sample space", "فضاء العينة"),
    ("probability mass function", "دالة الكتلة الاحتمالية"),
    ("cumulative distribution", "توزيع تراكمي"),
    ("standard error", "خطأ معياري"),
    ("type i error", "خطأ من النوع الأول"),
    ("type ii error", "خطأ من النوع الثاني"),
    ("statistical power", "قوة إحصائية"),
    ("confidence level", "مستوى الثقة"),
    ("null hypothesis", "فرضية صفرية"),
    ("alternative hypothesis", "فرضية بديلة"),
    ("linear independence", "استقلال خطي"),
    ("vector space", "فضاء متجهي"),
    ("orthonormal basis", "أساس متعامد ممنظم"),
    ("linear span", "امتداد خطي"),
    ("characteristic equation", "معادلة مميزة"),
    ("general solution", "حل عام"),
    ("particular solution", "حل خاص"),
    ("homogeneous equation", "معادلة متجانسة"),
    ("partial fractions", "كسور جزئية"),
    ("lhopital rule", "قاعدة لوبيتال"),
    ("jacobian matrix", "مصفوفة يعقوبية"),
    ("hessian matrix", "مصفوفة هسية"),
    ("directional derivative", "مشتقة اتجاهية"),
    ("line of best fit", "خط أفضل ملاءمة"),
    ("coefficient of determination", "معامل التحديد"),
    ("correlation coefficient", "معامل الارتباط"),
    ("skewness", "معامل الالتواء"),
    ("kurtosis", "تفرطح"),
    ("interquartile range", "مدى ربيعي"),
    ("box plot", "مخطط صندوقي"),
    ("scatter plot", "مخطط انتشار"),
    ("frequency distribution", "توزيع تكراري"),
    ("uniform distribution", "توزيع منتظم"),
    ("exponential distribution", "توزيع أسي"),
    ("normal probability plot", "مخطط الاحتمال الطبيعي"),
    # ── فيزياء حديثة وبصريات ──
    ("schrodinger equation", "معادلة شرودنغر"),
    ("photoelectric effect", "التأثير الكهروضوئي"),
    ("compton effect", "تأثير كومبتون"),
    ("blackbody radiation", "إشعاع الجسم الأسود"),
    ("planck constant", "ثابت بلانك"),
    ("de broglie wavelength", "طول موجة دي برولي"),
    ("bohr model", "نموذج بور"),
    ("energy level", "مستوى طاقة"),
    ("ground state", "حالة أرضية"),
    ("excited state", "حالة مثارة"),
    ("atomic nucleus", "نواة الذرة"),
    ("binding energy", "طاقة الربط"),
    ("mass defect", "نقص الكتلة"),
    ("nuclear fission", "انشطار نووي"),
    ("nuclear fusion", "اندماج نووي"),
    ("chain reaction", "تفاعل متسلسل"),
    ("radioactive half life", "عمر نصفي إشعاعي"),
    ("band gap", "فجوة النطاق"),
    ("valence band", "نطاق التكافؤ"),
    ("conduction band", "نطاق التوصيل"),
    ("pn junction", "وصلة موجب-سالب"),
    ("special relativity", "نسبية خاصة"),
    ("time dilation", "تمدد الزمن"),
    ("length contraction", "انكماش الطول"),
    ("mass energy equivalence", "تكافؤ الكتلة والطاقة"),
    ("angular momentum", "زخم زاوي"),
    ("moment of inertia", "عزم القصور الذاتي"),
    ("conservation of angular momentum", "حفظ الزخم الزاوي"),
    ("work energy theorem", "مبرهنة الشغل والطاقة"),
    ("electric potential", "جهد كهربائي"),
    ("electric potential difference", "فرق الجهد الكهربائي"),
    ("electrical resistivity", "مقاومة نوعية"),
    ("electrical conductivity", "موصلية كهربائية"),
    ("total internal reflection", "انعكاس كلي داخلي"),
    ("convex lens", "عدسة محدبة"),
    ("concave lens", "عدسة مقعرة"),
    ("focal point", "بؤرة"),
    ("young double slit experiment", "تجربة شقي يونغ"),
    ("constructive interference", "تداخل بناء"),
    ("destructive interference", "تداخل هدام"),
    ("index of refraction", "معامل الانكسار"),
    ("snell law", "قانون سنيل"),
    ("coulomb law", "قانون كولوم"),
    ("gauss law", "قانون غاوس"),
    ("faraday law", "قانون فاراداي"),
    ("lenz law", "قانون لنز"),
    ("ampere law", "قانون أمبير"),
    # ── كيمياء عضوية وتحليلية وحيوية ──
    ("physical chemistry", "كيمياء فيزيائية"),
    ("analytical chemistry", "كيمياء تحليلية"),
    ("aromatic compound", "مركب أروماتي"),
    ("structural isomer", "متماكب بنائي"),
    ("stereoisomer", "متماكب فراغي"),
    ("enantiomer", "مصاوغ مرآتي"),
    ("chirality", "لا تناظر مرآتي"),
    ("orbital hybridization", "تهجين المدارات"),
    ("sigma bond", "رابطة سيغما"),
    ("pi bond", "رابطة باي"),
    ("van der waals forces", "قوى فان دير فالس"),
    ("electronegativity", "كهرسلبية"),
    ("oxidation number", "عدد التأكسد"),
    ("redox reaction", "تفاعل أكسدة واختزال"),
    ("oxidizing agent", "عامل مؤكسد"),
    ("reducing agent", "عامل مختزل"),
    ("buffer solution", "محلول منظم"),
    ("equivalence point", "نقطة التكافؤ"),
    ("titration end point", "نقطة نهاية المعايرة"),
    ("standard solution", "محلول قياسي"),
    ("empirical formula", "صيغة أولية"),
    ("molecular formula", "صيغة جزيئية"),
    ("ideal gas law", "قانون الغاز المثالي"),
    ("dalton law", "قانون دالتون"),
    ("boyle law", "قانون بويل"),
    ("charles law", "قانون شارل"),
    ("activation complex", "معقد منشط"),
    ("chemical equilibrium", "اتزان كيميائي"),
    ("le chatelier principle", "مبدأ لو شاتيليه"),
    ("amino acid", "حمض أميني"),
    ("peptide bond", "رابطة ببتيدية"),
    ("nucleic acid", "حمض نووي"),
    ("nucleotide", "نوكليوتيد"),
    ("codon", "رامزة"),
    ("anticodon", "رامزة مضادة"),
    ("gluconeogenesis", "استحداث الجلوكوز"),
    ("oxidative phosphorylation", "فسفرة تأكسدية"),
    ("krebs cycle", "دورة كربس"),
    ("electron transport chain", "سلسلة نقل الإلكترون"),
    ("enzyme active site", "موقع فعال"),
    ("enzyme inhibitor", "مثبط إنزيمي"),
    ("allosteric site", "موقع تفارغي"),
    ("high performance liquid chromatography", "استشراب سائل عالي الأداء"),
    ("nuclear magnetic resonance", "رنين مغناطيسي نووي"),
    ("infrared spectroscopy", "مطيافية تحت الحمراء"),
    ("mass spectrometry", "مطيافية الكتلة"),
    ("beer lambert law", "قانون بير-لامبرت"),
    ("calibration curve", "منحنى معايرة"),
    # ── أحياء ووراثة ومناعة ──
    ("central dogma", "العقيدة المركزية"),
    ("protein translation", "ترجمة البروتين"),
    ("dna transcription", "نسخ الحمض النووي"),
    ("messenger rna", "حمض نووي ريبوزي رسول"),
    ("transfer rna", "حمض نووي ريبوزي ناقل"),
    ("homozygous", "متماثل اللواقح"),
    ("heterozygous", "متخالف اللواقح"),
    ("dominant allele", "أليل سائد"),
    ("recessive allele", "أليل متنحي"),
    ("punnett square", "مربع بونت"),
    ("natural selection", "انتخاب طبيعي"),
    ("speciation", "انتواع"),
    ("food chain", "سلسلة غذائية"),
    ("food web", "شبكة غذائية"),
    ("trophic level", "مستوى غذائي"),
    ("carrying capacity", "سعة التحمل"),
    ("ecosystem", "نظام بيئي"),
    ("biodiversity", "تنوع حيوي"),
    ("carbon cycle", "دورة الكربون"),
    ("nitrogen cycle", "دورة النتروجين"),
    ("active transport", "نقل نشط"),
    ("passive transport", "نقل سلبي"),
    ("facilitated diffusion", "انتشار ميسر"),
    ("endoplasmic reticulum", "شبكة إندوبلازمية"),
    ("golgi apparatus", "جهاز غولجي"),
    ("cell membrane", "غشاء خلوي"),
    ("chloroplast", "بلاستيدة خضراء"),
    ("gram positive", "موجب الغرام"),
    ("gram negative", "سالب الغرام"),
    ("gram stain", "صبغة غرام"),
    ("pathogenic organism", "كائن ممرض"),
    ("incubation period", "فترة الحضانة"),
    ("disease vector", "ناقل المرض"),
    ("antibiotic resistance", "مقاومة المضادات الحيوية"),
    ("innate immunity", "مناعة فطرية"),
    ("adaptive immunity", "مناعة مكتسبة"),
    ("antigen presenting cell", "خلية عارضة للمستضد"),
    ("inflammatory response", "استجابة التهابية"),
    ("autoimmune response", "استجابة مناعية ذاتية"),
    # ── طب وصيدلة وطب أسنان وتمريض ──
    ("cardiovascular system", "جهاز قلبي وعائي"),
    ("respiratory system", "جهاز تنفسي"),
    ("digestive system", "جهاز هضمي"),
    ("endocrine system", "جهاز غدي صم"),
    ("urinary system", "جهاز بولي"),
    ("reproductive system", "جهاز تناسلي"),
    ("musculoskeletal system", "جهاز عضلي هيكلي"),
    ("lymphatic system", "جهاز لمفي"),
    ("autonomic nervous system", "جهاز عصبي ذاتي"),
    ("sympathetic nervous system", "جهاز عصبي ودي"),
    ("parasympathetic nervous system", "جهاز عصبي لاودي"),
    ("medulla oblongata", "النخاع المستطيل"),
    ("pituitary gland", "الغدة النخامية"),
    ("thyroid gland", "الغدة الدرقية"),
    ("adrenal gland", "الغدة الكظرية"),
    ("coronary artery", "شريان تاجي"),
    ("pulmonary artery", "شريان رئوي"),
    ("pulmonary vein", "وريد رئوي"),
    ("sinoatrial node", "عقدة جيبية أذينية"),
    ("atrioventricular node", "عقدة أذينية بطينية"),
    ("cardiac cycle", "دورة قلبية"),
    ("stroke volume", "حجم الضربة"),
    ("cardiac output", "نتاج القلب"),
    ("blood pressure", "ضغط الدم"),
    ("systolic pressure", "ضغط انقباضي"),
    ("diastolic pressure", "ضغط انبساطي"),
    ("myocardial ischemia", "إقفار عضلة القلب"),
    ("heart failure", "قصور القلب"),
    ("atrial fibrillation", "رجفان أذيني"),
    ("deep vein thrombosis", "خثار وريدي عميق"),
    ("pulmonary embolism", "انصمام رئوي"),
    ("chronic obstructive pulmonary disease", "داء رئوي مزمن مسد"),
    ("acute respiratory distress", "ضائقة تنفسية حادة"),
    ("glomerular filtration rate", "معدل الرشح الكبيبي"),
    ("renal failure", "قصور كلوي"),
    ("diabetes mellitus", "داء السكري"),
    ("diabetes insipidus", "داء السكري الكاذب"),
    ("hyperthyroidism", "فرط نشاط الدرقية"),
    ("hypothyroidism", "قصور الدرقية"),
    ("peptic ulcer", "قرحة هضمية"),
    ("inflammatory bowel disease", "داء الأمعاء الالتهابي"),
    ("cerebrovascular accident", "حادثة وعائية دماغية"),
    ("complete blood count", "تعداد دم كامل"),
    ("white blood cell", "كرية دم بيضاء"),
    ("red blood cell", "كرية دم حمراء"),
    ("vital signs", "علامات حيوية"),
    ("oxygen saturation", "تشبع الأكسجين"),
    ("physical examination", "فحص سريري"),
    ("patient history", "السوابق المرضية"),
    ("informed consent", "موافقة مستنيرة"),
    ("randomized controlled trial", "تجربة معشاة ذات شواهد"),
    ("adverse drug reaction", "تفاعل دوائي ضار"),
    ("drug interaction", "تداخل دوائي"),
    ("pharmacokinetics", "حركية الدواء"),
    ("pharmacodynamics", "ديناميكية الدواء"),
    ("bioavailability", "توافر حيوي"),
    ("therapeutic index", "دليل علاجي"),
    ("therapeutic window", "نافذة علاجية"),
    ("first pass effect", "تأثير العبور الأول"),
    ("half life of drug", "عمر نصفي للدواء"),
    ("dosage form", "شكل صيدلاني"),
    ("generic drug", "دواء جنيس"),
    ("excipient", "سواغ"),
    ("shelf life", "مدة الصلاحية"),
    ("drug stability", "ثبات الدواء"),
    ("intravenous infusion", "تسريب وريدي"),
    ("aseptic technique", "تقنية عقيمة"),
    ("wound dressing", "تضميد الجرح"),
    ("pain scale", "مقياس الألم"),
    ("dental caries", "نخر سني"),
    ("periodontal disease", "مرض دواعم السن"),
    ("dental plaque", "لوحة سنية"),
    ("dental calculus", "قلح سني"),
    ("root canal treatment", "معالجة قناة الجذر"),
    ("orthodontics", "تقويم الأسنان"),
    ("endodontics", "مداواة اللب"),
    ("prosthodontics", "تعويضات سنية"),
    ("malocclusion", "سوء الإطباق"),
    ("dental implant", "زرعة سنية"),
    # ── جيولوجيا وبيئة وزراعة وعمارة ──
    ("igneous rock", "صخر ناري"),
    ("sedimentary rock", "صخر رسوبي"),
    ("metamorphic rock", "صخر متحول"),
    ("plate tectonics", "تكتونية الصفائح"),
    ("richter scale", "مقياس ريختر"),
    ("mohs scale", "مقياس موس"),
    ("water table", "منسوب الماء الجوفي"),
    ("confined aquifer", "خزان جوفي محصور"),
    ("unconfined aquifer", "خزان جوفي غير محصور"),
    ("stratigraphy", "علم الطبقات"),
    ("paleontology", "علم الأحافير"),
    ("greenhouse effect", "تأثير الدفيئة"),
    ("global warming", "احترار عالمي"),
    ("ozone layer", "طبقة الأوزون"),
    ("acid rain", "مطر حمضي"),
    ("renewable energy", "طاقة متجددة"),
    ("solar energy", "طاقة شمسية"),
    ("wind energy", "طاقة الرياح"),
    ("sustainable development", "تنمية مستدامة"),
    ("drip irrigation", "ري بالتنقيط"),
    ("sprinkler irrigation", "ري بالرش"),
    ("crop rotation", "دورة زراعية"),
    ("soil fertility", "خصوبة التربة"),
    ("organic matter", "مادة عضوية"),
    ("photosynthesis", "بناء ضوئي"),
    ("transpiration", "نتح"),
    ("germination", "إنبات"),
    ("geographic information system", "نظام معلومات جغرافية"),
    ("global positioning system", "نظام تحديد المواقع"),
    ("building information modeling", "نمذجة معلومات البناء"),
    ("floor plan", "مسقط أفقي"),
    ("site plan", "مخطط الموقع"),
    ("load bearing wall", "جدار حامل"),
    ("curtain wall", "جدار ستائري"),
    ("thermal insulation", "عزل حراري"),
    ("acoustic insulation", "عزل صوتي"),
    ("waterproofing", "عزل مائي"),
    ("building code", "كود البناء"),
    ("floor area ratio", "نسبة مساحة الطوابق"),
    ("natural lighting", "إضاءة طبيعية"),
    ("structural system", "نظام إنشائي"),
    # ── اقتصاد ومحاسبة وإدارة ──
    ("supply and demand", "العرض والطلب"),
    ("opportunity cost", "تكلفة الفرصة البديلة"),
    ("gross domestic product", "الناتج المحلي الإجمالي"),
    ("elasticity of demand", "مرونة الطلب"),
    ("marginal cost", "تكلفة حدية"),
    ("fixed cost", "تكلفة ثابتة"),
    ("variable cost", "تكلفة متغيرة"),
    ("break even point", "نقطة التعادل"),
    ("balance sheet", "قائمة المركز المالي"),
    ("income statement", "قائمة الدخل"),
    ("cash flow statement", "قائمة التدفقات النقدية"),
    ("accounts receivable", "ذمم مدينة"),
    ("accounts payable", "ذمم دائنة"),
    ("trial balance", "ميزان المراجعة"),
    ("double entry", "القيد المزدوج"),
    ("general ledger", "دفتر الأستاذ"),
    ("fiscal year", "سنة مالية"),
    ("depreciation expense", "مصروف الإهلاك"),
    ("working capital", "رأس المال العامل"),
    ("return on investment", "عائد الاستثمار"),
    ("net present value", "صافي القيمة الحالية"),
    ("internal rate of return", "معدل العائد الداخلي"),
    ("payback period", "فترة الاسترداد"),
    ("swot analysis", "تحليل سوات"),
    ("supply chain", "سلسلة الإمداد"),
    ("quality control", "ضبط الجودة"),
    ("quality assurance", "ضمان الجودة"),
    ("total quality management", "إدارة الجودة الشاملة"),
    ("just in time", "الإنتاج في الوقت المحدد"),
    ("project lifecycle", "دورة حياة المشروع"),
    ("critical path method", "طريقة المسار الحرج"),
    ("work breakdown structure", "هيكل تجزئة العمل"),
    ("risk assessment", "تقييم المخاطر"),
    # ── علم نفس وطرائق بحث ──
    ("cognitive behavioral therapy", "علاج معرفي سلوكي"),
    ("classical conditioning", "إشراط كلاسيكي"),
    ("operant conditioning", "إشراط إجرائي"),
    ("short term memory", "ذاكرة قصيرة المدى"),
    ("long term memory", "ذاكرة طويلة المدى"),
    ("working memory", "ذاكرة عاملة"),
    ("independent variable", "متغير مستقل"),
    ("dependent variable", "متغير تابع"),
    ("control group", "مجموعة ضابطة"),
    ("experimental group", "مجموعة تجريبية"),
    ("double blind study", "دراسة مزدوجة التعمية"),
    ("random sampling", "معاينة عشوائية"),
    ("stratified sampling", "معاينة طبقية"),
    ("qualitative research", "بحث نوعي"),
    ("quantitative research", "بحث كمي"),
    ("literature review", "مراجعة أدبيات"),
    ("research methodology", "منهجية البحث"),
    ("case study", "دراسة حالة"),
    ("longitudinal study", "دراسة طولية"),
    ("cross sectional study", "دراسة مقطعية"),
    # مختصرات
    ("sql", "لغة الاستعلامات البنيوية"),
    ("html", "لغة ترميز النص التشعبي"),
    ("css", "أوراق الأنماط المتتالية"),
    ("json", "ترميز كائنات جافاسكربت"),
    ("xml", "لغة الترميز الموسعة"),
    ("http", "بروتوكول نقل النص التشعبي"),
    ("tcp", "بروتوكول التحكم بالنقل"),
    ("udp", "بروتوكول مخطط بيانات المستخدم"),
    ("dns", "نظام أسماء النطاقات"),
    ("dhcp", "بروتوكول التهيئة الديناميكية"),
    ("api", "واجهة برمجية"),
    ("oop", "برمجة كائنية"),
    ("gui", "واجهة رسومية"),
    ("nlp", "معالجة اللغات الطبيعية"),
    ("cnn", "شبكة عصبية تلافيفية"),
    ("rnn", "شبكة عصبية تكرارية"),
    ("lstm", "ذاكرة طويلة قصيرة المدى"),
    ("svm", "آلة المتجهات الداعمة"),
    ("knn", "الجار الأقرب"),
    ("pca", "تحليل المكونات الرئيسية"),
    ("fft", "تحويل فورييه السريع"),
    ("dft", "تحويل فورييه المتقطع"),
    ("hvac", "تدفئة وتهوية وتكييف"),
    ("plc", "متحكم منطقي قابل للبرمجة"),
    ("scada", "نظام التحكم الإشرافي"),
    ("pwm", "تعديل عرض النبضة"),
    ("adc", "محول تماثلي رقمي"),
    ("dac", "محول رقمي تماثلي"),
    ("igbt", "ترانزستور بوابة معزولة"),
    ("mosfet", "ترانزستور تأثير المجال"),
    ("gis", "نظام معلومات جغرافية"),
    ("gps", "نظام تحديد المواقع"),
    ("bim", "نمذجة معلومات البناء"),
    ("hplc", "استشراب سائل عالي الأداء"),
    ("nmr", "رنين مغناطيسي نووي"),
    ("osi", "نموذج الاتصال المفتوح"),
    ("lan", "شبكة محلية"),
    ("wan", "شبكة واسعة"),
    ("vlan", "شبكة محلية افتراضية"),
    ("ssh", "صدفة آمنة"),
    ("ftp", "بروتوكول نقل الملفات"),
    ("bios", "نظام الإدخال والإخراج الأساسي"),
]

EXTRA_ALIASES: list[tuple[str, str]] = [
    ("هندسة المكامن", "reservoir engineering"),
    ("تكسير هيدروليكي", "hydraulic fracturing"),
    ("حقن الماء", "water flooding"),
    ("ضغط قاع البئر", "bottom hole pressure"),
    ("جدار قص", "shear wall"),
    ("إجهاد فعال", "effective stress"),
    ("محرك حثي", "induction motor"),
    ("سريان الأحمال", "load flow"),
    ("حركية الدواء", "pharmacokinetics"),
    ("قاعدة بيانات علائقية", "relational database"),
    ("شبكة عصبية تلافيفية", "convolutional neural network"),
    ("طريقة المسار الحرج", "critical path method"),
    ("نقطة التعادل", "break even point"),
    ("عزم القصور الذاتي", "moment of inertia"),
    ("معادلة شرودنغر", "schrodinger equation"),
]
