"""مصطلحات الطب والتمريض والصيدلة والأسنان والمختبر."""

from __future__ import annotations

MED_ENTRIES: list[tuple[str, str]] = [
    ("frontal bone", "عظم جبهي"),
    ("parietal bone", "عظم جداري"),
    ("temporal bone", "عظم صدغي"),
    ("occipital bone", "عظم قذالي"),
    ("sphenoid bone", "عظم وتدي"),
    ("ethmoid bone", "عظم غربالي"),
    ("zygomatic bone", "عظم وجني"),
    ("nasal bone", "عظم أنفي"),
    ("lacrimal bone", "عظم دمعي"),
    ("palatine bone", "عظم حنكي"),
    ("vomer bone", "عظم الميكعة"),
    ("inferior nasal concha", "القرين الأنفي السفلي"),
    ("mandible bone", "عظم الفك السفلي"),
    ("maxillary bone", "عظم الفك العلوي"),
    ("hyoid bone", "العظم اللامي"),
    ("clavicle bone", "عظم الترقوة"),
    ("scapula bone", "عظم لوح الكتف"),
    ("humerus bone", "عظم العضد"),
    ("radial bone", "عظم الكعبرة"),
    ("ulnar bone", "عظم الزند"),
    ("carpal bones", "عظام الرسغ"),
    ("metacarpal bones", "عظام المشط"),
    ("phalanges of hand", "سلاميات اليد"),
    ("femur bone", "عظم الفخذ"),
    ("patella bone", "عظم الرضفة"),
    ("tibia bone", "عظم الظنبوب"),
    ("fibula bone", "عظم الشظية"),
    ("tarsal bones", "عظام الرصغ"),
    ("metatarsal bones", "عظام مشط القدم"),
    ("calcaneus bone", "عظم العقب"),
    ("talus bone", "عظم القعب"),
    ("navicular bone", "عظم الزورقي"),
    ("cuboid bone", "عظم النردي"),
    ("cuneiform bone", "عظم إسفيني"),
    ("sternum bone", "عظم القص"),
    ("manubrium of sternum", "قبضة القص"),
    ("xiphoid process", "الناتئ الرهابي"),
    ("true rib", "ضلع حقيقي"),
    ("false rib", "ضلع كاذب"),
    ("floating rib", "ضلع سائب"),
    ("costal cartilage", "غضروف ضلعي"),
    ("cervical vertebra", "فقرة رقبية"),
    ("thoracic vertebra", "فقرة صدرية"),
    ("lumbar vertebra", "فقرة قطنية"),
    ("sacral vertebra", "فقرة عجزية"),
    ("intervertebral disc", "قرص بين الفقرات"),
    ("vertebral foramen", "الثقبة الفقرية"),
    ("spinous process", "ناتئ شوكي"),
    ("transverse process", "ناتئ مستعرض"),
    ("atlas vertebra", "الفقهة"),
    ("axis vertebra", "المحور"),
    ("sacrum bone", "عظم العجز"),
    ("coccyx bone", "عظم العصعص"),
    ("ilium bone", "عظم الحرقفة"),
    ("ischium bone", "عظم الإسك"),
    ("pubis bone", "عظم العانة"),
    ("acetabulum cavity", "جوف الحق"),
    ("obturator foramen", "الثقبة السدادية"),
    ("pelvic inlet", "مدخل الحوض"),
    ("pelvic outlet", "مخرج الحوض"),
    ("auditory ossicles", "عظيمات السمع"),
    ("malleus bone", "عظيم المطرقة"),
    ("incus bone", "عظيم السندان"),
    ("stapes bone", "عظيم الركاب"),
    ("biceps brachii", "العضلة ذات الرأسين العضدية"),
    ("triceps brachii", "العضلة ثلاثية الرؤوس العضدية"),
    ("deltoid muscle", "العضلة الدالية"),
    ("pectoralis major", "العضلة الصدرية الكبيرة"),
    ("pectoralis minor", "العضلة الصدرية الصغيرة"),
    ("latissimus dorsi", "العضلة الظهرية العريضة"),
    ("trapezius muscle", "العضلة شبه المنحرفة"),
    ("rectus abdominis", "العضلة المستقيمة البطنية"),
    ("external oblique muscle", "العضلة المائلة الظاهرة"),
    ("internal oblique muscle", "العضلة المائلة الباطنة"),
    ("transversus abdominis", "العضلة المستعرضة البطنية"),
    ("quadriceps femoris", "العضلة رباعية الرؤوس الفخذية"),
    ("hamstring muscles", "عضلات المأبض"),
    ("gastrocnemius muscle", "عضلة الساق التوأمية"),
    ("soleus muscle", "العضلة النعلية"),
    ("tibialis anterior", "العضلة الظنبوبية الأمامية"),
    ("gluteus maximus", "العضلة الألوية الكبرى"),
    ("gluteus medius", "العضلة الألوية الوسطى"),
    ("gluteus minimus", "العضلة الألوية الصغرى"),
    ("sartorius muscle", "العضلة الخياطية"),
    ("sternocleidomastoid muscle", "العضلة القصية الترقوية الخشائية"),
    ("masseter muscle", "العضلة الماضغة"),
    ("temporalis muscle", "العضلة الصدغية"),
    ("orbicularis oculi", "العضلة الدويرية العينية"),
    ("orbicularis oris", "العضلة الدويرية الفموية"),
    ("intercostal muscles", "العضلات الوربية"),
    ("erector spinae", "العضلة الناصبة للفقار"),
    ("rotator cuff", "الكفة المدورة"),
    ("supraspinatus muscle", "العضلة فوق الشوك"),
    ("infraspinatus muscle", "العضلة تحت الشوك"),
    ("subscapularis muscle", "العضلة تحت الكتف"),
    ("teres minor muscle", "العضلة المدورة الصغيرة"),
    ("teres major muscle", "العضلة المدورة الكبيرة"),
    ("brachialis muscle", "العضلة العضدية"),
    ("brachioradialis muscle", "العضلة العضدية الكعبرية"),
    ("iliopsoas muscle", "العضلة الحرقفية القطنية"),
    ("adductor longus", "العضلة المقربة الطويلة"),
    ("adductor magnus", "العضلة المقربة الكبيرة"),
    ("gracilis muscle", "العضلة الرشيقة"),
    ("piriformis muscle", "العضلة الكمثرية"),
    ("diaphragm muscle", "عضلة الحجاب الحاجز"),
    ("olfactory nerve", "العصب الشمي"),
    ("optic nerve", "العصب البصري"),
    ("oculomotor nerve", "العصب المحرك للعين"),
    ("trochlear nerve", "العصب البكري"),
    ("trigeminal nerve", "العصب ثلاثي التوائم"),
    ("abducens nerve", "العصب المبعد"),
    ("facial nerve", "العصب الوجهي"),
    ("vestibulocochlear nerve", "العصب الدهليزي القوقعي"),
    ("glossopharyngeal nerve", "العصب اللساني البلعومي"),
    ("vagus nerve", "العصب المبهم"),
    ("accessory nerve", "العصب الإضافي"),
    ("hypoglossal nerve", "العصب تحت اللسان"),
    ("phrenic nerve", "العصب الحجابي"),
    ("sciatic nerve", "العصب الوركي"),
    ("femoral nerve", "العصب الفخذي"),
    ("median nerve", "العصب الناصف"),
    ("ulnar nerve", "العصب الزندي"),
    ("radial nerve", "العصب الكعبري"),
    ("axillary nerve", "العصب الإبطي"),
    ("tibial nerve", "العصب الظنبوبي"),
    ("common peroneal nerve", "العصب الشظوي الأصلي"),
    ("brachial plexus", "الضفيرة العضدية"),
    ("cervical plexus", "الضفيرة الرقبية"),
    ("lumbar plexus", "الضفيرة القطنية"),
    ("sacral plexus", "الضفيرة العجزية"),
    ("spinal nerve root", "جذر العصب الشوكي"),
    ("dorsal nerve root", "الجذر الظهري"),
    ("ventral nerve root", "الجذر البطني"),
    ("sympathetic trunk", "الجذع الودي"),
    ("mitral valve", "الصمام التاجي"),
    ("tricuspid valve", "الصمام ثلاثي الشرف"),
    ("aortic valve", "الصمام الأبهري"),
    ("pulmonary valve", "الصمام الرئوي"),
    ("chordae tendineae", "الحبال الوترية"),
    ("papillary muscle", "عضلة حليمية"),
    ("interventricular septum", "الحاجز بين البطينين"),
    ("interatrial septum", "الحاجز بين الأذينين"),
    ("coronary sinus", "الجيب التاجي"),
    ("superior vena cava", "الوريد الأجوف العلوي"),
    ("inferior vena cava", "الوريد الأجوف السفلي"),
    ("hepatic portal vein", "الوريد البابي الكبدي"),
    ("hepatic artery", "الشريان الكبدي"),
    ("renal artery", "الشريان الكلوي"),
    ("renal vein", "الوريد الكلوي"),
    ("carotid artery", "الشريان السباتي"),
    ("subclavian artery", "الشريان تحت الترقوة"),
    ("brachial artery", "الشريان العضدي"),
    ("femoral artery", "الشريان الفخذي"),
    ("popliteal artery", "الشريان المأبضي"),
    ("circle of willis", "دائرة ويليس"),
    ("blood brain barrier", "الحاجز الدموي الدماغي"),
    ("thoracic duct", "القناة الصدرية"),
    ("lymph node", "عقدة لمفية"),
    ("thymus gland", "الغدة الزعترية"),
    ("palatine tonsil", "اللوزة الحنكية"),
    ("nasal cavity", "جوف الأنف"),
    ("oral cavity", "جوف الفم"),
    ("nasopharynx region", "البلعوم الأنفي"),
    ("oropharynx region", "البلعوم الفموي"),
    ("laryngopharynx region", "البلعوم الحنجري"),
    ("larynx structure", "الحنجرة"),
    ("epiglottis cartilage", "لسان المزمار"),
    ("vocal cord", "حبل صوتي"),
    ("bronchial tree", "الشجرة القصبية"),
    ("respiratory bronchiole", "قصيبة تنفسية"),
    ("alveolar sac", "كيس سنخي"),
    ("pleural cavity", "جوف الجنب"),
    ("visceral pleura", "الجنبة الحشوية"),
    ("parietal pleura", "الجنبة الجدارية"),
    ("pulmonary surfactant", "عامل فاعل بالسطح الرئوي"),
    ("tidal volume", "الحجم المدي"),
    ("vital capacity", "السعة الحيوية"),
    ("residual volume", "الحجم المتبقي"),
    ("total lung capacity", "السعة الرئوية الكلية"),
    ("inspiratory reserve volume", "حجم الاحتياط الشهيقي"),
    ("expiratory reserve volume", "حجم الاحتياط الزفيري"),
    ("anatomical dead space", "الحيز الميت التشريحي"),
    ("partial pressure of oxygen", "الضغط الجزئي للأكسجين"),
    ("partial pressure of carbon dioxide", "الضغط الجزئي لثاني أكسيد الكربون"),
    ("oxyhemoglobin dissociation curve", "منحنى تفارق الخضاب المؤكسج"),
    ("respiratory acidosis", "حماض تنفسي"),
    ("respiratory alkalosis", "قلاء تنفسي"),
    ("metabolic acidosis", "حماض استقلابي"),
    ("metabolic alkalosis", "قلاء استقلابي"),
    ("parotid gland", "الغدة النكفية"),
    ("submandibular gland", "الغدة تحت الفك"),
    ("sublingual gland", "الغدة تحت اللسان"),
    ("lower esophageal sphincter", "المصرة المريئية السفلية"),
    ("pyloric sphincter", "المصرة البوابية"),
    ("gastric mucosa", "مخاطية المعدة"),
    ("jejunum intestine", "الصائم"),
    ("ileum intestine", "اللفائفي"),
    ("cecum intestine", "الأعور"),
    ("ascending colon", "القولون الصاعد"),
    ("transverse colon", "القولون المستعرض"),
    ("descending colon", "القولون النازل"),
    ("sigmoid colon", "القولون السيني"),
    ("rectum intestine", "المستقيم"),
    ("anal canal", "القناة الشرجية"),
    ("liver lobule", "فصيص كبدي"),
    ("common bile duct", "القناة الصفراوية المشتركة"),
    ("cystic duct", "القناة المرارية"),
    ("hepatic duct", "القناة الكبدية"),
    ("pancreatic duct", "القناة البنكرياسية"),
    ("peristaltic movement", "حركة دودية"),
    ("salivary amylase", "أميلاز لعابي"),
    ("pancreatic lipase", "ليباز بنكرياسي"),
    ("pepsin enzyme", "إنزيم الببسين"),
    ("trypsin enzyme", "إنزيم التربسين"),
    ("bile salts", "أملاح صفراوية"),
    ("intestinal villi", "زغابات معوية"),
    ("microvilli brush border", "حافة فرشاتية من الزغيبات"),
    ("renal cortex", "قشرة الكلية"),
    ("renal medulla", "لب الكلية"),
    ("renal pelvis", "حويضة الكلية"),
    ("bowman capsule", "محفظة بومان"),
    ("proximal convoluted tubule", "النبيب الملفوف الداني"),
    ("loop of henle", "عروة هنلي"),
    ("distal convoluted tubule", "النبيب الملفوف القاصي"),
    ("collecting duct", "القناة الجامعة"),
    ("glomerular filtration", "الرشح الكبيبي"),
    ("tubular reabsorption", "إعادة الامتصاص النبيبي"),
    ("tubular secretion", "الإفراز النبيبي"),
    ("antidiuretic hormone", "الهرمون المضاد للإدرار"),
    ("renin angiotensin system", "جملة الرينين والأنجيوتنسين"),
    ("erythropoietin hormone", "هرمون الإريثروبويتين"),
    ("urinary bladder", "المثانة البولية"),
    ("urethra canal", "الإحليل"),
    ("hypothalamus gland", "تحت المهاد"),
    ("anterior pituitary", "النخامية الأمامية"),
    ("posterior pituitary", "النخامية الخلفية"),
    ("growth hormone", "هرمون النمو"),
    ("thyroid stimulating hormone", "الهرمون المنبه للدرقية"),
    ("adrenocorticotropic hormone", "الهرمون الموجه لقشر الكظر"),
    ("follicle stimulating hormone", "الهرمون المنبه للجريب"),
    ("luteinizing hormone", "الهرمون الملوتن"),
    ("prolactin hormone", "هرمون البرولاكتين"),
    ("oxytocin hormone", "هرمون الأوكسيتوسين"),
    ("thyroxine hormone", "هرمون الثيروكسين"),
    ("triiodothyronine hormone", "هرمون ثلاثي يودوثيرونين"),
    ("calcitonin hormone", "هرمون الكالسيتونين"),
    ("parathyroid hormone", "هرمون جارة الدرقية"),
    ("cortisol hormone", "هرمون الكورتيزول"),
    ("adrenaline hormone", "هرمون الأدرينالين"),
    ("noradrenaline hormone", "هرمون النورأدرينالين"),
    ("glucagon hormone", "هرمون الغلوكاغون"),
    ("estrogen hormone", "هرمون الإستروجين"),
    ("progesterone hormone", "هرمون البروجسترون"),
    ("testosterone hormone", "هرمون التستوستيرون"),
    ("melatonin hormone", "هرمون الميلاتونين"),
    ("negative feedback loop", "حلقة تغذية راجعة سلبية"),
    ("positive feedback loop", "حلقة تغذية راجعة إيجابية"),
    ("second messenger", "مرسال ثان"),
    ("target cell receptor", "مستقبل الخلية الهدف"),
    ("testis gland", "الخصية"),
    ("epididymis duct", "البربخ"),
    ("vas deferens", "الأسهر"),
    ("seminal vesicle", "الحويصل المنوي"),
    ("prostate gland", "غدة البروستات"),
    ("bulbourethral gland", "غدة كوبر"),
    ("endometrium layer", "بطانة الرحم"),
    ("myometrium layer", "عضلة الرحم"),
    ("perimetrium layer", "محيط الرحم"),
    ("fallopian tube", "قناة فالوب"),
    ("uterine cervix", "عنق الرحم"),
    ("vaginal canal", "المهبل"),
    ("umbilical cord", "الحبل السري"),
    ("amniotic fluid", "السائل الأمنيوسي"),
    ("fertilization process", "عملية الإخصاب"),
    ("implantation process", "عملية الانغراس"),
    ("gestation period", "مدة الحمل"),
    ("parturition process", "عملية الولادة"),
    ("lactation process", "عملية الإدرار"),
    ("menstrual cycle", "الدورة الشهرية"),
    ("ovulation process", "عملية الإباضة"),
    ("spermatogenesis process", "تكوين النطاف"),
    ("oogenesis process", "تكوين البويضات"),
    ("zygote cell", "اللاقحة"),
    ("blastocyst stage", "مرحلة الأرومة"),
    ("male gamete", "عروس ذكري"),
    ("female gamete", "عروس أنثوي"),
    ("acute myocardial infarction", "احتشاء عضلة القلب الحاد"),
    ("unstable angina", "ذبحة غير مستقرة"),
    ("stable angina", "ذبحة مستقرة"),
    ("heart murmur", "نفخة قلبية"),
    ("congestive heart failure", "قصور قلب احتقاني"),
    ("left ventricular failure", "قصور البطين الأيسر"),
    ("right ventricular failure", "قصور البطين الأيمن"),
    ("atrial flutter", "رفرفة أذينية"),
    ("ventricular fibrillation", "رجفان بطيني"),
    ("ventricular tachycardia", "تسرع بطيني"),
    ("sinus bradycardia", "بطء جيبي"),
    ("sinus tachycardia", "تسرع جيبي"),
    ("first degree heart block", "إحصار قلبي من الدرجة الأولى"),
    ("second degree heart block", "إحصار قلبي من الدرجة الثانية"),
    ("complete heart block", "إحصار قلبي تام"),
    ("pericardial effusion", "انصباب تأموري"),
    ("cardiac tamponade", "اندحاس قلبي"),
    ("infective endocarditis", "التهاب الشغاف العدوائي"),
    ("rheumatic heart disease", "داء القلب الرثوي"),
    ("mitral stenosis", "تضيق تاجي"),
    ("mitral regurgitation", "قلس تاجي"),
    ("aortic stenosis", "تضيق أبهري"),
    ("aortic regurgitation", "قلس أبهري"),
    ("hypertension urgency", "ارتفاع ضغط إسعافي"),
    ("hypertensive emergency", "طوارئ ارتفاع الضغط"),
    ("orthostatic hypotension", "هبوط الضغط الانتصابي"),
    ("peripheral artery disease", "داء الشرايين المحيطية"),
    ("varicose veins", "دوالي وريدية"),
    ("deep venous thrombosis", "خثار وريدي عميق"),
    ("pulmonary thromboembolism", "انصمام خثاري رئوي"),
    ("bronchial asthma", "ربو قصبي"),
    ("status asthmaticus", "حالة ربوية متواصلة"),
    ("community acquired pneumonia", "ذات رئة مكتسبة في المجتمع"),
    ("hospital acquired pneumonia", "ذات رئة مكتسبة في المستشفى"),
    ("pleural effusion", "انصباب جنبي"),
    ("pneumothorax condition", "استرواح الصدر"),
    ("tension pneumothorax", "استرواح صدر ضغطي"),
    ("pulmonary edema", "وذمة رئوية"),
    ("acute respiratory distress syndrome", "متلازمة الضائقة التنفسية الحادة"),
    ("chronic bronchitis", "التهاب قصبات مزمن"),
    ("pulmonary emphysema", "نفاخ رئوي"),
    ("bronchiectasis disease", "توسع القصبات"),
    ("lung abscess", "خراج الرئة"),
    ("pulmonary tuberculosis", "سل رئوي"),
    ("pleurisy inflammation", "التهاب الجنب"),
    ("acute kidney injury", "إصابة كلوية حادة"),
    ("chronic kidney disease", "داء كلوي مزمن"),
    ("nephrotic syndrome", "متلازمة كلوية"),
    ("nephritic syndrome", "متلازمة التهابية كلوية"),
    ("acute glomerulonephritis", "التهاب كبيبات حاد"),
    ("polycystic kidney disease", "داء الكلية متعددة الكيسات"),
    ("renal calculi", "حصيات كلوية"),
    ("urinary tract infection", "عدوى المسالك البولية"),
    ("benign prostatic hyperplasia", "فرط تنسج بروستات حميد"),
    ("prostate cancer", "سرطان البروستات"),
    ("bladder cancer", "سرطان المثانة"),
    ("acute liver failure", "قصور كبد حاد"),
    ("chronic liver disease", "داء كبد مزمن"),
    ("liver cirrhosis", "تشمع الكبد"),
    ("portal hypertension", "فرط ضغط الباب"),
    ("esophageal varices", "دوالي مريئية"),
    ("ascites fluid", "حبن"),
    ("hepatic encephalopathy", "اعتلال دماغي كبدي"),
    ("viral hepatitis", "التهاب كبد فيروسي"),
    ("hepatitis a infection", "عدوى التهاب الكبد أ"),
    ("hepatitis b infection", "عدوى التهاب الكبد ب"),
    ("hepatitis c infection", "عدوى التهاب الكبد ج"),
    ("cholelithiasis disease", "تحص صفراوي"),
    ("cholecystitis inflammation", "التهاب المرارة"),
    ("acute pancreatitis", "التهاب بنكرياس حاد"),
    ("chronic pancreatitis", "التهاب بنكرياس مزمن"),
    ("peptic ulcer disease", "داء القرحة الهضمية"),
    ("gastric ulcer", "قرحة معدية"),
    ("duodenal ulcer", "قرحة عفجية"),
    ("gastroesophageal reflux", "جزر معدي مريئي"),
    ("irritable bowel syndrome", "متلازمة الأمعاء الهيوجة"),
    ("ulcerative colitis", "التهاب القولون التقرحي"),
    ("crohn disease", "داء كرون"),
    ("acute appendicitis", "التهاب الزائدة الحاد"),
    ("intestinal obstruction", "انسداد معوي"),
    ("type one diabetes", "السكري من النمط الأول"),
    ("type two diabetes", "السكري من النمط الثاني"),
    ("diabetic ketoacidosis", "الحماض الكيتوني السكري"),
    ("hyperosmolar hyperglycemic state", "حالة فرط الأسمولية وفرط السكر"),
    ("hypoglycemic episode", "نوبة نقص سكر"),
    ("diabetic nephropathy", "اعتلال كلية سكري"),
    ("diabetic retinopathy", "اعتلال شبكية سكري"),
    ("diabetic neuropathy", "اعتلال أعصاب سكري"),
    ("graves disease", "داء غريفز"),
    ("hashimoto thyroiditis", "التهاب الدرقية لهاشيموتو"),
    ("thyroid nodule", "عقيدة درقية"),
    ("goiter enlargement", "ضخامة درقية"),
    ("cushing syndrome", "متلازمة كوشينغ"),
    ("addison disease", "داء أديسون"),
    ("hyperparathyroidism disease", "فرط جارات الدرق"),
    ("hypoparathyroidism disease", "قصور جارات الدرق"),
    ("ischemic stroke", "سكتة إقفارية"),
    ("hemorrhagic stroke", "سكتة نزفية"),
    ("transient ischemic attack", "نوبة إقفارية عابرة"),
    ("subarachnoid hemorrhage", "نزف تحت العنكبوتية"),
    ("subdural hematoma", "ورم دموي تحت الجافية"),
    ("epidural hematoma", "ورم دموي فوق الجافية"),
    ("bacterial meningitis", "التهاب سحايا جرثومي"),
    ("viral meningitis", "التهاب سحايا فيروسي"),
    ("epileptic seizure", "نوبة صرعية"),
    ("status epilepticus", "حالة صرعية"),
    ("parkinson disease", "داء باركنسون"),
    ("alzheimer disease", "داء ألزهايمر"),
    ("multiple sclerosis", "التصلب المتعدد"),
    ("myasthenia gravis", "الوهن العضلي الوبيل"),
    ("guillain barre syndrome", "متلازمة غيلان باريه"),
    ("migraine headache", "صداع شقيقي"),
    ("tension headache", "صداع توتري"),
    ("bell palsy", "شلل بل"),
    ("trigeminal neuralgia", "ألم العصب ثلاثي التوائم"),
    ("osteoarthritis disease", "الفصال العظمي"),
    ("rheumatoid arthritis", "التهاب المفاصل الرثياني"),
    ("gouty arthritis", "التهاب المفاصل النقرسي"),
    ("osteomyelitis infection", "التهاب العظم والنقي"),
    ("osteoporosis disease", "هشاشة العظام"),
    ("bone fracture", "كسر عظمي"),
    ("open fracture", "كسر مفتوح"),
    ("closed fracture", "كسر مغلق"),
    ("pathological fracture", "كسر مرضي"),
    ("greenstick fracture", "كسر غصن نضر"),
    ("comminuted fracture", "كسر مفتت"),
    ("displaced fracture", "كسر منزاح"),
    ("fracture reduction", "رد الكسر"),
    ("fracture fixation", "تثبيت الكسر"),
    ("compartment syndrome", "متلازمة الحيز"),
    ("iron deficiency anemia", "فقر دم بعوز الحديد"),
    ("megaloblastic anemia", "فقر دم ضخم الأرومات"),
    ("sickle cell disease", "داء الخلية المنجلية"),
    ("thalassemia disorder", "الثلاسيميا"),
    ("aplastic anemia", "فقر دم لاتنسجي"),
    ("hemolytic anemia", "فقر دم انحلالي"),
    ("thrombocytopenia disorder", "قلة الصفيحات"),
    ("disseminated intravascular coagulation", "تخثر منتشر داخل الأوعية"),
    ("hemophilia disorder", "الناعور"),
    ("leukemia disease", "ابيضاض الدم"),
    ("lymphoma disease", "لمفوما"),
    ("hodgkin lymphoma", "لمفوما هودجكين"),
    ("non hodgkin lymphoma", "لمفوما لاهودجكينية"),
    ("septic shock", "صدمة إنتانية"),
    ("hypovolemic shock", "صدمة نقص الحجم"),
    ("cardiogenic shock", "صدمة قلبية المنشأ"),
    ("anaphylactic shock", "صدمة تأقية"),
    ("systemic inflammatory response", "استجابة التهابية جهازية"),
    ("wound healing", "التئام الجرح"),
    ("primary intention healing", "التئام بالقصد الأول"),
    ("secondary intention healing", "التئام بالقصد الثاني"),
    ("pressure ulcer", "قرحة الضغط"),
    ("burn injury", "إصابة حرق"),
    ("first degree burn", "حرق من الدرجة الأولى"),
    ("second degree burn", "حرق من الدرجة الثانية"),
    ("third degree burn", "حرق من الدرجة الثالثة"),
    ("rule of nines", "قاعدة التسعات"),
    ("fluid resuscitation", "إنعاش بالسوائل"),
    ("blood transfusion", "نقل الدم"),
    ("cross matching", "اختبار التوافق"),
    ("blood group typing", "زمرة الدم"),
    ("universal donor", "معطي عام"),
    ("universal recipient", "آخذ عام"),
    ("complete blood count test", "اختبار تعداد الدم الكامل"),
    ("erythrocyte sedimentation rate", "سرعة تثفل الكريات"),
    ("c reactive protein", "بروتين سي الارتكاسي"),
    ("liver function tests", "اختبارات وظائف الكبد"),
    ("renal function tests", "اختبارات وظائف الكلية"),
    ("fasting blood glucose", "سكر الدم الصيامي"),
    ("oral glucose tolerance test", "اختبار تحمل الغلوكوز الفموي"),
    ("glycated hemoglobin", "خضاب سكري"),
    ("lipid profile", "مرتسم الشحوم"),
    ("ldl cholesterol", "كوليسترول منخفض الكثافة"),
    ("hdl cholesterol", "كوليسترول مرتفع الكثافة"),
    ("serum creatinine", "كرياتينين المصل"),
    ("blood urea nitrogen", "نتروجين يوريا الدم"),
    ("alanine aminotransferase", "ناقلة أمين الألانين"),
    ("aspartate aminotransferase", "ناقلة أمين الأسبارتات"),
    ("alkaline phosphatase", "الفوسفاتاز القلوية"),
    ("serum bilirubin", "بيليروبين المصل"),
    ("prothrombin time", "زمن البروثرومبين"),
    ("partial thromboplastin time", "زمن الثرومبوبلاستين الجزئي"),
    ("international normalized ratio", "النسبة المعيارية الدولية"),
    ("arterial blood gas", "غازات الدم الشرياني"),
    ("urinalysis test", "تحليل البول"),
    ("urine culture", "زرع البول"),
    ("blood culture", "زرع الدم"),
    ("sputum culture", "زرع القشع"),
    ("gram staining", "تلوين غرام"),
    ("acid fast stain", "تلوين صامد للحمض"),
    ("sensitivity testing", "اختبار التحسس"),
    ("minimum inhibitory concentration", "التركيز المثبط الأدنى"),
    ("broad spectrum antibiotic", "مضاد حيوي واسع الطيف"),
    ("narrow spectrum antibiotic", "مضاد حيوي ضيق الطيف"),
    ("bactericidal drug", "دواء مبيد للجراثيم"),
    ("bacteriostatic drug", "دواء موقف لنمو الجراثيم"),
    ("beta lactam antibiotic", "مضاد بيتا لاكتام"),
    ("penicillin antibiotic", "مضاد بنسليني"),
    ("cephalosporin antibiotic", "مضاد سيفالوسبوريني"),
    ("macrolide antibiotic", "مضاد ماكروليدي"),
    ("aminoglycoside antibiotic", "مضاد أمينوغليكوزيدي"),
    ("fluoroquinolone antibiotic", "مضاد فلوروكينولوني"),
    ("tetracycline antibiotic", "مضاد تتراسيكليني"),
    ("antifungal agent", "عامل مضاد للفطور"),
    ("antiviral agent", "عامل مضاد للفيروسات"),
    ("antiprotozoal agent", "عامل مضاد للأوالي"),
    ("anthelmintic agent", "عامل مضاد للديدان"),
    ("nonsteroidal anti inflammatory drug", "مضاد التهاب غير ستيروئيدي"),
    ("opioid analgesic", "مسكن أفيوني"),
    ("local anesthetic", "مخدر موضعي"),
    ("general anesthetic", "مخدر عام"),
    ("antihypertensive drug", "دواء خافض للضغط"),
    ("angiotensin converting enzyme inhibitor", "مثبط الإنزيم المحول للأنجيوتنسين"),
    ("angiotensin receptor blocker", "حاصر مستقبل الأنجيوتنسين"),
    ("beta blocker drug", "دواء حاصر بيتا"),
    ("calcium channel blocker", "حاصر قنوات الكالسيوم"),
    ("loop diuretic", "مدر العروة"),
    ("thiazide diuretic", "مدر ثيازيدي"),
    ("potassium sparing diuretic", "مدر حافظ للبوتاسيوم"),
    ("antiplatelet drug", "دواء مضاد للصفيحات"),
    ("anticoagulant drug", "دواء مضاد للتخثر"),
    ("thrombolytic drug", "دواء حال للخثرة"),
    ("statin drug", "دواء ستاتيني"),
    ("insulin preparation", "مستحضر إنسولين"),
    ("oral hypoglycemic agent", "خافض سكر فموي"),
    ("bronchodilator drug", "دواء موسع للقصبات"),
    ("corticosteroid drug", "دواء ستيروئيدي قشري"),
    ("antihistamine drug", "دواء مضاد للهيستامين"),
    ("proton pump inhibitor", "مثبط مضخة البروتون"),
    ("antiemetic drug", "دواء مضاد للإقياء"),
    ("laxative drug", "دواء ملين"),
    ("antidiarrheal drug", "دواء مضاد للإسهال"),
    ("antidepressant drug", "دواء مضاد للاكتئاب"),
    ("antipsychotic drug", "دواء مضاد للذهان"),
    ("anxiolytic drug", "دواء مزيل للقلق"),
    ("anticonvulsant drug", "دواء مضاد للاختلاج"),
    ("drug absorption", "امتصاص الدواء"),
    ("drug distribution", "توزيع الدواء"),
    ("drug metabolism", "استقلاب الدواء"),
    ("drug excretion", "إطراح الدواء"),
    ("first order kinetics", "حركية من المرتبة الأولى"),
    ("zero order kinetics", "حركية من المرتبة صفر"),
    ("steady state concentration", "تركيز الحالة الثابتة"),
    ("loading dose", "جرعة تحميل"),
    ("maintenance dose", "جرعة صيانة"),
    ("therapeutic drug monitoring", "مراقبة دوائية علاجية"),
    ("adverse effect profile", "مرتسم التأثيرات الضارة"),
    ("drug toxicity", "سمية الدواء"),
    ("contraindication list", "قائمة موانع الاستعمال"),
    ("enteric coated tablet", "قرص ملبس معويا"),
    ("sustained release tablet", "قرص مديد التحرر"),
    ("sublingual tablet", "قرص تحت اللسان"),
    ("effervescent tablet", "قرص فوار"),
    ("hard gelatin capsule", "كبسولة جيلاتينية صلبة"),
    ("oral suspension", "معلق فموي"),
    ("topical ointment", "مرهم موضعي"),
    ("ophthalmic drops", "قطرات عينية"),
    ("otic drops", "قطرات أذنية"),
    ("nasal spray", "بخاخ أنفي"),
    ("metered dose inhaler", "منشقة محددة الجرعة"),
    ("intravenous bolus", "حقنة وريدية سريعة"),
    ("intramuscular injection", "حقن عضلي"),
    ("subcutaneous injection", "حقن تحت الجلد"),
    ("intradermal injection", "حقن داخل الأدمة"),
    ("sterile technique", "تقنية عقيمة"),
    ("hand hygiene", "نظافة اليدين"),
    ("vital signs monitoring", "مراقبة العلامات الحيوية"),
    ("pulse oximetry", "قياس الأكسجة النبضي"),
    ("blood pressure measurement", "قياس ضغط الدم"),
    ("glasgow coma scale", "مقياس غلاسكو للغيبوبة"),
    ("pain assessment", "تقييم الألم"),
    ("intake and output", "الوارد والصادر"),
    ("pressure injury prevention", "الوقاية من إصابة الضغط"),
    ("fall risk assessment", "تقييم خطر السقوط"),
    ("medication administration", "إعطاء الدواء"),
    ("five rights of medication", "الحقوق الخمسة للدواء"),
    ("nasogastric tube", "أنبوب أنفي معدي"),
    ("urinary catheter", "قثطار بولي"),
    ("peripheral intravenous cannula", "قنية وريدية محيطية"),
    ("central venous catheter", "قثطار وريدي مركزي"),
    ("oxygen therapy", "معالجة بالأكسجين"),
    ("wound irrigation", "إرواء الجرح"),
    ("surgical asepsis", "عقامة جراحية"),
    ("informed consent form", "استمارة الموافقة المستنيرة"),
    ("preoperative care", "عناية قبل الجراحة"),
    ("postoperative care", "عناية بعد الجراحة"),
    ("dental enamel", "ميناء السن"),
    ("dentin layer", "طبقة العاج"),
    ("dental pulp", "لب السن"),
    ("cementum layer", "طبقة الملاط"),
    ("periodontal ligament", "الرباط حول السني"),
    ("gingival sulcus", "التلم اللثوي"),
    ("dental plaque biofilm", "غشاء اللويحة السنية"),
    ("dental calculus deposit", "ترسّب القلح السني"),
    ("gingivitis inflammation", "التهاب اللثة"),
    ("periodontitis disease", "التهاب دواعم السن"),
    ("dental caries lesion", "آفة نخر سني"),
    ("pulpitis inflammation", "التهاب اللب"),
    ("periapical abscess", "خراج حول الذروة"),
    ("root canal therapy", "مداواة قناة الجذر"),
    ("dental crown restoration", "تعويض تاج سني"),
    ("dental bridge restoration", "تعويض جسر سني"),
    ("complete denture", "بدلة سنية كاملة"),
    ("partial denture", "بدلة سنية جزئية"),
    ("dental implant fixture", "غرسة سنية"),
    ("orthodontic appliance", "جهاز تقويم"),
    ("malocclusion class", "صنف سوء الإطباق"),
    ("bitewing radiograph", "صورة شعاعية بين الأسنان"),
    ("panoramic radiograph", "صورة شعاعية بانورامية"),
    ("local dental anesthesia", "تخدير سني موضعي"),
    ("tooth extraction", "قلع السن"),
    ("scaling and root planing", "تقليح وتسوية الجذر"),
    ("fluoride application", "تطبيق الفلوريد"),
    ("oral hygiene instruction", "تعليمات صحة الفم"),
]
