"""مصطلحات الرياضيات والفيزياء والكيمياء والأحياء والجيولوجيا والبيئة."""

from __future__ import annotations

SCI_ENTRIES: list[tuple[str, str]] = [
    ("rolle theorem", "مبرهنة رول"),
    ("mean value theorem for integrals", "مبرهنة القيمة المتوسطة للتكامل"),
    ("cauchy mean value theorem", "مبرهنة القيمة المتوسطة لكوشي"),
    ("taylor theorem", "مبرهنة تايلور"),
    ("maclaurin expansion", "نشر ماكلورين"),
    ("binomial theorem", "مبرهنة ذات الحدين"),
    ("de moivre theorem", "مبرهنة دي موافر"),
    ("euler formula", "صيغة أويلر"),
    ("euler identity", "متطابقة أويلر"),
    ("cauchy riemann equations", "معادلات كوشي-ريمان"),
    ("analytic function", "دالة تحليلية"),
    ("holomorphic function", "دالة هولومورفية"),
    ("residue theorem", "مبرهنة الرواسب"),
    ("laurent series", "متسلسلة لوران"),
    ("contour integral", "تكامل كنتوري"),
    ("cauchy integral formula", "صيغة كوشي التكاملية"),
    ("maximum modulus principle", "مبدأ المعيار الأعظم"),
    ("liouville theorem", "مبرهنة ليوفيل"),
    ("open mapping theorem", "مبرهنة التطبيق المفتوح"),
    ("closed graph theorem", "مبرهنة البيان المغلق"),
    ("hahn banach theorem", "مبرهنة هان-باناخ"),
    ("banach fixed point theorem", "مبرهنة النقطة الثابتة لباناخ"),
    ("bolzano weierstrass theorem", "مبرهنة بولزانو-فايرشتراس"),
    ("heine borel theorem", "مبرهنة هاينه-بوريل"),
    ("intermediate value property", "خاصية القيمة الوسطى"),
    ("uniform continuity", "اتصال منتظم"),
    ("uniform convergence", "تقارب منتظم"),
    ("pointwise convergence", "تقارب نقطي"),
    ("absolute convergence", "تقارب مطلق"),
    ("conditional convergence", "تقارب شرطي"),
    ("power series", "متسلسلة قوى"),
    ("radius of convergence", "نصف قطر التقارب"),
    ("interval of convergence", "مجال التقارب"),
    ("fourier coefficient", "معامل فورييه"),
    ("parseval identity", "متطابقة بارسيفال"),
    ("plancherel theorem", "مبرهنة بلانشيريل"),
    ("convolution theorem statement", "نص مبرهنة الالتفاف"),
    ("dirac delta function", "دالة ديراك دلتا"),
    ("heaviside function", "دالة هيفسايد"),
    ("gamma function", "دالة غاما"),
    ("beta function", "دالة بيتا"),
    ("bessel function", "دالة بيسل"),
    ("legendre polynomial", "كثيرة حدود لوجندر"),
    ("chebyshev polynomial", "كثيرة حدود تشيبيشيف"),
    ("hermite polynomial", "كثيرة حدود هرميت"),
    ("laguerre polynomial", "كثيرة حدود لاغير"),
    ("orthogonal polynomials", "كثيرات حدود متعامدة"),
    ("sturm liouville problem", "مسألة شتورم-ليوفيل"),
    ("eigenfunction expansion", "نشر بالدوال الذاتية"),
    ("green function", "دالة غرين"),
    ("variation of parameters", "تغيير الوسائط"),
    ("undetermined coefficients", "معاملات غير معينة"),
    ("exact differential equation", "معادلة تفاضلية تامة"),
    ("integrating factor", "عامل مكامل"),
    ("separable equation", "معادلة قابلة للفصل"),
    ("bernoulli differential equation", "معادلة برنولي التفاضلية"),
    ("cauchy euler equation", "معادلة كوشي-أويلر"),
    ("wronskian determinant", "محدد ورونسكي"),
    ("fundamental set of solutions", "مجموعة حلول أساسية"),
    ("phase plane", "مستوي الطور"),
    ("equilibrium point", "نقطة اتزان"),
    ("stable node", "عقدة مستقرة"),
    ("unstable node", "عقدة غير مستقرة"),
    ("saddle equilibrium", "اتزان سرجي"),
    ("limit cycle", "دورة حدية"),
    ("lyapunov stability", "استقرار ليابونوف"),
    ("picard iteration", "تكرار بيكار"),
    ("existence uniqueness theorem", "مبرهنة الوجود والوحدانية"),
    ("lipschitz condition", "شرط ليبشيتز"),
    ("peano existence theorem", "مبرهنة وجود بيانو"),
    ("vector calculus", "حسبان المتجهات"),
    ("line integral of vector field", "تكامل خطي لحقل متجه"),
    ("surface integral of vector field", "تكامل سطحي لحقل متجه"),
    ("flux of a vector field", "فيض حقل متجه"),
    ("circulation of a vector field", "دوران حقل متجه"),
    ("conservative vector field", "حقل متجه محافظ"),
    ("solenoidal vector field", "حقل متجه عديم التباعد"),
    ("scalar potential", "جهد قياسي"),
    ("vector potential", "جهد متجه"),
    ("jacobian determinant", "محدد يعقوبي"),
    ("change of variables", "تغيير المتغيرات"),
    ("polar coordinates", "إحداثيات قطبية"),
    ("cylindrical coordinates", "إحداثيات أسطوانية"),
    ("spherical coordinates", "إحداثيات كروية"),
    ("arc length", "طول القوس"),
    ("curvature of a curve", "تقوس المنحنى"),
    ("torsion of a curve", "لي المنحنى"),
    ("frenet serret formulas", "صيغ فرينيه-سيريه"),
    ("osculating plane", "المستوي الملاصق"),
    ("normal plane", "المستوي الناظمي"),
    ("rectifying plane", "المستوي المقوم"),
    ("quadric surface", "سطح تربيعي"),
    ("ellipsoid surface", "سطح إهليلجي"),
    ("hyperboloid surface", "سطح زائد"),
    ("paraboloid surface", "سطح مكافئ"),
    ("cone surface", "سطح مخروطي"),
    ("cylinder surface", "سطح أسطواني"),
    ("ruled surface", "سطح مسطر"),
    ("tangent plane", "مستو مماس"),
    ("normal line", "مستقيم ناظم"),
    ("directional derivative value", "قيمة المشتقة الاتجاهية"),
    ("gradient vector", "متجه التدرج"),
    ("level surface", "سطح سوية"),
    ("constraint optimization", "استمثال مقيد"),
    ("lagrange function", "دالة لاغرانج"),
    ("karush kuhn tucker conditions", "شروط كاروش-كون-تاكر"),
    ("convex function", "دالة محدبة"),
    ("concave function", "دالة مقعرة"),
    ("convex set", "مجموعة محدبة"),
    ("linear programming", "برمجة خطية"),
    ("simplex method", "طريقة السمبلكس"),
    ("dual problem", "مسألة ثنائية"),
    ("primal problem", "مسألة أولية"),
    ("feasible region", "منطقة ممكنة"),
    ("objective function", "دالة الهدف"),
    ("basic feasible solution", "حل أساسي ممكن"),
    ("degeneracy in linear programming", "انحلال في البرمجة الخطية"),
    ("integer programming", "برمجة صحيحة"),
    ("nonlinear programming", "برمجة غير خطية"),
    ("dynamic programming principle", "مبدأ البرمجة الديناميكية"),
    ("shortest path problem", "مسألة أقصر مسار"),
    ("dijkstra algorithm", "خوارزمية دايكسترا"),
    ("bellman ford algorithm", "خوارزمية بلمان-فورد"),
    ("floyd warshall algorithm", "خوارزمية فلويد-وارشال"),
    ("minimum spanning tree", "شجرة امتداد صغرى"),
    ("kruskal algorithm", "خوارزمية كروسكال"),
    ("prim algorithm", "خوارزمية بريم"),
    ("maximum flow problem", "مسألة التدفق الأعظم"),
    ("ford fulkerson method", "طريقة فورد-فولكرسون"),
    ("max flow min cut theorem", "مبرهنة التدفق الأعظم والقطع الأصغر"),
    ("bipartite graph", "بيان ثنائي التجزئة"),
    ("planar graph", "بيان مستو"),
    ("eulerian path", "مسار أويلري"),
    ("hamiltonian path", "مسار هاملتوني"),
    ("graph coloring", "تلوين البيان"),
    ("chromatic number", "العدد اللوني"),
    ("adjacency matrix", "مصفوفة التجاور"),
    ("incidence matrix", "مصفوفة الوقوع"),
    ("degree of a vertex", "درجة الرأس"),
    ("connected graph", "بيان مترابط"),
    ("tree graph", "بيان شجري"),
    ("spanning tree", "شجرة امتداد"),
    ("boolean function", "دالة بوليانية"),
    ("truth assignment", "إسناد قيم الحقيقة"),
    ("predicate logic", "منطق المحمولات"),
    ("propositional logic", "منطق القضايا"),
    ("quantifier logic", "منطق الأسوار"),
    ("mathematical induction", "استقراء رياضي"),
    ("strong induction", "استقراء قوي"),
    ("pigeonhole principle", "مبدأ برج الحمام"),
    ("inclusion exclusion principle", "مبدأ الاحتواء والإقصاء"),
    ("generating function", "دالة مولدة"),
    ("recurrence relation", "علاقة تراجع"),
    ("closed form solution", "حل بصيغة مغلقة"),
    ("modular arithmetic", "حساب تقايس"),
    ("congruence relation", "علاقة تطابق"),
    ("chinese remainder theorem", "مبرهنة الباقي الصيني"),
    ("fermat little theorem", "مبرهنة فيرما الصغرى"),
    ("euler totient function", "دالة أويلر"),
    ("prime factorization", "تحليل إلى عوامل أولية"),
    ("greatest common divisor", "القاسم المشترك الأكبر"),
    ("least common multiple", "المضاعف المشترك الأصغر"),
    ("euclidean algorithm", "خوارزمية إقليدس"),
    ("diophantine equation", "معادلة ديوفنتية"),
    ("group homomorphism", "تشاكل زمري"),
    ("group isomorphism", "تماكل زمري"),
    ("cyclic group", "زمرة دورية"),
    ("abelian group", "زمرة أبيلية"),
    ("normal subgroup", "زمرة جزئية ناظمية"),
    ("quotient group", "زمرة خارج القسمة"),
    ("lagrange theorem of groups", "مبرهنة لاغرانج للزمر"),
    ("cayley theorem", "مبرهنة كيلي"),
    ("ring homomorphism", "تشاكل حلقي"),
    ("ideal of a ring", "مثالي حلقة"),
    ("principal ideal", "مثالي رئيسي"),
    ("field extension", "امتداد حقل"),
    ("galois group", "زمرة غالوا"),
    ("vector subspace", "فضاء جزئي متجه"),
    ("linear dependence", "ارتباط خطي"),
    ("basis of a vector space", "أساس فضاء متجهي"),
    ("dimension of vector space", "بعد الفضاء المتجهي"),
    ("change of basis", "تغيير الأساس"),
    ("transition matrix", "مصفوفة الانتقال"),
    ("similar matrices", "مصفوفات متشابهة"),
    ("diagonalizable matrix", "مصفوفة قابلة للتقطير"),
    ("jordan canonical form", "شكل جوردان القانوني"),
    ("characteristic polynomial", "كثيرة الحدود المميزة"),
    ("minimal polynomial", "كثيرة الحدود الأصغرية"),
    ("cayley hamilton theorem", "مبرهنة كيلي-هاميلتون"),
    ("rank nullity theorem", "مبرهنة الرتبة والفضاء المعدوم"),
    ("orthogonal projection", "إسقاط متعامد"),
    ("least squares solution", "حل المربعات الصغرى"),
    ("normal equations", "معادلات ناظمية"),
    ("qr factorization", "تحليل كيو آر"),
    ("singular values", "قيم شاذة"),
    ("spectral theorem", "مبرهنة طيفية"),
    ("positive semidefinite matrix", "مصفوفة موجبة شبه معرفة"),
    ("matrix norm", "نظيم مصفوفة"),
    ("vector norm", "نظيم متجه"),
    ("inner product space", "فضاء جداء داخلي"),
    ("hilbert space", "فضاء هلبرت"),
    ("banach space", "فضاء باناخ"),
    ("complete metric space", "فضاء متري تام"),
    ("compact set", "مجموعة متراصة"),
    ("open set", "مجموعة مفتوحة"),
    ("closed set", "مجموعة مغلقة"),
    ("closure of a set", "غلاقة مجموعة"),
    ("interior of a set", "داخلية مجموعة"),
    ("boundary of a set", "حدود مجموعة"),
    ("connected set", "مجموعة مترابطة"),
    ("continuous mapping", "تطبيق مستمر"),
    ("homeomorphism mapping", "تطبيق هوميومورفي"),
    ("metric topology", "طوبولوجيا مترية"),
    ("hausdorff space", "فضاء هاوسدورف"),
    ("sample mean", "متوسط العينة"),
    ("sample variance", "تباين العينة"),
    ("sample standard deviation", "انحراف معياري للعينة"),
    ("population mean", "متوسط المجتمع"),
    ("population variance", "تباين المجتمع"),
    ("unbiased estimator", "مقدر غير متحيز"),
    ("consistent estimator", "مقدر متسق"),
    ("efficient estimator", "مقدر كفء"),
    ("maximum likelihood estimator", "مقدر الأرجحية العظمى"),
    ("method of moments", "طريقة العزوم"),
    ("confidence interval estimate", "تقدير فترة الثقة"),
    ("prediction interval", "فترة تنبؤ"),
    ("hypothesis test", "اختبار فرضية"),
    ("test statistic", "إحصاءة الاختبار"),
    ("critical region", "منطقة حرجة"),
    ("significance level alpha", "مستوى الدلالة ألفا"),
    ("p value of test", "القيمة الاحتمالية للاختبار"),
    ("power of a test", "قوة الاختبار"),
    ("type one error probability", "احتمال خطأ النوع الأول"),
    ("type two error probability", "احتمال خطأ النوع الثاني"),
    ("paired t test", "اختبار تي للعينات المزدوجة"),
    ("two sample t test", "اختبار تي لعينتين"),
    ("one way anova", "تحليل تباين أحادي الاتجاه"),
    ("two way anova", "تحليل تباين ثنائي الاتجاه"),
    ("chi square goodness of fit", "اختبار مربع كاي لحسن المطابقة"),
    ("chi square test of independence", "اختبار مربع كاي للاستقلال"),
    ("fisher exact test", "اختبار فيشر الدقيق"),
    ("mann whitney test", "اختبار مان-ويتني"),
    ("wilcoxon signed rank test", "اختبار ويلكوكسون للرتب"),
    ("kruskal wallis test", "اختبار كروسكال-واليس"),
    ("kolmogorov smirnov test", "اختبار كولموغوروف-سميرنوف"),
    ("shapiro wilk test", "اختبار شابيرو-ويلك"),
    ("levene test", "اختبار ليفين"),
    ("bartlett test", "اختبار بارتليت"),
    ("pearson correlation", "ارتباط بيرسون"),
    ("spearman correlation", "ارتباط سبيرمان"),
    ("simple linear regression", "انحدار خطي بسيط"),
    ("multiple linear regression", "انحدار خطي متعدد"),
    ("residual analysis", "تحليل البواقي"),
    ("coefficient of determination value", "قيمة معامل التحديد"),
    ("adjusted r squared", "معامل تحديد معدل"),
    ("multicollinearity problem", "مشكلة التعدد الخطي"),
    ("heteroscedasticity problem", "مشكلة عدم تجانس التباين"),
    ("autocorrelation problem", "مشكلة الارتباط الذاتي"),
    ("durbin watson test", "اختبار دوربن-واتسون"),
    ("logistic regression model", "نموذج الانحدار اللوجستي"),
    ("odds ratio", "نسبة الأرجحية"),
    ("poisson regression", "انحدار بواسون"),
    ("survival analysis", "تحليل البقاء"),
    ("kaplan meier estimator", "مقدر كابلان-ماير"),
    ("cox proportional hazards", "مخاطر كوكس التناسبية"),
    ("hazard function", "دالة الخطورة"),
    ("censoring of data", "رقابة البيانات"),
    ("bayesian inference", "استدلال بايزي"),
    ("prior distribution", "توزيع سابق"),
    ("posterior distribution", "توزيع لاحق"),
    ("likelihood function", "دالة الأرجحية"),
    ("bayes factor", "عامل بايز"),
    ("markov chain", "سلسلة ماركوف"),
    ("transition probability", "احتمال انتقال"),
    ("stationary distribution", "توزيع مستقر"),
    ("poisson process", "عملية بواسون"),
    ("exponential waiting time", "زمن انتظار أسي"),
    ("central moment", "عزم مركزي"),
    ("moment generating function", "دالة مولدة للعزوم"),
    ("characteristic function", "دالة مميزة"),
    ("law of large numbers", "قانون الأعداد الكبيرة"),
    ("weak law of large numbers", "القانون الضعيف للأعداد الكبيرة"),
    ("strong law of large numbers", "القانون القوي للأعداد الكبيرة"),
    ("chebyshev inequality", "متباينة تشيبيشيف"),
    ("jensen inequality", "متباينة جنسن"),
    ("markov inequality", "متباينة ماركوف"),
    ("covariance matrix", "مصفوفة التغاير"),
    ("multivariate normal distribution", "توزيع طبيعي متعدد المتغيرات"),
    ("chi square distribution", "توزيع مربع كاي"),
    ("student t distribution", "توزيع تي للطالب"),
    ("f distribution", "توزيع إف"),
    ("beta distribution", "توزيع بيتا"),
    ("gamma distribution", "توزيع غاما"),
    ("weibull distribution", "توزيع وايبول"),
    ("lognormal distribution", "توزيع لوغاريتمي طبيعي"),
    ("geometric distribution", "توزيع هندسي"),
    ("negative binomial distribution", "توزيع ذي الحدين السالب"),
    ("hypergeometric distribution", "توزيع فوق هندسي"),
    ("bernoulli trial", "تجربة برنولي"),
    ("expected value operator", "مؤثر القيمة المتوقعة"),
    ("variance operator", "مؤثر التباين"),
    ("covariance operator", "مؤثر التغاير"),
    ("conditional expectation", "توقع شرطي"),
    ("law of total probability", "قانون الاحتمال الكلي"),
    ("bayes theorem statement", "نص مبرهنة بايز"),
    ("independent random variables", "متغيرات عشوائية مستقلة"),
    ("joint probability density", "كثافة احتمال مشتركة"),
    ("marginal distribution", "توزيع هامشي"),
    ("newton first law", "قانون نيوتن الأول"),
    ("newton second law", "قانون نيوتن الثاني"),
    ("newton third law", "قانون نيوتن الثالث"),
    ("conservation of linear momentum", "حفظ الزخم الخطي"),
    ("conservation of mechanical energy", "حفظ الطاقة الميكانيكية"),
    ("work energy principle", "مبدأ الشغل والطاقة"),
    ("impulse momentum theorem", "مبرهنة الدفع والزخم"),
    ("center of mass motion", "حركة مركز الكتلة"),
    ("moment of inertia tensor", "موتر عزم القصور"),
    ("parallel axis theorem", "مبرهنة المحور الموازي"),
    ("perpendicular axis theorem", "مبرهنة المحور المتعامد"),
    ("rolling without slipping", "تدحرج دون انزلاق"),
    ("angular velocity vector", "متجه السرعة الزاوية"),
    ("angular acceleration vector", "متجه التسارع الزاوي"),
    ("torque vector", "متجه عزم الدوران"),
    ("precession motion", "حركة المبادرة"),
    ("nutation motion", "حركة الترنح"),
    ("kepler first law", "قانون كبلر الأول"),
    ("kepler second law", "قانون كبلر الثاني"),
    ("kepler third law", "قانون كبلر الثالث"),
    ("gravitational potential", "جهد الجاذبية"),
    ("escape velocity", "سرعة الإفلات"),
    ("orbital velocity", "سرعة مدارية"),
    ("geostationary orbit", "مدار ثابت بالنسبة للأرض"),
    ("simple pendulum", "نواس بسيط"),
    ("physical pendulum", "نواس فيزيائي"),
    ("torsional pendulum", "نواس لي"),
    ("damped harmonic oscillator", "مهتز توافقي مخمد"),
    ("driven harmonic oscillator", "مهتز توافقي مقسور"),
    ("resonance frequency", "تردد الرنين"),
    ("quality factor", "معامل الجودة"),
    ("wave equation", "معادلة الموجة"),
    ("traveling wave", "موجة مسافرة"),
    ("standing wave", "موجة واقفة"),
    ("transverse wave", "موجة مستعرضة"),
    ("longitudinal wave", "موجة طولية"),
    ("wave superposition", "تراكب الأمواج"),
    ("beat frequency", "تردد الضربات"),
    ("doppler shift", "انزياح دوبلر"),
    ("sound intensity level", "مستوى شدة الصوت"),
    ("decibel scale", "مقياس الديسيبل"),
    ("young modulus experiment", "تجربة معامل يونغ"),
    ("hooke law experiment", "تجربة قانون هوك"),
    ("coulomb law statement", "نص قانون كولوم"),
    ("gauss law statement", "نص قانون غاوس"),
    ("electric flux", "فيض كهربائي"),
    ("electric dipole", "ثنائي قطب كهربائي"),
    ("electric dipole moment", "عزم ثنائي القطب الكهربائي"),
    ("capacitance of parallel plates", "سعة لوحين متوازيين"),
    ("energy stored in capacitor", "طاقة مختزنة في المكثف"),
    ("dielectric constant", "ثابت العزل"),
    ("polarization vector", "متجه الاستقطاب"),
    ("bound charge", "شحنة مقيدة"),
    ("free charge", "شحنة حرة"),
    ("ohm law statement", "نص قانون أوم"),
    ("resistivity of material", "مقاومة نوعية للمادة"),
    ("conductivity of material", "موصلية المادة"),
    ("drift velocity", "سرعة الانجراف"),
    ("current density", "كثافة التيار"),
    ("kirchhoff current law", "قانون كيرشوف للتيار"),
    ("kirchhoff voltage law", "قانون كيرشوف للجهد"),
    ("rc circuit", "دارة مقاومة ومكثف"),
    ("rl circuit", "دارة مقاومة وملف"),
    ("rlc circuit", "دارة مقاومة وملف ومكثف"),
    ("impedance of circuit", "ممانعة الدارة"),
    ("reactance of circuit", "مفاعلة الدارة"),
    ("resonance in rlc circuit", "رنين دارة مقاومة وملف ومكثف"),
    ("quality factor of circuit", "معامل جودة الدارة"),
    ("biot savart law", "قانون بيو-سافار"),
    ("ampere law statement", "نص قانون أمبير"),
    ("magnetic flux", "فيض مغناطيسي"),
    ("faraday law statement", "نص قانون فاراداي"),
    ("lenz law statement", "نص قانون لنز"),
    ("self inductance", "محاثة ذاتية"),
    ("mutual inductance", "محاثة متبادلة"),
    ("energy stored in inductor", "طاقة مختزنة في الملف"),
    ("lorentz force", "قوة لورنتز"),
    ("cyclotron frequency", "تردد السيكلوترون"),
    ("hall effect", "تأثير هول"),
    ("maxwell equations", "معادلات ماكسويل"),
    ("electromagnetic wave equation", "معادلة الموجة الكهرومغناطيسية"),
    ("poynting vector", "متجه بوينتنغ"),
    ("skin depth", "عمق التأثير السطحي"),
    ("snell law of refraction", "قانون سنيل للانكسار"),
    ("brewster angle", "زاوية بروستر"),
    ("critical angle", "زاوية حرجة"),
    ("thin lens equation", "معادلة العدسة الرقيقة"),
    ("lens maker equation", "معادلة صانع العدسة"),
    ("mirror equation", "معادلة المرآة"),
    ("spherical aberration", "زيغ كروي"),
    ("chromatic aberration", "زيغ لوني"),
    ("diffraction grating", "محزز الحيود"),
    ("single slit diffraction", "حيود الشق الأحادي"),
    ("double slit interference", "تداخل الشقين"),
    ("michelson interferometer", "مقياس تداخل مايكلسون"),
    ("polarization of light", "استقطاب الضوء"),
    ("malus law", "قانون مالوس"),
    ("photoelectric equation", "معادلة التأثير الكهروضوئي"),
    ("work function", "دالة الشغل"),
    ("stopping potential", "جهد الإيقاف"),
    ("compton wavelength", "طول موجة كومبتون"),
    ("de broglie relation", "علاقة دي برولي"),
    ("heisenberg uncertainty principle", "مبدأ هايزنبرغ للارتياب"),
    ("schrodinger time dependent equation", "معادلة شرودنغر المعتمدة على الزمن"),
    ("schrodinger time independent equation", "معادلة شرودنغر غير المعتمدة على الزمن"),
    ("wave function normalization", "معايرة الدالة الموجية"),
    ("probability current", "تيار الاحتمال"),
    ("expectation value in quantum mechanics", "القيمة المتوقعة في ميكانيكا الكم"),
    ("stationary state", "حالة مستقرة"),
    ("quantum harmonic oscillator", "مهتز توافقي كمومي"),
    ("particle in a box", "جسيم في صندوق"),
    ("tunneling effect", "تأثير النفق"),
    ("spin angular momentum", "زخم زاوي مغزلي"),
    ("pauli exclusion principle", "مبدأ استبعاد باولي"),
    ("hydrogen atom spectrum", "طيف ذرة الهيدروجين"),
    ("rydberg formula", "صيغة ريدبرغ"),
    ("bohr radius", "نصف قطر بور"),
    ("fine structure", "بنية دقيقة"),
    ("zeeman effect", "تأثير زيمان"),
    ("stark effect", "تأثير شتارك"),
    ("blackbody spectrum", "طيف الجسم الأسود"),
    ("planck law", "قانون بلانك"),
    ("wien law", "قانون فين"),
    ("rayleigh jeans law", "قانون رايلي-جينز"),
    ("stefan boltzmann constant", "ثابت ستيفان-بولتزمان"),
    ("special relativity postulates", "مصادرات النسبية الخاصة"),
    ("lorentz transformation", "تحويل لورنتز"),
    ("time dilation formula", "صيغة تمدد الزمن"),
    ("length contraction formula", "صيغة انكماش الطول"),
    ("relativistic momentum", "زخم نسبي"),
    ("rest energy", "طاقة السكون"),
    ("relativistic kinetic energy", "طاقة حركية نسبية"),
    ("mass energy relation", "علاقة الكتلة والطاقة"),
    ("radioactive decay law", "قانون الاضمحلال الإشعاعي"),
    ("decay constant", "ثابت الاضمحلال"),
    ("mean life", "عمر متوسط"),
    ("activity of a sample", "نشاط العينة"),
    ("becquerel unit", "وحدة البيكريل"),
    ("half life formula", "صيغة العمر النصفي"),
    ("alpha decay", "اضمحلال ألفا"),
    ("beta decay", "اضمحلال بيتا"),
    ("gamma decay", "اضمحلال غاما"),
    ("binding energy per nucleon", "طاقة الربط لكل نيوكلون"),
    ("mass defect calculation", "حساب نقص الكتلة"),
    ("fission chain reaction", "تفاعل انشطار متسلسل"),
    ("critical mass", "كتلة حرجة"),
    ("moderator material", "مادة مهدئة"),
    ("control rod", "قضيب تحكم"),
    ("semiconductor band structure", "بنية نطاقات شبه الموصل"),
    ("intrinsic semiconductor", "شبه موصل ذاتي"),
    ("extrinsic semiconductor", "شبه موصل دخيل"),
    ("n type semiconductor", "شبه موصل من النوع السالب"),
    ("p type semiconductor", "شبه موصل من النوع الموجب"),
    ("donor impurity", "شائبة مانحة"),
    ("acceptor impurity", "شائبة آخذة"),
    ("fermi level", "مستوى فيرمي"),
    ("fermi dirac distribution", "توزيع فيرمي-ديراك"),
    ("depletion region", "منطقة الاستنزاف"),
    ("built in potential", "جهد مبني داخليا"),
    ("forward bias", "انحياز أمامي"),
    ("reverse bias", "انحياز عكسي"),
    ("zener diode", "ثنائي زينر"),
    ("light emitting diode", "ثنائي باعث للضوء"),
    ("photodiode device", "ثنائي ضوئي"),
    ("solar cell efficiency", "مردود الخلية الشمسية"),
    ("ideal gas equation", "معادلة الغاز المثالي"),
    ("van der waals equation", "معادلة فان دير فالس"),
    ("compressibility factor", "معامل الانضغاطية"),
    ("dalton partial pressure law", "قانون دالتون للضغوط الجزئية"),
    ("raoult law statement", "نص قانون راؤول"),
    ("henry law statement", "نص قانون هنري"),
    ("colligative properties", "خواص تجمعية"),
    ("boiling point elevation", "ارتفاع درجة الغليان"),
    ("freezing point depression", "انخفاض درجة التجمد"),
    ("osmotic pressure", "ضغط تناضحي"),
    ("chemical potential", "جهد كيميائي"),
    ("gibbs phase rule", "قاعدة أطوار جبس"),
    ("clapeyron equation", "معادلة كلايبرون"),
    ("clausius clapeyron equation", "معادلة كلاوزيوس-كلايبرون"),
    ("hess law", "قانون هس"),
    ("standard enthalpy of formation", "إنثالبي التكوين القياسي"),
    ("standard entropy", "إنتروبيا قياسية"),
    ("gibbs free energy change", "تغير طاقة جبس الحرة"),
    ("equilibrium constant expression", "عبارة ثابت الاتزان"),
    ("reaction quotient", "حاصل التفاعل"),
    ("le chatelier principle statement", "نص مبدأ لو شاتيليه"),
    ("acid dissociation constant", "ثابت تفكك الحمض"),
    ("base dissociation constant", "ثابت تفكك القاعدة"),
    ("ionic product of water", "الجداء الأيوني للماء"),
    ("ph scale", "مقياس الأس الهيدروجيني"),
    ("buffer capacity", "سعة المحلول المنظم"),
    ("henderson hasselbalch equation", "معادلة هندرسون-هاسلبالخ"),
    ("solubility product", "جداء الذوبان"),
    ("common ion effect", "تأثير الأيون المشترك"),
    ("nernst equation", "معادلة نرنست"),
    ("electrochemical cell", "خلية كهروكيميائية"),
    ("galvanic cell", "خلية غلفانية"),
    ("electrolytic cell", "خلية تحليلية"),
    ("standard electrode potential", "جهد قطب قياسي"),
    ("faraday law of electrolysis", "قانون فاراداي للتحليل الكهربائي"),
    ("oxidation state", "حالة التأكسد"),
    ("half reaction", "نصف تفاعل"),
    ("balancing redox equation", "موازنة معادلة الأكسدة والاختزال"),
    ("rate law expression", "عبارة قانون المعدل"),
    ("integrated rate law", "قانون المعدل المتكامل"),
    ("first order reaction", "تفاعل من المرتبة الأولى"),
    ("second order reaction", "تفاعل من المرتبة الثانية"),
    ("zero order reaction", "تفاعل من المرتبة صفر"),
    ("pseudo first order", "مرتبة أولى ظاهرية"),
    ("activation energy barrier", "حاجز طاقة التنشيط"),
    ("transition state", "حالة انتقالية"),
    ("catalyst mechanism", "آلية الحفاز"),
    ("enzyme kinetics", "حركية الإنزيم"),
    ("michaelis menten equation", "معادلة ميكايليس-مينتن"),
    ("lineweaver burk plot", "مخطط لاينويفر-بورك"),
    ("competitive inhibition", "تثبيط تنافسي"),
    ("noncompetitive inhibition", "تثبيط غير تنافسي"),
    ("allosteric regulation", "تنظيم تفارغي"),
    ("iupac nomenclature", "تسمية أيوباك"),
    ("alkane homologous series", "سلسلة الألكانات المتجانسة"),
    ("alkene addition reaction", "تفاعل إضافة الألكين"),
    ("alkyne addition reaction", "تفاعل إضافة الألكاين"),
    ("markovnikov rule", "قاعدة ماركوفنيكوف"),
    ("anti markovnikov addition", "إضافة ضد ماركوفنيكوف"),
    ("electrophilic addition", "إضافة إلكتروفيلية"),
    ("nucleophilic substitution", "استبدال نوكليوفيلي"),
    ("sn1 reaction", "تفاعل استبدال أحادي الجزيء"),
    ("sn2 reaction", "تفاعل استبدال ثنائي الجزيء"),
    ("elimination reaction", "تفاعل حذف"),
    ("e1 reaction", "تفاعل حذف أحادي الجزيء"),
    ("e2 reaction", "تفاعل حذف ثنائي الجزيء"),
    ("grignard reagent", "كاشف غرينيار"),
    ("aldol condensation", "تكاثف ألدولي"),
    ("cannizzaro reaction", "تفاعل كانيزارو"),
    ("friedel crafts alkylation", "ألكلة فريدل-كرافتس"),
    ("friedel crafts acylation", "أسيلة فريدل-كرافتس"),
    ("diels alder reaction", "تفاعل ديلز-ألدر"),
    ("wittig reaction", "تفاعل فيتيغ"),
    ("hoffmann rearrangement", "إعادة ترتيب هوفمان"),
    ("beckmann rearrangement", "إعادة ترتيب بكمان"),
    ("claisen condensation", "تكاثف كلايزن"),
    ("williamson ether synthesis", "اصطناع ويليامسون للإيثر"),
    ("aromatic electrophilic substitution", "استبدال إلكتروفيلي أروماتي"),
    ("ortho para director", "موجه أورثو وبارا"),
    ("meta director", "موجه ميتا"),
    ("resonance structure", "بنية رنينية"),
    ("hyperconjugation effect", "تأثير الترافق الفائق"),
    ("inductive effect", "تأثير حثي"),
    ("steric hindrance", "إعاقة فراغية"),
    ("optical isomer", "مصاوغ ضوئي"),
    ("geometric isomer", "مصاوغ هندسي"),
    ("cis isomer", "مصاوغ مقرون"),
    ("trans isomer", "مصاوغ مفروق"),
    ("racemic mixture", "مزيج راسيمي"),
    ("meso compound", "مركب ميزو"),
    ("fischer projection", "إسقاط فيشر"),
    ("newman projection", "إسقاط نيومان"),
    ("chair conformation", "هيئة الكرسي"),
    ("boat conformation", "هيئة القارب"),
    ("glycolysis pathway", "مسار تحلل السكر"),
    ("krebs cycle pathway", "مسار دورة كربس"),
    ("electron transport pathway", "مسار نقل الإلكترون"),
    ("oxidative phosphorylation pathway", "مسار الفسفرة التأكسدية"),
    ("gluconeogenesis pathway", "مسار استحداث الغلوكوز"),
    ("glycogenolysis pathway", "مسار تحلل الغليكوجين"),
    ("glycogenesis pathway", "مسار تكوين الغليكوجين"),
    ("pentose phosphate pathway", "مسار فوسفات البنتوز"),
    ("beta oxidation", "أكسدة بيتا"),
    ("fatty acid synthesis", "اصطناع الحموض الدهنية"),
    ("urea cycle", "دورة اليوريا"),
    ("amino acid deamination", "نزع أمين الحمض الأميني"),
    ("transamination reaction", "تفاعل نقل الأمين"),
    ("dna replication fork", "شوكة تضاعف الحمض النووي"),
    ("leading strand", "الشريط القائد"),
    ("lagging strand", "الشريط المتأخر"),
    ("okazaki fragment", "قطعة أوكازاكي"),
    ("dna polymerase", "بوليميراز الدنا"),
    ("rna polymerase", "بوليميراز الرنا"),
    ("helicase enzyme", "إنزيم الهيليكاز"),
    ("ligase enzyme", "إنزيم الليغاز"),
    ("primase enzyme", "إنزيم البريماز"),
    ("topoisomerase enzyme", "إنزيم التوبوإيزوميراز"),
    ("promoter region", "منطقة المحفز"),
    ("operator region", "منطقة المشغل"),
    ("operon model", "نموذج الأوبيرون"),
    ("lac operon", "أوبيرون اللاكتوز"),
    ("transcription factor", "عامل نسخ"),
    ("start codon", "رامزة البدء"),
    ("stop codon", "رامزة التوقف"),
    ("anticodon loop", "عروة الرامزة المضادة"),
    ("ribosomal subunit", "وحيدة ريبوزومية"),
    ("peptide bond formation", "تكوين الرابطة الببتيدية"),
    ("primary structure of protein", "البنية الأولية للبروتين"),
    ("secondary structure of protein", "البنية الثانوية للبروتين"),
    ("tertiary structure of protein", "البنية الثالثية للبروتين"),
    ("quaternary structure of protein", "البنية الرابعية للبروتين"),
    ("alpha helix", "حلزون ألفا"),
    ("beta sheet", "صفيحة بيتا"),
    ("denaturation of protein", "تمسخ البروتين"),
    ("enzyme substrate complex", "معقد الإنزيم والمادة"),
    ("induced fit model", "نموذج التلاؤم المستحث"),
    ("lock and key model", "نموذج القفل والمفتاح"),
    ("allosteric enzyme", "إنزيم تفارغي"),
    ("feedback inhibition", "تثبيط بالتغذية الراجعة"),
    ("mitosis stages", "مراحل الانقسام الخيطي"),
    ("prophase stage", "مرحلة الطور التمهيدي"),
    ("metaphase stage", "مرحلة الطور الاستوائي"),
    ("anaphase stage", "مرحلة الطور الانفصالي"),
    ("telophase stage", "مرحلة الطور النهائي"),
    ("cytokinesis process", "عملية انقسام السيتوبلازم"),
    ("meiosis stages", "مراحل الانقسام المنصف"),
    ("crossing over", "تعابر"),
    ("independent assortment", "توزيع مستقل"),
    ("homologous chromosomes", "صبغيات متماثلة"),
    ("sister chromatids", "صبغيات شقيقة"),
    ("centromere region", "منطقة القسيم المركزي"),
    ("spindle fiber", "ليف المغزل"),
    ("punnett square analysis", "تحليل مربع بونت"),
    ("monohybrid cross", "تهجين أحادي"),
    ("dihybrid cross", "تهجين ثنائي"),
    ("test cross", "تهجين اختباري"),
    ("incomplete dominance", "سيادة غير تامة"),
    ("codominance inheritance", "وراثة السيادة المشتركة"),
    ("sex linked inheritance", "وراثة مرتبطة بالجنس"),
    ("polygenic inheritance", "وراثة متعددة الجينات"),
    ("hardy weinberg equilibrium", "اتزان هاردي-واينبرغ"),
    ("allele frequency", "تواتر الأليل"),
    ("genotype frequency", "تواتر النمط الجيني"),
    ("genetic drift", "انجراف جيني"),
    ("gene flow", "انسياب جيني"),
    ("founder effect", "تأثير المؤسس"),
    ("bottleneck effect", "تأثير عنق الزجاجة"),
    ("natural selection pressure", "ضغط الانتخاب الطبيعي"),
    ("adaptive radiation", "إشعاع تكيفي"),
    ("convergent evolution", "تطور متقارب"),
    ("divergent evolution", "تطور متباعد"),
    ("homologous structure", "بنية متماثلة"),
    ("analogous structure", "بنية متماثلة الوظيفة"),
    ("vestigial structure", "بنية أثرية"),
    ("cladogram diagram", "مخطط تفرعي"),
    ("phylogenetic tree", "شجرة تطورية"),
    ("binomial nomenclature", "تسمية ثنائية"),
    ("taxonomic hierarchy", "تسلسل تصنيفي"),
    ("kingdom classification", "تصنيف الممالك"),
    ("prokaryotic cell", "خلية بدائية النواة"),
    ("eukaryotic cell", "خلية حقيقية النواة"),
    ("cell theory", "نظرية الخلية"),
    ("fluid mosaic model", "نموذج الفسيفساء المائع"),
    ("phospholipid bilayer", "طبقة مزدوجة من الشحوم الفوسفورية"),
    ("membrane protein", "بروتين غشائي"),
    ("selective permeability", "نفاذية انتقائية"),
    ("osmosis in cells", "التناضح في الخلايا"),
    ("hypotonic solution", "محلول منخفض التوتر"),
    ("hypertonic solution", "محلول مرتفع التوتر"),
    ("isotonic solution", "محلول متساوي التوتر"),
    ("facilitated diffusion process", "عملية الانتشار الميسر"),
    ("sodium potassium pump", "مضخة الصوديوم والبوتاسيوم"),
    ("endocytosis process", "عملية الالتقام"),
    ("exocytosis process", "عملية الإخراج الخلوي"),
    ("phagocytosis process", "عملية البلعمة"),
    ("pinocytosis process", "عملية الشرب الخلوي"),
    ("mitochondrial matrix", "مطرس المتقدرة"),
    ("cristae of mitochondria", "أعراف المتقدرة"),
    ("chloroplast thylakoid", "ثيلاكويد البلاستيدة"),
    ("stroma of chloroplast", "سدى البلاستيدة"),
    ("light dependent reaction", "تفاعل معتمد على الضوء"),
    ("calvin cycle", "دورة كالفن"),
    ("photosystem one", "النظام الضوئي الأول"),
    ("photosystem two", "النظام الضوئي الثاني"),
    ("carbon fixation", "تثبيت الكربون"),
    ("transpiration pull", "سحب النتح"),
    ("cohesion tension theory", "نظرية التماسك والشد"),
    ("stomatal opening", "انفتاح الثغور"),
    ("xylem tissue", "نسيج الخشب"),
    ("phloem tissue", "نسيج اللحاء"),
    ("root hair", "شعيرة جذرية"),
    ("apical meristem", "نسيج إنشائي قمي"),
    ("lateral meristem", "نسيج إنشائي جانبي"),
    ("phototropism response", "استجابة الانتحاء الضوئي"),
    ("geotropism response", "استجابة الانتحاء الأرضي"),
    ("auxin hormone", "هرمون الأوكسين"),
    ("gibberellin hormone", "هرمون الجبرلين"),
    ("cytokinin hormone", "هرمون السيتوكينين"),
    ("abscisic acid", "حمض الأبسيسيك"),
    ("ethylene hormone", "هرمون الإيثيلين"),
    ("nitrogen fixation", "تثبيت النتروجين"),
    ("nitrification process", "عملية النترجة"),
    ("denitrification process", "عملية عكس النترجة"),
    ("ammonification process", "عملية النشدرة"),
    ("carbon cycle reservoir", "مستودع دورة الكربون"),
    ("water cycle process", "عملية دورة الماء"),
    ("phosphorus cycle", "دورة الفوسفور"),
    ("energy pyramid", "هرم الطاقة"),
    ("biomass pyramid", "هرم الكتلة الحيوية"),
    ("numbers pyramid", "هرم الأعداد"),
    ("gross primary productivity", "الإنتاجية الأولية الإجمالية"),
    ("net primary productivity", "الإنتاجية الأولية الصافية"),
    ("ecological succession", "تعاقب بيئي"),
    ("primary succession", "تعاقب أولي"),
    ("secondary succession", "تعاقب ثانوي"),
    ("climax community", "مجتمع الذروة"),
    ("keystone species", "نوع مفتاحي"),
    ("invasive species", "نوع غاز"),
    ("endangered species", "نوع مهدد"),
    ("habitat fragmentation", "تجزؤ الموطن"),
    ("biodiversity hotspot", "بقعة ساخنة للتنوع الحيوي"),
    ("greenhouse gas", "غاز دفيئة"),
    ("carbon footprint", "بصمة كربونية"),
    ("ozone depletion", "نفاد الأوزون"),
    ("acid deposition", "ترسب حمضي"),
    ("eutrophication process", "عملية الإثراء الغذائي"),
    ("biological oxygen demand", "طلب الأكسجين الحيوي"),
    ("particulate matter", "جسيمات معلقة"),
    ("photochemical smog", "ضباب دخاني كيميائي ضوئي"),
    ("renewable resource", "مورد متجدد"),
    ("nonrenewable resource", "مورد غير متجدد"),
    ("sustainable yield", "عطاء مستدام"),
    ("igneous intrusion", "اندساس ناري"),
    ("extrusive igneous rock", "صخر ناري سطحي"),
    ("intrusive igneous rock", "صخر ناري جوفي"),
    ("clastic sedimentary rock", "صخر رسوبي فتاتي"),
    ("chemical sedimentary rock", "صخر رسوبي كيميائي"),
    ("foliated metamorphic rock", "صخر متحول متورق"),
    ("nonfoliated metamorphic rock", "صخر متحول غير متورق"),
    ("rock cycle", "دورة الصخر"),
    ("mineral hardness", "صلادة المعدن"),
    ("mineral cleavage", "انفصام المعدن"),
    ("mineral streak", "مخدش المعدن"),
    ("mineral luster", "بريق المعدن"),
    ("silicate mineral", "معدن سيليكاتي"),
    ("carbonate mineral", "معدن كربوني"),
    ("oxide mineral", "معدن أكسيدي"),
    ("sulfide mineral", "معدن كبريتيدي"),
    ("bowen reaction series", "سلسلة تفاعل بوين"),
    ("convergent plate boundary", "حد صفائح تقاربي"),
    ("divergent plate boundary", "حد صفائح تباعدي"),
    ("transform plate boundary", "حد صفائح تحويلي"),
    ("mid ocean ridge", "حيد وسط المحيط"),
    ("subduction zone", "نطاق الانغراز"),
    ("seafloor spreading", "اتساع قاع البحر"),
    ("continental drift", "انجراف القارات"),
    ("pangaea supercontinent", "قارة بانجيا"),
    ("focus of earthquake", "بؤرة الزلزال"),
    ("epicenter of earthquake", "مركز الزلزال السطحي"),
    ("seismic wave", "موجة زلزالية"),
    ("primary seismic wave", "موجة زلزالية أولية"),
    ("secondary seismic wave", "موجة زلزالية ثانوية"),
    ("surface seismic wave", "موجة زلزالية سطحية"),
    ("richter magnitude", "قدر ريختر"),
    ("moment magnitude", "قدر العزم"),
    ("mercalli intensity", "شدة ميركالي"),
    ("normal fault", "صدع عادي"),
    ("reverse fault", "صدع عكسي"),
    ("strike slip fault", "صدع انزلاق مضربي"),
    ("anticline fold", "طية محدبة"),
    ("syncline fold", "طية مقعرة"),
    ("angular unconformity", "عدم توافق زاوي"),
    ("disconformity surface", "سطح عدم توافق مواز"),
    ("nonconformity surface", "سطح لا توافق"),
    ("index fossil", "أحفورة دالة"),
    ("relative dating", "تأريخ نسبي"),
    ("absolute dating", "تأريخ مطلق"),
    ("radiometric dating", "تأريخ إشعاعي"),
    ("half life dating", "تأريخ بالعمر النصفي"),
    ("geologic time scale", "سلم الزمن الجيولوجي"),
    ("precambrian time", "زمن ما قبل الكمبري"),
    ("paleozoic era", "حقب الحياة القديمة"),
    ("mesozoic era", "حقب الحياة الوسطى"),
    ("cenozoic era", "حقب الحياة الحديثة"),
    ("confined aquifer system", "نظام خزان جوفي محصور"),
    ("unconfined aquifer system", "نظام خزان جوفي حر"),
    ("artesian well", "بئر ارتوازي"),
    ("water table aquifer", "خزان منسوب الماء"),
    ("porosity of rock", "مسامية الصخر"),
    ("permeability of rock", "نفاذية الصخر"),
    ("soil horizon", "أفق التربة"),
    ("soil profile", "مقطع التربة"),
    ("humus content", "محتوى الدبال"),
    ("laterite soil", "تربة لاتيريت"),
    ("loam soil", "تربة طفالية"),
    ("clay soil", "تربة طينية"),
    ("sandy soil", "تربة رملية"),
    ("cation exchange capacity", "سعة التبادل الكاتيوني"),
    ("soil ph", "أس التربة الهيدروجيني"),
    ("field capacity of soil", "السعة الحقلية للتربة"),
    ("wilting point", "نقطة الذبول"),
    ("available water", "ماء متاح"),
    ("drip irrigation system", "نظام الري بالتنقيط"),
    ("sprinkler irrigation system", "نظام الري بالرش"),
    ("surface irrigation", "ري سطحي"),
    ("furrow irrigation", "ري بالخطوط"),
    ("crop water requirement", "الاحتياج المائي للمحصول"),
    ("evapotranspiration of crop", "تبخر ونتح المحصول"),
    ("irrigation efficiency", "كفاءة الري"),
    ("leaching requirement", "احتياج الغسل"),
    ("soil salinity", "ملوحة التربة"),
    ("nitrogen fertilizer", "سماد نتروجيني"),
    ("phosphorus fertilizer", "سماد فوسفوري"),
    ("potassium fertilizer", "سماد بوتاسي"),
    ("organic fertilizer", "سماد عضوي"),
    ("integrated pest management", "إدارة متكاملة للآفات"),
    ("biological control", "مكافحة حيوية"),
    ("herbicide resistance", "مقاومة مبيد الأعشاب"),
    ("photosynthetic efficiency", "كفاءة البناء الضوئي"),
    ("harvest index", "دليل الحصاد"),
    ("plant breeding", "تربية النبات"),
    ("hybrid vigor", "قوة الهجين"),
    ("seed germination test", "اختبار إنبات البذور"),
    ("vegetative propagation", "تكاثر خضري"),
    ("tissue culture", "زراعة الأنسجة"),
]
