"""مصطلحات سريرية وهندسية إضافية شائعة في الكتب الجامعية."""

from __future__ import annotations

REF_ENTRIES: list[tuple[str, str]] = [
    ("acute coronary syndrome", "متلازمة تاجية حادة"),
    ("st elevation myocardial infarction", "احتشاء عضلة القلب مع ارتفاع القطعة إس تي"),
    ("non st elevation myocardial infarction", "احتشاء عضلة القلب دون ارتفاع القطعة إس تي"),
    ("percutaneous coronary intervention", "تدخل تاجي عبر الجلد"),
    ("coronary artery bypass graft", "مجازة شريانية تاجية"),
    ("cardiac catheterization", "قثطرة قلبية"),
    ("echocardiography study", "دراسة تخطيط صدى القلب"),
    ("electrocardiogram interpretation", "تفسير مخطط القلب"),
    ("holter monitoring", "مراقبة هولتر"),
    ("exercise stress test", "اختبار جهد"),
    ("heart valve replacement", "استبدال صمام قلبي"),
    ("pacemaker implantation", "زرع ناظمة قلبية"),
    ("implantable cardioverter defibrillator", "مزيل رجفان مقوم قابل للزرع"),
    ("atrial septal defect", "عيب الحاجز الأذيني"),
    ("ventricular septal defect", "عيب الحاجز البطيني"),
    ("patent ductus arteriosus", "بقاء القناة الشريانية"),
    ("tetralogy of fallot", "رباعية فالو"),
    ("coarctation of the aorta", "تضيق برزخ الأبهر"),
    ("aortic dissection", "تسلخ الأبهر"),
    ("aortic aneurysm", "أم الدم الأبهرية"),
    ("peripheral vascular disease", "داء وعائي محيطي"),
    ("intermittent claudication", "عرج متقطع"),
    ("acute limb ischemia", "إقفار طرف حاد"),
    ("chronic limb ischemia", "إقفار طرف مزمن"),
    ("varicose vein surgery", "جراحة الدوالي"),
    ("mechanical ventilation", "تهوية آلية"),
    ("noninvasive ventilation", "تهوية غير باضعة"),
    ("continuous positive airway pressure", "ضغط هوائي إيجابي مستمر"),
    ("positive end expiratory pressure", "ضغط نهاية الزفير الإيجابي"),
    ("tidal volume setting", "ضبط الحجم المدي"),
    ("oxygen saturation target", "هدف إشباع الأكسجين"),
    ("arterial blood gas interpretation", "تفسير غازات الدم الشرياني"),
    ("chest tube insertion", "إدخال مفجر صدري"),
    ("thoracentesis procedure", "بزل الصدر"),
    ("bronchoscopy procedure", "تنظير القصبات"),
    ("spirometry test", "اختبار قياس التنفس"),
    ("peak expiratory flow", "ذروة الجريان الزفيري"),
    ("forced vital capacity", "السعة الحيوية القسرية"),
    ("forced expiratory volume", "الحجم الزفيري القسري"),
    ("obstructive lung disease", "داء رئوي انسدادي"),
    ("restrictive lung disease", "داء رئوي تقييدي"),
    ("pulmonary function test", "اختبار وظيفة الرئة"),
    ("acute asthma exacerbation", "تفاقم ربو حاد"),
    ("copd exacerbation", "تفاقم الداء الرئوي المزمن"),
    ("community acquired pneumonia treatment", "علاج ذات الرئة المكتسبة في المجتمع"),
    ("hospital acquired pneumonia treatment", "علاج ذات الرئة المكتسبة في المستشفى"),
    ("tuberculosis treatment regimen", "نظام علاج السل"),
    ("pleural effusion drainage", "نزح الانصباب الجنبي"),
    ("pneumothorax management", "تدبير استرواح الصدر"),
    ("acute respiratory failure", "قصور تنفس حاد"),
    ("chronic respiratory failure", "قصور تنفس مزمن"),
    ("upper gastrointestinal bleeding", "نزف هضمي علوي"),
    ("lower gastrointestinal bleeding", "نزف هضمي سفلي"),
    ("peptic ulcer bleeding", "نزف قرحة هضمية"),
    ("esophageal variceal bleeding", "نزف دوالي مريئية"),
    ("endoscopic hemostasis", "إرقاء بالتنظير"),
    ("colonoscopy procedure", "تنظير القولون"),
    ("upper endoscopy", "تنظير هضمي علوي"),
    ("liver function interpretation", "تفسير وظائف الكبد"),
    ("ascites paracentesis", "بزل الحبن"),
    ("spontaneous bacterial peritonitis", "التهاب الصفاق الجرثومي العفوي"),
    ("hepatic encephalopathy management", "تدبير الاعتلال الدماغي الكبدي"),
    ("acute pancreatitis management", "تدبير التهاب البنكرياس الحاد"),
    ("gallstone disease", "داء الحصيات الصفراوية"),
    ("cholecystectomy procedure", "استئصال المرارة"),
    ("appendectomy procedure", "استئصال الزائدة"),
    ("bowel obstruction management", "تدبير انسداد الأمعاء"),
    ("inflammatory bowel disease treatment", "علاج داء الأمعاء الالتهابي"),
    ("irritable bowel syndrome management", "تدبير متلازمة الأمعاء الهيوجة"),
    ("celiac disease diagnosis", "تشخيص الداء الزلاقي"),
    ("acute kidney injury staging", "تصنيف الإصابة الكلوية الحادة"),
    ("chronic kidney disease staging", "تصنيف الداء الكلوي المزمن"),
    ("hemodialysis treatment", "علاج بالديال الدموي"),
    ("peritoneal dialysis", "ديال صفاقي"),
    ("renal replacement therapy", "علاج معوض للكلية"),
    ("urinary tract infection treatment", "علاج عدوى المسالك البولية"),
    ("nephrolithiasis management", "تدبير الحصيات الكلوية"),
    ("benign prostatic hyperplasia treatment", "علاج فرط تنسج البروستات الحميد"),
    ("prostate specific antigen", "مستضد البروستات النوعي"),
    ("urine dipstick", "شريط البول"),
    ("microscopic hematuria", "بيلة دموية مجهرية"),
    ("proteinuria measurement", "قياس البيلة البروتينية"),
    ("diabetic ketoacidosis management", "تدبير الحماض الكيتوني السكري"),
    ("hyperosmolar state management", "تدبير حالة فرط الأسمولية"),
    ("hypoglycemia management", "تدبير نقص سكر الدم"),
    ("insulin regimen", "نظام الإنسولين"),
    ("oral antidiabetic therapy", "علاج فموي خافض للسكر"),
    ("thyroid function test", "اختبار وظيفة الدرقية"),
    ("hyperthyroidism treatment", "علاج فرط الدرقية"),
    ("hypothyroidism treatment", "علاج قصور الدرقية"),
    ("adrenal insufficiency", "قصور الكظر"),
    ("cushing syndrome diagnosis", "تشخيص متلازمة كوشينغ"),
    ("osteoporosis treatment", "علاج هشاشة العظام"),
    ("dual energy x ray absorptiometry", "قياس امتصاص الأشعة السينية مزدوج الطاقة"),
    ("fracture immobilization", "تثبيت الكسر"),
    ("open reduction internal fixation", "رد مفتوح وتثبيت داخلي"),
    ("closed reduction", "رد مغلق"),
    ("external fixation", "تثبيت خارجي"),
    ("cast immobilization", "تثبيت بجبيرة"),
    ("compartment syndrome diagnosis", "تشخيص متلازمة الحيز"),
    ("anterior cruciate ligament", "الرباط الصليبي الأمامي"),
    ("posterior cruciate ligament", "الرباط الصليبي الخلفي"),
    ("medial collateral ligament", "الرباط الجانبي الإنسي"),
    ("lateral collateral ligament", "الرباط الجانبي الوحشي"),
    ("meniscus tear", "تمزق الهلالة"),
    ("rotator cuff tear", "تمزق الكفة المدورة"),
    ("hip fracture", "كسر الورك"),
    ("femoral neck fracture", "كسر عنق الفخذ"),
    ("intertrochanteric fracture", "كسر بين المدورين"),
    ("colles fracture", "كسر كولس"),
    ("scaphoid fracture", "كسر الزورقي"),
    ("spinal cord injury", "إصابة الحبل الشوكي"),
    ("cervical spine immobilization", "تثبيت العمود الرقبي"),
    ("intervertebral disc herniation", "فتق القرص بين الفقرات"),
    ("sciatica pain", "ألم عرق النسا"),
    ("osteoarthritis management", "تدبير الفصال العظمي"),
    ("rheumatoid arthritis treatment", "علاج التهاب المفاصل الرثياني"),
    ("gout management", "تدبير النقرس"),
    ("septic arthritis", "التهاب مفصل إنتاني"),
    ("solid tumor", "ورم صلب"),
    ("hematologic malignancy", "خباثة دموية"),
    ("tumor staging", "تصنيف مرحلة الورم"),
    ("tumor grading", "تصنيف درجة الورم"),
    ("tnm classification", "تصنيف الورم والعقد والنقائل"),
    ("metastatic disease", "داء نقائلي"),
    ("neoadjuvant therapy", "علاج مساعد قبل الجراحة"),
    ("adjuvant therapy", "علاج مساعد"),
    ("chemotherapy regimen", "نظام علاج كيميائي"),
    ("radiation therapy", "علاج إشعاعي"),
    ("targeted therapy", "علاج موجه"),
    ("immunotherapy treatment", "علاج مناعي"),
    ("palliative care", "رعاية تلطيفية"),
    ("performance status", "حالة الأداء"),
    ("tumor marker", "واسم ورمي"),
    ("biopsy interpretation", "تفسير الخزعة"),
    ("fine needle aspiration", "رشف بالإبرة الرفيعة"),
    ("core needle biopsy", "خزعة بالإبرة القاطعة"),
    ("excisional biopsy", "خزعة استئصالية"),
    ("margin status", "حالة الحواف"),
    ("sentinel lymph node", "عقدة لمفية حارسة"),
    ("breast conserving surgery", "جراحة محافظة على الثدي"),
    ("mastectomy procedure", "استئصال الثدي"),
    ("anemia workup", "استقصاء فقر الدم"),
    ("microcytic anemia", "فقر دم صغير الكريات"),
    ("macrocytic anemia", "فقر دم كبير الكريات"),
    ("normocytic anemia", "فقر دم سوي الكريات"),
    ("iron studies", "دراسات الحديد"),
    ("serum ferritin", "فيريتين المصل"),
    ("transferrin saturation", "إشباع الترانسفرين"),
    ("vitamin b12 level", "مستوى فيتامين ب12"),
    ("folate level", "مستوى الفولات"),
    ("coagulation profile", "مرتسم التخثر"),
    ("bleeding time", "زمن النزف"),
    ("clotting time", "زمن التخثر"),
    ("platelet count", "عدد الصفيحات"),
    ("white cell differential", "تعداد تفريقي للكريات البيض"),
    ("neutrophilia finding", "كثرة العدلات"),
    ("neutropenia finding", "قلة العدلات"),
    ("lymphocytosis finding", "كثرة اللمفاويات"),
    ("eosinophilia finding", "كثرة الحمضات"),
    ("blood film", "فيلم الدم"),
    ("bone marrow biopsy", "خزعة نقي العظم"),
    ("blood transfusion reaction", "تفاعل نقل الدم"),
    ("hemolytic transfusion reaction", "تفاعل نقل انحلالي"),
    ("febrile transfusion reaction", "تفاعل نقل حروري"),
    ("allergic transfusion reaction", "تفاعل نقل تحسسي"),
    ("massive transfusion protocol", "بروتوكول نقل ضخم"),
    ("sepsis bundle", "حزمة تدبير الإنتان"),
    ("septic shock management", "تدبير الصدمة الإنتانية"),
    ("fluid resuscitation protocol", "بروتوكول الإنعاش بالسوائل"),
    ("vasopressor therapy", "علاج رافع للتوتر الوعائي"),
    ("inotropic support", "دعم مقو للقلوصية"),
    ("central venous pressure", "ضغط وريدي مركزي"),
    ("mean arterial pressure", "ضغط شرياني وسطي"),
    ("shock index", "منسب الصدمة"),
    ("glasgow coma scale score", "درجة مقياس غلاسكو"),
    ("airway breathing circulation", "الطريق الهوائي والتنفس والدوران"),
    ("primary survey", "مسح أولي"),
    ("secondary survey", "مسح ثانوي"),
    ("cervical spine protection", "حماية العمود الرقبي"),
    ("trauma team activation", "تفعيل فريق الرضوح"),
    ("burn surface area", "مساحة سطح الحرق"),
    ("parkland formula", "صيغة باركلاند"),
    ("tetanus prophylaxis", "وقاية من الكزاز"),
    ("wound debridement", "إنضار الجرح"),
    ("abscess drainage", "نزح الخراج"),
    ("incision and drainage", "شق ونزح"),
    ("suture removal", "إزالة القطب"),
    ("sterile dressing", "ضماد عقيم"),
    ("hand hygiene moment", "لحظة نظافة اليدين"),
    ("standard precaution", "احتياط قياسي"),
    ("contact precaution", "احتياط التماس"),
    ("droplet precaution", "احتياط القطيرات"),
    ("airborne precaution", "احتياط الهواء"),
    ("personal protective equipment use", "استخدام معدات الوقاية"),
    ("needle stick injury", "إصابة وخز الإبرة"),
    ("post exposure prophylaxis", "وقاية بعد التعرض"),
    ("antibiotic stewardship", "ترشيد المضادات الحيوية"),
    ("empiric antibiotic therapy", "علاج مضاد حيوي تجريبي"),
    ("culture guided therapy", "علاج موجه بالزرع"),
    ("minimum inhibitory concentration value", "قيمة التركيز المثبط الأدنى"),
    ("gram stain result", "نتيجة تلوين غرام"),
    ("acid fast bacilli", "عصيات صامدة للحمض"),
    ("blood culture set", "مجموعة زرع الدم"),
    ("urine culture result", "نتيجة زرع البول"),
    ("sputum culture result", "نتيجة زرع القشع"),
    ("cerebrospinal fluid analysis", "تحليل السائل الدماغي الشوكي"),
    ("lumbar puncture", "بزل قطني"),
    ("opening pressure", "ضغط الفتح"),
    ("meningitis treatment", "علاج التهاب السحايا"),
    ("encephalitis diagnosis", "تشخيص التهاب الدماغ"),
    ("stroke pathway", "مسار السكتة"),
    ("thrombolysis window", "نافذة الحل الخثاري"),
    ("ischemic stroke management", "تدبير السكتة الإقفارية"),
    ("hemorrhagic stroke management", "تدبير السكتة النزفية"),
    ("transient ischemic attack workup", "استقصاء النوبة الإقفارية العابرة"),
    ("seizure management", "تدبير الاختلاج"),
    ("status epilepticus treatment", "علاج الحالة الصرعية"),
    ("migraine treatment", "علاج الشقيقة"),
    ("parkinson treatment", "علاج داء باركنسون"),
    ("dementia assessment", "تقييم الخرف"),
    ("depression screening", "تحري الاكتئاب"),
    ("suicide risk assessment", "تقييم خطر الانتحار"),
    ("mental status exam", "فحص الحالة العقلية"),
    ("antenatal visit", "زيارة رعاية الحمل"),
    ("fetal heart rate", "معدل قلب الجنين"),
    ("fundal height", "ارتفاع قاع الرحم"),
    ("gestational age assessment", "تقييم العمر الحملي"),
    ("preeclampsia management", "تدبير مقدمات الارتعاج"),
    ("eclampsia management", "تدبير الارتعاج"),
    ("postpartum hemorrhage management", "تدبير نزف ما بعد الولادة"),
    ("active management of third stage", "تدبير فعال للمرحلة الثالثة"),
    ("apgar score assessment", "تقييم درجة أبغار"),
    ("neonatal resuscitation", "إنعاش الوليد"),
    ("breastfeeding support", "دعم الرضاعة الطبيعية"),
    ("contraception counseling", "إرشاد منع الحمل"),
    ("pap smear screening", "تحري لطاخة باب"),
    ("visual acuity test", "اختبار حدة البصر"),
    ("intraocular pressure measurement", "قياس ضغط العين"),
    ("slit lamp examination", "فحص بالمصباح الشقي"),
    ("fundoscopy examination", "فحص قاع العين"),
    ("cataract surgery", "جراحة الساد"),
    ("glaucoma treatment", "علاج الزرق"),
    ("refractive error correction", "تصحيح الخطأ الانكساري"),
    ("otoscopy examination", "فحص منظار الأذن"),
    ("hearing assessment", "تقييم السمع"),
    ("pure tone audiometry", "قياس سمع بالنغمة الصافية"),
    ("tympanometry test", "اختبار قياس الطبلة"),
    ("acute otitis media treatment", "علاج التهاب الأذن الوسطى الحاد"),
    ("sinusitis treatment", "علاج التهاب الجيوب"),
    ("epistaxis management", "تدبير الرعاف"),
    ("dental caries prevention", "الوقاية من النخر السني"),
    ("root canal treatment steps", "خطوات معالجة قناة الجذر"),
    ("periodontal therapy", "علاج دواعم السن"),
    ("oral hygiene instruction plan", "خطة تعليم صحة الفم"),
    ("fluoride varnish", "طلاء الفلوريد"),
    ("local anesthetic technique", "تقنية التخدير الموضعي"),
    ("pharmacokinetic parameter", "وسيط حركية الدواء"),
    ("volume of distribution", "حجم التوزع"),
    ("clearance of drug", "تصفية الدواء"),
    ("elimination half life", "عمر الإطراح النصفي"),
    ("bioavailability fraction", "جزء التوافر الحيوي"),
    ("steady state level", "مستوى الحالة الثابتة"),
    ("loading dose calculation", "حساب جرعة التحميل"),
    ("maintenance dose calculation", "حساب جرعة الصيانة"),
    ("therapeutic index value", "قيمة الدليل العلاجي"),
    ("dose response curve", "منحنى الجرعة والاستجابة"),
    ("agonist drug", "دواء ناهض"),
    ("antagonist drug", "دواء مناهض"),
    ("partial agonist", "ناهض جزئي"),
    ("receptor affinity", "ألفة المستقبل"),
    ("receptor efficacy", "فعالية المستقبل"),
    ("adverse drug event", "حادثة دوائية ضارة"),
    ("drug drug interaction", "تداخل دواء مع دواء"),
    ("contraindication statement", "بيان مانع الاستعمال"),
    ("black box warning", "تحذير الصندوق الأسود"),
    ("generic substitution", "استبدال بالدواء الجنيس"),
    ("bioequivalent product", "مستحضر مكافئ حيويا"),
    ("controlled release formulation", "صيغة مديدة التحرر"),
    ("immediate release formulation", "صيغة فورية التحرر"),
    ("parenteral route", "طريق حقني"),
    ("enteral route", "طريق معوي"),
    ("topical route", "طريق موضعي"),
    ("inhalation route", "طريق استنشاقي"),
    ("first pass metabolism", "استقلاب العبور الأول"),
    ("cyp450 enzyme", "إنزيم السيتوكروم بي 450"),
    ("enzyme induction", "تحريض الإنزيم"),
    ("enzyme inhibition", "تثبيط الإنزيم"),
    ("renal dose adjustment", "تعديل الجرعة الكلوية"),
    ("hepatic dose adjustment", "تعديل الجرعة الكبدية"),
    ("pediatric dose calculation", "حساب جرعة الأطفال"),
    ("geriatric prescribing", "وصف دوائي للمسنين"),
    ("pregnancy drug category", "فئة الدواء في الحمل"),
    ("teratogenic effect", "أثر مشوه للجنين"),
    ("ototoxic drug", "دواء سام للأذن"),
    ("nephrotoxic drug", "دواء سام للكلية"),
    ("hepatotoxic drug", "دواء سام للكبد"),
    ("cardiotoxic drug", "دواء سام للقلب"),
    ("reinforced concrete beam design", "تصميم جائز خرسانة مسلحة"),
    ("singly reinforced beam", "جائز مسلح مفرد"),
    ("doubly reinforced beam", "جائز مسلح مزدوج"),
    ("flanged beam design", "تصميم جائز بشفة"),
    ("one way slab analysis", "تحليل بلاطة باتجاه واحد"),
    ("two way slab analysis", "تحليل بلاطة باتجاهين"),
    ("flat plate design", "تصميم بلاطة منبسطة"),
    ("punching shear reinforcement", "تسليح القص الثاقب"),
    ("short column interaction", "تفاعل العمود القصير"),
    ("slender column magnification", "تضخيم العمود النحيف"),
    ("footing design", "تصميم القاعدة"),
    ("combined footing design", "تصميم القاعدة المشتركة"),
    ("pile foundation design", "تصميم الأساس الوتدي"),
    ("retaining wall design", "تصميم الجدار الساند"),
    ("shear wall design", "تصميم جدار القص"),
    ("moment resisting frame design", "تصميم إطار مقاوم للعزوم"),
    ("load combination factor", "معامل تركيبة الأحمال"),
    ("serviceability check", "تحقق حد الخدمة"),
    ("deflection check", "تحقق السهم"),
    ("crack control", "ضبط التشقق"),
    ("development length check", "تحقق طول التثبيت"),
    ("lap splice length", "طول وصل التراكب"),
    ("concrete mix design", "تصميم الخلطة الخرسانية"),
    ("water cement ratio limit", "حد نسبة الماء إلى الأسمنت"),
    ("slump test result", "نتيجة اختبار الهبوط"),
    ("compressive strength test", "اختبار مقاومة الانضغاط"),
    ("splitting tensile test", "اختبار الشد بالفلق"),
    ("flexural strength test", "اختبار مقاومة الانحناء"),
    ("modulus of rupture", "معامل التمزق"),
    ("creep coefficient", "معامل الزحف"),
    ("shrinkage strain", "انفعال الانكماش"),
    ("durability requirement", "متطلب الديمومة"),
    ("exposure condition", "ظرف التعرض"),
    ("cover requirement", "متطلب الغطاء"),
    ("bar spacing", "تباعد القضبان"),
    ("stirrup design", "تصميم الكانة"),
    ("torsion design", "تصميم اللي"),
    ("bond stress", "إجهاد التماسك"),
    ("anchorage length", "طول التثبيت"),
    ("standard hook detail", "تفصيلة العكفة القياسية"),
    ("soil bearing capacity", "قدرة تحمل التربة"),
    ("allowable bearing pressure", "ضغط التحمل المسموح"),
    ("ultimate bearing capacity", "قدرة التحمل الحدية"),
    ("settlement calculation", "حساب الهبوط"),
    ("immediate settlement", "هبوط آني"),
    ("consolidation settlement", "هبوط الانضمام"),
    ("differential settlement", "هبوط تفاضلي"),
    ("factor of safety against sliding", "معامل أمان ضد الانزلاق"),
    ("factor of safety against overturning", "معامل أمان ضد الانقلاب"),
    ("active earth pressure coefficient", "معامل ضغط التربة الفعال"),
    ("passive earth pressure coefficient", "معامل ضغط التربة المقاوم"),
    ("rankine earth pressure", "ضغط التربة لرانكين"),
    ("coulomb earth pressure", "ضغط التربة لكولوم"),
    ("slope stability analysis", "تحليل استقرار المنحدر"),
    ("method of slices", "طريقة الشرائح"),
    ("bishop simplified method", "طريقة بيشوب المبسطة"),
    ("janbu method", "طريقة يانبو"),
    ("spencer method", "طريقة سبنسر"),
    ("liquefaction potential", "احتمال التمييع"),
    ("standard penetration resistance", "مقاومة الاختراق القياسي"),
    ("cone resistance", "مقاومة المخروط"),
    ("undrained strength", "مقاومة غير مصرفة"),
    ("drained strength", "مقاومة مصرفة"),
    ("mohr circle of stress", "دائرة مور للإجهاد"),
    ("principal stress direction", "اتجاه الإجهاد الرئيسي"),
    ("maximum shear stress plane", "مستوي إجهاد القص الأعظم"),
    ("strain compatibility", "توافق الانفعال"),
    ("stress strain relationship", "علاقة الإجهاد والانفعال"),
    ("hooke law region", "منطقة قانون هوك"),
    ("yield plateau", "عتبة الخضوع"),
    ("strain hardening region", "منطقة التقسية الانفعالية"),
    ("necking region", "منطقة التعنق"),
    ("ultimate load", "الحمل الحدي"),
    ("working load", "حمل التشغيل"),
    ("permissible stress", "إجهاد مسموح"),
    ("factor of safety value", "قيمة معامل الأمان"),
    ("euler critical load", "حمل أويلر الحرج"),
    ("slenderness limit", "حد النحافة"),
    ("effective length factor", "معامل الطول الفعال"),
    ("lateral torsional buckling check", "تحقق الانبعاج الجانبي الالتوائي"),
    ("local buckling check", "تحقق الانبعاج الموضعي"),
    ("plastic moment capacity", "سعة العزم اللدن"),
    ("shape factor value", "قيمة معامل الشكل"),
    ("collapse load factor", "معامل حمل الانهيار"),
    ("virtual work equation", "معادلة الشغل الافتراضي"),
    ("influence line ordinate", "إحداثي خط التأثير"),
    ("maximum moment envelope", "غلاف العزم الأعظم"),
    ("shear envelope", "غلاف القص"),
    ("moving load analysis", "تحليل الحمل المتحرك"),
    ("three moment equation", "معادلة العزوم الثلاثة"),
    ("moment distribution iteration", "تكرار توزيع العزوم"),
    ("stiffness coefficient", "معامل الجسوءة"),
    ("carry over moment", "عزم منقول"),
    ("fixed end moment value", "قيمة عزم الطرف المثبت"),
    ("degree of static indeterminacy", "درجة عدم التعيين السكوني"),
    ("degree of kinematic indeterminacy", "درجة عدم التعيين الحركي"),
    ("stable determinate structure", "منشأ مستقر معين"),
    ("unstable structure", "منشأ غير مستقر"),
    ("mechanism formation", "تشكل آلية"),
    ("open channel uniform flow", "جريان منتظم في قناة مفتوحة"),
    ("manning formula", "صيغة ماننغ"),
    ("chezy formula", "صيغة شيزي"),
    ("critical depth", "عمق حرج"),
    ("normal depth", "عمق منتظم"),
    ("hydraulic radius", "نصف القطر الهيدروليكي"),
    ("froude number value", "قيمة عدد فرود"),
    ("specific energy curve", "منحنى الطاقة النوعية"),
    ("hydraulic jump length", "طول القفزة الهيدروليكية"),
    ("sequant depth", "عمق مرافق"),
    ("weir coefficient", "معامل الهدار"),
    ("orifice coefficient", "معامل الفوهة"),
    ("venturi meter discharge", "تصريف مقياس فنتوري"),
    ("pitot tube velocity", "سرعة أنبوب بيتو"),
    ("bernoulli equation application", "تطبيق معادلة برنولي"),
    ("continuity equation application", "تطبيق معادلة الاستمرارية"),
    ("momentum equation application", "تطبيق معادلة الزخم"),
    ("darcy weisbach equation", "معادلة دارسي-فايسباخ"),
    ("minor loss coefficient", "معامل الفقد الموضعي"),
    ("pump head", "ضاغط المضخة"),
    ("pump power", "قدرة المضخة"),
    ("pump efficiency", "مردود المضخة"),
    ("cavitation check", "تحقق التكهف"),
    ("npsh available", "صافي ضغط السحب المتاح"),
    ("npsh required", "صافي ضغط السحب المطلوب"),
    ("affinity law", "قانون التشابه"),
    ("specific speed calculation", "حساب السرعة النوعية"),
    ("reynolds number calculation", "حساب عدد رينولدز"),
    ("laminar flow regime", "نظام الجريان الصفائحي"),
    ("turbulent flow regime", "نظام الجريان المضطرب"),
    ("boundary layer thickness", "سماكة الطبقة الحدية"),
    ("drag force calculation", "حساب قوة السحب"),
    ("lift force calculation", "حساب قوة الرفع"),
    ("mach number calculation", "حساب عدد ماخ"),
    ("compressible flow relation", "علاقة الجريان القابل للانضغاط"),
    ("isentropic flow relation", "علاقة الجريان متساوي الإنتروبيا"),
    ("normal shock", "موجة صدم ناظمية"),
    ("oblique shock", "موجة صدم مائلة"),
    ("nozzle flow", "جريان الفوهة"),
    ("diffuser flow", "جريان الناشر"),
    ("rankine cycle analysis", "تحليل دورة رانكن"),
    ("otto cycle analysis", "تحليل دورة أوتو"),
    ("diesel cycle analysis", "تحليل دورة ديزل"),
    ("brayton cycle analysis", "تحليل دورة برايتون"),
    ("refrigeration cycle analysis", "تحليل دورة التبريد"),
    ("coefficient of performance calculation", "حساب معامل الأداء"),
    ("carnot efficiency limit", "حد مردود كارنو"),
    ("entropy balance", "موازنة الإنتروبيا"),
    ("exergy analysis", "تحليل الإكسيرجي"),
    ("heat exchanger effectiveness", "فعالية المبادل الحراري"),
    ("lmtd method", "طريقة متوسط فرق الحرارة اللوغاريتمي"),
    ("ntu method", "طريقة عدد وحدات الانتقال"),
    ("fouling resistance", "مقاومة التوسخ"),
    ("overall heat transfer coefficient calculation", "حساب معامل انتقال الحرارة الكلي"),
    ("conduction shape factor", "معامل شكل التوصيل"),
    ("fin heat transfer", "انتقال الحرارة بالزعنفة"),
    ("radiation heat exchange", "تبادل الحرارة بالإشعاع"),
    ("view factor calculation", "حساب معامل الرؤية"),
    ("blackbody emissive power", "قدرة إصدار الجسم الأسود"),
    ("psychrometric process path", "مسار العملية على مخطط الهواء الرطب"),
    ("sensible heat ratio", "نسبة الحرارة المحسوسة"),
    ("cooling load", "حمل التبريد"),
    ("heating load", "حمل التدفئة"),
    ("infiltration load", "حمل التسرب الهوائي"),
    ("ventilation load", "حمل التهوية"),
    ("thermal comfort zone", "منطقة الراحة الحرارية"),
    ("relative humidity control", "ضبط الرطوبة النسبية"),
    ("dew point control", "ضبط نقطة الندى"),
    ("three phase power", "قدرة ثلاثية الطور"),
    ("line to line voltage", "جهد بين الخطوط"),
    ("line to neutral voltage", "جهد بين الخط والحيادي"),
    ("power factor improvement", "تحسين معامل القدرة"),
    ("capacitor sizing", "تحجيم المكثف"),
    ("transformer equivalent circuit", "دارة المحول المكافئة"),
    ("transformer voltage regulation", "تنظيم جهد المحول"),
    ("transformer efficiency calculation", "حساب مردود المحول"),
    ("open circuit test result", "نتيجة اختبار الدارة المفتوحة"),
    ("short circuit test result", "نتيجة اختبار القصر"),
    ("induction motor torque", "عزم المحرك الحثي"),
    ("induction motor slip", "انزلاق المحرك الحثي"),
    ("synchronous speed calculation", "حساب السرعة التزامنية"),
    ("starting current", "تيار الإقلاع"),
    ("full load current", "تيار الحمل الكامل"),
    ("star delta starting", "إقلاع نجمة مثلث"),
    ("direct online starting", "إقلاع مباشر"),
    ("fault level", "مستوى العطل"),
    ("short circuit current", "تيار القصر"),
    ("symmetrical component analysis", "تحليل المركبات المتماثلة"),
    ("sequence network", "شبكة التتابع"),
    ("load flow study", "دراسة سريان الأحمال"),
    ("newton raphson method for load flow", "طريقة نيوتن رافسون لسريان الأحمال"),
    ("gauss seidel method for load flow", "طريقة غاوس سايدل لسريان الأحمال"),
    ("economic load dispatch", "توزيع اقتصادي للأحمال"),
    ("transient stability study", "دراسة الاستقرار العابر"),
    ("swing equation solution", "حل معادلة التأرجح"),
    ("critical clearing angle", "زاوية الفصل الحرجة"),
    ("equal area criterion application", "تطبيق معيار المساحات المتساوية"),
    ("relay coordination", "تنسيق المرحلات"),
    ("overcurrent protection", "حماية زيادة التيار"),
    ("differential protection", "حماية تفاضلية"),
    ("distance protection", "حماية مسافية"),
    ("circuit breaker selection", "اختيار قاطع الدائرة"),
    ("arc interruption", "قطع القوس"),
    ("insulation level", "مستوى العزل"),
    ("surge arrester selection", "اختيار مانعة الصواعق"),
    ("grounding system design", "تصميم منظومة التأريض"),
    ("step voltage", "جهد الخطوة"),
    ("touch voltage", "جهد اللمس"),
    ("corona inception", "بدء الهالة"),
    ("sag and tension", "الارتخاء والشد"),
    ("string efficiency calculation", "حساب كفاءة سلسلة العوازل"),
    ("per unit calculation", "حساب الوحدة النسبية"),
    ("base impedance", "ممانعة الأساس"),
    ("base current", "تيار الأساس"),
    ("base voltage", "جهد الأساس"),
    ("bus admittance formation", "تكوين مصفوفة مسايرة القضبان"),
    ("jacobian matrix of load flow", "مصفوفة يعقوبية لسريان الأحمال"),
    ("fast fourier transform application", "تطبيق تحويل فورييه السريع"),
    ("z transform of sequence", "تحويل زد للمتتالية"),
    ("laplace transform of function", "تحويل لابلاس للدالة"),
    ("inverse laplace transform method", "طريقة تحويل لابلاس العكسي"),
    ("convolution integral", "تكامل الالتفاف"),
    ("impulse response of system", "استجابة النظام النبضية"),
    ("step response of system", "استجابة النظام للخطوة"),
    ("frequency response of system", "استجابة النظام الترددية"),
    ("bode magnitude plot", "مخطط مقدار بود"),
    ("bode phase plot", "مخطط طور بود"),
    ("gain margin measurement", "قياس هامش الكسب"),
    ("phase margin measurement", "قياس هامش الطور"),
    ("nyquist stability criterion", "معيار استقرار نيكويست"),
    ("routh hurwitz table", "جدول روث هيرويتز"),
    ("root locus sketch", "رسم المحل الهندسي للجذور"),
    ("pid controller tuning", "ضبط المتحكم التناسبي التكاملي التفاضلي"),
    ("steady state error calculation", "حساب خطأ الحالة المستقرة"),
    ("rise time measurement", "قياس زمن الصعود"),
    ("settling time measurement", "قياس زمن الاستقرار"),
    ("overshoot percentage", "نسبة التجاوز"),
    ("damping ratio calculation", "حساب نسبة التخميد"),
    ("natural frequency calculation", "حساب التردد الطبيعي"),
    ("state space model", "نموذج فضاء الحالة"),
    ("controllability test", "اختبار قابلية التحكم"),
    ("observability test", "اختبار قابلية الرصد"),
    ("state feedback design", "تصميم تغذية راجعة للحالة"),
    ("observer gain", "كسب الراصد"),
    ("pole placement design", "تصميم تعيين الأقطاب"),
    ("sampling theorem application", "تطبيق مبرهنة أخذ العينات"),
    ("aliasing prevention", "منع التراكب الطيفي"),
    ("quantization noise", "ضوضاء التكميم"),
    ("signal to noise ratio calculation", "حساب نسبة الإشارة إلى الضوضاء"),
    ("modulation index calculation", "حساب دليل التعديل"),
    ("am waveform", "شكل موجة التعديل السعوي"),
    ("fm waveform", "شكل موجة التعديل الترددي"),
    ("pcm system", "نظام التعديل النبضي المرمز"),
    ("delta modulation", "تعديل دلتا"),
    ("line coding", "ترميز الخط"),
    ("crc checksum", "مجموع فحص التكرار الدوري"),
    ("hamming distance", "مسافة هامنغ"),
    ("shannon capacity formula", "صيغة سعة شانون"),
    ("osi layer function", "وظيفة طبقة نموذج الاتصال"),
    ("tcp handshake", "مصافحة بروتوكول التحكم بالنقل"),
    ("ip addressing", "عنونة بروتوكول الإنترنت"),
    ("subnet calculation", "حساب الشبكة الفرعية"),
    ("routing table", "جدول التوجيه"),
    ("dns resolution", "تحليل أسماء النطاقات"),
    ("http request", "طلب بروتوكول نقل النص"),
    ("tls handshake", "مصافحة أمن طبقة النقل"),
    ("sql query optimization", "تحسين استعلام لغة الاستعلامات"),
    ("database normalization step", "خطوة تطبيع قاعدة البيانات"),
    ("entity relationship mapping", "تحويل مخطط الكيانات"),
    ("transaction acid property", "خاصية أسيد للمعاملة"),
    ("concurrency control", "ضبط التزامن"),
    ("deadlock handling", "معالجة التوقف التام"),
    ("page replacement policy", "سياسة استبدال الصفحات"),
    ("cpu scheduling algorithm", "خوارزمية جدولة المعالج"),
    ("process synchronization", "تزامن العمليات"),
    ("memory fragmentation", "تجزؤ الذاكرة"),
    ("compiler optimization", "تحسين المترجم"),
    ("lexical analyzer", "محلل معجمي"),
    ("syntax analyzer", "محلل نحوي"),
    ("semantic analyzer", "محلل دلالي"),
    ("object oriented principle", "مبدأ كائني التوجه"),
    ("solid design principle", "مبدأ تصميم سولد"),
    ("unit test case", "حالة اختبار وحدة"),
    ("regression test suite", "حزمة اختبار الانحدار"),
    ("agile sprint", "سبرنت أجايل"),
    ("scrum backlog", "سجل سكرم"),
    ("version control workflow", "سير عمل إدارة الإصدارات"),
    ("continuous integration pipeline", "خط التكامل المستمر"),
    ("machine learning pipeline", "خط تعلم الآلة"),
    ("training validation split", "تقسيم التدريب والتحقق"),
    ("cross validation fold", "طية التحقق المتقاطع"),
    ("confusion matrix calculation", "حساب مصفوفة الالتباس"),
    ("precision recall curve", "منحنى الإحكام والاستدعاء"),
    ("roc auc score", "درجة المساحة تحت منحنى روك"),
    ("overfitting prevention", "منع فرط الملاءمة"),
    ("feature engineering", "هندسة السمات"),
    ("gradient descent update", "تحديث نزول التدرج"),
    ("backpropagation step", "خطوة الانتشار العكسي"),
    ("activation function choice", "اختيار دالة التنشيط"),
    ("loss function choice", "اختيار دالة الخسارة"),
    ("hyperparameter tuning", "ضبط الوسائط الفائقة"),
    ("bias variance decomposition", "تفكيك الانحياز والتباين"),
    ("principal component", "مكون رئيس"),
    ("k means objective", "دالة هدف المتوسطات"),
    ("support vector margin", "هامش المتجه الداعم"),
    ("decision tree split", "تقسيم شجرة القرار"),
    ("random forest ensemble", "تجميع الغابة العشوائية"),
    ("neural network layer", "طبقة الشبكة العصبية"),
    ("convolution operation", "عملية التفاف"),
    ("pooling operation", "عملية التجميع"),
    ("attention weight", "وزن الانتباه"),
    ("word embedding vector", "متجه تضمين الكلمة"),
    ("natural language pipeline", "خط معالجة اللغة الطبيعية"),
    ("computer vision pipeline", "خط الرؤية الحاسوبية"),
    ("reinforcement learning reward", "مكافأة التعلم التعزيزي"),
    ("markov decision process", "عملية قرار ماركوف"),
    ("q learning update", "تحديث تعلم كيو"),
    ("policy gradient", "تدرج السياسة"),
]
