"""مصطلحات الهيدرولوجيا والموارد المائية."""

from __future__ import annotations

HYDRO_ENTRIES: list[tuple[str, str]] = [
    # ── الدورة والموازنة ──
    ("engineering hydrology", "الهيدرولوجيا الهندسية"),
    ("surface water hydrology", "هيدرولوجيا المياه السطحية"),
    ("groundwater hydrology", "هيدرولوجيا المياه الجوفية"),
    ("hydrologic cycle of water", "الدورة الهيدرولوجية للماء"),
    ("hydrologic water balance", "الموازنة المائية الهيدرولوجية"),
    ("catchment water balance", "موازنة الحوض المائية"),
    ("water balance equation", "معادلة الموازنة المائية"),
    ("change in storage", "تغير التخزين"),
    ("hydrologic year", "السنة الهيدرولوجية"),
    ("water year of record", "السنة المائية للسجل"),
    ("hydrometeorology of storms", "أرصاد العواصف الهيدرولوجية"),
    ("hydrometry of streams", "القياس المائي للمجاري"),
    ("hydrometric network", "الشبكة الهيدرومترية"),
    # ── الهطول ──
    ("point rainfall measurement", "قياس المطر النقطي"),
    ("areal rainfall estimation", "تقدير المطر المساحي"),
    ("rainfall depth of storm", "عمق مطر العاصفة"),
    ("rainfall duration of storm", "مدة مطر العاصفة"),
    ("design rainfall depth", "عمق المطر التصميمي"),
    ("recording rain gauge", "مقياس مطر مسجل"),
    ("nonrecording rain gauge", "مقياس مطر غير مسجل"),
    ("tipping bucket rain gauge", "مقياس مطر ذو الدلو القلاب"),
    ("weighing type rain gauge", "مقياس مطر وزني"),
    ("radar rainfall estimate", "تقدير المطر بالرادار"),
    ("satellite rainfall estimate", "تقدير المطر بالأقمار"),
    ("thiessen polygon method", "طريقة مضلع ثيسن"),
    ("isohyetal method of rainfall", "طريقة خطوط تساوي المطر"),
    ("arithmetic mean rainfall", "متوسط المطر الحسابي"),
    ("normal ratio method", "طريقة النسبة الطبيعية"),
    ("missing rainfall data", "بيانات المطر المفقودة"),
    ("double mass curve", "منحنى الكتلة المضاعفة"),
    ("consistency of rainfall record", "اتساق سجل المطر"),
    ("depth duration curve", "منحنى العمق-المدة"),
    ("intensity duration curve", "منحنى الشدة-المدة"),
    ("depth area duration analysis", "تحليل العمق-المساحة-المدة"),
    ("intensity duration frequency curve", "منحنى الشدة-المدة-التكرار"),
    ("areal reduction factor", "معامل التخفيض المساحي"),
    ("probable maximum precipitation", "الهطول الأعظم المحتمل"),
    ("storm transposition method", "طريقة نقل العاصفة"),
    ("moisture maximization of storm", "تعظيم رطوبة العاصفة"),
    ("design storm hyetograph", "مخطط هطول العاصفة التصميمية"),
    ("alternating block method", "طريقة الكتل المتناوبة"),
    ("triangular hyetograph", "مخطط هطول مثلثي"),
    ("chicago storm method", "طريقة عاصفة شيكاغو"),
    ("station year method", "طريقة محطة-سنة"),
    ("mann kendall trend test", "اختبار اتجاه مان-كندال"),
    # ── الفواقد والرشح والتبخر ──
    ("interception loss of rainfall", "فقد اعتراض المطر"),
    ("canopy interception storage", "تخزين اعتراض الغطاء النباتي"),
    ("throughfall of rainfall", "المطر النافذ من الغطاء"),
    ("stemflow of rainfall", "جريان المطر على الساق"),
    ("depression storage of rainfall", "تخزين المنخفضات للمطر"),
    ("initial abstraction of rainfall", "الفقد الابتدائي للمطر"),
    ("rainfall excess depth", "عمق فائض المطر"),
    ("phi index method", "طريقة دليل فاي"),
    ("w index of infiltration", "دليل دبليو للرشح"),
    ("constant loss rate", "معدل فقد ثابت"),
    ("infiltration rate of soil", "معدل رشح التربة"),
    ("cumulative infiltration depth", "عمق الرشح التراكمي"),
    ("horton infiltration equation", "معادلة هورتون للرشح"),
    ("green ampt infiltration", "رشح غرين-أمبت"),
    ("philip infiltration equation", "معادلة فيليب للرشح"),
    ("wetting front advance", "تقدم جبهة الابتلال"),
    ("time to ponding", "زمن بدء التبرك"),
    ("sorptivity of soil", "امتصاصية التربة"),
    ("saturated hydraulic conductivity", "الناقلية الهيدروليكية المشبعة"),
    ("richards equation of flow", "معادلة ريتشاردز للجريان"),
    ("soil water retention curve", "منحنى احتباس ماء التربة"),
    ("field capacity moisture", "رطوبة السعة الحقلية"),
    ("permanent wilting point", "نقطة الذبول الدائم"),
    ("available water capacity", "سعة الماء المتاح"),
    ("soil moisture deficit", "عجز رطوبة التربة"),
    ("potential evaporation rate", "معدل التبخر الكامن"),
    ("actual evaporation rate", "معدل التبخر الفعلي"),
    ("class a evaporation pan", "حوض التبخر من الصنف أ"),
    ("pan coefficient of evaporation", "معامل حوض التبخر"),
    ("penman evaporation equation", "معادلة بنمان للتبخر"),
    ("penman monteith equation", "معادلة بنمان-مونتيث"),
    ("priestley taylor method", "طريقة بريستلي-تايلور"),
    ("hargreaves evapotranspiration", "تبخر ونتح هارغريفز"),
    ("thornthwaite method", "طريقة ثورنثويت"),
    ("blaney criddle method", "طريقة بلاني-كريدل"),
    ("reference evapotranspiration", "التبخر والنتح المرجعي"),
    ("crop evapotranspiration rate", "معدل تبخر ونتح المحصول"),
    ("crop coefficient of water", "معامل المحصول المائي"),
    ("energy balance method", "طريقة ميزان الطاقة"),
    ("mass transfer method", "طريقة انتقال الكتلة"),
    # ── الحوض والجريان ──
    ("drainage basin characteristics", "خصائص حوض التصريف"),
    ("catchment area of basin", "مساحة مستجمع الحوض"),
    ("watershed divide line", "خط تقسيم المياه"),
    ("stream network of basin", "شبكة مجاري الحوض"),
    ("stream order of channel", "رتبة المجرى"),
    ("bifurcation ratio of streams", "نسبة تفرع المجاري"),
    ("drainage density of basin", "كثافة تصريف الحوض"),
    ("stream frequency of basin", "تكرار مجاري الحوض"),
    ("form factor of basin", "معامل شكل الحوض"),
    ("compactness coefficient of basin", "معامل اندماج الحوض"),
    ("elongation ratio of basin", "نسبة استطالة الحوض"),
    ("circulatory ratio of basin", "نسبة استدارة الحوض"),
    ("relief ratio of basin", "نسبة تضاريس الحوض"),
    ("ruggedness number of basin", "رقم وعورة الحوض"),
    ("main stream length", "طول المجرى الرئيسي"),
    ("basin average slope", "الميل المتوسط للحوض"),
    ("channel bed slope", "ميل قاع المجرى"),
    ("overland flow length", "طول الجريان فوق الأرض"),
    ("hypsometric curve of basin", "المنحنى الهبسومتري للحوض"),
    ("dendritic drainage pattern", "نمط تصريف شجري"),
    ("trellis drainage pattern", "نمط تصريف متشابك"),
    ("radial drainage pattern", "نمط تصريف شعاعي"),
    ("perennial stream flow", "جريان مجرى دائم"),
    ("intermittent stream flow", "جريان مجرى متقطع"),
    ("ephemeral stream flow", "جريان مجرى موسمي قصير"),
    ("gaining stream reach", "وصول مجرى كاسب"),
    ("losing stream reach", "وصول مجرى فاقد"),
    ("overland flow runoff", "جريان سطحي فوق الأرض"),
    ("interflow through soil", "جريان بيني خلال التربة"),
    ("subsurface stormflow", "جريان عاصفة تحت سطحي"),
    ("direct runoff volume", "حجم الجريان المباشر"),
    ("baseflow of stream", "الجريان القاعدي للمجرى"),
    ("runoff depth of storm", "عمق جريان العاصفة"),
    ("runoff volume of storm", "حجم جريان العاصفة"),
    ("runoff ratio of basin", "نسبة جريان الحوض"),
    ("peak discharge of flood", "التصريف الأقصى للفيضان"),
    ("bankfull discharge of channel", "تصريف امتلاء ضفاف المجرى"),
    # ── المخططات المائية ──
    ("rainfall hyetograph of storm", "مخطط هطول العاصفة"),
    ("stage hydrograph of stream", "مخطط منسوب المجرى"),
    ("discharge hydrograph of stream", "مخطط تصريف المجرى"),
    ("flood hydrograph of basin", "مخطط فيضان الحوض"),
    ("direct runoff hydrograph", "مخطط الجريان المباشر"),
    ("rising limb of hydrograph", "طرف الصعود في المخطط المائي"),
    ("recession limb of hydrograph", "طرف الانحسار في المخطط المائي"),
    ("peak of hydrograph", "ذروة المخطط المائي"),
    ("time to peak of hydrograph", "زمن الذروة للمخطط المائي"),
    ("lag time of basin", "زمن تخلف الحوض"),
    ("baseflow separation method", "طريقة فصل الجريان القاعدي"),
    ("master recession curve", "منحنى الانحسار الرئيسي"),
    ("unit hydrograph theory", "نظرية المخطط المائي الواحدي"),
    ("instantaneous unit hydrograph", "المخطط المائي الواحدي اللحظي"),
    ("synthetic unit hydrograph", "مخطط مائي واحدي تركيبي"),
    ("dimensionless unit hydrograph", "مخطط واحدي لا بعدي"),
    ("s hydrograph method", "طريقة مخطط إس"),
    ("hydrograph convolution", "التفاف المخطط المائي"),
    ("snyder synthetic hydrograph", "مخطط سنايدر التركيبي"),
    ("scs triangular hydrograph", "المخطط المثلثي لطريقة المنحنى"),
    ("clark unit hydrograph", "مخطط كلارك الواحدي"),
    ("nash cascade model", "نموذج سلسلة ناش"),
    ("time area histogram", "مدرج الزمن-المساحة"),
    ("isochrone map of basin", "خريطة خطوط تساوي الزمن"),
    ("distribution graph method", "طريقة مخطط التوزيع"),
    ("scs curve number method", "طريقة رقم المنحنى"),
    ("curve number of catchment", "رقم منحنى المستجمع"),
    ("hydrologic soil group", "المجموعة الهيدرولوجية للتربة"),
    ("antecedent moisture condition", "حالة الرطوبة السابقة"),
    ("potential maximum retention", "الاحتباس الأعظم المحتمل"),
    ("initial abstraction ratio", "نسبة الفقد الابتدائي"),
    ("impervious area fraction", "نسبة المساحة الكتيمة"),
    ("directly connected impervious area", "المساحة الكتيمة المتصلة مباشرة"),
    ("modified rational method", "الطريقة المنطقية المعدلة"),
    ("kirpich time of concentration", "زمن التركيز بصيغة كيربيش"),
    ("scs lag equation", "معادلة تخلف طريقة المنحنى"),
    ("time of travel in channel", "زمن الانتقال في المجرى"),
    ("inlet time of urban basin", "زمن المدخل للحوض الحضري"),
    # ── التكرار والفيضان ──
    ("flood frequency analysis", "تحليل تكرار الفيضان"),
    ("annual maximum series", "سلسلة القيم العظمى السنوية"),
    ("partial duration series", "سلسلة المدد الجزئية"),
    ("return period of flood", "فترة عودة الفيضان"),
    ("exceedance probability of flood", "احتمال تجاوز الفيضان"),
    ("plotting position formula", "صيغة موقع الرسم"),
    ("weibull plotting position", "موقع رسم وايبول"),
    ("gumbel extreme value distribution", "توزيع غامبل للقيم المتطرفة"),
    ("log pearson type three", "لوغاريتم بيرسون النوع الثالث"),
    ("lognormal flood distribution", "التوزيع اللوغاريتمي الطبيعي للفيضان"),
    ("generalized extreme value distribution", "توزيع القيم المتطرفة المعمم"),
    ("method of moments fitting", "ملاءمة بطريقة العزوم"),
    ("l moment flood analysis", "تحليل الفيضان بعزوم إل"),
    ("regional flood frequency", "تكرار الفيضان الإقليمي"),
    ("index flood method", "طريقة فيضان الدليل"),
    ("skew coefficient of floods", "معامل التواء الفيضانات"),
    ("confidence limits of flood", "حدود الثقة للفيضان"),
    ("hydrologic risk of design", "الخطر الهيدرولوجي للتصميم"),
    ("encounter probability of flood", "احتمال مصادفة الفيضان"),
    ("design return period", "فترة العودة التصميمية"),
    ("standard project flood", "فيضان المشروع القياسي"),
    ("probable maximum flood hydrograph", "مخطط الفيضان الأعظم المحتمل"),
    ("inflow design flood", "فيضان التصميم الداخل"),
    ("spillway design flood", "فيضان تصميم المفيض"),
    ("dam break flood wave", "موجة فيضان انهيار السد"),
    ("floodplain inundation map", "خريطة غمر السهل الفيضي"),
    ("flood risk mapping", "رسم خطر الفيضان"),
    # ── التتبع والخزانات ──
    ("flood routing through channel", "تتبع الفيضان عبر المجرى"),
    ("hydrologic reservoir routing", "التتبع الهيدرولوجي للخزان"),
    ("muskingum routing method", "طريقة تتبع ماسكنغم"),
    ("muskingum cunge method", "طريقة ماسكنغم-كونج"),
    ("level pool routing", "تتبع منسوب الخزان الثابت"),
    ("storage indication method", "طريقة دلالة التخزين"),
    ("inflow hydrograph of reservoir", "مخطط الجريان الداخل للخزان"),
    ("outflow hydrograph of reservoir", "مخطط الجريان الخارج من الخزان"),
    ("kinematic wave routing", "تتبع الموجة الحركية"),
    ("dynamic wave routing", "تتبع الموجة الديناميكية"),
    ("diffusion wave approximation", "تقريب الموجة الانتشارية"),
    ("saint venant equations", "معادلات سان فينان"),
    ("continuity equation of flow", "معادلة استمرارية الجريان"),
    ("live storage of reservoir", "التخزين الحي للخزان"),
    ("dead storage of reservoir", "التخزين الميت للخزان"),
    ("flood control storage", "تخزين السيطرة على الفيضان"),
    ("conservation storage of reservoir", "تخزين الحفظ في الخزان"),
    ("surcharge storage of reservoir", "التخزين الإضافي للخزان"),
    ("reservoir rule curve", "منحنى تشغيل الخزان"),
    ("mass curve of reservoir", "منحنى كتلة الخزان"),
    ("rippl mass diagram", "مخطط ريبل للكتلة"),
    ("sequent peak algorithm", "خوارزمية الذروة المتتابعة"),
    ("firm yield of reservoir", "العطاء الثابت للخزان"),
    ("reservoir operation policy", "سياسة تشغيل الخزان"),
    ("evaporation loss from reservoir", "فقد التبخر من الخزان"),
    ("reservoir sedimentation rate", "معدل ترسيب الخزان"),
    ("trap efficiency of reservoir", "كفاءة احتجاز الخزان"),
    ("brune trap efficiency curve", "منحنى برون لكفاءة الاحتجاز"),
    ("useful life of reservoir", "العمر المفيد للخزان"),
    ("service spillway of dam", "مفيض الخدمة للسد"),
    ("emergency spillway of dam", "مفيض الطوارئ للسد"),
    ("auxiliary spillway of dam", "المفيض المساعد للسد"),
    ("ungated spillway crest", "عتبة مفيض بلا بوابات"),
    ("gated spillway operation", "تشغيل المفيض ذي البوابات"),
    ("spillway rating curve", "منحنى تصريف المفيض"),
    ("freeboard of embankment", "الارتفاع الحر للردم"),
    ("outlet works of dam", "أعمال مخرج السد"),
    # ── القياس ──
    ("streamflow gauging station", "محطة قياس جريان المجرى"),
    ("stage discharge rating curve", "منحنى منسوب-تصريف"),
    ("velocity area method", "طريقة السرعة-المساحة"),
    ("current meter measurement", "قياس بمقياس السرعة"),
    ("dilution gauging method", "طريقة القياس بالتخفيف"),
    ("slope area method", "طريقة الميل-المساحة"),
    ("float method of discharge", "طريقة العوامة للتصريف"),
    ("acoustic doppler profiler", "مقطع دوبلر الصوتي"),
    ("staff gauge reading", "قراءة مقياس المنسوب"),
    ("water level recorder", "مسجل منسوب الماء"),
    ("shifting control of rating", "تحكم متغير لمنحنى التصريف"),
    ("flow duration curve", "منحنى مدة الجريان"),
    ("seven day low flow", "الجريان المنخفض لسبعة أيام"),
    ("low flow frequency analysis", "تحليل تكرار الجريان المنخفض"),
    # ── الهيدرولوجيا الحضرية ──
    ("urban stormwater hydrology", "هيدرولوجيا مياه العواصف الحضرية"),
    ("stormwater management practice", "ممارسة إدارة مياه العواصف"),
    ("detention basin storage", "تخزين حوض الاحتجاز"),
    ("retention pond storage", "تخزين بركة الاحتباس"),
    ("peak flow attenuation", "تخفيف ذروة الجريان"),
    ("runoff volume reduction", "تخفيض حجم الجريان"),
    ("water quality volume", "حجم جودة المياه"),
    ("first flush of runoff", "الدفقة الأولى للجريان"),
    ("best management practice", "أفضل ممارسة إدارية"),
    ("bioswale for stormwater", "مسيل حيوي لمياه العواصف"),
    ("infiltration trench design", "تصميم خندق الرشح"),
    ("permeable pavement system", "نظام الرصف النفاذ"),
    ("green roof hydrology", "هيدرولوجيا السطح الأخضر"),
    ("rainwater harvesting system", "منظومة حصاد مياه المطر"),
    ("low impact development", "التطوير منخفض الأثر"),
    ("storm sewer design", "تصميم مجرى العواصف"),
    # ── النماذج ──
    ("rainfall runoff model", "نموذج المطر-الجريان"),
    ("lumped hydrologic model", "نموذج هيدرولوجي مجمع"),
    ("distributed hydrologic model", "نموذج هيدرولوجي موزع"),
    ("conceptual hydrologic model", "نموذج هيدرولوجي مفاهيمي"),
    ("physically based hydrologic model", "نموذج هيدرولوجي فيزيائي الأساس"),
    ("event based hydrologic model", "نموذج هيدرولوجي قائم على الحدث"),
    ("continuous hydrologic simulation", "محاكاة هيدرولوجية مستمرة"),
    ("hec hydrologic modeling system", "نظام النمذجة الهيدرولوجية"),
    ("soil and water assessment tool", "أداة تقييم التربة والماء"),
    ("storm water management model", "نموذج إدارة مياه العواصف"),
    ("sacramento soil moisture model", "نموذج رطوبة تربة ساكرامنتو"),
    ("tank model of runoff", "نموذج الخزانات للجريان"),
    ("linear reservoir model", "نموذج الخزان الخطي"),
    ("calibration of hydrologic model", "معايرة النموذج الهيدرولوجي"),
    ("validation of hydrologic model", "تحقق النموذج الهيدرولوجي"),
    ("sensitivity analysis of model", "تحليل حساسية النموذج"),
    ("nash sutcliffe efficiency", "كفاءة ناش-ساتكليف"),
    ("percent bias of simulation", "الانحياز المئوي للمحاكاة"),
    ("observed discharge hydrograph", "مخطط التصريف المرصود"),
    ("simulated discharge hydrograph", "مخطط التصريف المحاكى"),
    ("split sample calibration", "معايرة العينة المقسومة"),
    # ── الجفاف ──
    ("meteorological drought index", "دليل الجفاف المناخي"),
    ("hydrological drought of stream", "الجفاف الهيدرولوجي للمجرى"),
    ("agricultural drought index", "دليل الجفاف الزراعي"),
    ("drought duration and severity", "مدة الجفاف وشدته"),
    ("standardized precipitation index", "دليل الهطول المعياري"),
    ("palmer drought severity index", "دليل بالمر لشدة الجفاف"),
    ("aridity index of climate", "دليل الجفاف المناخي"),
    ("environmental flow requirement", "متطلب الجريان البيئي"),
    ("instream flow need", "حاجة الجريان داخل المجرى"),
    # ── الثلج ──
    ("snow hydrology of basin", "هيدرولوجيا الثلج للحوض"),
    ("snow water equivalent", "المكافئ المائي للثلج"),
    ("snowmelt runoff hydrograph", "مخطط جريان ذوبان الثلج"),
    ("degree day factor of melt", "معامل درجة-اليوم للذوبان"),
    ("rain on snow event", "حدث مطر على الثلج"),
    ("snowpack accumulation", "تراكم الغطاء الثلجي"),
    ("ablation of snowpack", "اجتثاث الغطاء الثلجي"),
    # ── المياه الجوفية ──
    ("hydraulic head of aquifer", "الضاغط الهيدروليكي للخزان"),
    ("pressure head of water", "ضاغط ضغط الماء"),
    ("elevation head of water", "ضاغط ارتفاع الماء"),
    ("hydraulic gradient of flow", "الميل الهيدروليكي للجريان"),
    ("darcy law of seepage", "قانون دارسي للتسرب"),
    ("darcy velocity of flow", "سرعة دارسي للجريان"),
    ("seepage velocity of groundwater", "سرعة تسرب المياه الجوفية"),
    ("effective porosity of aquifer", "المسامية الفعالة للخزان"),
    ("specific retention of aquifer", "الاحتباس النوعي للخزان"),
    ("specific storage of aquifer", "التخزين النوعي للخزان"),
    ("storativity of confined aquifer", "معامل تخزين الخزان المحصور"),
    ("transmissivity of aquifer", "ناقلية الخزان الجوفي"),
    ("anisotropy of hydraulic conductivity", "تباين الناقلية الهيدروليكية"),
    ("heterogeneity of aquifer", "عدم تجانس الخزان"),
    ("aquitard confining layer", "طبقة حاجزة ضعيفة النفاذية"),
    ("aquiclude confining bed", "طبقة حاجزة كتيمة"),
    ("perched water table", "منسوب ماء معلق"),
    ("potentiometric surface map", "خريطة سطح الجهد"),
    ("piezometric head contour", "كنتور الضاغط البيزومتري"),
    ("leaky confined aquifer", "خزان محصور راشح"),
    ("artesian flowing well", "بئر ارتوازي متدفق"),
    ("steady radial flow to well", "جريان شعاعي مستقر نحو البئر"),
    ("unsteady radial flow to well", "جريان شعاعي غير مستقر نحو البئر"),
    ("dupuit assumption of flow", "فرضية دوبوي للجريان"),
    ("thiem equation for well", "معادلة ثيم للبئر"),
    ("cooper jacob method", "طريقة كوبر-جاكوب"),
    ("pumping test of aquifer", "اختبار ضخ الخزان"),
    ("recovery test of well", "اختبار استعادة البئر"),
    ("step drawdown test", "اختبار الهبوط المتدرج"),
    ("slug test of aquifer", "اختبار الحقن اللحظي للخزان"),
    ("well loss coefficient", "معامل فقد البئر"),
    ("specific capacity of pumping well", "السعة النوعية لبئر الضخ"),
    ("well interference effect", "أثر تداخل الآبار"),
    ("image well method", "طريقة البئر الوهمي"),
    ("observation well hydrograph", "مخطط بئر المراقبة"),
    ("safe yield of aquifer", "العطاء الآمن للخزان"),
    ("sustainable yield of aquifer", "العطاء المستدام للخزان"),
    ("groundwater recharge rate", "معدل تغذية المياه الجوفية"),
    ("artificial recharge basin", "حوض تغذية اصطناعية"),
    ("managed aquifer recharge", "تغذية الخزان المدارة"),
    ("injection well for recharge", "بئر حقن للتغذية"),
    ("groundwater budget equation", "معادلة موازنة المياه الجوفية"),
    ("overexploitation of groundwater", "استنزاف المياه الجوفية"),
    ("water table decline rate", "معدل هبوط منسوب الماء"),
    ("land subsidence from pumping", "هبوط الأرض بسبب الضخ"),
    ("seawater intrusion into aquifer", "تداخل مياه البحر في الخزان"),
    ("ghyben herzberg relation", "علاقة غيبن-هرزبرغ"),
    ("freshwater saltwater interface", "سطح تماس الماء العذب والمالح"),
    ("upconing of saline water", "صعود المياه المالحة"),
    ("capture zone of well", "نطاق أسر البئر"),
    ("wellhead protection area", "منطقة حماية رأس البئر"),
    ("groundwater vulnerability index", "دليل هشاشة المياه الجوفية"),
    ("drastic vulnerability index", "دليل دراستيك للهشاشة"),
    ("advection dispersion equation", "معادلة الانتقال والانتشار"),
    ("hydrodynamic dispersion coefficient", "معامل التشتت الهيدروديناميكي"),
    ("retardation factor of solute", "معامل تأخير المذاب"),
    ("constant head boundary", "حد منسوب ثابت"),
    ("no flow boundary condition", "شرط حد عديم الجريان"),
    ("specified flux boundary", "حد تدفق محدد"),
    ("modflow groundwater model", "نموذج مودفلو للمياه الجوفية"),
    ("particle tracking of solute", "تتبع جسيمات المذاب"),
    # ── التسرب والسدود ──
    ("seepage analysis of dam", "تحليل تسرب السد"),
    ("phreatic surface in dam", "سطح التشبع في السد"),
    ("seepage face of slope", "وجه التسرب في المنحدر"),
    ("capillary fringe zone", "نطاق الحاشية الشعرية"),
    ("exit gradient of seepage", "الميل المخرج للتسرب"),
    ("critical hydraulic gradient", "الميل الهيدروليكي الحرج"),
    ("flow net of seepage", "شبكة جريان التسرب"),
    ("equipotential line of seepage", "خط تساوي الجهد للتسرب"),
    ("uplift pressure under dam", "ضغط الرفع تحت السد"),
    ("filter criteria of drain", "معايير مرشح المصرف"),
    ("toe drain of dam", "مصرف قدم السد"),
    ("drainage blanket of dam", "بساط تصريف السد"),
    ("relief well downstream", "بئر تخفيف في المؤخر"),
    ("grout curtain cutoff", "ستارة حقن قاطعة"),
    ("cutoff wall of seepage", "جدار قطع للتسرب"),
    # ── الرواسب ──
    ("sediment yield of watershed", "ناتج رواسب المستجمع"),
    ("sediment delivery ratio", "نسبة إيصال الرواسب"),
    ("universal soil loss equation", "معادلة فقد التربة العامة"),
    ("revised soil loss equation", "معادلة فقد التربة المنقحة"),
    ("rainfall erosivity factor", "معامل قدرة المطر على الانجراف"),
    ("soil erodibility factor", "معامل قابلية التربة للانجراف"),
    ("slope length factor", "معامل طول الميل"),
    ("cover management factor", "معامل الغطاء والإدارة"),
    ("support practice factor", "معامل ممارسة الدعم"),
    ("sheet erosion of soil", "انجراف صفحي للتربة"),
    ("rill erosion of soil", "انجراف أخدودي للتربة"),
    ("gully erosion of watershed", "انجراف أخدودي عميق للمستجمع"),
    ("bed load transport", "نقل حمل القاع"),
    ("suspended sediment load", "حمل الرواسب المعلقة"),
    ("wash load of river", "حمل الغسل للنهر"),
    ("total sediment load", "الحمل الرسوبي الكلي"),
    ("sediment rating curve", "منحنى تصريف الرواسب"),
    ("channel aggradation process", "عملية الترسيب في المجرى"),
    ("channel degradation process", "عملية نحر المجرى"),
    ("local scour at pier", "نحر موضعي عند الركيزة"),
    ("general scour of channel", "نحر عام للمجرى"),
    ("bank erosion of river", "انجراف ضفة النهر"),
    ("braided river channel", "مجرى نهر مجدول"),
    ("meandering river reach", "وصول نهر متعرج"),
    ("regime theory of canals", "نظرية نظام القنوات"),
    ("lacey regime equation", "معادلة نظام لاسي"),
    # ── الري والطلب ──
    ("crop water requirement", "الاحتياج المائي للمحصول"),
    ("net irrigation requirement", "صافي الاحتياج الإروائي"),
    ("gross irrigation requirement", "إجمالي الاحتياج الإروائي"),
    ("leaching requirement of salts", "احتياج غسل الأملاح"),
    ("irrigation scheduling plan", "خطة جدولة الري"),
    ("application efficiency of irrigation", "كفاءة إضافة الري"),
    ("conveyance efficiency of canal", "كفاءة نقل القناة"),
    ("distribution uniformity of water", "انتظام توزيع الماء"),
    ("furrow irrigation method", "طريقة الري بالأتلام"),
    ("basin irrigation method", "طريقة الري بالأحواض"),
    ("border irrigation method", "طريقة الري بالشرائح"),
    ("sprinkler irrigation system", "منظومة الري بالرش"),
    ("drip irrigation system", "منظومة الري بالتنقيط"),
    ("center pivot irrigation", "الري المحوري المركزي"),
    ("duty of irrigation water", "واجب ماء الري"),
    ("delta of crop water", "عمق ماء المحصول"),
    ("base period of crop", "فترة الأساس للمحصول"),
    ("canal seepage loss", "فقد تسرب القناة"),
    ("canal lining benefit", "فائدة تبطين القناة"),
    ("waterlogging of farmland", "تغدق الأراضي الزراعية"),
    ("subsurface drainage system", "منظومة الصرف تحت السطحي"),
    ("tile drain spacing", "تباعد المصارف الأنبوبية"),
    ("drainage coefficient of land", "معامل صرف الأرض"),
    ("return flow from irrigation", "الجريان الراجع من الري"),
    ("conjunctive use of water", "الاستخدام المترافق للماء"),
    ("water allocation plan", "خطة تخصيص المياه"),
    ("integrated water resources management", "الإدارة المتكاملة للموارد المائية"),
    # ── جودة الماء في المجرى ──
    ("self purification of stream", "التنقية الذاتية للمجرى"),
    ("oxygen sag curve", "منحنى هبوط الأكسجين"),
    ("streeter phelps equation", "معادلة ستريتر-فيلبس"),
    ("point source pollutant load", "حمل ملوث من مصدر نقطي"),
    ("nonpoint source pollution", "تلوث من مصدر غير نقطي"),
    ("total maximum daily load", "الحمل اليومي الأقصى الكلي"),
    ("sodium adsorption ratio", "نسبة ادمصاص الصوديوم"),
    ("total dissolved solids of water", "المواد الصلبة الذائبة الكلية في الماء"),
    ("watershed management plan", "خطة إدارة المستجمع"),
    ("check dam for runoff", "سد حاجز للجريان"),
    ("percolation tank recharge", "تغذية بخزان الارتشاح"),
    ("contour bund for conservation", "حاجز كنتوري للحفظ"),
]
