"""مصطلحات التربة والمنشآت والأساسات والفولاذ."""

from __future__ import annotations

STRUCT_ENTRIES: list[tuple[str, str]] = [
    # ── ميكانيك التربة ──
    ("soil mechanics", "ميكانيك التربة"),
    ("soil classification system", "نظام تصنيف التربة"),
    ("unified soil classification", "التصنيف الموحد للتربة"),
    ("aashto soil classification", "تصنيف آشتو للتربة"),
    ("grain size distribution", "توزيع حجم الحبيبات"),
    ("particle size analysis", "تحليل حجم الحبيبات"),
    ("sieve analysis of soil", "تحليل التربة بالمناخل"),
    ("hydrometer analysis", "تحليل الهيدروميتر"),
    ("atterberg limits", "حدود أتربرغ"),
    ("liquid limit of soil", "حد السيولة للتربة"),
    ("plastic limit of soil", "حد اللدونة للتربة"),
    ("shrinkage limit of soil", "حد الانكماش للتربة"),
    ("plasticity index of soil", "دليل اللدونة للتربة"),
    ("liquidity index of soil", "دليل السيولة للتربة"),
    ("consistency index of soil", "دليل القوام للتربة"),
    ("activity of clay", "فعالية الغضار"),
    ("gravel fraction", "جزء الحصى"),
    ("sand fraction", "جزء الرمل"),
    ("silt fraction", "جزء الغرين"),
    ("clay fraction", "جزء الغضار"),
    ("well graded soil", "تربة جيدة التدرج"),
    ("poorly graded soil", "تربة سيئة التدرج"),
    ("gap graded soil", "تربة متقطعة التدرج"),
    ("uniformity coefficient of soil", "معامل الانتظام للتربة"),
    ("coefficient of curvature", "معامل الانحناء"),
    ("proctor compaction test", "اختبار رص بروكتور"),
    ("standard proctor test", "اختبار بروكتور القياسي"),
    ("modified proctor test", "اختبار بروكتور المعدل"),
    ("zero air voids line", "خط انعدام الفراغات الهوائية"),
    ("compaction curve of soil", "منحنى الرص للتربة"),
    ("california bearing ratio", "نسبة تحمل كاليفورنيا"),
    ("cbr test of soil", "اختبار نسبة تحمل كاليفورنيا"),
    ("plate load test", "اختبار تحميل الصفيحة"),
    ("standard penetration test", "اختبار الاختراق القياسي"),
    ("spt blow count", "عدد ضربات الاختراق القياسي"),
    ("pressuremeter test", "اختبار مقياس الضغط"),
    ("dilatometer test", "اختبار مقياس التمدد"),
    ("cross hole test", "اختبار بين الآبار"),
    ("downhole seismic test", "اختبار زلزالي داخل البئر"),
    ("rock quality designation", "دليل جودة الصخر"),
    ("core recovery ratio", "نسبة استخلاص اللب"),
    ("split spoon sampler", "آخذ العينة بالملعقة المشطورة"),
    ("shelby tube sampler", "أنبوب شلبي لأخذ العينة"),
    ("thin wall sampler", "آخذ عينة رقيق الجدار"),
    ("triaxial compression test", "اختبار الضغط ثلاثي المحاور"),
    ("consolidated drained test", "اختبار منضم مصرف"),
    ("consolidated undrained test", "اختبار منضم غير مصرف"),
    ("unconsolidated undrained test", "اختبار غير منضم غير مصرف"),
    ("direct shear test", "اختبار القص المباشر"),
    ("residual shear strength", "مقاومة القص المتبقية"),
    ("peak shear strength", "مقاومة القص القصوى"),
    ("cohesion intercept", "تقاطع التماسك"),
    ("angle of internal friction", "زاوية الاحتكاك الداخلي"),
    ("effective stress principle", "مبدأ الإجهاد الفعال"),
    ("total stress analysis", "تحليل الإجهاد الكلي"),
    ("effective stress analysis", "تحليل الإجهاد الفعال"),
    ("pore water pressure", "ضغط ماء المسام"),
    ("excess pore pressure", "ضغط المسام الزائد"),
    ("coefficient of earth pressure at rest", "معامل ضغط التربة الساكن"),
    ("active earth pressure", "ضغط التربة الفعال"),
    ("passive earth pressure", "ضغط التربة المقاوم"),
    ("rankine earth pressure", "ضغط التربة لرانكين"),
    ("coulomb earth pressure", "ضغط التربة لكولوم"),
    ("lateral earth pressure", "ضغط التربة الجانبي"),
    ("surcharge load on soil", "حمل إضافي على التربة"),
    ("slope stability analysis", "تحليل استقرار المنحدر"),
    ("infinite slope analysis", "تحليل المنحدر اللانهائي"),
    ("finite slope analysis", "تحليل المنحدر المحدود"),
    ("bishop simplified method", "طريقة بيشوب المبسطة"),
    ("ordinary method of slices", "طريقة الشرائح العادية"),
    ("janbu method of slices", "طريقة يانبو للشرائح"),
    ("spencer method of slices", "طريقة سبنسر للشرائح"),
    ("factor of safety of slope", "معامل أمان المنحدر"),
    ("critical slip surface", "سطح الانزلاق الحرج"),
    ("tension crack in slope", "شق شد في المنحدر"),
    ("rapid drawdown condition", "حالة الهبوط السريع للمنسوب"),
    ("seepage force in soil", "قوة التسرب في التربة"),
    ("quick condition of soil", "حالة التربة السريعة"),
    ("critical hydraulic gradient", "الميل الهيدروليكي الحرج"),
    ("exit hydraulic gradient", "الميل الهيدروليكي عند المخرج"),
    ("equipotential line of seepage", "خط تساوي الجهد للتسرب"),
    ("uplift pressure on foundation", "ضغط الرفع على الأساس"),
    ("graded filter criteria", "معايير المرشح المتدرج"),
    ("capillary rise in soil", "الصعود الشعري في التربة"),
    ("soil suction pressure", "ضغط المص في التربة"),
    ("swelling potential of clay", "قابلية انتفاخ الغضار"),
    ("collapsible soil", "تربة قابلة للانهيار"),
    ("expansive clay soil", "تربة غضارية انتفاخية"),
    ("dispersive clay soil", "تربة غضارية مشتتة"),
    ("organic soil deposit", "تربة عضوية"),
    ("peat soil layer", "طبقة تربة خثية"),
    ("loess soil deposit", "تربة لوس"),
    ("residual soil profile", "مقطع تربة متبقية"),
    ("transported soil deposit", "تربة منقولة"),
    ("alluvial soil deposit", "تربة فيضية"),
    ("sensitive clay", "غضار حساس"),
    ("sensitivity of clay", "حساسية الغضار"),
    ("oedometer test", "اختبار الأويدومتر"),
    ("consolidation test curve", "منحنى اختبار الانضمام"),
    ("virgin compression line", "خط الانضغاط البكر"),
    ("recompression index", "دليل إعادة الانضغاط"),
    ("coefficient of volume compressibility", "معامل الانضغاط الحجمي"),
    ("constrained modulus of soil", "معامل التربة المقيد"),
    ("effective overburden pressure", "ضغط العبء الفعال"),
    ("pressure bulb in soil", "بصلة الإجهاد في التربة"),
    ("boussinesq stress distribution", "توزيع الإجهاد لبوسينسك"),
    ("newmark influence chart", "مخطط نيومارك للتأثير"),
    ("westergaard stress solution", "حل ويسترجارد للإجهاد"),
    ("contact pressure under footing", "ضغط التماس تحت القاعدة"),
    ("modulus of subgrade reaction", "معامل رد فعل التربة"),
    ("coefficient of subgrade reaction", "معامل رد فعل طبقة التأسيس"),
    ("ground improvement method", "طريقة تحسين التربة"),
    ("vibro compaction", "الرص بالاهتزاز"),
    ("dynamic compaction of soil", "الرص الديناميكي للتربة"),
    ("stone column improvement", "تحسين بأعمدة حجرية"),
    ("wick drain installation", "تركيب مصارف فتيلية"),
    ("jet grouting", "الحقن النفاث"),
    ("permeation grouting", "الحقن بالتخلل"),
    ("deep soil mixing", "الخلط العميق للتربة"),
    ("reinforced earth wall", "جدار تربة مسلحة"),
    ("mechanically stabilized earth", "تربة مثبتة ميكانيكيا"),
    ("soil structure interaction", "التفاعل بين التربة والمنشأ"),
    ("immediate settlement of soil", "هبوط التربة الآني"),
    ("consolidation settlement of clay", "هبوط الانضمام للغضار"),
    ("differential settlement of foundation", "الهبوط التفاضلي للأساس"),
    ("allowable total settlement", "الهبوط الكلي المسموح"),
    ("time rate of consolidation", "معدل الانضمام مع الزمن"),
    # ── الأساسات ──
    ("shallow foundation system", "نظام أساس سطحي"),
    ("deep foundation system", "نظام أساس عميق"),
    ("isolated footing", "قاعدة منفردة"),
    ("wall footing", "قاعدة جدارية"),
    ("strip footing", "قاعدة شريطية"),
    ("strap footing", "قاعدة رابطة"),
    ("combined footing", "قاعدة مشتركة"),
    ("raft foundation", "أساس حصيري"),
    ("mat foundation", "أساس حصيري"),
    ("floating foundation", "أساس عائم"),
    ("compensated foundation", "أساس معوّض"),
    ("grillage foundation", "أساس شبكي"),
    ("pier foundation", "أساس ركيزة"),
    ("caisson foundation", "أساس قيسون"),
    ("open caisson", "قيسون مفتوح"),
    ("pneumatic caisson", "قيسون هوائي"),
    ("well foundation", "أساس بئر"),
    ("ultimate bearing capacity", "قدرة التحمل القصوى"),
    ("net ultimate bearing capacity", "قدرة التحمل القصوى الصافية"),
    ("safe bearing capacity", "قدرة التحمل الآمنة"),
    ("allowable bearing capacity", "قدرة التحمل المسموحة"),
    ("presumptive bearing capacity", "قدرة التحمل الافتراضية"),
    ("terzaghi bearing capacity", "قدرة التحمل لتيرزاغي"),
    ("meyerhof bearing capacity", "قدرة التحمل لمايرهوف"),
    ("hansen bearing capacity", "قدرة التحمل لهانسن"),
    ("vesic bearing capacity", "قدرة التحمل لفيسيك"),
    ("bearing capacity factors", "معاملات قدرة التحمل"),
    ("shape factor of footing", "معامل شكل القاعدة"),
    ("depth factor of footing", "معامل عمق القاعدة"),
    ("inclination factor of load", "معامل ميل الحمل"),
    ("groundwater correction factor", "معامل تصحيح المياه الجوفية"),
    ("eccentricity of footing load", "لامركزية حمل القاعدة"),
    ("kern of the footing", "لب القاعدة"),
    ("one way shear in footing", "قص باتجاه واحد في القاعدة"),
    ("two way shear in footing", "قص باتجاهين في القاعدة"),
    ("flexural reinforcement of footing", "تسليح انحناء القاعدة"),
    ("pedestal under column", "قاعدة قصيرة تحت العمود"),
    ("plinth beam", "عتبة الأرضية"),
    ("grade beam", "جائز التأسيس"),
    ("tie beam of foundation", "جائز ربط الأساس"),
    ("strap beam", "جائز رابط"),
    ("displacement pile", "وتد إزاحة"),
    ("nondisplacement pile", "وتد دون إزاحة"),
    ("cast in situ pile", "وتد مصبوب بالموقع"),
    ("precast concrete pile", "وتد خرساني مسبق الصب"),
    ("steel h pile", "وتد فولاذي مقطع H"),
    ("micropile foundation", "أساس وتد دقيق"),
    ("helical pile", "وتد حلزوني"),
    ("continuous flight auger pile", "وتد البريمة المستمرة"),
    ("underreamed pile", "وتد موسع القاعدة"),
    ("belled pile", "وتد جرسي"),
    ("batter pile", "وتد مائل"),
    ("raking pile", "وتد مائل"),
    ("tension pile", "وتد شد"),
    ("anchor pile", "وتد تثبيت"),
    ("pile spacing requirement", "اشتراط تباعد الأوتاد"),
    ("piled raft foundation", "أساس حصيري على أوتاد"),
    ("static pile load test", "اختبار تحميل الوتد الساكن"),
    ("dynamic pile load test", "اختبار تحميل الوتد الديناميكي"),
    ("pile driving analyzer", "محلل دق الأوتاد"),
    ("wave equation analysis of piles", "تحليل معادلة الموجة للأوتاد"),
    ("ultimate pile capacity", "قدرة الوتد القصوى"),
    ("skin friction capacity", "قدرة الاحتكاك السطحي"),
    ("end bearing capacity of pile", "قدرة ارتكاز طرف الوتد"),
    ("group efficiency of piles", "كفاءة مجموعة الأوتاد"),
    ("block failure of pile group", "انهيار كتلي لمجموعة الأوتاد"),
    ("settlement of pile group", "هبوط مجموعة الأوتاد"),
    ("neutral plane of pile", "المستوي المحايد للوتد"),
    ("lateral capacity of pile", "قدرة الوتد الجانبية"),
    ("pile soil lateral curve", "منحنى التربة الجانبي للوتد"),
    ("machine foundation block", "كتلة أساس الماكنة"),
    ("resonance of machine foundation", "رنين أساس الماكنة"),
    ("allowable vibration amplitude", "سعة الاهتزاز المسموحة"),
    ("heel of retaining wall", "كعب الجدار الساند"),
    ("toe of retaining wall", "مقدمة الجدار الساند"),
    ("stem of retaining wall", "ساق الجدار الساند"),
    ("shear key of wall", "مفتاح قص الجدار"),
    ("overturning of retaining wall", "انقلاب الجدار الساند"),
    ("sliding of retaining wall", "انزلاق الجدار الساند"),
    ("weep hole in wall", "ثقب بزل في الجدار"),
    ("braced excavation", "حفرة مدعمة"),
    ("anchored excavation wall", "جدار حفرة مثبت"),
    ("diaphragm wall", "جدار حاجز"),
    ("secant pile wall", "جدار أوتاد متقاطعة"),
    ("contiguous pile wall", "جدار أوتاد متلاصقة"),
    ("soldier pile wall", "جدار أوتاد رأسية بألواح"),
    ("top down construction", "إنشاء من الأعلى إلى الأسفل"),
    ("bottom up construction", "إنشاء من الأسفل إلى الأعلى"),
    ("jacked pile underpinning", "تدعيم بأوتاد مدفوعة بالضغط"),
    ("blinding concrete layer", "طبقة خرسانة النظافة"),
    ("lean concrete blinding", "خرسانة نظافة ضعيفة"),
    ("mud mat concrete", "طبقة خرسانة النظافة"),
    ("allowable net bearing pressure", "ضغط التحمل الصافي المسموح"),
    ("angular distortion of foundation", "التشوه الزاوي للأساس"),
    ("tilt of foundation", "ميل الأساس"),
    ("rigid foundation assumption", "فرض أساس صلد"),
    ("flexible foundation assumption", "فرض أساس مرن"),
    ("foundation waterproofing", "عزل الأساس المائي"),
    ("damp proof course", "طبقة مانعة للرطوبة"),
    # ── المنشآت ──
    ("structural analysis method", "طريقة التحليل الإنشائي"),
    ("structural design process", "عملية التصميم الإنشائي"),
    ("structural engineering", "الهندسة الإنشائية"),
    ("determinate structure", "منشأ معين"),
    ("indeterminate structure", "منشأ غير معين"),
    ("statically determinate beam", "جائز معين سكونيا"),
    ("statically indeterminate beam", "جائز غير معين سكونيا"),
    ("plane truss", "جائز شبكي مستوي"),
    ("space truss", "جائز شبكي فراغي"),
    ("plane frame", "إطار مستوي"),
    ("space frame structure", "هيكل فراغي"),
    ("portal frame", "إطار بوابة"),
    ("gable frame", "إطار جملوني"),
    ("continuous beam", "جائز مستمر"),
    ("cantilever beam", "جائز كابولي"),
    ("simply supported beam", "جائز بسيط الاستناد"),
    ("propped cantilever beam", "جائز كابولي مسند"),
    ("fixed end beam", "جائز طرفاه مثبتان"),
    ("overhanging beam", "جائز بروز"),
    ("influence line diagram", "مخطط خط التأثير"),
    ("influence line for shear", "خط تأثير القص"),
    ("influence line for moment", "خط تأثير العزم"),
    ("muller breslau principle", "مبدأ مولر-بريسلاو"),
    ("moment distribution method", "طريقة توزيع العزوم"),
    ("hardy cross method", "طريقة هاردي كروس"),
    ("slope deflection method", "طريقة الميل والهبوط"),
    ("three moment equation", "معادلة العزوم الثلاثة"),
    ("moment area method", "طريقة مساحة العزم"),
    ("conjugate beam method", "طريقة الجائز المرافق"),
    ("virtual work method", "طريقة العمل الافتراضي"),
    ("unit load method", "طريقة الحمل الواحدي"),
    ("castigliano theorem", "مبرهنة كاستيليانو"),
    ("flexibility method", "طريقة المرونة"),
    ("force method of analysis", "طريقة القوى"),
    ("stiffness method", "طريقة الصلابة"),
    ("displacement method", "طريقة الإزاحات"),
    ("direct stiffness method", "طريقة الصلابة المباشرة"),
    ("member stiffness matrix", "مصفوفة صلابة العنصر"),
    ("structure stiffness matrix", "مصفوفة صلابة المنشأ"),
    ("carry over factor", "معامل الترحيل"),
    ("distribution factor", "معامل التوزيع"),
    ("fixed end moment", "عزم الطرف المثبت"),
    ("sway frame analysis", "تحليل الإطار مع الإزاحة الجانبية"),
    ("nonsway frame", "إطار دون إزاحة جانبية"),
    ("sidesway of frame", "الإزاحة الجانبية للإطار"),
    ("second order p delta effect", "تأثير بي-دلتا من المرتبة الثانية"),
    ("plastic hinge", "مفصل لدن"),
    ("plastic moment capacity", "سعة العزم اللدن"),
    ("shape factor of section", "معامل شكل المقطع"),
    ("collapse load of structure", "حمل انهيار المنشأ"),
    ("mechanism method", "طريقة الآلية"),
    ("upper bound theorem", "مبرهنة الحد الأعلى"),
    ("lower bound theorem", "مبرهنة الحد الأدنى"),
    ("yield line theory", "نظرية خطوط الخضوع"),
    ("yield line pattern", "نمط خطوط الخضوع"),
    ("flat plate slab", "بلاطة مسطحة دون تيجان"),
    ("waffle slab", "بلاطة مفرغة شبكية"),
    ("ribbed slab", "بلاطة معصبة"),
    ("hollow block slab", "بلاطة طابوق مفرغ"),
    ("drop panel", "بلاطة ساقطة"),
    ("column capital", "تاج العمود"),
    ("spandrel beam", "جائز واجهة"),
    ("lintel beam", "عتبة فتحة"),
    ("coupling beam", "جائز رابط"),
    ("transfer beam", "جائز ناقل"),
    ("deep beam", "جائز عميق"),
    ("shear wall", "جدار قص"),
    ("coupled shear wall", "جدار قص مزدوج"),
    ("structural core wall", "جدار نواة إنشائي"),
    ("outrigger system", "نظام الأذرع"),
    ("belt truss", "جائز شبكي حزامي"),
    ("framed tube structure", "منشأ أنبوبي إطاري"),
    ("bundled tube structure", "منشأ أنابيب مجمعة"),
    ("diagrid structure", "منشأ شبكة قطرية"),
    ("braced frame", "إطار مكثف"),
    ("moment resisting frame", "إطار مقاوم للعزوم"),
    ("dual structural system", "نظام إنشائي مزدوج"),
    ("response spectrum analysis", "تحليل طيف الاستجابة"),
    ("design response spectrum", "طيف الاستجابة التصميمي"),
    ("seismic base shear", "قص القاعدة الزلزالي"),
    ("seismic weight of building", "الوزن الزلزالي للمبنى"),
    ("fundamental period of structure", "الدور الأساسي للمنشأ"),
    ("modal analysis of structure", "التحليل النمطي للمنشأ"),
    ("time history analysis", "تحليل السجل الزمني"),
    ("equivalent lateral force method", "طريقة القوة الجانبية المكافئة"),
    ("story drift", "إزاحة الطابق النسبية"),
    ("drift limit of story", "حد إزاحة الطابق"),
    ("soft story irregularity", "عدم انتظام الطابق اللين"),
    ("weak story irregularity", "عدم انتظام الطابق الضعيف"),
    ("torsional irregularity", "عدم الانتظام الالتوائي"),
    ("pounding of adjacent buildings", "تصادم المباني المتجاورة"),
    ("seismic separation joint", "فاصل زلزالي"),
    ("structural ductility", "مطيلية المنشأ"),
    ("response modification factor", "معامل تعديل الاستجابة"),
    ("overstrength factor", "معامل المقاومة الزائدة"),
    ("seismic importance factor", "معامل الأهمية الزلزالي"),
    ("single degree of freedom system", "نظام بدرجة حرية واحدة"),
    ("multi degree of freedom system", "نظام بدرجات حرية متعددة"),
    ("natural frequency of structure", "التردد الطبيعي للمنشأ"),
    ("natural period of vibration", "دور الاهتزاز الطبيعي"),
    ("damping ratio", "نسبة التخميد"),
    ("mode shape of vibration", "شكل نمط الاهتزاز"),
    ("modal participation factor", "معامل المساهمة النمطية"),
    ("wind pressure on structure", "ضغط الرياح على المنشأ"),
    ("gust effect factor", "معامل تأثير العصف"),
    ("tributary area of load", "المساحة التابعة للحمل"),
    ("structural load path", "مسار الحمل الإنشائي"),
    ("load combination", "تراكيب الأحمال"),
    ("serviceability limit state", "حالة حد الخدمة"),
    ("ultimate limit state", "حالة الحد الأقصى"),
    ("working stress design", "تصميم إجهاد التشغيل"),
    ("limit state design", "تصميم حالات الحدود"),
    ("strength design method", "طريقة التصميم بالمقاومة"),
    ("allowable stress design", "تصميم الإجهاد المسموح"),
    ("cracked section properties", "خصائص المقطع المتشقق"),
    ("gross section properties", "خصائص المقطع الإجمالي"),
    ("effective moment of inertia", "عزم القصور الفعال"),
    ("development length of reinforcement", "طول التثبيت للتسليح"),
    ("lap splice of bars", "تراكب القضبان"),
    ("mechanical splice of bars", "وصل ميكانيكي للقضبان"),
    ("bundled reinforcing bars", "قضبان تسليح مجمعة"),
    ("curtailment of reinforcement", "قطع التسليح"),
    ("bar bending schedule", "جدول ثني القضبان"),
    ("stirrup reinforcement", "تسليح الكانات"),
    ("spiral reinforcement", "تسليح حلزوني"),
    ("confinement reinforcement", "تسليح الحصر"),
    ("column interaction diagram", "مخطط تفاعل العمود"),
    ("moment magnification factor", "معامل تضخيم العزم"),
    ("minimum eccentricity of column", "اللامركزية الدنيا للعمود"),
    ("compatibility torsion", "لي التوافق"),
    ("equilibrium torsion", "لي التوازن"),
    ("shear friction", "احتكاك القص"),
    ("strut and tie model", "نموذج الدعامة والشداد"),
    ("nodal zone", "منطقة عقدية"),
    ("bottle shaped strut", "دعامة قنينة الشكل"),
    ("corbel design", "تصميم الكابول القصير"),
    ("prestressed concrete member", "عنصر خرساني مسبق الإجهاد"),
    ("pretensioned concrete", "خرسانة مسبقة الشد"),
    ("post tensioned concrete", "خرسانة لاحقة الشد"),
    ("prestressing tendon", "كيبل سبق الإجهاد"),
    ("bonded tendon", "كيبل متماسك"),
    ("unbonded tendon", "كيبل غير متماسك"),
    ("prestress loss", "فقد سبق الإجهاد"),
    ("elastic shortening loss", "فقد التقلص المرن"),
    ("relaxation of prestressing steel", "ارتخاء فولاذ سبق الإجهاد"),
    ("friction loss in tendon", "فقد الاحتكاك في الكيبل"),
    ("wobble friction coefficient", "معامل احتكاك التموج"),
    ("transfer length of prestress", "طول انتقال سبق الإجهاد"),
    ("camber of prestressed member", "تقوس العنصر مسبق الإجهاد"),
    ("load balancing method", "طريقة موازنة الأحمال"),
    ("shear connector", "رابط قص"),
    ("headed stud connector", "رابط مسمار برأس"),
    ("partial composite interaction", "تفاعل مركب جزئي"),
    ("full composite interaction", "تفاعل مركب تام"),
    # ── الفولاذ ──
    ("structural steel", "فولاذ إنشائي"),
    ("steel structure", "منشأ فولاذي"),
    ("steel design", "تصميم فولاذي"),
    ("hot rolled steel section", "مقطع فولاذي مدلفن على الساخن"),
    ("cold formed steel section", "مقطع فولاذي مشكل على البارد"),
    ("built up steel section", "مقطع فولاذي مركب"),
    ("wide flange beam", "جائز جناح عريض"),
    ("steel channel section", "مقطع مجرى فولاذي"),
    ("equal angle section", "مقطع زاوية متساوية"),
    ("unequal angle section", "مقطع زاوية غير متساوية"),
    ("steel tee section", "مقطع حرف T فولاذي"),
    ("hollow structural section", "مقطع إنشائي مجوف"),
    ("rectangular hollow section", "مقطع مجوف مستطيل"),
    ("circular hollow section", "مقطع مجوف دائري"),
    ("steel plate girder", "جائز صفائحي فولاذي"),
    ("yield stress of steel", "إجهاد خضوع الفولاذ"),
    ("ultimate tensile stress of steel", "إجهاد الشد الأقصى للفولاذ"),
    ("modulus of elasticity of steel", "معامل مرونة الفولاذ"),
    ("steel tension member", "عنصر فولاذي معرض للشد"),
    ("net section of member", "المقطع الصافي للعنصر"),
    ("effective net area", "المساحة الصافية الفعالة"),
    ("shear lag effect", "تأثير تخلف القص"),
    ("block shear rupture", "تمزق القص الكتلي"),
    ("staggered bolt holes", "ثقوب براغي متبادلة"),
    ("gage distance of bolts", "مسافة التباعد العرضي للبراغي"),
    ("pitch of bolts", "خطوة البراغي"),
    ("edge distance of bolt", "مسافة حافة البرغي"),
    ("end distance of bolt", "مسافة نهاية البرغي"),
    ("standard bolt hole", "ثقب برغي قياسي"),
    ("oversized bolt hole", "ثقب برغي موسع"),
    ("slotted bolt hole", "ثقب برغي مشقوق"),
    ("bearing type connection", "وصلة تحميل"),
    ("slip critical connection", "وصلة حرجة الانزلاق"),
    ("snug tight bolt", "برغي مشدود بالتماس"),
    ("pretensioned high strength bolt", "برغي عالي المقاومة مسبق الشد"),
    ("bolt shear strength", "مقاومة قص البرغي"),
    ("bolt bearing strength", "مقاومة تحميل البرغي"),
    ("prying action of bolts", "فعل الانتزاع للبراغي"),
    ("fillet weld throat thickness", "سمك حلق اللحام الزاوي"),
    ("effective throat of weld", "الحلق الفعال للحام"),
    ("complete joint penetration weld", "لحام اختراق تام للوصلة"),
    ("partial joint penetration weld", "لحام اختراق جزئي للوصلة"),
    ("plug weld", "لحام سداد"),
    ("slot weld", "لحام شق"),
    ("matching welding electrode", "إلكترود لحام مكافئ"),
    ("flexural buckling of column", "انبعاج انحنائي للعمود"),
    ("torsional buckling", "انبعاج التوائي"),
    ("flexural torsional buckling", "انبعاج انحنائي التوائي"),
    ("local buckling of plate", "انبعاج موضعي للصفيحة"),
    ("width to thickness ratio", "نسبة العرض إلى السمك"),
    ("compact steel section", "مقطع فولاذي مكتنز"),
    ("noncompact steel section", "مقطع فولاذي غير مكتنز"),
    ("slender steel section", "مقطع فولاذي نحيف"),
    ("effective length factor", "معامل الطول الفعال"),
    ("alignment chart for frames", "مخطط المحاذاة للإطارات"),
    ("euler buckling load", "حمل انبعاج أويلر"),
    ("critical buckling stress", "إجهاد الانبعاج الحرج"),
    ("lateral torsional buckling", "الانبعاج الجانبي الالتوائي"),
    ("unbraced length of beam", "طول الجائز غير المسنود"),
    ("moment gradient factor", "معامل تدرج العزم"),
    ("lateral bracing of beam", "تسنيد جانبي للجائز"),
    ("plastic section modulus", "معامل المقطع اللدن"),
    ("elastic section modulus", "معامل المقطع المرن"),
    ("warping constant of section", "ثابت الالتواء للمقطع"),
    ("saint venant torsion constant", "ثابت لي سان فينان"),
    ("shear center of section", "مركز القص للمقطع"),
    ("transverse stiffener", "مقوي عرضي"),
    ("bearing stiffener", "مقوي تحميل"),
    ("longitudinal stiffener", "مقوي طولي"),
    ("tension field action", "فعل حقل الشد"),
    ("web crippling", "سحق جانة الجائز"),
    ("web local yielding", "خضوع موضعي للجانة"),
    ("steel roof truss", "جائز شبكي للسقف"),
    ("warren truss", "جائز وارن الشبكي"),
    ("pratt truss", "جائز برات الشبكي"),
    ("howe truss", "جائز هاو الشبكي"),
    ("fink roof truss", "جائز فينك للسقف"),
    ("steel purlin", "مدادة فولاذية"),
    ("steel girt", "عارضة جدارية فولاذية"),
    ("sag rod", "قضيب منع الترهّل"),
    ("eave strut", "عنصر إفريز"),
    ("steel rafter", "رافدة فولاذية"),
    ("knee brace", "دعامة ركبة"),
    ("portal bracing", "تكثيف بوابة"),
    ("composite steel beam", "جائز فولاذي مركب"),
    ("steel floor deck", "سطح فولاذي للأرضية"),
    ("metal deck slab", "بلاطة سطح معدني"),
    ("shear stud on beam", "مسمار قص على الجائز"),
    ("residual stress in steel", "إجهاد متبق في الفولاذ"),
    ("moment connection of steel", "وصلة عزم فولاذية"),
    ("simple steel connection", "وصلة فولاذية بسيطة"),
    ("semi rigid connection", "وصلة شبه صلبة"),
    ("seated beam connection", "وصلة جائز بمقعد"),
    ("extended end plate connection", "وصلة صفيحة طرفية ممتدة"),
    ("flush end plate connection", "وصلة صفيحة طرفية مستوية"),
    ("column splice connection", "وصلة وصل العمود"),
    ("beam splice connection", "وصلة وصل الجائز"),
    ("steel base plate design", "تصميم صفيحة قاعدة فولاذية"),
    ("anchor rod of column", "قضيب تثبيت العمود"),
    ("grout under base plate", "حقن تحت صفيحة القاعدة"),
    ("fire protection of steel", "حماية الفولاذ من الحريق"),
    ("intumescent fire coating", "طلاء منتفخ مقاوم للحريق"),
    ("hot dip galvanizing", "جلفنة بالغمر الساخن"),
    ("steel erection sequence", "تسلسل نصب الفولاذ"),
    ("temporary erection bracing", "تكثيف مؤقت للنصب"),
    ("shop drawing of steel", "مخطط ورشة للفولاذ"),
    ("lamellar tearing", "تمزق طبقي"),
    ("fatigue of steel member", "كلال العنصر الفولاذي"),
    ("brittle fracture of steel", "كسر هش للفولاذ"),
    ("charpy impact test", "اختبار صدم تشاربي"),
    ("lrfd steel design", "تصميم فولاذي بمعاملات الحمولة والمقاومة"),
    ("asd steel design", "تصميم فولاذي بالإجهاد المسموح"),
    ("resistance factor of steel", "معامل المقاومة للفولاذ"),
    ("plastic neutral axis", "المحور المحايد اللدن"),
    ("steel beam column member", "عنصر جائز-عمود فولاذي"),
    ("interaction equation of steel", "معادلة التفاعل للفولاذ"),
    ("direct analysis method", "طريقة التحليل المباشر"),
    ("effective length method", "طريقة الطول الفعال"),
    ("notional lateral load", "حمل جانبي افتراضي"),
    ("initial geometric imperfection", "عيب هندسي ابتدائي"),
    ("out of plumbness", "خروج عن الشاقول"),
    ("second order structural analysis", "تحليل إنشائي من المرتبة الثانية"),
]
