"""دفعة إضافية: تخصصات سريرية، إلكترونيات، أجهزة، تغذية، صحة عامة، روبوتات."""

from __future__ import annotations

MORE_ENTRIES: list[tuple[str, str]] = [
    ("conjunctiva membrane", "ملتحمة العين"),
    ("cornea layer", "طبقة القرنية"),
    ("iris of eye", "قزحية العين"),
    ("pupil of eye", "حدقة العين"),
    ("lens of eye", "عدسة العين"),
    ("retina layer", "طبقة الشبكية"),
    ("optic disc", "القرص البصري"),
    ("macula lutea", "البقعة الصفراء"),
    ("fovea centralis", "النقرة المركزية"),
    ("aqueous humor", "الخلط المائي"),
    ("vitreous humor", "الخلط الزجاجي"),
    ("lacrimal gland", "الغدة الدمعية"),
    ("extraocular muscles", "عضلات خارج المقلة"),
    ("visual acuity", "حدة البصر"),
    ("refractive error", "خطأ انكساري"),
    ("myopia condition", "قصر النظر"),
    ("hyperopia condition", "مد البصر"),
    ("astigmatism condition", "اللابؤرية"),
    ("presbyopia condition", "قصو البصر"),
    ("cataract opacity", "ساد"),
    ("glaucoma disease", "الزرق"),
    ("intraocular pressure", "ضغط داخل المقلة"),
    ("diabetic macular edema", "وذمة البقعة السكرية"),
    ("retinal detachment", "انفصال الشبكية"),
    ("conjunctivitis inflammation", "التهاب الملتحمة"),
    ("external ear", "الأذن الظاهرة"),
    ("middle ear", "الأذن الوسطى"),
    ("inner ear", "الأذن الباطنة"),
    ("tympanic membrane", "غشاء الطبل"),
    ("eustachian tube", "نفير أوستاش"),
    ("cochlea structure", "القوقعة"),
    ("vestibular apparatus", "الجهاز الدهليزي"),
    ("semicircular canals", "القنوات الهلالية"),
    ("otitis media", "التهاب الأذن الوسطى"),
    ("otitis externa", "التهاب الأذن الظاهرة"),
    ("hearing loss", "نقص السمع"),
    ("conductive hearing loss", "نقص سمع توصيلي"),
    ("sensorineural hearing loss", "نقص سمع حسي عصبي"),
    ("tinnitus symptom", "طنين الأذن"),
    ("vertigo symptom", "دوار"),
    ("sinusitis inflammation", "التهاب الجيوب"),
    ("allergic rhinitis", "التهاب أنف تحسسي"),
    ("tonsillitis inflammation", "التهاب اللوزتين"),
    ("pharyngitis inflammation", "التهاب البلعوم"),
    ("laryngitis inflammation", "التهاب الحنجرة"),
    ("epistaxis bleeding", "رعاف"),
    ("nasal septum deviation", "انحراف الوتيرة"),
    ("epidermis layer", "طبقة البشرة"),
    ("dermis layer", "طبقة الأدمة"),
    ("hypodermis layer", "طبقة تحت الأدمة"),
    ("sebaceous gland", "غدة دهنية"),
    ("sweat gland", "غدة عرقية"),
    ("hair follicle", "جريب الشعرة"),
    ("melanocyte cell", "خلية ميلانينية"),
    ("keratinocyte cell", "خلية متقرنة"),
    ("atopic dermatitis", "التهاب جلد تأتبي"),
    ("contact dermatitis", "التهاب جلد تماسي"),
    ("psoriasis disease", "الصداف"),
    ("acne vulgaris", "العد الشائع"),
    ("urticaria reaction", "شرى"),
    ("cellulitis infection", "التهاب الهلل"),
    ("impetigo infection", "القوباء"),
    ("tinea infection", "سعفة"),
    ("scabies infestation", "الجرب"),
    ("melanoma tumor", "ورم ميلانيني"),
    ("basal cell carcinoma", "سرطانة الخلايا القاعدية"),
    ("squamous cell carcinoma", "سرطانة الخلايا الحرشفية"),
    ("antenatal care", "رعاية قبل الولادة"),
    ("prenatal screening", "تحر قبل الولادة"),
    ("gestational age", "عمر حملي"),
    ("first trimester", "الثلث الأول"),
    ("second trimester", "الثلث الثاني"),
    ("third trimester", "الثلث الثالث"),
    ("ectopic pregnancy", "حمل منتبذ"),
    ("molar pregnancy", "حمل رحوي"),
    ("placenta previa", "مشيمة منزاحة"),
    ("placental abruption", "انفصال المشيمة"),
    ("preeclampsia disorder", "مقدمات الارتعاج"),
    ("eclampsia seizure", "ارتعاج"),
    ("gestational diabetes", "سكري حملي"),
    ("preterm labor", "مخاض خداج"),
    ("premature rupture of membranes", "تمزق الأغشية الباكر"),
    ("postpartum hemorrhage", "نزف تال للولادة"),
    ("cesarean section", "عملية قيصرية"),
    ("vaginal delivery", "ولادة مهبلية"),
    ("apgar score", "درجة أبغار"),
    ("neonatal jaundice", "يرقان وليدي"),
    ("respiratory distress of newborn", "ضائقة تنفسية للوليد"),
    ("breastfeeding counseling", "إرشاد الرضاعة الطبيعية"),
    ("contraceptive method", "وسيلة منع حمل"),
    ("intrauterine device", "جهاز داخل الرحم"),
    ("oral contraceptive", "مانع حمل فموي"),
    ("infertility evaluation", "تقييم العقم"),
    ("polycystic ovary syndrome", "متلازمة المبيض متعدد الكيسات"),
    ("endometriosis disease", "انتباذ بطاني رحمي"),
    ("uterine fibroid", "ورم ليفي رحمي"),
    ("cervical cancer screening", "تحري سرطان عنق الرحم"),
    ("pap smear", "لطاخة بابانيكولاو"),
    ("major depressive disorder", "اضطراب اكتئابي جسيم"),
    ("generalized anxiety disorder", "اضطراب القلق المعمم"),
    ("panic disorder", "اضطراب الهلع"),
    ("bipolar disorder", "اضطراب ثنائي القطب"),
    ("schizophrenia disorder", "الفصام"),
    ("obsessive compulsive disorder", "اضطراب وسواسي قهري"),
    ("post traumatic stress disorder", "اضطراب الكرب التالي للرضح"),
    ("attention deficit hyperactivity", "نقص الانتباه وفرط الحركة"),
    ("autism spectrum disorder", "اضطراب طيف التوحد"),
    ("substance use disorder", "اضطراب تعاطي المواد"),
    ("delirium state", "هذيان"),
    ("dementia syndrome", "متلازمة الخرف"),
    ("suicidal ideation", "أفكار انتحارية"),
    ("mental status examination", "فحص الحالة العقلية"),
    ("cognitive behavioral session", "جلسة علاج معرفي سلوكي"),
    ("antipsychotic medication", "دواء مضاد للذهان"),
    ("mood stabilizer", "مثبت مزاج"),
    ("pediatric growth chart", "مخطط نمو الأطفال"),
    ("developmental milestone", "معلم نمائي"),
    ("vaccination schedule", "جدول التطعيم"),
    ("oral rehydration solution", "محلول إماهة فموي"),
    ("dehydration assessment", "تقييم التجفاف"),
    ("febrile seizure", "اختلاج حروري"),
    ("acute otitis media in children", "التهاب أذن وسطى حاد عند الأطفال"),
    ("bronchiolitis infection", "التهاب القصيبات"),
    ("croup illness", "خناق حنجري"),
    ("failure to thrive", "فشل النمو"),
    ("kwashiorkor malnutrition", "سوء تغذية كواشيوركور"),
    ("marasmus malnutrition", "سوء تغذية مرازمس"),
    ("iron deficiency in children", "عوز الحديد عند الأطفال"),
    ("vitamin d deficiency", "عوز فيتامين د"),
    ("vitamin a deficiency", "عوز فيتامين أ"),
    ("vitamin b12 deficiency", "عوز فيتامين ب12"),
    ("folate deficiency", "عوز الفولات"),
    ("vitamin c deficiency", "عوز فيتامين ج"),
    ("vitamin k deficiency", "عوز فيتامين ك"),
    ("calcium deficiency", "عوز الكالسيوم"),
    ("iodine deficiency", "عوز اليود"),
    ("zinc deficiency", "عوز الزنك"),
    ("macronutrient intake", "وارد المغذيات الكبرى"),
    ("micronutrient intake", "وارد المغذيات الصغرى"),
    ("basal metabolic rate", "معدل الاستقلاب الأساسي"),
    ("body mass index", "مؤشر كتلة الجسم"),
    ("waist circumference", "محيط الخصر"),
    ("energy requirement", "الاحتياج من الطاقة"),
    ("protein requirement", "الاحتياج من البروتين"),
    ("dietary fiber", "ألياف غذائية"),
    ("saturated fatty acid", "حمض دهني مشبع"),
    ("unsaturated fatty acid", "حمض دهني غير مشبع"),
    ("essential amino acid", "حمض أميني أساسي"),
    ("essential fatty acid", "حمض دهني أساسي"),
    ("glycemic index", "المنسب السكري"),
    ("glycemic load", "الحمل السكري"),
    ("food allergy", "تحسس غذائي"),
    ("food intolerance", "عدم تحمل غذائي"),
    ("lactose intolerance", "عدم تحمل اللاكتوز"),
    ("celiac disease", "الداء الزلاقي"),
    ("enteral nutrition", "تغذية معوية"),
    ("parenteral nutrition", "تغذية وريدية"),
    ("malnutrition screening", "تحري سوء التغذية"),
    ("obesity classification", "تصنيف السمنة"),
    ("incidence rate", "معدل الوقوع"),
    ("prevalence rate", "معدل الانتشار"),
    ("mortality rate", "معدل الوفيات"),
    ("case fatality rate", "معدل الإماتة"),
    ("attack rate", "معدل الهجمة"),
    ("relative risk", "خطر نسبي"),
    ("attributable risk", "خطر منسوب"),
    ("number needed to treat", "عدد يلزم علاجه"),
    ("sensitivity of test", "حساسية الاختبار"),
    ("specificity of test", "نوعية الاختبار"),
    ("positive predictive value", "قيمة تنبؤية إيجابية"),
    ("negative predictive value", "قيمة تنبؤية سلبية"),
    ("likelihood ratio", "نسبة الأرجحية التشخيصية"),
    ("screening program", "برنامج تحر"),
    ("lead time bias", "انحياز زمن التقدم"),
    ("selection bias", "انحياز الاختيار"),
    ("information bias", "انحياز المعلومات"),
    ("confounding bias", "انحياز الإرباك"),
    ("outbreak investigation", "تقصي الفاشية"),
    ("epidemic curve", "منحنى الوباء"),
    ("endemic disease", "مرض متوطن"),
    ("pandemic disease", "مرض جائح"),
    ("herd immunity", "مناعة القطيع"),
    ("vaccine efficacy", "نجاعة اللقاح"),
    ("cold chain", "سلسلة التبريد"),
    ("notifiable disease", "مرض واجب التبليغ"),
    ("contact tracing", "تقصي المخالطين"),
    ("quarantine measure", "تدبير الحجر"),
    ("isolation measure", "تدبير العزل"),
    ("standard precautions", "احتياطات قياسية"),
    ("hand washing technique", "تقنية غسل اليدين"),
    ("personal protective equipment", "معدات الوقاية الشخصية"),
    ("nosocomial infection", "عدوى مكتسبة في المستشفى"),
    ("antimicrobial stewardship", "ترشيد مضادات الميكروبات"),
    ("gram positive cocci", "مكورات موجبة الغرام"),
    ("gram negative bacilli", "عصيات سالبة الغرام"),
    ("staphylococcus aureus", "المكورة العنقودية الذهبية"),
    ("streptococcus pyogenes", "المكورة العقدية المقيحة"),
    ("streptococcus pneumoniae", "المكورة الرئوية"),
    ("escherichia coli", "الإشريكية القولونية"),
    ("klebsiella pneumoniae", "الكلبسيلة الرئوية"),
    ("pseudomonas aeruginosa", "الزائفة الزنجارية"),
    ("mycobacterium tuberculosis", "المتفطرة السلية"),
    ("clostridium difficile", "المطثية العسيرة"),
    ("candida albicans", "المبيضات البيضاء"),
    ("plasmodium falciparum", "المتصورة المنجلية"),
    ("hepatitis b virus", "فيروس التهاب الكبد ب"),
    ("human immunodeficiency virus", "فيروس العوز المناعي البشري"),
    ("influenza virus", "فيروس الإنفلونزا"),
    ("innate immune response", "استجابة مناعية فطرية"),
    ("adaptive immune response", "استجابة مناعية مكتسبة"),
    ("humoral immunity", "مناعة خلطية"),
    ("cell mediated immunity", "مناعة خلوية"),
    ("antigen presentation", "عرض المستضد"),
    ("major histocompatibility complex", "معقد التوافق النسيجي الكبير"),
    ("helper t cell", "خلية تائية مساعدة"),
    ("cytotoxic t cell", "خلية تائية سامة"),
    ("regulatory t cell", "خلية تائية منظمة"),
    ("memory b cell", "خلية بائية ذاكرة"),
    ("plasma cell", "خلية بلازمية"),
    ("immunoglobulin g", "غلوبولين مناعي ج"),
    ("immunoglobulin m", "غلوبولين مناعي م"),
    ("immunoglobulin a", "غلوبولين مناعي أ"),
    ("immunoglobulin e", "غلوبولين مناعي هـ"),
    ("complement cascade", "سلسلة المتممة"),
    ("opsonization process", "تهيئة للبلعمة"),
    ("cytokine storm", "عاصفة السيتوكينات"),
    ("hypersensitivity reaction", "تفاعل فرط تحسس"),
    ("type one hypersensitivity", "فرط تحسس من النمط الأول"),
    ("type two hypersensitivity", "فرط تحسس من النمط الثاني"),
    ("type three hypersensitivity", "فرط تحسس من النمط الثالث"),
    ("type four hypersensitivity", "فرط تحسس من النمط الرابع"),
    ("autoimmune disease mechanism", "آلية المرض المناعي الذاتي"),
    ("plain radiograph", "صورة شعاعية بسيطة"),
    ("chest radiograph", "صورة صدر شعاعية"),
    ("abdominal radiograph", "صورة بطن شعاعية"),
    ("contrast study", "دراسة بالوسط الظليل"),
    ("computed tomography scan", "تصوير مقطعي محوسب"),
    ("magnetic resonance imaging scan", "تصوير بالرنين المغناطيسي"),
    ("ultrasound imaging", "تصوير بالأمواج فوق الصوتية"),
    ("doppler ultrasound", "أمواج فوق صوتية دوبلر"),
    ("nuclear medicine scan", "مسح طب نووي"),
    ("positron emission tomography", "تصوير مقطعي بالإصدار البوزيتروني"),
    ("bone densitometry", "قياس كثافة العظم"),
    ("mammography screening", "تحري بالتصوير الشعاعي للثدي"),
    ("image guided biopsy", "خزعة موجهة بالصورة"),
    ("radiation dose", "جرعة إشعاعية"),
    ("contrast nephropathy", "اعتلال كلية بالوسط الظليل"),
    ("aseptic surgical field", "حقل جراحي عقيم"),
    ("skin incision", "شق جلدي"),
    ("blunt dissection", "تسليخ كليل"),
    ("sharp dissection", "تسليخ حاد"),
    ("hemostasis technique", "تقنية الإرقاء"),
    ("suture material", "مادة الخياطة"),
    ("interrupted suture", "خياطة متقطعة"),
    ("continuous suture", "خياطة مستمرة"),
    ("subcuticular suture", "خياطة تحت الجلد"),
    ("wound drain", "مفزغ الجرح"),
    ("surgical site infection", "عدوى موضع الجراحة"),
    ("informed surgical consent", "موافقة جراحية مستنيرة"),
    ("world health organization checklist", "قائمة منظمة الصحة العالمية"),
    ("postoperative pain control", "ضبط الألم بعد الجراحة"),
    ("deep vein thrombosis prophylaxis", "وقاية من الخثار الوريدي العميق"),
    ("enhanced recovery after surgery", "تعاف معزز بعد الجراحة"),
    ("laparoscopic surgery", "جراحة بالمنظار"),
    ("open surgery", "جراحة مفتوحة"),
    ("minimally invasive surgery", "جراحة قليلة البضع"),
    ("anesthesia induction", "تحريض التخدير"),
    ("anesthesia maintenance", "إبقاء التخدير"),
    ("airway management", "تدبير الطريق الهوائي"),
    ("endotracheal intubation", "تنبيب رغامي"),
    ("laryngeal mask airway", "طريق هوائي بقناع حنجري"),
    ("capnography monitoring", "مراقبة تخطيط ثاني أكسيد الكربون"),
    ("neuromuscular blockade", "إحصار عضلي عصبي"),
    ("reversal of blockade", "عكس الإحصار"),
    ("spinal anesthesia", "تخدير شوكي"),
    ("epidural anesthesia", "تخدير فوق الجافية"),
    ("local infiltration anesthesia", "تخدير بالترشيح الموضعي"),
    ("logic high level", "مستوى منطقي عال"),
    ("logic low level", "مستوى منطقي منخفض"),
    ("boolean expression", "عبارة بوليانية"),
    ("truth table minimization", "تبسيط جدول الحقيقة"),
    ("karnaugh map", "مخطط كارنوف"),
    ("sum of products", "مجموع الجداءات"),
    ("product of sums", "جداء المجاميع"),
    ("and gate", "بوابة و"),
    ("or gate", "بوابة أو"),
    ("not gate", "بوابة ليس"),
    ("nand gate", "بوابة ناند"),
    ("nor gate", "بوابة نور"),
    ("xor gate", "بوابة أو الحصرية"),
    ("xnor gate", "بوابة نفي أو الحصرية"),
    ("combinational circuit", "دارة توافقية"),
    ("sequential circuit", "دارة تتابعية"),
    ("sr latch", "ماسك وضع وإعادة وضع"),
    ("d flip flop", "قلاب من النوع دي"),
    ("jk flip flop", "قلاب من النوع جي كي"),
    ("t flip flop", "قلاب من النوع تي"),
    ("clock signal", "إشارة ساعة"),
    ("setup time", "زمن التهيئة"),
    ("hold time", "زمن الثبات"),
    ("propagation delay", "تأخير الانتشار"),
    ("multiplexer circuit", "دارة ناخب"),
    ("demultiplexer circuit", "دارة موزع"),
    ("encoder circuit", "دارة مرمز"),
    ("decoder circuit", "دارة مفكك ترميز"),
    ("half adder", "جامع نصفي"),
    ("full adder", "جامع كامل"),
    ("ripple carry adder", "جامع حمل متعاقب"),
    ("arithmetic logic unit", "وحدة حساب ومنطق"),
    ("register file", "ملف المسجلات"),
    ("program counter", "عداد البرنامج"),
    ("instruction register", "مسجل التعليمة"),
    ("memory address register", "مسجل عنوان الذاكرة"),
    ("memory data register", "مسجل بيانات الذاكرة"),
    ("instruction cycle", "دورة التعليمة"),
    ("fetch decode execute", "جلب وفك وتنفيذ"),
    ("pipeline hazard", "مخاطرة خط التعليمات"),
    ("data hazard", "مخاطرة بيانات"),
    ("control hazard", "مخاطرة تحكم"),
    ("branch prediction", "تنبؤ التفرع"),
    ("cache hit", "إصابة الذاكرة المخبأة"),
    ("cache miss", "إخفاق الذاكرة المخبأة"),
    ("write through policy", "سياسة الكتابة المباشرة"),
    ("write back policy", "سياسة الكتابة الراجعة"),
    ("direct mapped cache", "ذاكرة مخبأة ذات تعيين مباشر"),
    ("set associative cache", "ذاكرة مخبأة تجميعية المجموعات"),
    ("virtual address", "عنوان افتراضي"),
    ("physical address", "عنوان فيزيائي"),
    ("page offset", "إزاحة الصفحة"),
    ("tlb miss", "إخفاق مخزن الترجمة"),
    ("interrupt request", "طلب مقاطعة"),
    ("direct memory access", "وصول مباشر للذاكرة"),
    ("bus arbitration", "تحكيم الممر"),
    ("serial communication", "اتصال تسلسلي"),
    ("parallel communication", "اتصال تفرعي"),
    ("uart interface", "واجهة إرسال واستقبال لا تزامنية"),
    ("spi interface", "واجهة طرفية تسلسلية"),
    ("i2c interface", "واجهة الدارة المتكاملة البينية"),
    ("analog signal", "إشارة تماثلية"),
    ("digital signal", "إشارة رقمية"),
    ("sampling rate", "معدل أخذ العينات"),
    ("quantization error", "خطأ التكميم"),
    ("aliasing effect", "تأثير التراكب الطيفي"),
    ("anti aliasing filter", "مرشح ضد التراكب"),
    ("nyquist rate", "معدل نيكويست"),
    ("reconstruction filter", "مرشح إعادة البناء"),
    ("finite impulse response filter", "مرشح استجابة نبضية منتهية"),
    ("infinite impulse response filter", "مرشح استجابة نبضية غير منتهية"),
    ("z transform analysis", "تحليل بتحويل زد"),
    ("discrete time signal", "إشارة زمنية متقطعة"),
    ("continuous time signal", "إشارة زمنية مستمرة"),
    ("fourier series expansion", "نشر متسلسلة فورييه"),
    ("discrete fourier transform pair", "زوج تحويل فورييه المتقطع"),
    ("fast fourier transform algorithm", "خوارزمية تحويل فورييه السريع"),
    ("window function", "دالة نافذة"),
    ("spectral leakage", "تسرب طيفي"),
    ("signal to noise ratio value", "قيمة نسبة الإشارة إلى الضوضاء"),
    ("bit error rate value", "قيمة معدل خطأ البتات"),
    ("modulation index", "دليل التعديل"),
    ("amplitude modulation wave", "موجة تعديل سعوي"),
    ("frequency modulation wave", "موجة تعديل ترددي"),
    ("phase modulation wave", "موجة تعديل طوري"),
    ("superheterodyne receiver", "مستقبل فوق هيتيرودايني"),
    ("intermediate frequency", "تردد وسيط"),
    ("antenna gain", "كسب الهوائي"),
    ("radiation pattern", "نمط الإشعاع"),
    ("half power beamwidth", "عرض الحزمة عند نصف القدرة"),
    ("friis transmission equation", "معادلة فريس للإرسال"),
    ("path loss", "فقد المسار"),
    ("fading channel", "قناة خفوت"),
    ("multipath propagation", "انتشار متعدد المسارات"),
    ("diversity reception", "استقبال تنوع"),
    ("multiple access", "نفاذ متعدد"),
    ("frequency division multiple access", "نفاذ متعدد بتقسيم التردد"),
    ("time division multiple access", "نفاذ متعدد بتقسيم الزمن"),
    ("code division multiple access", "نفاذ متعدد بتقسيم الترميز"),
    ("orthogonal frequency division", "تقسيم ترددي متعامد"),
    ("mimo system", "نظام مداخل ومخارج متعددة"),
    ("channel coding", "ترميز القناة"),
    ("source coding", "ترميز المصدر"),
    ("huffman coding", "ترميز هوفمان"),
    ("convolutional code", "ترميز تلافيفي"),
    ("viterbi decoding", "فك ترميز فيتربي"),
    ("error detection", "كشف الخطأ"),
    ("error correction", "تصحيح الخطأ"),
    ("information entropy", "إنتروبيا المعلومات"),
    ("mutual information", "معلومات متبادلة"),
    ("sensor calibration", "معايرة الحساس"),
    ("transducer element", "عنصر محول طاقة"),
    ("strain gauge bridge", "جسر مقياس الانفعال"),
    ("wheatstone bridge", "جسر ويتستون"),
    ("thermocouple sensor", "حساس مزدوج حراري"),
    ("resistance temperature detector", "كاشف حرارة مقاومي"),
    ("thermistor sensor", "حساس ثرمستور"),
    ("lvdt sensor", "حساس تفاضلي خطي متغير"),
    ("capacitive sensor", "حساس سعوي"),
    ("inductive sensor", "حساس حثي"),
    ("piezoelectric sensor", "حساس كهرضغطي"),
    ("photodiode sensor", "حساس ثنائي ضوئي"),
    ("ultrasonic sensor", "حساس فوق صوتي"),
    ("pressure transducer", "محول ضغط"),
    ("flow meter", "مقياس جريان"),
    ("level sensor", "حساس منسوب"),
    ("ph electrode", "قطب الأس الهيدروجيني"),
    ("signal conditioning", "تكييف الإشارة"),
    ("instrumentation amplifier", "مضخم أجهزة"),
    ("common mode rejection", "رفض النمط المشترك"),
    ("offset voltage", "جهد الإزاحة"),
    ("gain bandwidth product", "جداء الكسب وعرض النطاق"),
    ("slew rate", "معدل التغير"),
    ("input impedance", "ممانعة الدخل"),
    ("output impedance", "ممانعة الخرج"),
    ("feedback amplifier", "مضخم بتغذية راجعة"),
    ("negative feedback amplifier", "مضخم بتغذية راجعة سلبية"),
    ("oscillator circuit", "دارة مهتز"),
    ("crystal oscillator", "مهتز بلوري"),
    ("active filter", "مرشح فعال"),
    ("passive filter", "مرشح غير فعال"),
    ("low pass filter circuit", "دارة مرشح تمرير منخفض"),
    ("high pass filter circuit", "دارة مرشح تمرير عال"),
    ("band pass filter circuit", "دارة مرشح تمرير نطاقي"),
    ("notch filter", "مرشح إيقاف نطاقي"),
    ("analog to digital resolution", "ميز المحول التماثلي الرقمي"),
    ("sampling and hold", "أخذ عينة وتثبيت"),
    ("successive approximation converter", "محول التقريب المتتالي"),
    ("flash converter", "محول ومضي"),
    ("digital to analog resolution", "ميز المحول الرقمي التماثلي"),
    ("pid tuning", "ضبط المتحكم التناسبي التكاملي التفاضلي"),
    ("ziegler nichols method", "طريقة زيغلر-نيكولز"),
    ("on off controller", "متحكم تشغيل وإيقاف"),
    ("proportional band", "نطاق التناسب"),
    ("integral time", "زمن التكامل"),
    ("derivative time", "زمن التفاضل"),
    ("set point", "نقطة الضبط"),
    ("process variable", "متغير العملية"),
    ("manipulated variable", "متغير متداول"),
    ("disturbance variable", "متغير اضطراب"),
    ("error signal", "إشارة الخطأ"),
    ("actuator device", "جهاز مشغل"),
    ("control valve", "صمام تحكم"),
    ("valve positioner", "محدد وضع الصمام"),
    ("cascade control", "تحكم متسلسل"),
    ("feedforward control", "تحكم أمامي التغذية"),
    ("feedback control loop", "حلقة تحكم بتغذية راجعة"),
    ("stability margin", "هامش الاستقرار"),
    ("bode plot analysis", "تحليل مخطط بود"),
    ("nyquist plot analysis", "تحليل مخطط نيكويست"),
    ("root locus analysis", "تحليل المحل الهندسي للجذور"),
    ("state space representation", "تمثيل فضاء الحالة"),
    ("controllability matrix", "مصفوفة قابلية التحكم"),
    ("observability matrix", "مصفوفة قابلية الرصد"),
    ("state feedback", "تغذية راجعة للحالة"),
    ("observer design", "تصميم الراصد"),
    ("pole placement", "تعيين الأقطاب"),
    ("robot manipulator", "مناور روبوتي"),
    ("degree of freedom of robot", "درجة حرية الروبوت"),
    ("forward kinematics", "كينماتيكا مباشرة"),
    ("inverse kinematics", "كينماتيكا عكسية"),
    ("jacobian of manipulator", "يعقوبي المناور"),
    ("denavit hartenberg parameters", "وسائط دنافيت-هارتنبرغ"),
    ("end effector", "مؤثر طرفي"),
    ("workspace of robot", "حيز عمل الروبوت"),
    ("trajectory planning", "تخطيط المسار"),
    ("joint space", "فضاء المفاصل"),
    ("cartesian space", "فضاء ديكارتي"),
    ("servo motor", "محرك مؤازر"),
    ("stepper motor", "محرك خطوي"),
    ("encoder feedback", "تغذية راجعة من المرمز"),
    ("robot dynamics", "ديناميكا الروبوت"),
    ("computed torque control", "تحكم بالعزم المحسوب"),
    ("impedance control", "تحكم بالممانعة"),
    ("force control", "تحكم بالقوة"),
    ("machine vision system", "نظام رؤية آلية"),
    ("image thresholding", "عتبة الصورة"),
    ("edge detection", "كشف الحواف"),
    ("feature matching", "مطابقة السمات"),
    ("camera calibration", "معايرة الكاميرا"),
    ("homogeneous transformation", "تحويل متجانس"),
    ("rotation matrix", "مصفوفة دوران"),
    ("translation vector", "متجه انسحاب"),
    ("euler angles", "زوايا أويلر"),
    ("quaternion representation", "تمثيل بالرباعيات"),
    ("mobile robot", "روبوت متنقل"),
    ("odometry estimation", "تقدير المسافة المقطوعة"),
    ("simultaneous localization and mapping", "تموضع ورسم خريطة متزامنان"),
    ("path planning algorithm", "خوارزمية تخطيط المسار"),
    ("obstacle avoidance", "تجنب العوائق"),
    ("proportional integral derivative control of robot", "تحكم تناسبي تكاملي تفاضلي للروبوت"),
    ("embedded system", "نظام مدمج"),
    ("microcontroller architecture", "معمارية المتحكم الدقيق"),
    ("real time operating system", "نظام تشغيل للزمن الحقيقي"),
    ("interrupt service routine", "روتين خدمة المقاطعة"),
    ("watchdog timer", "مؤقت رقابة"),
    ("pulse width modulation output", "خرج تعديل عرض النبضة"),
    ("analog input channel", "قناة دخل تماثلية"),
    ("digital input output", "دخل وخرج رقمي"),
    ("firmware development", "تطوير البرنامج الثابت"),
    ("in circuit debugger", "منقح داخل الدارة"),
    ("printed circuit board", "لوحة دارة مطبوعة"),
    ("schematic capture", "رسم المخطط"),
    ("pcb layout", "تخطيط لوحة الدارة"),
    ("ground plane", "مستوي التأريض"),
    ("decoupling capacitor", "مكثف فصل"),
    ("electromagnetic compatibility", "توافق كهرومغناطيسي"),
    ("electromagnetic interference", "تداخل كهرومغناطيسي"),
    ("electrostatic discharge", "تفريغ كهروستاتيكي"),
    ("creep test", "اختبار الزحف"),
    ("fatigue test", "اختبار الكلال"),
    ("impact test", "اختبار الصدم"),
    ("hardness test", "اختبار الصلادة"),
    ("nondestructive testing", "اختبار غير إتلافي"),
    ("ultrasonic testing", "اختبار فوق صوتي"),
    ("radiographic testing", "اختبار شعاعي"),
    ("magnetic particle testing", "اختبار بالجسيمات المغناطيسية"),
    ("liquid penetrant testing", "اختبار بالسوائل النافذة"),
    ("eddy current testing", "اختبار بالتيارات الدوامة"),
    ("welding procedure specification", "مواصفة إجراء اللحام"),
    ("heat affected zone", "المنطقة المتأثرة بالحرارة"),
    ("weld defect", "عيب لحام"),
    ("porosity in weld", "مسامية في اللحام"),
    ("lack of fusion", "نقص الانصهار"),
    ("undercut defect", "عيب القطع السفلي"),
    ("slag inclusion", "احتباس الخبث"),
    ("residual stress after welding", "إجهاد متبق بعد اللحام"),
    ("post weld heat treatment", "معالجة حرارية بعد اللحام"),
    ("shielded metal arc welding", "لحام قوسي معدني محجب"),
    ("gas metal arc welding", "لحام قوسي معدني غازي"),
    ("gas tungsten arc welding", "لحام قوسي تنغستني غازي"),
    ("submerged arc welding", "لحام قوسي مغمور"),
    ("resistance spot welding", "لحام نقطي مقاومي"),
    ("brazing process", "عملية الكي بالنحاس"),
    ("soldering process", "عملية اللحام بالقصدير"),
    ("casting process", "عملية السباكة"),
    ("sand casting", "سباكة رملية"),
    ("die casting", "سباكة بالقالب"),
    ("investment casting", "سباكة بالشمع المفقود"),
    ("forging process", "عملية الحدادة"),
    ("rolling process", "عملية الدرفلة"),
    ("extrusion process", "عملية البثق"),
    ("drawing process", "عملية السحب"),
    ("sheet metal forming", "تشكيل الصفائح"),
    ("deep drawing", "سحب عميق"),
    ("blanking operation", "عملية القص الكامل"),
    ("punching operation", "عملية التخريم"),
    ("bending operation", "عملية الثني"),
    ("machining allowance", "سماح التشغيل"),
    ("cutting speed", "سرعة القطع"),
    ("feed rate", "معدل التغذية"),
    ("depth of cut", "عمق القطع"),
    ("tool wear", "بلى العدة"),
    ("tool life", "عمر العدة"),
    ("taylor tool life equation", "معادلة تايلور لعمر العدة"),
    ("surface finish", "إنهاء السطح"),
    ("tolerance grade", "درجة التسامح"),
    ("fit system", "نظام التوافق"),
    ("clearance fit", "توافق بخلوص"),
    ("interference fit", "توافق بالتداخل"),
    ("transition fit", "توافق انتقالي"),
    ("geometric dimensioning", "تحديد أبعاد هندسي"),
    ("datum reference", "مرجع إسناد"),
    ("computer aided design", "تصميم بمساعدة الحاسوب"),
    ("computer aided manufacturing", "تصنيع بمساعدة الحاسوب"),
    ("computer numerical control machining", "تشغيل بالتحكم الرقمي الحاسوبي"),
    ("g code program", "برنامج كود جي"),
    ("tool path", "مسار العدة"),
    ("rapid prototyping", "نمذجة سريعة"),
    ("fused deposition modeling", "نمذجة بالترسيب المنصهر"),
    ("selective laser sintering", "تلبيد ليزري انتقائي"),
    ("stereolithography process", "عملية الطباعة التجسيمية"),
    ("additive manufacturing process", "عملية التصنيع بالإضافة"),
    ("subtractive manufacturing", "تصنيع بالإزالة"),
    ("lean production system", "نظام إنتاج رشيق"),
    ("value stream mapping", "رسم تيار القيمة"),
    ("takt time", "زمن الإيقاع"),
    ("cycle time of process", "زمن دورة العملية"),
    ("overall equipment effectiveness", "فعالية المعدات الإجمالية"),
    ("preventive maintenance", "صيانة وقائية"),
    ("predictive maintenance", "صيانة تنبؤية"),
    ("corrective maintenance", "صيانة تصحيحية"),
    ("mean time between failures", "متوسط الزمن بين الأعطال"),
    ("mean time to repair", "متوسط زمن الإصلاح"),
    ("reliability function", "دالة الموثوقية"),
    ("failure rate", "معدل الإخفاق"),
    ("bathtub curve", "منحنى حوض الاستحمام"),
    ("fault tree analysis", "تحليل شجرة الأعطال"),
    ("failure mode and effects analysis", "تحليل أنماط الإخفاق وآثارها"),
    ("root cause analysis", "تحليل السبب الجذري"),
    ("ishikawa diagram", "مخطط إيشيكاوا"),
    ("five whys method", "طريقة اللماذات الخمس"),
    ("statistical quality control", "ضبط الجودة الإحصائي"),
    ("acceptance sampling", "معاينة القبول"),
    ("process capability index", "دليل مقدرة العملية"),
    ("control limits", "حدود الضبط"),
    ("specification limits", "حدود المواصفة"),
    ("assignable cause", "سبب قابل للتعيين"),
    ("common cause variation", "تغير بسبب مشترك"),
]
