"""مصطلحات علمية ثابتة داخل آلية الترجمة.

تُستبدل العبارة المعروفة قبل المحرك، وتُصحَّح الكلمة التي يرجعها المحرك كما هي.
لا يغيّر هذا الملف أوامر البوت ولا نصوص الواجهة.
"""

from __future__ import annotations

import re

from services.glossary_cs import CS_ENTRIES
from services.glossary_eng import ENG_ENTRIES
from services.glossary_extra import EXTRA_ALIASES, EXTRA_ENTRIES, EXTRA_FORCE_SHORT
from services.glossary_med import MED_ENTRIES
from services.glossary_more import MORE_ENTRIES
from services.glossary_ref import REF_ENTRIES
from services.glossary_sci import SCI_ENTRIES
from services.glossary_struct import STRUCT_ENTRIES
from services.glossary_hydro import HYDRO_ENTRIES
from services.glossary_soil import SOIL_ENTRIES
from services.field_context import sense_for
from services.glossary_wide import WIDE_ENTRIES

# كلمات تحتمل أكثر من معنى: تُترجم علمياً إذا كانت النص كله،
# ولا تُفرض داخل الجملة حتى يبقى السياق للمحرك.
AMBIGUOUS = {
    "acid", "area", "base", "beam", "bond", "cell", "charge", "class", "control",
    "culture", "current", "cycle", "degree", "density", "derivative", "energy",
    "expression", "field", "filter", "flow", "force", "form", "friction", "function",
    "gas", "group", "heat", "integral", "joint", "level", "light", "limit", "line",
    "load", "mass", "mean", "medium", "mode", "model", "moment", "motor", "network",
    "normal", "operation", "order", "organ", "phase", "plant", "plasma", "point",
    "population", "power", "pressure", "process",
    "range", "rate", "reduction", "resistance", "root", "sample", "series",
    "set", "settlement", "signal", "solution", "spring", "state", "strain",
    "strength", "stress", "system", "table", "tissue", "tolerance", "type",
    "value", "valve", "vessel", "volume", "wave", "work", "concrete",
}

# مختصرات وحروف يونانية ومصطلحات قصيرة لا لبس علمي فيها.
FORCE_SHORT = {
    "ac", "adp", "alpha", "anova", "atp", "beta", "bmi", "cad", "cam", "cbc",
    "cfd", "cns", "co2", "copd", "cosine", "cpu", "ct", "dc", "delta", "dna",
    "ecg", "eeg", "ekg", "emf", "epsilon", "eta", "fem", "gamma", "gene", "gfr",
    "gtp", "h2o", "hcl", "hiv", "icu", "ion", "kappa", "lambda", "mri", "mrna",
    "mu", "nad", "nu", "o2", "ode", "omega", "pcr", "pde", "ph", "phi", "pi",
    "pid", "psi", "ram", "rho", "rms", "rna", "rom", "sigma", "sine", "tau",
    "theta", "trna", "uv", "zeta",
}

# (إنجليزي، عربي) — الإنجليزي بالشكل المفضل عند الترجمة من العربية.
ENTRIES: list[tuple[str, str]] = [
    # ── رياضيات ──
    ("finite element method", "طريقة العناصر المحدودة"),
    ("finite element analysis", "تحليل العناصر المحدودة"),
    ("finite element", "عنصر محدود"),
    ("finite difference", "فرق محدود"),
    ("partial differential equation", "معادلة تفاضلية جزئية"),
    ("ordinary differential equation", "معادلة تفاضلية عادية"),
    ("differential equation", "معادلة تفاضلية"),
    ("partial derivative", "مشتقة جزئية"),
    ("total derivative", "مشتقة كلية"),
    ("definite integral", "تكامل محدد"),
    ("indefinite integral", "تكامل غير محدد"),
    ("double integral", "تكامل ثنائي"),
    ("triple integral", "تكامل ثلاثي"),
    ("line integral", "تكامل خطي"),
    ("surface integral", "تكامل سطحي"),
    ("integration by parts", "تكامل بالتجزيء"),
    ("chain rule", "قاعدة السلسلة"),
    ("product rule", "قاعدة الجداء"),
    ("quotient rule", "قاعدة القسمة"),
    ("taylor series", "متسلسلة تايلور"),
    ("maclaurin series", "متسلسلة ماكلورين"),
    ("fourier series", "متسلسلة فورييه"),
    ("fourier transform", "تحويل فورييه"),
    ("laplace transform", "تحويل لابلاس"),
    ("inverse laplace transform", "تحويل لابلاس العكسي"),
    ("z transform", "تحويل زد"),
    ("linear algebra", "جبر خطي"),
    ("abstract algebra", "جبر مجرد"),
    ("set theory", "نظرية المجموعات"),
    ("number theory", "نظرية الأعداد"),
    ("complex number", "عدد مركب"),
    ("imaginary number", "عدد تخيلي"),
    ("real number", "عدد حقيقي"),
    ("rational number", "عدد نسبي"),
    ("irrational number", "عدد غير نسبي"),
    ("prime number", "عدد أولي"),
    ("natural number", "عدد طبيعي"),
    ("integer", "عدد صحيح"),
    ("identity matrix", "مصفوفة الوحدة"),
    ("inverse matrix", "مصفوفة عكسية"),
    ("matrix multiplication", "ضرب المصفوفات"),
    ("gaussian elimination", "حذف غاوسي"),
    ("linear transformation", "تحويل خطي"),
    ("inner product", "جداء داخلي"),
    ("dot product", "جداء قياسي"),
    ("cross product", "جداء متجهي"),
    ("unit vector", "متجه وحدة"),
    ("normal vector", "متجه عمودي"),
    ("null space", "فضاء معدوم"),
    ("column space", "فضاء الأعمدة"),
    ("row space", "فضاء الصفوف"),
    ("eigenvalue", "قيمة ذاتية"),
    ("eigenvector", "متجه ذاتي"),
    ("determinant", "محدد"),
    ("transpose", "منقول"),
    ("orthogonal", "متعامد"),
    ("orthonormal", "متعامد ممنظم"),
    ("scalar", "كمية قياسية"),
    ("tensor", "موتر"),
    ("gradient", "تدرج"),
    ("divergence", "تباعد"),
    ("curl", "التفاف"),
    ("laplacian", "لابلاسي"),
    ("polynomial", "كثيرة حدود"),
    ("quadratic equation", "معادلة تربيعية"),
    ("linear equation", "معادلة خطية"),
    ("inflection point", "نقطة انعطاف"),
    ("critical point", "نقطة حرجة"),
    ("saddle point", "نقطة سرجية"),
    ("local maximum", "نهاية عظمى محلية"),
    ("local minimum", "نهاية صغرى محلية"),
    ("asymptote", "محور تقارب"),
    ("hypotenuse", "وتر"),
    ("numerator", "بسط"),
    ("denominator", "مقام"),
    ("logarithm", "لوغاريتم"),
    ("exponential", "أسي"),
    ("factorial", "مضروب"),
    ("permutation", "تبديل"),
    ("combination", "توافق"),
    ("binomial", "ذو الحدين"),
    ("theorem", "مبرهنة"),
    ("lemma", "تمهيدية"),
    ("corollary", "لازمة"),
    ("axiom", "مسلّمة"),
    ("postulate", "مصادرة"),
    ("congruent", "متطابق"),
    ("perpendicular", "عمودي"),
    ("parallel", "متواز"),
    ("cotangent", "ظل التمام"),
    ("secant", "قاطع"),
    ("cosecant", "قاطع التمام"),
    ("sine", "جيب"),
    ("cosine", "جيب التمام"),
    ("trigonometry", "حساب مثلثات"),
    ("calculus", "حسبان"),
    ("differential calculus", "حساب التفاضل"),
    ("integral calculus", "حساب التكامل"),
    ("numerical analysis", "تحليل عددي"),
    ("interpolation", "استيفاء"),
    ("extrapolation", "استكمال خارجي"),
    ("convergence", "تقارب"),
    ("continuity", "اتصال"),
    ("differentiable", "قابل للاشتقاق"),
    ("antiderivative", "مشتقة عكسية"),
    ("boundary condition", "شرط حدودي"),
    ("initial condition", "شرط ابتدائي"),
    ("boundary value problem", "مسألة قيم حدية"),
    ("initial value problem", "مسألة قيم ابتدائية"),
    ("lagrange multiplier", "مضروب لاغرانج"),
    ("newton method", "طريقة نيوتن"),
    ("newton raphson method", "طريقة نيوتن-رافسون"),
    ("optimization", "استمثال"),
    ("constraint", "قيد"),
    ("inequality", "متباينة"),
    ("equation", "معادلة"),
    ("fraction", "كسر"),
    ("decimal", "عدد عشري"),
    ("percentage", "نسبة مئوية"),
    ("proportion", "تناسب"),
    ("infinity", "ما لا نهاية"),
    ("subset", "مجموعة جزئية"),
    ("intersection", "تقاطع"),
    ("union", "اتحاد"),
    ("complement", "متمم"),
    ("domain", "مجال"),
    ("codomain", "مجال مقابل"),
    ("inverse function", "دالة عكسية"),
    ("composite function", "دالة مركبة"),
    ("continuous function", "دالة متصلة"),
    ("discrete", "متقطع"),
    ("sequence", "متتالية"),
    ("matrices", "مصفوفات"),
    ("matrix", "مصفوفة"),
    ("vector", "متجه"),
    ("radius", "نصف قطر"),
    ("diameter", "قطر"),
    ("circumference", "محيط"),
    ("perimeter", "محيط"),
    ("vertex", "رأس"),
    ("vertices", "رؤوس"),
    ("parabola", "قطع مكافئ"),
    ("ellipse", "قطع ناقص"),
    ("hyperbola", "قطع زائد"),
    ("polynomial equation", "معادلة كثيرات الحدود"),
    ("alpha", "ألفا"),
    ("beta", "بيتا"),
    ("gamma", "غاما"),
    ("delta", "دلتا"),
    ("epsilon", "إبسيلون"),
    ("zeta", "زيتا"),
    ("eta", "إيتا"),
    ("theta", "ثيتا"),
    ("kappa", "كابا"),
    ("lambda", "لامدا"),
    ("mu", "ميو"),
    ("nu", "نيو"),
    ("pi", "باي"),
    ("rho", "رو"),
    ("sigma", "سيغما"),
    ("tau", "تاو"),
    ("phi", "فاي"),
    ("psi", "بسي"),
    ("omega", "أوميغا"),
    # ── إحصاء ──
    ("standard deviation", "انحراف معياري"),
    ("confidence interval", "فترة ثقة"),
    ("null hypothesis", "فرضية العدم"),
    ("alternative hypothesis", "فرضية بديلة"),
    ("linear regression", "انحدار خطي"),
    ("logistic regression", "انحدار لوجستي"),
    ("normal distribution", "توزيع طبيعي"),
    ("binomial distribution", "توزيع ذي الحدين"),
    ("poisson distribution", "توزيع بواسون"),
    ("probability density function", "دالة كثافة الاحتمال"),
    ("cumulative distribution function", "دالة التوزيع التراكمي"),
    ("random variable", "متغير عشوائي"),
    ("expected value", "قيمة متوقعة"),
    ("chi square", "مربع كاي"),
    ("chi-square", "مربع كاي"),
    ("p-value", "قيمة احتمالية"),
    ("p value", "قيمة احتمالية"),
    ("t-test", "اختبار تي"),
    ("t test", "اختبار تي"),
    ("analysis of variance", "تحليل التباين"),
    ("anova", "تحليل التباين"),
    ("hypothesis", "فرضية"),
    ("variance", "تباين"),
    ("covariance", "تباين مشترك"),
    ("correlation", "ارتباط"),
    ("regression", "انحدار"),
    ("median", "وسيط"),
    ("histogram", "مدرج تكراري"),
    ("quartile", "ربيع"),
    ("percentile", "مئين"),
    ("outlier", "قيمة شاذة"),
    ("population", "مجتمع إحصائي"),
    ("statistic", "إحصاءة"),
    ("probability", "احتمال"),
    ("bayesian", "بايزي"),
    ("likelihood", "أرجحية"),
    ("significance level", "مستوى المعنوية"),
    ("degrees of freedom", "درجات الحرية"),
    ("mean", "متوسط"),
    ("mode", "منوال"),
    # ── فيزياء ──
    ("kinetic energy", "طاقة حركية"),
    ("potential energy", "طاقة كامنة"),
    ("conservation of energy", "حفظ الطاقة"),
    ("conservation of momentum", "حفظ الزخم"),
    ("angular momentum", "زخم زاوي"),
    ("moment of inertia", "عزم القصور الذاتي"),
    ("center of mass", "مركز الكتلة"),
    ("center of gravity", "مركز الثقل"),
    ("simple harmonic motion", "حركة توافقية بسيطة"),
    ("projectile motion", "حركة مقذوف"),
    ("normal force", "قوة عمودية"),
    ("gravitational field", "مجال جاذبي"),
    ("electric field", "مجال كهربائي"),
    ("magnetic field", "مجال مغناطيسي"),
    ("electromagnetic wave", "موجة كهرومغناطيسية"),
    ("electromagnetic", "كهرومغناطيسي"),
    ("quantum mechanics", "ميكانيكا الكم"),
    ("wave function", "دالة موجية"),
    ("uncertainty principle", "مبدأ عدم اليقين"),
    ("special relativity", "النسبية الخاصة"),
    ("general relativity", "النسبية العامة"),
    ("photoelectric effect", "التأثير الكهروضوئي"),
    ("doppler effect", "تأثير دوبلر"),
    ("thermodynamics", "ديناميكا حرارية"),
    ("first law of thermodynamics", "القانون الأول للديناميكا الحرارية"),
    ("second law of thermodynamics", "القانون الثاني للديناميكا الحرارية"),
    ("specific heat", "حرارة نوعية"),
    ("heat capacity", "سعة حرارية"),
    ("thermal conductivity", "موصلية حرارية"),
    ("black body", "جسم أسود"),
    ("ideal gas", "غاز مثالي"),
    ("boyle's law", "قانون بويل"),
    ("charles's law", "قانون شارل"),
    ("hooke's law", "قانون هوك"),
    ("ohm's law", "قانون أوم"),
    ("coulomb's law", "قانون كولوم"),
    ("faraday's law", "قانون فاراداي"),
    ("newton's law", "قانون نيوتن"),
    ("snell's law", "قانون سنيل"),
    ("young's modulus", "معامل يونغ"),
    ("shear modulus", "معامل القص"),
    ("bulk modulus", "معامل الحجم"),
    ("poisson's ratio", "نسبة بواسون"),
    ("refractive index", "معامل الانكسار"),
    ("focal length", "بعد بؤري"),
    ("half life", "عمر النصف"),
    ("half-life", "عمر النصف"),
    ("radioactive decay", "اضمحلال إشعاعي"),
    ("angular velocity", "سرعة زاوية"),
    ("angular acceleration", "تسارع زاوي"),
    ("fluid mechanics", "ميكانيكا الموائع"),
    ("bernoulli's principle", "مبدأ برنولي"),
    ("continuity equation", "معادلة الاستمرارية"),
    ("reynolds number", "عدد رينولدز"),
    ("mach number", "عدد ماخ"),
    ("laminar flow", "جريان صفائحي"),
    ("turbulent flow", "جريان مضطرب"),
    ("wavelength", "طول موجي"),
    ("frequency", "تردد"),
    ("amplitude", "سعة"),
    ("interference", "تداخل"),
    ("diffraction", "حيود"),
    ("refraction", "انكسار"),
    ("reflection", "انعكاس"),
    ("velocity", "سرعة"),
    ("acceleration", "تسارع"),
    ("momentum", "زخم"),
    ("torque", "عزم الدوران"),
    ("inertia", "قصور ذاتي"),
    ("friction", "احتكاك"),
    ("gravity", "جاذبية"),
    ("buoyancy", "طفو"),
    ("viscosity", "لزوجة"),
    ("turbulence", "اضطراب"),
    ("entropy", "إنتروبيا"),
    ("enthalpy", "إنثالبي"),
    ("convection", "حمل حراري"),
    ("conduction", "توصيل"),
    ("radiation", "إشعاع"),
    ("photon", "فوتون"),
    ("electron", "إلكترون"),
    ("proton", "بروتون"),
    ("neutron", "نيوترون"),
    ("nucleus", "نواة"),
    ("isotope", "نظير"),
    ("quantum", "كم"),
    ("relativity", "نسبية"),
    ("kinematics", "كينماتيكا"),
    ("dynamics", "ديناميكا"),
    ("statics", "إستاتيكا"),
    ("equilibrium", "اتزان"),
    ("oscillation", "تذبذب"),
    ("resonance", "رنين"),
    ("optics", "بصريات"),
    ("magnification", "تكبير"),
    ("capacitor", "مكثف"),
    ("inductor", "محث"),
    ("resistor", "مقاوم"),
    ("capacitance", "سعة كهربائية"),
    ("inductance", "محاثة"),
    ("impedance", "ممانعة"),
    ("reactance", "مفاعلة"),
    ("admittance", "مسايرة"),
    ("voltage", "جهد"),
    ("current", "تيار"),
    ("resistance", "مقاومة"),
    ("circuit", "دائرة"),
    ("wavelengths", "أطوال موجية"),
    ("mass", "كتلة"),
    ("weight", "وزن"),
    ("density", "كثافة"),
    ("pressure", "ضغط"),
    ("force", "قوة"),
    ("energy", "طاقة"),
    ("power", "قدرة"),
    ("work", "شغل"),
    ("efficiency", "كفاءة"),
    ("tension", "شد"),
    ("compression", "انضغاط"),
    ("shear", "قص"),
    ("stress", "إجهاد"),
    ("strain", "انفعال"),
    ("elastic", "مرن"),
    ("plastic deformation", "تشوه لدن"),
    ("stress-strain curve", "منحنى الإجهاد والانفعال"),
    ("stress strain curve", "منحنى الإجهاد والانفعال"),
    # ── هندسة ──
    ("structural analysis", "تحليل إنشائي"),
    ("bending moment", "عزم الانحناء"),
    ("shear force", "قوة القص"),
    ("shear stress", "إجهاد القص"),
    ("normal stress", "إجهاد عمودي"),
    ("bending stress", "إجهاد الانحناء"),
    ("principal stress", "إجهاد رئيسي"),
    ("reinforced concrete", "خرسانة مسلحة"),
    ("prestressed concrete", "خرسانة مسبقة الإجهاد"),
    ("steel structure", "منشأ فولاذي"),
    ("dead load", "حمل ميت"),
    ("live load", "حمل حي"),
    ("wind load", "حمل رياح"),
    ("factor of safety", "معامل أمان"),
    ("yield strength", "مقاومة الخضوع"),
    ("ultimate strength", "مقاومة قصوى"),
    ("ultimate tensile strength", "مقاومة الشد القصوى"),
    ("modulus of elasticity", "معامل المرونة"),
    ("mohr's circle", "دائرة مور"),
    ("strain gauge", "مقياس انفعال"),
    ("simply supported beam", "جائز بسيط الاستناد"),
    ("cantilever beam", "جائز كابولي"),
    ("moment of resistance", "عزم المقاومة"),
    ("soil mechanics", "ميكانيكا التربة"),
    ("bearing capacity", "قدرة التحمل"),
    ("computational fluid dynamics", "ديناميكا الموائع الحسابية"),
    ("internal combustion engine", "محرك احتراق داخلي"),
    ("heat exchanger", "مبادل حراري"),
    ("heat transfer", "انتقال الحرارة"),
    ("mass transfer", "انتقال الكتلة"),
    ("carnot cycle", "دورة كارنو"),
    ("rankine cycle", "دورة رانكن"),
    ("otto cycle", "دورة أوتو"),
    ("diesel cycle", "دورة ديزل"),
    ("alternating current", "تيار متناوب"),
    ("direct current", "تيار مستمر"),
    ("three phase", "ثلاثي الطور"),
    ("power factor", "معامل القدرة"),
    ("short circuit", "دارة قصر"),
    ("open circuit", "دارة مفتوحة"),
    ("kirchhoff's law", "قانون كيرشوف"),
    ("kirchhoff's current law", "قانون كيرشوف للتيار"),
    ("kirchhoff's voltage law", "قانون كيرشوف للجهد"),
    ("thevenin's theorem", "مبرهنة ثيفنين"),
    ("norton's theorem", "مبرهنة نورتون"),
    ("mesh analysis", "تحليل العرى"),
    ("nodal analysis", "تحليل العقد"),
    ("transfer function", "دالة التحويل"),
    ("control system", "نظام تحكم"),
    ("feedback", "تغذية راجعة"),
    ("closed loop", "حلقة مغلقة"),
    ("open loop", "حلقة مفتوحة"),
    ("bode plot", "مخطط بود"),
    ("nyquist plot", "مخطط نيكويست"),
    ("root locus", "المحل الهندسي للجذور"),
    ("pid controller", "متحكم تناسبي تكاملي تفاضلي"),
    ("signal processing", "معالجة الإشارة"),
    ("integrated circuit", "دائرة متكاملة"),
    ("operational amplifier", "مضخم عملياتي"),
    ("logic gate", "بوابة منطقية"),
    ("boolean algebra", "جبر بولياني"),
    ("truth table", "جدول حقيقة"),
    ("microcontroller", "متحكم دقيق"),
    ("microprocessor", "معالج دقيق"),
    ("semiconductor", "شبه موصل"),
    ("transistor", "ترانزستور"),
    ("diode", "ثنائي"),
    ("transformer", "محول"),
    ("generator", "مولد"),
    ("bandwidth", "عرض النطاق"),
    ("sampling frequency", "تردد أخذ العينات"),
    ("nyquist frequency", "تردد نيكويست"),
    ("reinforced steel", "حديد التسليح"),
    ("reinforcement", "تسليح"),
    ("formwork", "قالب صب"),
    ("curing", "إنضاج"),
    ("slump test", "اختبار الهبوط"),
    ("compressive strength", "مقاومة الانضغاط"),
    ("tensile strength", "مقاومة الشد"),
    ("fatigue", "كلال"),
    ("fracture mechanics", "ميكانيكا الكسر"),
    ("corrosion", "تآكل"),
    ("welding", "لحام"),
    ("bearing", "محمل"),
    ("gear", "ترس"),
    ("shaft", "عمود إدارة"),
    ("turbine", "عنفة"),
    ("compressor", "ضاغط"),
    ("nozzle", "فوهة"),
    ("boiler", "مرجل"),
    ("condenser", "مكثف بخاري"),
    ("pump", "مضخة"),
    ("valve", "صمام"),
    ("buckling", "انبعاج"),
    ("torsion", "التواء"),
    ("deflection", "سهم"),
    ("truss", "جمالون"),
    ("cantilever", "كابولي"),
    ("foundation", "أساس"),
    ("footing", "قاعدة أساس"),
    ("column", "عمود"),
    ("slab", "بلاطة"),
    ("beam", "جائز"),
    ("concrete", "خرسانة"),
    ("aggregate", "ركام"),
    ("cement", "أسمنت"),
    ("rebar", "قضيب تسليح"),
    ("hydraulics", "هيدروليكا"),
    ("hydrology", "هيدرولوجيا"),
    ("groundwater", "مياه جوفية"),
    ("permeability", "نفاذية"),
    ("consolidation", "انضمام"),
    ("settlement", "هبوط"),
    ("retaining wall", "جدار ساند"),
    ("open channel", "قناة مفتوحة"),
    ("manning equation", "معادلة ماننغ"),
    ("darcy's law", "قانون دارسي"),
    ("bernoulli equation", "معادلة برنولي"),
    ("wastewater", "مياه صرف"),
    ("sewage", "مياه مجاري"),
    ("coagulation", "تخثر"),
    ("sedimentation", "ترسيب"),
    ("filtration", "ترشيح"),
    ("disinfection", "تطهير"),
    ("potable water", "ماء صالح للشرب"),
    ("biochemical oxygen demand", "طلب الأكسجين الكيميائي الحيوي"),
    ("chemical oxygen demand", "طلب الأكسجين الكيميائي"),
    ("activated sludge", "حمأة منشطة"),
    ("distillation", "تقطير"),
    ("absorption", "امتصاص"),
    ("adsorption", "ادمصاص"),
    ("crystallization", "تبلور"),
    ("stoichiometry", "قياس اتحادية العناصر"),
    ("molarity", "مولارية"),
    ("molality", "مولالية"),
    ("mole fraction", "كسر مولي"),
    ("activation energy", "طاقة التنشيط"),
    ("reaction rate", "معدل التفاعل"),
    ("chemical kinetics", "حركية كيميائية"),
    ("equilibrium constant", "ثابت الاتزان"),
    ("le chatelier's principle", "مبدأ لو شاتيليه"),
    ("gibbs free energy", "طاقة جبس الحرة"),
    ("enthalpy of formation", "إنثالبي التكوين"),
    ("raoult's law", "قانون راؤول"),
    ("henry's law", "قانون هنري"),
    ("ideal solution", "محلول مثالي"),
    ("mass balance", "موازنة الكتلة"),
    ("energy balance", "موازنة الطاقة"),
    ("reynolds", "رينولدز"),
    ("nusselt number", "عدد نسلت"),
    ("prandtl number", "عدد برانتل"),
    ("heat flux", "فيض حراري"),
    ("thermal resistance", "مقاومة حرارية"),
    ("conduction heat transfer", "انتقال الحرارة بالتوصيل"),
    ("convection heat transfer", "انتقال الحرارة بالحمل"),
    ("radiation heat transfer", "انتقال الحرارة بالإشعاع"),
    ("laminar", "صفائحي"),
    ("turbulent", "مضطرب"),
    ("incompressible", "غير قابل للانضغاط"),
    ("compressible flow", "جريان قابل للانضغاط"),
    ("boundary layer", "طبقة حدية"),
    ("drag force", "قوة سحب"),
    ("lift force", "قوة رفع"),
    ("airfoil", "جنيح"),
    ("mach", "ماخ"),
    ("nozzle", "فوهة"),
    ("diffuser", "ناشر"),
    ("isentropic", "متساوي الإنتروبيا"),
    ("adiabatic", "كظوم"),
    ("isothermal", "متساوي الحرارة"),
    ("isobaric", "متساوي الضغط"),
    ("isochoric", "متساوي الحجم"),
    ("enthalpy", "إنثالبي"),
    ("entropy", "إنتروبيا"),
    # ── كيمياء ──
    ("periodic table", "الجدول الدوري"),
    ("atomic number", "عدد ذري"),
    ("mass number", "عدد كتلي"),
    ("electron configuration", "التوزيع الإلكتروني"),
    ("covalent bond", "رابطة تساهمية"),
    ("ionic bond", "رابطة أيونية"),
    ("hydrogen bond", "رابطة هيدروجينية"),
    ("oxidation", "أكسدة"),
    ("redox", "أكسدة واختزال"),
    ("carboxylic acid", "حمض كربوكسيلي"),
    ("functional group", "زمرة وظيفية"),
    ("organic chemistry", "كيمياء عضوية"),
    ("inorganic chemistry", "كيمياء لاعضوية"),
    ("activation energy", "طاقة التنشيط"),
    ("avogadro's number", "عدد أفوجادرو"),
    ("molar mass", "كتلة مولية"),
    ("titration", "معايرة"),
    ("precipitate", "راسب"),
    ("solvent", "مذيب"),
    ("solute", "مذاب"),
    ("buffer", "محلول منظم"),
    ("endothermic", "ماص للحرارة"),
    ("exothermic", "ناشر للحرارة"),
    ("catalyst", "حفاز"),
    ("enzyme", "إنزيم"),
    ("polymer", "بوليمر"),
    ("monomer", "مونومر"),
    ("isomer", "مصاوغ"),
    ("alkane", "ألكان"),
    ("alkene", "ألكين"),
    ("alkyne", "ألكاين"),
    ("aldehyde", "ألدهيد"),
    ("ketone", "كيتون"),
    ("ester", "إستر"),
    ("amine", "أمين"),
    ("benzene", "بنزين"),
    ("aromatic", "عطري"),
    ("aliphatic", "أليفاتي"),
    ("orbital", "مدار"),
    ("valence", "تكافؤ"),
    ("cation", "كاتيون"),
    ("anion", "أنيون"),
    ("ion", "أيون"),
    ("molecule", "جزيء"),
    ("atom", "ذرة"),
    ("mole", "مول"),
    ("acid", "حمض"),
    ("solution", "محلول"),
    ("concentration", "تركيز"),
    ("ph", "الأس الهيدروجيني"),
    ("h2o", "ماء"),
    ("co2", "ثاني أكسيد الكربون"),
    ("o2", "أكسجين"),
    ("n2", "نيتروجين"),
    ("hcl", "حمض الهيدروكلوريك"),
    ("naoh", "هيدروكسيد الصوديوم"),
    ("h2so4", "حمض الكبريتيك"),
    # ── طب وأحياء ──
    ("myocardial infarction", "احتشاء عضلة القلب"),
    ("heart failure", "قصور القلب"),
    ("blood pressure", "ضغط الدم"),
    ("heart rate", "معدل ضربات القلب"),
    ("respiratory rate", "معدل التنفس"),
    ("body temperature", "درجة حرارة الجسم"),
    ("diabetes mellitus", "داء السكري"),
    ("diabetes insipidus", "داء السكري الكاذب"),
    ("hypertension", "ارتفاع ضغط الدم"),
    ("hypotension", "انخفاض ضغط الدم"),
    ("hyperglycemia", "فرط سكر الدم"),
    ("hypoglycemia", "نقص سكر الدم"),
    ("atherosclerosis", "تصلب عصيدي"),
    ("myocardium", "عضلة القلب"),
    ("endocardium", "شغاف"),
    ("pericardium", "تأمور"),
    ("central nervous system", "الجهاز العصبي المركزي"),
    ("peripheral nervous system", "الجهاز العصبي المحيطي"),
    ("spinal cord", "الحبل الشوكي"),
    ("cranial nerve", "عصب قحفي"),
    ("magnetic resonance imaging", "التصوير بالرنين المغناطيسي"),
    ("computed tomography", "التصوير المقطعي المحوسب"),
    ("electrocardiogram", "مخطط كهربية القلب"),
    ("electroencephalogram", "مخطط كهربية الدماغ"),
    ("complete blood count", "تعداد الدم الكامل"),
    ("red blood cell", "كرية حمراء"),
    ("white blood cell", "كرية بيضاء"),
    ("blood cell", "خلية دموية"),
    ("stem cell", "خلية جذعية"),
    ("cell membrane", "غشاء خلوي"),
    ("cell wall", "جدار خلوي"),
    ("smooth muscle", "عضلة ملساء"),
    ("skeletal muscle", "عضلة هيكلية"),
    ("cardiac muscle", "عضلة قلبية"),
    ("bone marrow", "نقي العظم"),
    ("connective tissue", "نسيج ضام"),
    ("epithelial tissue", "نسيج ظهاري"),
    ("nervous tissue", "نسيج عصبي"),
    ("muscle tissue", "نسيج عضلي"),
    ("amino acid", "حمض أميني"),
    ("fatty acid", "حمض دهني"),
    ("nucleic acid", "حمض نووي"),
    ("citric acid cycle", "دورة حمض الستريك"),
    ("krebs cycle", "دورة كريبس"),
    ("electron transport chain", "سلسلة نقل الإلكترون"),
    ("gene expression", "تعبير جيني"),
    ("protein synthesis", "تخليق البروتين"),
    ("dna replication", "تضاعف الحمض النووي"),
    ("messenger rna", "الحمض النووي الريبوزي الرسول"),
    ("transfer rna", "الحمض النووي الريبوزي الناقل"),
    ("base pair", "زوج قاعدي"),
    ("in vitro", "في المختبر"),
    ("in vivo", "في الجسم الحي"),
    ("in situ", "في الموضع"),
    ("oxidative stress", "إجهاد تأكسدي"),
    ("psychological stress", "إجهاد نفسي"),
    ("side effect", "تأثير جانبي"),
    ("adverse effect", "تأثير ضائر"),
    ("clinical trial", "تجربة سريرية"),
    ("double blind", "مزدوج التعمية"),
    ("placebo", "دواء وهمي"),
    ("antibiotic resistance", "مقاومة المضادات الحيوية"),
    ("infectious disease", "مرض معد"),
    ("autoimmune disease", "مرض مناعي ذاتي"),
    ("inflammatory response", "استجابة التهابية"),
    ("immune system", "جهاز مناعي"),
    ("cardiac output", "نتاج قلبي"),
    ("stroke volume", "حجم الدفقة"),
    ("glomerular filtration rate", "معدل الرشح الكبيبي"),
    ("pulmonary embolism", "انصمام رئوي"),
    ("deep vein thrombosis", "خثار وريدي عميق"),
    ("cerebrovascular accident", "حادث وعائي دماغي"),
    ("chronic obstructive pulmonary disease", "داء الانسداد الرئوي المزمن"),
    ("urinary tract infection", "عدوى المسالك البولية"),
    ("peptic ulcer", "قرحة هضمية"),
    ("inflammatory bowel", "أمعاء التهابية"),
    ("myocardial", "عضلي قلبي"),
    ("infarction", "احتشاء"),
    ("ischemia", "إقفار"),
    ("necrosis", "نخر"),
    ("apoptosis", "موت خلوي مبرمج"),
    ("hyperplasia", "فرط التنسج"),
    ("hypertrophy", "تضخم"),
    ("atrophy", "ضمور"),
    ("metaplasia", "حؤول"),
    ("dysplasia", "خلل التنسج"),
    ("neoplasia", "تنشؤ"),
    ("metastasis", "نقيلة"),
    ("carcinoma", "سرطانة"),
    ("sarcoma", "ساركومة"),
    ("benign", "حميد"),
    ("malignant", "خبيث"),
    ("biopsy", "خزعة"),
    ("diagnosis", "تشخيص"),
    ("prognosis", "مآل"),
    ("symptom", "عرض"),
    ("syndrome", "متلازمة"),
    ("etiology", "سببيات"),
    ("pathogenesis", "إمراض"),
    ("idiopathic", "مجهول السبب"),
    ("congenital", "خلقي"),
    ("chronic", "مزمن"),
    ("acute", "حاد"),
    ("inflammation", "التهاب"),
    ("infection", "عدوى"),
    ("edema", "وذمة"),
    ("sepsis", "إنتان"),
    ("thrombosis", "خثار"),
    ("embolism", "انصمام"),
    ("aneurysm", "أم الدم"),
    ("arrhythmia", "اضطراب النظم"),
    ("tachycardia", "تسرع القلب"),
    ("bradycardia", "بطء القلب"),
    ("angina", "ذبحة"),
    ("pneumonia", "ذات الرئة"),
    ("asthma", "ربو"),
    ("bronchitis", "التهاب القصبات"),
    ("tuberculosis", "سل"),
    ("hepatitis", "التهاب الكبد"),
    ("cirrhosis", "تشمع"),
    ("nephritis", "التهاب الكلية"),
    ("anemia", "فقر الدم"),
    ("leukemia", "ابيضاض الدم"),
    ("hemoglobin", "خضاب"),
    ("platelet", "صفيحة دموية"),
    ("leukocyte", "كرية بيضاء"),
    ("erythrocyte", "كرية حمراء"),
    ("hormone", "هرمون"),
    ("insulin", "أنسولين"),
    ("cortisol", "كورتيزول"),
    ("neuron", "عصبون"),
    ("synapse", "مشبك"),
    ("neurotransmitter", "ناقل عصبي"),
    ("axon", "محوار"),
    ("dendrite", "زائدة شجرية"),
    ("myelin", "ميالين"),
    ("cerebellum", "مخيخ"),
    ("cerebrum", "مخ"),
    ("brainstem", "جذع الدماغ"),
    ("cortex", "قشرة"),
    ("meningitis", "التهاب السحايا"),
    ("epilepsy", "صرع"),
    ("ligament", "رباط"),
    ("tendon", "وتر"),
    ("cartilage", "غضروف"),
    ("osteoarthritis", "فصال عظمي"),
    ("osteoporosis", "تخلخل العظم"),
    ("fracture", "كسر"),
    ("dislocation", "خلع"),
    ("artery", "شريان"),
    ("vein", "وريد"),
    ("capillary", "شعيرة دموية"),
    ("aorta", "أبهر"),
    ("ventricle", "بطين"),
    ("atrium", "أذين"),
    ("alveolus", "سنخ"),
    ("alveoli", "أسناخ"),
    ("bronchus", "قصبة"),
    ("trachea", "رغامى"),
    ("diaphragm", "حجاب حاجز"),
    ("nephron", "نفرون"),
    ("glomerulus", "كبيبة"),
    ("ureter", "حالب"),
    ("bladder", "مثانة"),
    ("duodenum", "اثنا عشر"),
    ("esophagus", "مريء"),
    ("pancreas", "بنكرياس"),
    ("gallbladder", "مرارة"),
    ("appendix", "زائدة دودية"),
    ("epidermis", "بشرة"),
    ("dermis", "أدمة"),
    ("uterus", "رحم"),
    ("ovary", "مبيض"),
    ("placenta", "مشيمة"),
    ("embryo", "جنين مبكر"),
    ("fetus", "جنين"),
    ("chromosome", "صبغي"),
    ("allele", "أليل"),
    ("genotype", "نمط جيني"),
    ("phenotype", "نمط ظاهري"),
    ("mutation", "طفرة"),
    ("replication", "تضاعف"),
    ("transcription", "انتساخ"),
    ("ribosome", "ريبوسوم"),
    ("mitochondria", "ميتوكوندريا"),
    ("mitochondrion", "ميتوكوندريا"),
    ("cytoplasm", "سيتوبلازم"),
    ("mitosis", "انقسام خيطي"),
    ("meiosis", "انقسام منصف"),
    ("osmosis", "تناضح"),
    ("diffusion", "انتشار"),
    ("homeostasis", "استتباب"),
    ("metabolism", "أيض"),
    ("catabolism", "تقويض"),
    ("anabolism", "ابتناء"),
    ("glycolysis", "تحلل سكري"),
    ("photosynthesis", "تركيب ضوئي"),
    ("antibody", "جسم مضاد"),
    ("antigen", "مستضد"),
    ("vaccine", "لقاح"),
    ("immunity", "مناعة"),
    ("antibiotic", "مضاد حيوي"),
    ("bacteria", "بكتيريا"),
    ("virus", "فيروس"),
    ("fungus", "فطر"),
    ("parasite", "طفيلي"),
    ("pathogen", "عامل ممرض"),
    ("protein", "بروتين"),
    ("lipid", "دهن"),
    ("carbohydrate", "كربوهيدرات"),
    ("glucose", "غلوكوز"),
    ("enzyme", "إنزيم"),
    ("gene", "جين"),
    ("dna", "الحمض النووي"),
    ("rna", "الحمض النووي الريبوزي"),
    ("mrna", "الحمض النووي الريبوزي الرسول"),
    ("trna", "الحمض النووي الريبوزي الناقل"),
    ("atp", "أدينوسين ثلاثي الفوسفات"),
    ("adp", "أدينوسين ثنائي الفوسفات"),
    ("gtp", "غوانوسين ثلاثي الفوسفات"),
    ("nad", "ثنائي نوكليوتيد الأدنين والنيكوتيناميد"),
    ("mri", "التصوير بالرنين المغناطيسي"),
    ("ct", "تصوير مقطعي"),
    ("ecg", "مخطط كهربية القلب"),
    ("ekg", "مخطط كهربية القلب"),
    ("eeg", "مخطط كهربية الدماغ"),
    ("cbc", "تعداد الدم الكامل"),
    ("bmi", "منسب كتلة الجسم"),
    ("gfr", "معدل الرشح الكبيبي"),
    ("copd", "داء الانسداد الرئوي المزمن"),
    ("hiv", "فيروس العوز المناعي البشري"),
    ("pcr", "تفاعل البوليميراز المتسلسل"),
    ("icu", "وحدة العناية المركزة"),
    ("cns", "الجهاز العصبي المركزي"),
    ("tumor", "ورم"),
    ("cancer", "سرطان"),
    ("fever", "حمى"),
    ("hemorrhage", "نزف"),
    ("hematoma", "ورم دموي"),
    ("abscess", "خراج"),
    ("ulcer", "قرحة"),
    ("lesion", "آفة"),
    ("cyst", "كيسة"),
    ("polyp", "سليلة"),
    ("stenosis", "تضيق"),
    ("occlusion", "انسداد"),
    ("perforation", "انثقاب"),
    ("fistula", "ناسور"),
    ("hernia", "فتق"),
    ("anesthesia", "تخدير"),
    ("incision", "شق جراحي"),
    ("suture", "خياطة"),
    ("prophylaxis", "وقاية"),
    ("contraindication", "مضاد استطباب"),
    ("dose", "جرعة"),
    ("intravenous", "وريدي"),
    ("intramuscular", "حقن عضلي"),
    ("subcutaneous", "تحت الجلد"),
    ("oral", "فموي"),
    ("sensitivity", "حساسية"),
    ("specificity", "نوعية"),
    ("incidence", "حدوث"),
    ("prevalence", "انتشار"),
    ("mortality", "وفيات"),
    ("morbidity", "مراضة"),
    ("anatomy", "تشريح"),
    ("physiology", "علم وظائف الأعضاء"),
    ("pathology", "علم الأمراض"),
    ("histology", "علم الأنسجة"),
    ("pharmacology", "علم الأدوية"),
    ("microbiology", "علم الأحياء الدقيقة"),
    ("immunology", "علم المناعة"),
    ("biochemistry", "كيمياء حيوية"),
    ("genetics", "وراثيات"),
    ("epidemiology", "وبائيات"),
    ("cell", "خلية"),
    ("tissue", "نسيج"),
    ("organ", "عضو"),
    ("liver", "كبد"),
    ("kidney", "كلية"),
    ("lung", "رئة"),
    ("brain", "دماغ"),
    ("heart", "قلب"),
    ("blood", "دم"),
    ("bone", "عظم"),
    ("muscle", "عضلة"),
    ("nerve", "عصب"),
    ("skin", "جلد"),
    ("stomach", "معدة"),
    ("intestine", "أمعاء"),
    ("colon", "قولون"),
    ("spleen", "طحال"),
    ("thyroid", "درقية"),
    ("plasma", "بلازما"),
    ("serum", "مصل"),
    # ── حاسوب وعلوم أخرى شائعة في الدراسة ──
    ("artificial intelligence", "ذكاء اصطناعي"),
    ("machine learning", "تعلم الآلة"),
    ("deep learning", "تعلم عميق"),
    ("neural network", "شبكة عصبية"),
    ("data structure", "بنية بيانات"),
    ("operating system", "نظام تشغيل"),
    ("time complexity", "تعقيد زمني"),
    ("space complexity", "تعقيد حيزي"),
    ("binary search", "بحث ثنائي"),
    ("gradient descent", "نزول التدرج"),
    ("overfitting", "فرط الملاءمة"),
    ("underfitting", "قصور الملاءمة"),
    ("backpropagation", "انتشار عكسي"),
    ("convolution", "التفاف"),
    ("algorithm", "خوارزمية"),
    ("encryption", "تشفير"),
    ("database", "قاعدة بيانات"),
    ("compiler", "مترجم برمجي"),
    ("processor", "معالج"),
    ("bandwidth", "عرض النطاق"),
    ("protocol", "بروتوكول"),
    ("latency", "زمن الاستجابة"),
    ("cpu", "وحدة معالجة مركزية"),
    ("ram", "ذاكرة وصول عشوائي"),
    ("rom", "ذاكرة قراءة فقط"),
    ("fem", "طريقة العناصر المحدودة"),
    ("cfd", "ديناميكا الموائع الحسابية"),
    ("cad", "تصميم بمساعدة الحاسوب"),
    ("cam", "تصنيع بمساعدة الحاسوب"),
    ("ode", "معادلة تفاضلية عادية"),
    ("pde", "معادلة تفاضلية جزئية"),
    ("pid", "تناسبي تكاملي تفاضلي"),
    ("ac", "تيار متناوب"),
    ("dc", "تيار مستمر"),
    ("emf", "قوة دافعة كهربائية"),
    ("rms", "جذر متوسط المربعات"),
    ("uv", "أشعة فوق بنفسجية"),
    ("load", "حمل"),
    ("flow", "جريان"),
    ("field", "مجال"),
    ("charge", "شحنة"),
    ("set", "مجموعة"),
    ("derivative", "مشتقة"),
    ("integral", "تكامل"),
    ("limit", "نهاية"),
    ("function", "دالة"),
    ("equation", "معادلة"),
    ("probability", "احتمال"),
    ("variable", "متغير"),
    ("constant", "ثابت"),
    ("parameter", "وسيط"),
    ("coefficient", "معامل"),
    ("differential", "تفاضل"),
    ("vector", "متجه"),
    ("scalar", "كمية قياسية"),
    ("matrix", "مصفوفة"),
    ("theorem", "مبرهنة"),
    ("proof", "برهان"),
    ("graph", "بيان"),
    ("vertex", "رأس"),
    ("edge", "حرف"),
    ("node", "عقدة"),
    ("element", "عنصر"),
    ("mesh", "شبكة عناصر"),
    ("node", "عقدة"),
    ("iteration", "تكرار"),
    ("convergence", "تقارب"),
    ("divergence", "تباعد"),
    ("approximation", "تقريب"),
    ("simulation", "محاكاة"),
    ("calibration", "معايرة"),
    ("tolerance", "سماح"),
    ("precision", "إحكام"),
    ("accuracy", "دقة"),
    ("uncertainty", "ارتياب"),
    ("dimensionless", "لا بعدي"),
    ("nonlinear", "غير خطي"),
    ("non-linear", "غير خطي"),
    ("non linear", "غير خطي"),
    ("linear", "خطي"),
    ("homogeneous", "متجانس"),
    ("heterogeneous", "غير متجانس"),
    ("isotropic", "متماثل الخواص"),
    ("anisotropic", "غير متماثل الخواص"),
    ("viscosity", "لزوجة"),
    ("density", "كثافة"),
    ("temperature", "درجة حرارة"),
    ("pressure", "ضغط"),
    ("volume", "حجم"),
    ("area", "مساحة"),
    ("velocity", "سرعة"),
    ("acceleration", "تسارع"),
    ("displacement", "إزاحة"),
    ("deformation", "تشوه"),
    ("elasticity", "مرونة"),
    ("plasticity", "لدونة"),
    ("ductility", "مطيلية"),
    ("brittleness", "هشاشة"),
    ("hardness", "صلادة"),
    ("toughness", "متانة"),
    ("stiffness", "جسوءة"),
    ("strength", "مقاومة"),
    ("stress", "إجهاد"),
    ("strain", "انفعال"),
    ("moment", "عزم"),
    ("shear", "قص"),
    ("torsion", "التواء"),
    ("bending", "انحناء"),
    ("axial", "محوري"),
    ("radial", "قطري"),
    ("tangential", "مماسي"),
    ("normal", "عمودي"),
    ("equilibrium", "اتزان"),
    ("stability", "استقرار"),
    ("resonance", "رنين"),
    ("damping", "تخميد"),
    ("vibration", "اهتزاز"),
    ("frequency", "تردد"),
    ("amplitude", "سعة"),
    ("period", "دور"),
    ("wavelength", "طول موجي"),
    ("phase", "طور"),
    ("amplitude modulation", "تعديل سعوي"),
    ("frequency modulation", "تعديل ترددي"),
    ("low pass filter", "مرشح تمرير منخفض"),
    ("high pass filter", "مرشح تمرير عال"),
    ("band pass filter", "مرشح تمرير نطاقي"),
    ("fourier", "فورييه"),
    ("laplace", "لابلاس"),
    ("newton", "نيوتن"),
    ("pascal", "باسكال"),
    ("joule", "جول"),
    ("watt", "واط"),
    ("hertz", "هرتز"),
    ("coulomb", "كولوم"),
    ("volt", "فولت"),
    ("ampere", "أمبير"),
    ("ohm", "أوم"),
    ("farad", "فاراد"),
    ("henry", "هنري"),
    ("tesla", "تسلا"),
    ("weber", "ويبر"),
    ("kelvin", "كلفن"),
    ("celsius", "مئوية"),
    ("mole", "مول"),
    ("candela", "قنديلة"),
    ("cell phone", "هاتف محمول"),
    ("mobile phone", "هاتف محمول"),
    ("fuel cell", "خلية وقود"),
    ("solar cell", "خلية شمسية"),
    ("light beam", "شعاع ضوئي"),
    ("laser beam", "شعاع ليزر"),
    ("ion beam", "شعاع أيوني"),
    ("power supply", "مصدر قدرة"),
    ("power plant", "محطة توليد"),
    ("data set", "مجموعة بيانات"),
    ("concrete example", "مثال ملموس"),
]

# صيغ عربية شائعة عند الطلاب تُقابل المصطلح الإنجليزي.
AR_ALIASES: list[tuple[str, str]] = [
    ("جلطة قلبية", "myocardial infarction"),
    ("الجلطة القلبية", "myocardial infarction"),
    ("ضغط الدم", "blood pressure"),
    ("طريقة العناصر المحددة", "finite element method"),
    ("العناصر المحددة", "finite element"),
    ("معادلة تفاضلية جزئية", "partial differential equation"),
    ("انحراف معياري", "standard deviation"),
    ("قيمة ذاتية", "eigenvalue"),
    ("متجه ذاتي", "eigenvector"),
    ("حمض نووي", "DNA"),
    ("رنين مغناطيسي", "magnetic resonance imaging"),
    ("تخطيط القلب", "electrocardiogram"),
    ("اشعة مقطعية", "computed tomography"),
    ("أشعة مقطعية", "computed tomography"),
    ("خرسانة مسلحة", "reinforced concrete"),
    ("عزم الانحناء", "bending moment"),
    ("اجهاد", "stress"),
    ("انفعال", "strain"),
]

_DIAC = re.compile(r"[\u064B-\u0652\u0670\u0640]")
_AFFIX = re.compile(r"^([^\w\u0600-\u06FF]*)(.*?)([^\w\u0600-\u06FF]*)$", re.DOTALL)
_AR_CHARS = re.compile(r"[\u0600-\u06FF]")
_EN_CHARS = re.compile(r"[A-Za-z]")


def _norm_en(text: str) -> str:
    text = text.replace("’", "'").replace("‘", "'").replace("`", "'")
    text = re.sub(r"\s+", " ", text).strip().casefold()
    return text


def _norm_ar(text: str) -> str:
    text = _DIAC.sub("", text)
    text = (
        text.replace("أ", "ا")
        .replace("إ", "ا")
        .replace("آ", "ا")
        .replace("ى", "ي")
        .replace("ؤ", "و")
        .replace("ئ", "ي")
        .replace("ة", "ه")
    )
    return re.sub(r"\s+", " ", text).strip()


def _en_pattern(term: str) -> re.Pattern[str]:
    esc = re.escape(term)
    if term.casefold().endswith(("s", "x", "z", "ch", "sh")):
        suffix = r"(?:'s|es)?"
    else:
        suffix = r"(?:'s|s)?"
    return re.compile(rf"(?<![\w]){esc}{suffix}(?![\w])", re.IGNORECASE)


def _ar_pattern(term: str) -> re.Pattern[str]:
    return re.compile(rf"(?<![\w]){re.escape(term)}(?![\w])")


def _is_forced(english: str) -> bool:
    key = _norm_en(english)
    if key in AMBIGUOUS:
        return False
    if " " in key or "-" in key:
        return True
    if key in FORCE_SHORT or key in EXTRA_FORCE_SHORT:
        return True
    return len(key) >= 8


_EN: dict[str, str] = {}
_AR: dict[str, str] = {}
_EN_FORCE: list[tuple[re.Pattern[str], str, str]] = []
_EN_ALL: list[tuple[re.Pattern[str], str, str]] = []
_AR_ALL: list[tuple[re.Pattern[str], str, str]] = []


def _build() -> None:
    all_entries = (
        ENTRIES
        + EXTRA_ENTRIES
        + MED_ENTRIES
        + ENG_ENTRIES
        + SCI_ENTRIES
        + CS_ENTRIES
        + MORE_ENTRIES
        + WIDE_ENTRIES
        + REF_ENTRIES
        + STRUCT_ENTRIES
        + HYDRO_ENTRIES
        + SOIL_ENTRIES
    )
    ordered = sorted(all_entries, key=lambda item: (len(item[0]), item[0].count(" ")), reverse=True)
    for english, arabic in ordered:
        ek = _norm_en(english)
        if not ek or not arabic:
            continue
        _EN.setdefault(ek, arabic)
        _AR.setdefault(_norm_ar(arabic), english)
        needle = ek
        compiled = _en_pattern(english)
        _EN_ALL.append((compiled, needle, arabic))
        if _is_forced(english):
            _EN_FORCE.append((compiled, needle, arabic))

    ar_pairs = [(arabic, english) for english, arabic in all_entries]
    ar_pairs.extend(AR_ALIASES)
    ar_pairs.extend(EXTRA_ALIASES)
    ar_pairs.sort(key=lambda item: len(item[0]), reverse=True)
    seen_surface: set[str] = set()
    for arabic, english in ar_pairs:
        ak = _norm_ar(arabic)
        if not ak:
            continue
        _AR.setdefault(ak, english)
        if arabic in seen_surface:
            continue
        seen_surface.add(arabic)
        _AR_ALL.append((_ar_pattern(arabic), arabic, english))


_build()


def _lookup_english(core: str) -> str | None:
    key = _norm_en(core)
    if key in _EN:
        return _EN[key]
    if len(key) >= 4 and key.endswith("ies") and f"{key[:-3]}y" in _EN:
        return _EN[f"{key[:-3]}y"]
    if len(key) >= 4 and key.endswith("es") and key[:-2] in _EN:
        return _EN[key[:-2]]
    if len(key) >= 3 and key.endswith("s") and not key.endswith("ss") and key[:-1] in _EN:
        return _EN[key[:-1]]
    return None


def _lookup_arabic(core: str) -> str | None:
    return _AR.get(_norm_ar(core))


def lookup_preserving(text: str, direction: str) -> str | None:
    """إذا كان النص كله مصطلحاً معروفاً تُرجعه بترجمته العلمية مع علامات الترقيم."""
    raw = (text or "").strip()
    if len(raw) < 2:
        return None
    match = _AFFIX.match(raw)
    if not match:
        return None
    prefix, core, suffix = match.group(1), match.group(2).strip(), match.group(3)
    if len(core) < 2:
        return None
    if direction == "en_ar":
        hit = sense_for(core) or _lookup_english(core)
    else:
        hit = _lookup_arabic(core)
    if not hit:
        return None
    return f"{prefix}{hit}{suffix}"


def _apply_patterns(
    text: str,
    patterns: list[tuple[re.Pattern[str], str, str]],
    *,
    english: bool,
    respect_field: bool = False,
) -> str:
    if not text:
        return text
    if english:
        text = text.replace("’", "'").replace("‘", "'")
        if not _EN_CHARS.search(text):
            return text
    elif not _AR_CHARS.search(text):
        return text

    hay = text.casefold() if english else text
    for pattern, needle, target in patterns:
        if respect_field and sense_for(needle):
            continue
        probe = needle if english else needle
        if english:
            if probe not in hay:
                continue
        elif probe not in text and _norm_ar(probe) not in _norm_ar(text):
            continue
        updated = pattern.sub(target, text)
        if updated != text:
            text = updated
            if english:
                hay = text.casefold()
    return text


def apply_known_terms(text: str, direction: str) -> str:
    """يزرع ترجمة المصطلحات المستقرة داخل النص قبل إرساله للمحرك."""
    if direction == "en_ar":
        return _apply_patterns(text, _EN_FORCE, english=True)
    return _apply_patterns(text, _AR_ALL, english=False)


def repair_copied(text: str, direction: str) -> str:
    """يستبدل المصطلح الذي أرجعه المحرك كما هو بترجمته العلمية."""
    if direction == "en_ar":
        return _apply_patterns(text, _EN_ALL, english=True, respect_field=True)
    return _apply_patterns(text, _AR_ALL, english=False)
