# حالات المحادثة (ConversationHandler states)

# Translation
TR_WAIT_TEXT = 10
TR_WAIT_FILE = 11
TR_WAIT_DIRECTION = 12
TR_WAIT_IMAGE = 13
TR_WAIT_COLOR = 14

# PDF Tools
PDF_IMG_TO_PDF = 30
PDF_TO_IMG = 31
PDF_WORD_TO_PDF = 32
PDF_TO_WORD = 33
PDF_MERGE = 34
PDF_SPLIT = 35
PDF_COMPRESS = 36
PDF_EXTRACT = 37
PDF_REORDER = 38
PDF_SLIDES_NUP = 39

# Exams — بسيط مثل Poll
EXAM_WAIT_CODE = 60
EXAM_CREATE_TITLE = 61
EXAM_CREATE_DURATION = 62
EXAM_Q_TEXT = 63
EXAM_Q_IMAGE = 64
EXAM_Q_OPTIONS = 65
EXAM_AFTER_SAVE = 66
EXAM_BULK_INPUT = 67
EXAM_EDIT_ONE = 68

# Admin
ADMIN_NOTIFY = 70
ADMIN_CHANNEL_USERNAME = 71
ADMIN_CHANNEL_LINK = 72
ADMIN_EXAM_TITLE = 73
ADMIN_EXAM_DURATION = 74
ADMIN_EXAM_SOURCE = 75
ADMIN_ADD_QUESTION = 78
ADMIN_QUESTION_OPTIONS = 79
ADMIN_QUESTION_ANSWER = 80
ADMIN_CHANNEL_ADD = 81
ADMIN_CHANNEL_EDIT = 82
ADMIN_USER_SEARCH = 83
GUARD_PICK_GROUP = 110
GUARD_WAIT_CHANNELS = 111
GUARD_ADMIN_CHANNELS = 112

# Report cover generator
RC_LANGUAGE = 100
RC_FULL_NAME = 90
RC_UNIVERSITY = 92
RC_DEPARTMENT = 93
RC_SUBJECT = 94
RC_TITLE = 95
RC_SUPERVISOR = 96
RC_DATE = 97
RC_LOGO = 98
RC_FORMAT = 99
RC_EDIT_VALUE = 102
